### ISSUE TITLE
Alert syntax errors for "imported and not used" imports

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#104]
This is the most annoying feature of go compiler –it fails when source files contain unused imports:

```
drivers/azurenew/azurenew.go:4: imported and not used: "errors"
drivers/azurenew/azurenew.go:6: imported and not used: "os"
drivers/azurenew/azurenew.go:7: imported and not used: "os/exec"
drivers/azurenew/azurenew.go:8: imported and not used: "strings"
```

Every time I refactor code I find myself going through the compile-edit-compile-edit... loop and I think vscode can help here.

We just need to highlight imports as syntax errors and say "imported and not used". Not sure if doable but that'd make thinks a great deal easier. Maybe goimports can help. https://godoc.org/golang.org/x/tools/cmd/goimports

**Comment by newhook** [comment]
Use goimports.

**Comment by ahmetalpbalkan** [comment]
@newhook hmm the readme doesn't mention goimports but interestingly I started to get this error:

![image](https://cloud.githubusercontent.com/assets/159209/11428200/af9ed282-941d-11e5-916d-3c653d9a873c.png)

I don't have goimports installed yet.

**Comment by lukehoban** [comment]
The "format" command will run whichever of `gofmt`, `goimports` or `goreturns` you choose via `go.formatTool` settings.  These build on one another so `goimports` does everything `gofmt` does plus more and `goreturns` does everything `goimports` does plus more.  

For what you want here, you want at least `goimports` which will automatically add/remove imports as needed by your code.

Out of the box, assuming you've installed all the tools (see [this comment](https://github.com/Microsoft/vscode-go/issues/106#issuecomment-159977630)), running `Format Document` should fix up imports for you.

https://github.com/Microsoft/vscode-go/issues/14 is tracking adding an option to enabled format-on-save so that you don't even need to do a separate action to get formatting + imports fixup.

Given all that, I'm not sure there's anything additional to address here.  If you think there is something beyond what's tracked in those other issues though feel free to reopen.
