### ISSUE TITLE
Tools are searched in GOPATH/bin even if they are available in PATH

### ISSUE THREAD

**Issue by coxx** [Microsoft/vscode-go#1063]
Sometimes vscode-go displays a message 
> The "go-outline" command is not available. Use "go get -v github.com/ramya-rao-a/go-outline" to install. 

and tries to install it using **go get**. 

But actually the tool is available in system-wide PATH.

Personally, I don't like to mix GOPATH/bin and development tools so my linters, code generators and other tools are under PATH (it could be /usr/local/bin, ~/bin or whatever).

**Comment by ramya-rao-a** [comment]
That shouldn't happen. Am on vacation right now without access to my mac.

Will look into it next week.

The extension is pretty easy to debug if you want to give it a try before then

**Comment by ramya-rao-a** [comment]
Oops didn't mean to close the issue

**Comment by ramya-rao-a** [comment]
@coxx I am able to repro the case where one might get the message `The Go extension is better with the latest version of "go-outline". Use "go get -u -v github.com/ramya-rao-a/go-outline" to update`

This is because one might have an older version of `go-outline` and extension suggests to update to the newer version.

But am not able to repro your case where you get the error `The "go-outline" command is not available. Use "go get -v github.com/ramya-rao-a/go-outline" to install`

Does this happen only with the `go-outline` tool and not any of the others?
Do you see this error when you run the `Go to Symbol in File.. " or "Go: Add Import" commands?
These are the only 2 commands that use the `go-outline` tool.

The way the extension tries to find the Go tools is
- Search in the `bin` folder under `go.toolsGopath` setting
- If not found, Search in the `bin` folder under whatever is the GOPATH you see when you run `Go: Current GOPATH` command
- If not found, Search in the folders specified in the PATH env var
- If not found, Search in the `bin` folder under the GOROOT

Can you open your dev console (Run `Developer: Toggle Developer Tools`) and see what if the value of `process['env']['PATH']` is what you'd expect. i.e it contains the folder that contains `go-outline`?

**Comment by coxx** [comment]
Sorry, my bad. I'll close the issue.

**Comment by ramya-rao-a** [comment]
wait, what, how?

**Comment by coxx** [comment]
I've re-checked and can confirm that the issue is only reproduced if go-outline is outdated. 
It'd be nice if the message would be more informative (and go-outline could report some version).

**Comment by ramya-rao-a** [comment]
I want to repro that.

- I did a `go get -u github.com/lukehoban/go-outline` which is the older `go-outline` and doesn't support the `-modified` flag.
- Reload VS Code
- Used the `Go to Symbol in File` feature that uses `go-outline` under the hood
- I get the message `The Go extension is better with the latest version of "go-outline". Use "go get -u -v github.com/ramya-rao-a/go-outline" to update`

But I don't get what you saw i.e "The "go-outline" command is not available. Use "go get -v github.com/ramya-rao-a/go-outline" to install"

Can you share your repro steps?
