### ISSUE TITLE
go test: i flag may be set only once

### ISSUE THREAD

**Issue by ardan-bkennedy** [Microsoft/vscode-go#1064]
I use the "-i" flag on building but this is also being applied to go test. 

```
"go.buildFlags": ["-i"],
```

It appears "go test" is being run in the background when I open a test file.

This is the error I get at the top of the source file for the package statement:
```
go test: i flag may be set only once
run "go help test" or "go help testflag" for more information
```

The help for `go test` says:
```
	-i
	    Install packages that are dependencies of the test.
	    Do not run the test.
```

---

Can we set flags separately for build and test?

**Comment by ramya-rao-a** [comment]
We do have a separate setting called testFlags which gets used when running tests via the test commands

Do you have buildOnSave set to "workspace"? That runs go test ./... (but does not actually run the test) using the buildflags. That's causing the problem. Couldn't find a way to build all files (including test files) in the workspace 

From the past couple of releases we have been setting -i by default while building

So you can skip passing it via buildflags to fix the issue you are seeing

Am on a vacation right now. Once am back, will fix the usage of flags so that the double use issue wont occur again

**Comment by ardan-bkennedy** [comment]
> We do have a separate setting called testFlags which gets used when running tests via the test commands
> 
> Do you have buildOnSave set to "workspace"? That runs go test ./... (but does not actually run the test) using the buildflags. That's causing the problem. Couldn't find a way to build all files (including test files) in the workspace
> 
When this started happening I saw that option and switched it to package. That was a very nice change.
> From the past couple of releases we have been setting -i by default while building
> 
This is always an excellent change. So then I guess I don’t need to do anything!
> So you can skip passing it via buildflags to fix the issue you are seeing
> 
> Am on a vacation right now. Once am back, will fix the usage of flags so that the double use issue wont occur again
> 
Thanks for responding on vacation.

I think that the flags should be separate for each tool.

**Comment by ramya-rao-a** [comment]
The fix to ignore the `-i` flag from `go.buildFlags` (because we add it internally anyway) is out in the latest update (0.6.63) of the Go extension
