### ISSUE TITLE
gorename path error - file not found when cygwin diff in windows path

### ISSUE THREAD

**Issue by smithjacobj** [Microsoft/vscode-go#1082]
My issue is identical to #665, but the closure to that issue indicated that the issue was "fixed" as of 0.6.56

My specs:
- Windows 7 x64
- VS Code 1.13.1
- Go extension version 0.6.62

Same exact error, but in my case, as per [this comment](https://github.com/Microsoft/vscode-go/issues/665#issuecomment-275900315), the issue was the Cygwin `diff` bin in my path. I removed the Cygwin bin directory completely from my path as I mostly use MinGW, restarted VS Code, and the symbol rename worked perfectly.

**Comment by ramya-rao-a** [comment]
Ah that's my mistake, I removed the workarounds https://github.com/Microsoft/vscode-go/commit/1adae1f5ca29cab14655e2f5537b75f2084c9d4a thinking I was pulling in the version of the diff module (3.2.0) that had the fix.

Turns out its 3.3.0 version that has the fix.

The next update to the Go extension will have the fix.

**Comment by ramya-rao-a** [comment]
The fix is out in the latest update (0.6.63) to the Go extension
