### ISSUE TITLE
The plugin auto removed a used module in import list.

### ISSUE THREAD

**Issue by blaketairan** [Microsoft/vscode-go#1107]
I have problem.
When i use command+s to save, "github.com/deckarep/golang-set" module will be removed from import list. But i do use "mapset.NewSetFromSlice(x)" in my code.
With import "github.com/deckarep/golang-set", command "go build ..." or "go run ..." is well, if not, the command will report "undefined: mapset in mapset.NewSetFromSlice".
So i have to use vim to edit this file after using vscode, so sad...

**Comment by ramya-rao-a** [comment]
@blaketairan Formatting is run on save. Looks like it is removing your imports.

By default, the formatting tool used is `goreturns`, can you change it to `gofmt` and see if the issue still occurs?

In your user settings add the following:
`"go.formatTool": "gofmt"`

If this solves your issue then the issue is with the `goreturns` tool.

**Comment by blaketairan** [comment]
Thank you so much for helping! @ramya-rao-a 
goreturns is the reason.

**Comment by ramya-rao-a** [comment]
@blaketairan Please do file an issue in the repo for goreturns

**Comment by blaketairan** [comment]
https://github.com/sqs/goreturns/issues/34

**Comment by blaketairan** [comment]
^_^ https://github.com/sqs/goreturns/issues/34
