### ISSUE TITLE
gometalinter is installed in `go.gopath` and not into `go.toolsGopath`

### ISSUE THREAD

**Issue by alex-slynko** [Microsoft/vscode-go#1110]
WE are using custom GOPATH for our code and system GOPATH for tools, but when I set  "go.lintTool": "gometalinter" to equal "gometalinter" and clicked "Install all" for missing packages, it installed all the tools into custom GOPATH.

**Comment by ramya-rao-a** [comment]
This was intentional as gometalinter expects its linters to be in the GOPATH. If gometalinter was installed elsewhere along with its linters, then it fails with "can't find executable in $PATH`

But there is a way around it which is to pass the "toolsGopath" as additional GOPATH to the process that does the linting.

Fixed with https://github.com/Microsoft/vscode-go/commit/27038d14098cb5b56e291046cb715c09ae5038a6

**Comment by alex-slynko** [comment]
Thanks @ramya-rao-a

**Comment by ramya-rao-a** [comment]
`gometalinter` will now be installed in the `go.toolsGopath` in the latest update (0.6.64)
