### ISSUE TITLE
Test environment variables on a per-project basis

### ISSUE THREAD

**Issue by pschuegr** [Microsoft/vscode-go#1114]
Hi,

I'm trying to get some environment variables passed to my go tests, and I'm wondering why the `launch.json`  `env` is not respected when running tests?  Am I missing something? Is there a better way to do this?  I see that there is a "go.testEnvVars" configuration available, but I don't see why this should be a global setting to vscode.

Thanks!

**Comment by ramya-rao-a** [comment]
launch.json file is used for debugging your code or tests.

Using `go.testEnvVars` is the way to pass env vars to your tests.

You can set this in your "Workspace settings" instead of "User Settings"

![screen shot 2017-07-26 at 6 53 44 pm](https://user-images.githubusercontent.com/16890566/28650942-c087054c-7233-11e7-94c0-97582f24e27f.png)
