### ISSUE TITLE
Generate docs comments for functions

### ISSUE THREAD

**Issue by rsinensis** [Microsoft/vscode-go#1127]
Can you add generated code annotation function?
Automatically completes a generic template for function annotation.

Like this:

![docthis](https://raw.githubusercontent.com/joelday/vscode-docthis/master/images/demo.gif)

**Comment by ramya-rao-a** [comment]
@fatih @zmb3 Do you have anything similar for vim-go/go-plus?

I am sure there is a Go tool out there that could add comments on functions based on its signature.

**Comment by zmb3** [comment]
Seems like an anti-pattern to me, for several reasons:

- GoDoc doesn't use fancy markup syntax like JavaDoc or JSDoc - it's just text.  These type of tools are useful in auto-filling out the boring repetitive markup, but we don't have that in Go.
- Some people request just enough to suppress `go vet` warnings about exported identifiers being undocumented - but this defeats the purpose of the warning, which is to tell you that something is undocumented so that you go back and do it.

**Comment by ramya-rao-a** [comment]
Makes sense, looping in more people for their thoughts

cc @rakyll, @campoy

**Comment by rakyll** [comment]
What @zmb3 said.

Godoc doesn't have annotations. We also prefer the doc to be targeting more to the humans than to machines.

**Comment by ramya-rao-a** [comment]
Thanks @rakyll and @zmb3 

@rsinensis Hope the explaination above helps as to why we shouldnt be going down this route.
