### ISSUE TITLE
GOPATH from .zshenv not detected correctly

### ISSUE THREAD

**Issue by verkvieto** [microsoft/vscode-go#1133]
I have my GOPATH set in `~/.zshenv` via `export GOPATH=$HOME`. Running the `Go: Current GOPATH` command from the command palette shows the GOPATH as `~/go` when it should be `~`.

![screenshot from 2017-08-06 01-58-57](https://user-images.githubusercontent.com/17302454/29001306-a90f1dda-7a4b-11e7-8ecc-42110b7f5bff.png)

```
go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/brandon"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build562657282=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

**Comment by ramya-rao-a** [comment]
@brandon-schumann Can you open the integrated terminal and run `echo $GOPATH` as well as `go env` and compare results?

**Comment by brandon-schumann** [comment]
@ramya-rao-a you can see the results of `echo $GOPATH`, `echo $PATH`, and `go env` in the integrated terminal in the screenshot below.
![screenshot from 2017-08-07 12-04-30](https://user-images.githubusercontent.com/17302454/29037282-972ff710-7b68-11e7-8c25-996cd9a86665.png)
The results in the integratted terminal are as expected (GOPATH set to `~`); however, the `Go: Current GOPATH` command shows differently (GOPATH set to `~/go`) and is the GOPATH that is actually used.

I can work around this in the meantime by setting the `go.gopath` in the `settings.json` file or by setting `go.inferGopath` to `true`. Only the default setting of detecting the GOPATH from the envrionment variable seems to not be working.

**Comment by ramya-rao-a** [comment]
Thanks @brandon-schumann 

@Tyriar Can you think of any reason why the process for extension host might not have the environment variables as set in ~/.zshenv, but the integrated terminal does?

**Comment by Tyriar** [comment]
@ramya-rao-a VS Code's environment is build by launching a $SHELL process and parsing the output of `env` https://github.com/Microsoft/vscode/blob/8bb4ffb4efe724a2454f1a618b41edd7f45b661f/src/vs/code/node/shellEnv.ts#L27

@brandon-schumann is `$SHELL` set to `zsh`? What's the output of `echo $SHELL` on a external terminal?

**Comment by brandon-schumann** [comment]
@Tyriar `echo $SHELL` returns `/bin/zsh`.

**Comment by Tyriar** [comment]
I would expect it to work then if `$SHELL` is `zsh`. @joaomoreno any ideas why `~/.zshenv` is not being sourced in VS Code's environment?

**Comment by joaomoreno** [comment]
No idea. There should be a warning in the Devtools console saying `renderer did not receive lazyEnv in time`. Do you confirm?

**Comment by ramya-rao-a** [comment]
@brandon-schumann Is this still an issue?

**Comment by brandon-schumann** [comment]
@ramya-rao-a Yes it's still an issue. `~/go` still seems to be used even though the `GOPATH` is set to `$HOME` in `~/.zshenv`.

**Comment by ramya-rao-a** [comment]
Do you see the warning as mentioned in https://github.com/Microsoft/vscode-go/issues/1133#issuecomment-325281635 ?

**Comment by brandon-schumann** [comment]
@ramya-rao-a no I do not see that warning in the Devtools console.

**Comment by ramya-rao-a** [comment]
@Tyriar @joaomoreno Any more thoughts? Env vars from `~/.zshenv` seem to be reaching the terminal but not the extension host

**Comment by zero-master** [comment]
I failed to reproduce this issue.

![image](https://user-images.githubusercontent.com/1130261/36381398-621376ea-15c0-11e8-8dfc-9b22e20ad2ed.png)

```
code --version
1.20.0

zsh --version
zsh 5.4.2 (x86_64-unknown-linux-gnu)
```

**Comment by markbrownsword** [comment]
I also get this issue, on Ubuntu, using bash (setup is in .bashrc)
$GOPATH = /home/mark/projects/go
VSCODE Go: Current GOPATH = /home/mark/go

Setting `go.inferGopath` to `true` gets around it.

![](https://user-images.githubusercontent.com/10730429/36616123-b787fde8-1936-11e8-8f53-a008b5bfbe7b.png?raw=true)

**Comment by RifeWang** [comment]
![屏幕快照 2019-05-22 上午11 47 17](https://user-images.githubusercontent.com/20348639/58147250-3819ee80-7c8c-11e9-8159-753067c0452a.png)

The result of `GO: CURRENT GOPATH` is defferent with `go env` in my zsh .

**Comment by mlushpenko** [comment]
I have the same, but it seems to be broader issue - path can't be detected for hadolint and cloud code extensions as well, it's driving me crazy. My guess other exetnsions that depend on command line tools won't work as well. I use zsh.

**Comment by mlushpenko** [comment]
What worked for me is printing proper paths by running:
```
go env GOPATH
go env GOROOT
```

and then using those outputs in user `settings.json`:
```
"go.gopath": "/Users/maksym/go",
"go.goroot": "/usr/local/Cellar/go/1.12.5/libexec",
```

**Comment by RifeWang** [comment]
I do not need GOPATH when I upgrade go version and use go modules.

**Comment by mlushpenko** [comment]
I am using go modules as well, but no documentation would show up for me at all and now works again, not matter if I start it up from shell or normally. Maybe GOROOT would be enough. Anyway, I shared what worked for me, you may have different situation.

**Comment by BnMcG** [comment]
I think I'm seeing a similar problem using version 0.11.9 of the extension, and version 1.40.1 of VS Code on MacOS Mojave 10.14. It doesn't look like the Go extension is sourcing the correct path at all. 

I have Go installed via Homebrew at `/usr/local/bin/go`. The integrated terminal has the `$PATH` variable correctly sourced (presumably from `~/.zshenv`, while the extension only appears to look in: `PATH(/usr/bin:/bin:/usr/sbin:/sbin)`.

I'm using zsh 5.7.1 - VS Code does correctly source my environment variables if I launch VS Code directly from a zsh terminal rather than Finder. I also tried exporting my path in `~/.zshrc` with no luck.

**Comment by gauravaditya** [comment]
Similar issue for me as well on Ubuntu 18.04, go env works is vscode terminal if i launch code directly from from the zsh terminal, however it doesn't work if i lanch vscode using shortcut, however in the latter case it works if i again source .profile after opening vscode

**Comment by hyangah** [comment]
@gauravaditya It's likely that the shortcut launcher will start vscode with the system default environment variables which don't include GOPATH. If it's not possible to adjust the launcher, I think users should do either 1) set `go.gopath` explicitly, or 2) live with Go's default GOPATH ($HOME/go).

**Comment by gauravaditya** [comment]
thanks for the reply, i will try that.

**Comment by BnMcG** [comment]
I had another crack at this this morning, and think I may have figured it out. At least in my case on MacOS, ZSH was a red herring. 

It turns out that the MacOS GUI (including the dock and finder) don't source environment variables from your chosen shell, and thus applications launched via the GUI don't include these variables. This is why launching from inside a ZSH shell works as expected, but launching from the GUI doesn't.

To fix on MacOS Mojave, I had to add the following file: `~/Library/LaunchAgents/setenv.PATH.plist`:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
  <plist version="1.0">
  <dict>
  <key>Label</key>
  <string>setenv.PATH</string>
  <key>ProgramArguments</key>
  <array>
    <string>sh</string>
    <string>-c</string>
    <string>
      launchctl setenv PATH $PATH:/usr/local/bin
      killall Dock
    </string>  
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
```

This adds `/usr/local/bin` (where I have the `go` binary installed) to the PATH variable used by the GUI, then restarts the dock (so it picks up the new variable). I no longer get errors finding the `go` binary when launching VS Code via the GUI. 

The method of doing this seems to change across different MacOS versions, but this seems to be the way to do change the environment variables used by the dock and finder  for at least the last couple of versions of MacOS.

**Comment by hyangah** [comment]
https://code.visualstudio.com/docs/editor/integrated-terminal#_why-are-there-duplicate-paths-in-the-terminals-path-environment-variable-andor-why-are-they-reversed 
This doc is about the integrated terminal, but it also explains how VS code gets env vars when launching.

> When VS Code launches for the first time, in order to source your "development environment", it launches your configured shell as a login shell, **which runs your `~/.profile/`, `~/.bash_profile/`, `~/.zprofile` scripts**.

(note: .zshenv or .zshrc is not listed there) 

Workarounds available now are 
  1) to explicitly set the GOPATH using extension's setting, or 
  2) configure the login shell scripts, or
  3) start `code` from the fully configured shell (but be aware that the mac launcher reuses already launched code instance if exists), or
  4) customize the launcher, if on mac.

If VS Code does not read the environment variables, there is not much we can do from the extension -- unless we teach the extension to understand various shell scripts' settings and process them. But I think that's beyond the scope of this extension.

If you have any more questions or ideas for improving docs, please file a new issue in the new home of this extension. (github.com/golang/vscode-go)

**Comment by dennis-tra** [comment]
_Disclaimer: I haven't read the whole thread but came here because my `~/.zshenv` wasn't loaded in the integrated terminal._

While the doc about the integrated terminal indeed explains which environment variables are loaded, the behaviour deviates from what would be expected according to the docs of zsh as can be found here: http://zsh.sourceforge.net/Doc/Release/Files.html#Files

There it describes the order of files that are read upon start and stop of a shell session:
> Commands are first read from /etc/zshenv; this cannot be overridden. Subsequent behaviour is modified by the RCS and GLOBAL_RCS options; the former affects all startup files, while the second only affects global startup files (those shown here with an path starting with a /). If one of the options is unset at any point, any subsequent startup file(s) of the corresponding type will not be read. It is also possible for a file in $ZDOTDIR to re-enable GLOBAL_RCS. Both RCS and GLOBAL_RCS are set by default.
>
> Commands are then read from $ZDOTDIR/.zshenv. If the shell is a login shell, commands are read from /etc/zprofile and then $ZDOTDIR/.zprofile. Then, if the shell is interactive, commands are read from /etc/zshrc and then $ZDOTDIR/.zshrc. Finally, if the shell is a login shell, /etc/zlogin and $ZDOTDIR/.zlogin are read.

I checked that moving my `~/.zshenv` configuration to `/etc/zshenv` solves my particular problem.

However I'm still wondering _why_ `$ZDOTDIR/.zshenv` is not loaded, because it clearly says that zsh would attempt to load the file (regardless of (non-)login/(non-)interactive shells).

I also checked that the `RCS` and `GLOBAL_RCS` zsh options are set in the integrated terminal - they are.

Is VSCode somehow tinkering with the `RCS` and `GLOBAL_RCS` options or applies some command line parameters to zsh?

**Comment by hyangah** [comment]
@dennis-tra The environment variable and shell handling is done by VS Code. Can you please file an issue in github.com/microsoft/vscode? Thanks!
