### ISSUE TITLE
Is there anyway to make IntelliSense of function parameters stays longer?

### ISSUE THREAD

**Issue by davyzhang** [Microsoft/vscode-go#1175]
When I typed a function name, the hint tool tip window just disappears.

unlike typescript's IntelliSense,  the function parameters' hints stay till the I close the function with )

**Comment by ramya-rao-a** [comment]
@davyzhang The UI for the tooltip and for rest of the editor for that matter is the same for all languages. Extensions cannot change the UI.

Can you share a video or gif of the issue you are seeing? include both typescript and go for comparison

**Comment by davyzhang** [comment]
Sorry for the vague explanation, 

here is how vscode-go works even if I turned on useCodeSnippetsOnFunctionSuggest
![golang](https://dl.dropboxusercontent.com/u/84845057/go.gif)

Here is how typescript's  suggestions of functions work
![typescript](https://dl.dropboxusercontent.com/u/84845057/ts.gif)

the tooltip window stays and changes during input process, and also highlights current parameter.

**Comment by ramya-rao-a** [comment]
What you have shown for typescript is called "Signature Help" or "Parameter Hints".
It shows up in the below cases
1. when you type the `(` after the function name 
2. when you press `Cmd+Shift+Space` or `Ctrl+Shift+Space` insider the `()` after the function name

In your Go example, since you have enabled `useCodeSnippetsOnFunctionSuggest`, the parameters are already filled up. So there are no hints. In this case you can use option 2 above

When you enable `typescript.useCodeSnippetsOnFunctionSuggest`, you will see the exact same behavior as you see for Go

**Comment by davyzhang** [comment]
I know how it goes now, the problem is that my function has a long list of parameters, so I split them into multiple lines like 
```go
func abc(a,b,c,d,e string, 
f time.Time)
```
and the signature help won't work

**Comment by ramya-rao-a** [comment]
Ah! thats a bug

Logged #1183 to track that
