### ISSUE TITLE
Parameter hints don't show up in tests

### ISSUE THREAD

**Issue by joelpresence** [Microsoft/vscode-go#1184]
I'm running VSCode 1.15.1 with go 1.8.3 on macOS 10.12.6.

When in a test method like
```
func TestFoo(t *testing.T) {
  assert := assert.New(t)

  foo := NewFoo()
  foo.SomeMethod(/* params completion doesn't work here */)
}
```
This used to work before.  Nothing has changed on my end so it seems like either VSCode or the go plugin has an issue?

Here's my custom vscode settings:
```
{
    "editor.fontFamily": "Fira Code",
    "editor.fontSize": 14,
    "editor.fontLigatures": true,
    "editor.minimap.enabled": false,
    "go.testEnvVars": {
        "REDISCLOUD_URL": "redis://localhost:6379"
    },
    "editor.formatOnSave": false,
    "workbench.colorTheme": "Monokai Dimmed",
    "files.autoSave": "afterDelay",
    "files.autoSaveDelay": 2000,
    "go.formatOnSave": false,
    "go.gocodeAutoBuild": true
}
```
Here's my `go env` output:
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/joel/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/mz/tzh0vwxd08jgh0lx24v39gx40000gn/T/go-build747771611=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

Strangely, the params completion/suggestion **does** work in non test files.  But for some reason it doesn't now work in test files though.  It used to work in **both** test and non test files.

Any ideas?

Thanks!

**Comment by ramya-rao-a** [comment]
Works for me... 
Tried both in Mac (go 1.8.3) and Windows (go 1.7)

![image](https://user-images.githubusercontent.com/16890566/29982504-cd37ee7e-8f06-11e7-810b-884e099267de.png)

Can you run `Go: Install/Update Tools` to ensure all the Go tools are up to date, reload VS Code and try again?

**Comment by ramya-rao-a** [comment]
And just to be on the same page you are referring to the parameter hints as shown in my screenshot above and not the suggestion/auto-completion correct?

**Comment by joelpresence** [comment]
@ramya-rao-a thanks for the quick response!

I had tried those things before and they didn't help, but I'll try them again ... Hold on!  :-)

And yes, I mean parameter hints, like in your screenshot.

**Comment by joelpresence** [comment]
```
Installing 13 tools
  gocode
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  gomodifytags
  impl
  godef
  godoc
  goreturns
  golint
  gotests

Installing github.com/nsf/gocode SUCCEEDED
Installing github.com/tpng/gopkgs SUCCEEDED
Installing github.com/ramya-rao-a/go-outline SUCCEEDED
Installing github.com/acroca/go-symbols SUCCEEDED
Installing golang.org/x/tools/cmd/guru SUCCEEDED
Installing golang.org/x/tools/cmd/gorename SUCCEEDED
Installing github.com/fatih/gomodifytags SUCCEEDED
Installing github.com/josharian/impl SUCCEEDED
Installing github.com/rogpeppe/godef SUCCEEDED
Installing golang.org/x/tools/cmd/godoc SUCCEEDED
Installing sourcegraph.com/sqs/goreturns SUCCEEDED
Installing github.com/golang/lint/golint SUCCEEDED
Installing github.com/cweill/gotests/... SUCCEEDED

All tools successfully installed. You're ready to Go :).

**Comment by joelpresence** [comment]
Didn't help.  :-( . Still broken.  Any suggestions?

I do get a popup, but it is not useful, whereas in a non-test file I'll see something like `foo(accountId int64, name string)` in the test file the popup says `foo(int64, string)` as in the param names are dropped.  So that's not useful to me because I need to know the names of the params as well as their types.

Any ideas why the param names are being dropped by VSCode/VSCode-go?

Thanks

**Comment by ramya-rao-a** [comment]
that's weird, I have no idea and I cannot repro

If you are up for it I can help you debug the issue by running the extension from source

**Comment by joelpresence** [comment]
I am up for it!  How do I run the extension from source?

**Comment by ramya-rao-a** [comment]
Great! 

- Follow the steps here: https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension
- Add breakpoint at https://github.com/Microsoft/vscode-go/blob/master/src/goSignature.ts#L36
- Trigger Signature Help by `Ctrl/Cmd+shift+Space` from insider the `()`, the breakpoint will be hit
- Debug away

**Comment by joelpresence** [comment]
Thanks @ramya-rao-a !  I will attempt to debug this weekend and report back in this issue ...

**Comment by ramya-rao-a** [comment]
@joelpresence Any updates here?
Do you still see the issue?

**Comment by jonathan-robertson** [comment]
@joelpresence I'm on go 1.9.2 but was initially having a similar issue until I realized the problem was on my end. This might not apply to you, but it did for me and may help you or someone else who winds up on this issue page.

Using the example you provided:
```go
func TestFoo(t *testing.T) {
  assert := assert.New(t)

  foo := NewFoo()
  foo.SomeMethod(/* params completion doesn't work here */)
}
```

No package methods will populate params for me (even standard packages like `fmt`) unless that package is in the import block. This seems relatively basic at first, but I had gotten used to having the import block collapsed and relied on `goimport` to auto-import packages for me on save, so this was something that took me a bit of time to notice. I'd be 'in the flow' and suddenly not seeing params for methods I created a few months ago and rarely use anymore. 

Sometimes `goimports` appears to be triggered automatically while I'm programming without having to manually save to trigger it... but it seems that this doesn't happen when an error is present. Having a variable declared but not used will result in an error, so (it could be a stretch) perhaps this is related to what you were experiencing?

As a supporting example, the following code does not provide suggestions for me (for `fmt`) unless I add "fmt" to the import block, or manually save (which adds fmt for me):

```go
import (
	"os"
	"testing"
	// no fmt here... suggestions come back if I add fmt
)

func TestFoo(t *testing.T) {
	file, _ := os.Create("fishy.txt") // saving identifies this as an error
	data := fmt.Sprintf([no suggestions here])
}
```
> *helpful side-tip: write ```go for the opening of a code block to use syntax highlighting for go*
---

And for context in case something weird is going on:
```
~$ go env
GOARCH="amd64"
GOBIN="/Users/jonathan/Documents/Code/Go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jonathan/Documents/Code/Go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.9.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.9.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r6/yktk_7bx1214yr07d5j67vx40000gn/T/go-build559840623=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
```

**Comment by jonathan-robertson** [comment]
@joelpresence actually... I just experienced it again and my recommendation above didn't apply. I did notice, however, that the headers disappeared/reappeared while I was writing my line of code, so maybe that operation temporarily knocks out the param suggestions :(

I'm referring specifically to these, which sometimes disappear while I'm in the process of writing a line of code:
```go 
run test | debug test
func blabla(t *testing.T) { ... }
```

I'm on VSCode v1.18.1, btw

**Comment by ramya-rao-a** [comment]
@jonathan-robertson The codelens for "run test" and "debug test" have nothing to do with the parameter hints or the tools that provide the parameter hints. They get re-created/adjusted everytime there is a change to the file.

Apart from that, are you saying that the parameter hints do not appear in test files even when the import statements exist for the package?

**Comment by jonathan-robertson** [comment]
@ramya-rao-a 

> The codelens for "run test" and "debug test" have nothing to do with the parameter hints or the tools that provide the parameter hints. They get re-created/adjusted everytime there is a change to the file.

Thanks for the insight!

> Apart from that, are you saying that the parameter hints do not appear in test files even when the import statements exist for the package?

Yes, that's what I'm referring to.

Both my test file and go file are within the same folder, but are in different packages (see [strategy 2 on this page for example](https://stackoverflow.com/questions/19998250/proper-package-naming-for-testing-with-the-go-language)).

I recently thought that maybe this was due to having both packages in the same folder, thinking maybe this wasn't the kind of situation the extension was programmed for or something. So I tried separating them into different folders, but this did not seem to make any difference.

This problem doest's seem to be happening with standard libraries like `fmt`, though. In the same line where I'm failing to see param suggestions on the funcs for my package under test, I **do** see params for packages like `fmt` so long as they're included in the import block. This gives me the impression that something isn't quite right with the detection of the package that I'm testing

The package under test doesn't have to be `go install`ed for param suggestions to work... does it?
Or is it possible that there's something in my go env that's causing a problem with param suggestions - perhaps some way that my package's params aren't being detected?

**Comment by ramya-rao-a** [comment]
@jonathan-robertson Can you share your settings? Also, when you hover on function names, do you see the complete signature + any docs associated with the function?

**Comment by jonathan-robertson** [comment]
> Can you share your settings?

Are you referring to my Visual Studio Code settings? If so, here they are:

```json
{
    "editor.tabSize": 2,

    "editor.wordWrap": "on",
    "terminal.integrated.shellArgs.osx": [
        "-l"
    ],
    "workbench.colorTheme": "Monokai",
    "workbench.iconTheme": "vs-seti",
    "window.zoomLevel": 0
}
```

> Also, when you hover on function names, do you see the complete signature + any docs associated with the function?

No signature or docs appear when I hover over any of the funcs from this package (when using them outside of their package). Actually, nothing appears - not even a blank box.

Hovering of each of these funcs when *inside* the package does show the complete signature and docs as we'd expect.

**Comment by ramya-rao-a** [comment]
What about the `Go To Definition` feature? Does that work on these functions?

**Comment by jonathan-robertson** [comment]
When I try that, a small tooltip appears with the text `No definition found for NAME` (where NAME is the func I'm trying to find the definition for).

**Comment by ramya-rao-a** [comment]
The `Go To Definition` feature, the hover feature and the signature help all use the same set of tools behind the scenes. By default they use `godef`. You can make the extension use `gogetdoc` instead by adding the setting `"go.docsTool": "gogetdoc"`

Can you open the console? From the menu, select Help -> Developer Tools, then click on console.
You should be able to see the error message from the tool (godef or gogetdoc)

**Comment by jonathan-robertson** [comment]
> You can make the extension use gogetdoc instead by adding the setting "go.docsTool": "gogetdoc"

Thank you so much!
After making this change and restarting Visual Studio Code, tips appear as expected while I'm filling in params and when I hover over a method from the package I was having trouble with before.

Using `Go To Definition` also works flawlessly now :)

<img width="621" alt="screen shot 2017-12-01 at 5 47 01 am" src="https://user-images.githubusercontent.com/5396045/33481738-704c843a-d65b-11e7-88c8-7c0d9691e062.png">
<img width="503" alt="screen shot 2017-12-01 at 5 48 14 am" src="https://user-images.githubusercontent.com/5396045/33481739-705c2174-d65b-11e7-9504-f81c42fd37d1.png">

---

> Can you open the console? From the menu, select Help -> Developer Tools, then click on console.
You should be able to see the error message from the tool (godef or gogetdoc)

Sure! For what it's worth, I tried this before making any changes and was expecting that I *might* run into trouble with `gogetdoc` as well (but `gogetdoc` works great!)

## Error when using `godef`
```
Command failed: /Users/jonathan/Documents/code/go/bin/godef -t -i -f /Users/jonathan/Documents/code/go/src/github.com/jonathan-robertson/lockedarchive/service/service.go -o 2783
godef: no declaration found for secure.GenerateKeyContainer
shell.ts:459
  | e.onUnexpectedError | @ | shell.ts:459
-- | -- | -- | --
  | (anonymous) | @ | shell.ts:419
  | e.onUnexpectedExternalError | @ | errors.ts:125
  | t.onUnexpectedExternalError | @ | errors.ts:146
  | (anonymous) | @ | goToDeclaration.ts:45
  | v | @ | winjs.base.raw.js:1209
  | enter | @ | winjs.base.raw.js:901
  | _run | @ | winjs.base.raw.js:1068
  | _error | @ | winjs.base.raw.js:1041
  | v | @ | winjs.base.raw.js:1209
  | enter | @ | winjs.base.raw.js:901
  | _run | @ | winjs.base.raw.js:1068
  | _error | @ | winjs.base.raw.js:1041
  | (anonymous) | @ | async.ts:361
  | done | @ | winjs.base.raw.js:1378
  | v | @ | winjs.base.raw.js:1224
  | enter | @ | winjs.base.raw.js:901
  | _run | @ | winjs.base.raw.js:1068
  | _error | @ | winjs.base.raw.js:1041
  | e.resolveErr | @ | lazyPromise.ts:78
  | e._receiveOneMessage | @ | rpcProtocol.ts:68
  | (anonymous) | @ | rpcProtocol.ts:32
  | (anonymous) | @ | rpcProtocol.ts:157
  | e.invoke | @ | callbackList.ts:36
  | e.fire | @ | event.ts:123
  | (anonymous) | @ | ipc.net.ts:82
  | emitOne | @ | events.js:96
  | emit | @ | events.js:191
  | readableAddChunk | @ | _stream_readable.js:178
  | Readable.push | @ | _stream_readable.js:136
  | onread | @ | net.js:560
```

**Comment by ramya-rao-a** [comment]
Ok, so looks like `godef` fails to find the definition for `secure.GenerateKeyContainer`.
I would suggest to run that command (`/Users/jonathan/Documents/code/go/bin/godef -t -i -f /Users/jonathan/Documents/code/go/src/github.com/jonathan-robertson/lockedarchive/service/service.go -o 2783`) from your terminal and see if you can get any more details on the error and then log the issue in the repo for godef.

When logging the issue on godef, if you can get a smalller code sample where you can repro, then that would be helpful for folks on godef to help.

Closing this issue as the workaround of using `gogetdoc` helps.

**Comment by jonathan-robertson** [comment]
Awesome, thanks for all the help you’ve provided! I really appreciate it :)

**Comment by ramya-rao-a** [comment]
No problem, Happy Coding!
