### ISSUE TITLE
Moving line down breaks "else" block indentation

### ISSUE THREAD

**Issue by willfaught** [microsoft/vscode-go#1198]
Start with:

```go
var w int

if x {
	y()
} else {
	z()
}
```

and put your cursor on the w declaration.

Now move the current line down, below the if/else block. It will now look like this:

```go
if x {
	y()
	} else {
		z()
	}
	var w int
```

**Comment by uudashr** [comment]
I think this goes to Go grammar on the vscode, not Go extension

**Comment by ramya-rao-a** [comment]
The indentation follows the rules specified in https://github.com/Microsoft/vscode-go/blob/0.6.65/src/goMain.ts#L269 int he Go extension which is in turn is taken from the Go grammar in https://github.com/atom/language-go/blob/813dff0ad2f5af6de1d823794daece0f397de3b8/settings/language-go.cson

I tried something similar in typescript and the indentation works just fine. So its not core vscode mis-using the indentation rules when moving lines.

The bug is in the indentation rules of Go.

**Comment by zmb3** [comment]
Works as expected in Atom, so may just want to make sure your grammar is in sync with Atom's.

**Comment by ramya-rao-a** [comment]
Grammar is the same, I think its something to do with how VS Code applies the indentation rules

**Comment by ramya-rao-a** [comment]
When the `else` appears in a new line, things are good
```
        var w int
	if x {
		y()
	}
	else {
		y()
	}
```

Instead of applying the "decrease indent rule" due to the closing `}` of the `if` block, an "increase indent rule" is getting applied due to the opening `{` of the `else` block.

cc @rebornix

**Comment by ramya-rao-a** [comment]
@rebornix Can you please transfer this issue to the VS Code repo?

**Comment by ramya-rao-a** [comment]
Closing this issue as there is no action item from the extension's side.
Please log the issue on VS Code repo if one is not already logged
