### ISSUE TITLE
go-to-definition doesnt work in diff editor for staged files

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode-go#1204]
See: https://github.com/Microsoft/vscode/issues/34034

It used to be the case that I could go to definitions directly from the right hand pane of the diff editor (ie, from the pane that represents the current version of the file). This is no longer the case, and it makes looking at diffs more challenging.  This seemed to change sometime between 2-3 months ago.

**Comment by ramya-rao-a** [comment]
Weird.. it works for me
And I tried all 3 implementations for going to definition
- default
- gogetdoc
- language server

Any errors in the dev console?

**Comment by josh-tepper** [comment]
unfortunately, nothing in the dev console.  I'll turn on tracing for the lang server to see how it's being invoked.  Will try to update later today

**Comment by josh-tepper** [comment]
This seems to affect files in the git index (ie, staged files), but not changes that are just in the working tree. Do you observe the issue with files in the index?

It seems like it's probably a vscode issue because it also affects the java plugin.

**Comment by ramya-rao-a** [comment]
That's right..

In the diff for working files, when you right click, you get the below commands in the context menu
![image](https://user-images.githubusercontent.com/16890566/30349144-c74b84a8-97c6-11e7-96e4-1518aef68c82.png)


In the diff for staged files, you get only the `Copy` command

**Comment by ramya-rao-a** [comment]
Closing this one and re-opening the upstream issue https://github.com/Microsoft/vscode/issues/34034

**Comment by josh-tepper** [comment]
@ramya-rao-a -- see the upstream issue.  It seems that the responsibility for handling index version is on the language plugins.  Not sure whether or not this is something that the go plugin would be interested in doing.

**Comment by ramya-rao-a** [comment]
Thanks for reporting this @josh-tepper and for your patience

As discussed in https://github.com/Microsoft/vscode/issues/34034, the right side view in the diff view when files are staged use what's in the index file version.

Files on disk use the scheme `file`.  The index ones use the `git` scheme. 

And all the Go related featuresare registered only for on disk files due to https://github.com/Microsoft/vscode-go/blob/0.6.65/src/goMode.ts#L10

I removed the constraint on the file scheme, and now features like Go To Definition, Find All References, Hover etc should work in the diff view for staged files. With the removal of these constraints the Go extension gets called when you hit F12 for example. And since the extension uses the file on disk to then get definitions

So if you had a case where you had both staged and unstaged changes for the same file, then things will not work as expected unless like it was suggested in the upstream issue, we replace file contents etc. I wouldnt want to go down that route yet. There is not enough ROI there.

If you are using the Go language server (which I know you do :) ), the above fix doesnt apply
The language server returns with "unable to read out-of-workspace resource from virtual file system".

Am not sure how to go about fixing that.

**Comment by ramya-rao-a** [comment]
Also do you mind giving the fix a spin? All you need to do is
- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` and reload VS Code.

Note: the fix doesnt work when you use the language server

**Comment by ramya-rao-a** [comment]
Here is a scenario where results might be unexpected.

- Say you have 2 files A and B. B uses a symbol defined in A
- There are staged changes for both A and B
- There is unstaged changes for the symbol definition in A
- Now in the staged view, run "Go to Definition" on the symbol in B

You will be taken to the symbol in file A as per file on disk and not as per the staged changes for A

**Comment by ramya-rao-a** [comment]
@josh-tepper https://github.com/Microsoft/vscode/issues/34034#issuecomment-331815272 is a convincing argument for reverting the change I made to fix this issue.

Let's open an issue for the language server instead.
