### ISSUE TITLE
"Current GOPATH" command does not work

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#124]
It says "no handler found for the command go.gopath".

![image](https://cloud.githubusercontent.com/assets/159209/11462041/302e6bfe-96c3-11e5-8a91-a88ad626512a.png)

![image](https://cloud.githubusercontent.com/assets/159209/11462043/37858806-96c3-11e5-817e-0c7c16f6bf89.png)

**Comment by lukehoban** [comment]
This is because you haven't opened any `.go` files and Code doesn't activate extensions until the filetype they apply to has been opened.  

If you open a `.go` file and then rerun, it should work.

There's no real way to fix this properly in the Go extension - something will have to be done in Code itself to address https://github.com/Microsoft/vscode/issues/810.
