### ISSUE TITLE
Sub packages in stdlib is no autocomplete

### ISSUE THREAD

**Issue by paulviks** [Microsoft/vscode-go#1263]
Hello,
last update broken autocomplete sub packages in standard library,
Example:
When i write template. after dot symbol autocomplete showing methods or types from package http/template. After update to version 0.6.66 I wrote template.Template and when save file goimports tool adding import.

Best regards,
Paul

**Comment by ramya-rao-a** [comment]
@paulviks Current version is 0.6.66
I just went back to 0.6.65, and this issue still exists. So its not the last update that has caused this issue.

Actually the root cause is that, completion of unimported packages never worked if there was more than 1 match. In your case `template` matches with both `html/template` and `text/template`.

There is no clear solution here... What should the completions have? Symbols from `html/template` or `text/template` ?

Do you see this issue with any other sub package from stdlib?

**Comment by paulviks** [comment]
Ok, my bad sorry. 
I see this case in package path/filepath. When I type filapath after dot symbol then is no show any suggestion on editor. I did not think there could be more types in different packages, and sollution is no simple.

**Comment by ramya-rao-a** [comment]
No problem,  Happy Coding!
