### ISSUE TITLE
Golang definition not working 

### ISSUE THREAD

**Issue by Jeyanthinath** [Microsoft/vscode-go#1268]
I installed vscode-go extenstion and Installed the godef as suggested , still the same error is coming when I pressed ctrl and trying to see the definition of a code 

![image](https://user-images.githubusercontent.com/2253649/31307088-87750120-ab7a-11e7-8032-dcba86e9cf80.png)

**Comment by arbourd** [comment]
This might be an environmental pathing issue. Have you checked if you can find `godef` from the VS Code console?

**Comment by Jeyanthinath** [comment]
@arbourd thanks for that , I changed the gopath and  goroot ,now things are working fine!

But one more problem raised , I cannot able to change the first gopath I set in vscode, eventhough I removed from configuration json and I set a different path in .bashrc, whenever I tired to display gopath it is showing old path

**Comment by arbourd** [comment]
It sounds like VS Code is having trouble inferring your gopath. Try setting it exactly in the settings (`go.gopath`) or playing around with the infer shell options.

You could also pop into the #vscode channel on the [Gopher's slack](https://invite.slack.golangbridge.org/) for some more assistance with your pathing.

Either way it'd be great if you could close this issue as Go To Def is working.

**Comment by ramya-rao-a** [comment]
Thanks @arbourd :)

@Jeyanthinath Did you restart VSCode after making changes to gopath in the .bashrc? If not, then those changes cannot show up.

Closing this issue for now.

If the go path set in .bashrc still doesn't show up after you removed the gopath from the VS Code settings and restarting VS Code, feel free to re-open the issue here.
