### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by srcbase** [Microsoft/vscode-go#1271]
[lukehoban.Go] Cannot read property 'substr' of undefined: TypeError: C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js Cannot read property 'substr' of undefined

**Comment by ramya-rao-a** [comment]
@srcbase This is known to happen in the latest release if you are working on a Go file but you do not have any folder opened in VS Code.

Current workarounds until I release the next update are
- Open the folder containing the file you are working on in VS Code and then continue as usual OR
- Install the Go extension from master which has the fix for this issue. Steps for this are
     - Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
     - Run `code --install-extension Go-latest.vsix` from the command line
     - Reload VSCode
