### ISSUE TITLE
Autocompletion of current function doesn't happen in Godoc comment

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode-go#1291]
![vsc](https://user-images.githubusercontent.com/50314/31794547-afc28074-b4f0-11e7-9031-3c11685cbf1a.gif)

Say I have this:

```go
// SetT<caret>
func SetThing() {
}
```

I expect code completion to automatically suggest `SetThing` for me. If I type `SetT`, nothing happens. If hit cmd-space to force autocompletion, I might get `SetThing` (or something else starting with `SetT`), but it's a textual autocompletion, not a code completion.

Apologies if this has come up before. I distinctly remember writing about it in a comment, a long time ago.

**Comment by ramya-rao-a** [comment]
There are multiple layers at play here

1. Completions do not appear as you type when inside comments. This is a VS Code feature. You can tweak this by editing the `editor.quickSuggestions` setting
2. When you do force a autocompletion, the Go extension intentionally does not invoke `gocode` for suggestions when typing inside a line comment as it was considered as noise
3. Funnily `gocode` does get invoked when you are inside a block comment. This is because there was no simple way of figuring out the start and end of the block comment without parsing the whole file contents

One solution I have in mind is to invoke gocode for line comments if `editor.quickSuggestions` supported comments. i.e if `editor.quickSuggestions` was set to `true` or `editor.quickSuggestions.comments` was set to `true`, then the Go extension will return suggestions when inside comments.

Or we will have to introduce a new setting just to enable suggestions inside comments

Thoughts?

**Comment by atombender** [comment]
That sounds like a good solution. I didn't know about the `editor.quickSuggestions` setting, thanks.

**Comment by zh-h** [comment]
![default](https://user-images.githubusercontent.com/13273151/36098857-883154f8-103b-11e8-9eec-d3e96f1dfbc9.png)

@atombender  d42e48bf30a3da3936bf1d7f5bbbd8b2e51dd66a This is my solution, but i thing it is useless now😥

**Comment by ramya-rao-a** [comment]
Closing this in favor of #1005
