### ISSUE TITLE
Cannot undo rename

### ISSUE THREAD

**Issue by jchannon** [Microsoft/vscode-go#13]
If you use the rename functionality then press CMD+Z nothing happens

**Comment by newhook** [comment]
I don't think it is possible to support this correct with the current gorename command as gorename directly changes the source files.

**Comment by lukehoban** [comment]
@newhook Agreed - this is a limitation of using `gorename`.  Since the underlying library provides a modifiable global variable bound to the function which actually writes the files to disk I have some hope that either the existing `gorename` could be enhanced to provide the results of the rename to stdout instead of writing to disk, or that a new custom front-end to the underlying library could be used by the `vscode-go` tooling to work around this.

**Comment by lukehoban** [comment]
See also https://github.com/golang/go/issues/13355.

**Comment by lukehoban** [comment]
Note that with https://github.com/golang/go/issues/13355 now in gorename, it should be possible to fix this.

**Comment by ramya-rao-a** [comment]
This feature is now available in the latest version of the Go extension : 0.6.44

**Note**: Needs `diff` tool which is not available on Windows by default. Windows users can install it from [DiffUtils for Windows](http://gnuwin32.sourceforge.net/packages/diffutils.htm)
 In the absence of the `diff` tool, rename operation will work as it did before i.e change the file on disk.

**Comment by daniel-trinh** [comment]
When I undo after a rename, it seems to only undo the change in the current file, instead of across all files. 

This is on macOS 10.12, using Go extension : 0.6.55.

Am I missing something?

**Comment by ramya-rao-a** [comment]
undo in VS Code has always been applicable on the current file. @rebornix correct me if I am wrong

**Comment by rebornix** [comment]
@ramya-rao-a AFAIK, undo doesn't cross files, which is a predictable behavior.

**Comment by daniel-trinh** [comment]
Fair enough, I suppose I'll just do another rename instead of an undo. The reason I thought this was possible was because Intellij IDEA seems to do undos across files after a rename. Thanks for the response.
