### ISSUE TITLE
new feature requests comparable to other IDE's

### ISSUE THREAD

**Issue by chandradeepak** [Microsoft/vscode-go#1312]
- Unused variables and functions should be highlighted in gray color. Right now they are all in same color.
- We know clicking on field takes it to its definition. but if clicked on struct field should populate all the references for that field or a function . (this is  very useful)
- Find all references is very slow when compared to other IDE's
- go.gocodeAutoBuild": false should be false by default . I spent 2 hours figuring out why intellisense was slow. Any new user who feels frustrated with intellisense will switch to other IDE's if they don't know how to fix it. 
- If i open a project called say sarama then the root folder should be sarama and there should be sub folders inside that . Now the root folder or the project directory is not shown. this is useful if you have multiple projects open we can immediately tell which is which by seeing the root folder .
- Importing should import default and standard by default .  for example if i start typing fmt.Println it should import fmt . Now it asks for fmt package in various other github projects i have in my GOPATH.  
- Also we should be able to see the project view and the whole class view in visual studio which lets you browse through the structs and functions easily.
- Rename a struct field should be easier . now it has some thing called symbol rename but it is difficult . In Gogland it allows to do shift + F6 and we can rename a field and all the reference of that filed would be automatically renamed.
- There should be option to disable the right side overview that is shown which shows code like a snake.
- go debugger should be built in 
- using vscode ICONS color theme made the IDE much more friendly
- The right side bar which gives a over view should have red, yellow highlighting the errors.

**Comment by chandradeepak** [comment]
<img width="1414" alt="screen shot 2017-11-01 at 12 29 21 am" src="https://user-images.githubusercontent.com/6901293/32264406-c6533158-be9b-11e7-90d4-9e7a968f07f0.png">

**Comment by radu-matei** [comment]
> Find all references is very slow when compared to other IDE's

This is why I came to the repo! I think it might also search in the `vendor` folder? Personally I don't need this unless I'm doing it in a file from the `vendor` folder.

**Comment by alexsasharegan** [comment]
## Import Precedence: Std Lib default

>Importing should import default and standard by default . for example if i start typing fmt.Println it should import fmt . Now it asks for fmt package in various other github projects i have in my GOPATH.

I was going to create a feature request around this. I think a configuration option to create auto import precedence would be ideal. The most sane default for such a config option being the go std lib bubbles to the top of the import autocomplete list.

**Comment by ramya-rao-a** [comment]
@chandradeepak Thanks for the detailed feedback. I'll try to address them as best as I can


- > Unused variables and functions should be highlighted in gray color. Right now they are all in same color.

Red for errors and Green for warnings is the standard used in VS Code. Using different colors based on the type of error will not scale well. The error/warning text shows up when hovering over the lines which has the error/warning as well as when using the F8 key to navigate between the error/warnings. This should help in identifying the unused variables and functions


- > We know clicking on field takes it to its definition. but if clicked on struct field should populate all the references for that field or a function . (this is  very useful)

The `Find all references` feature does exactly that when run on the struct field.

- > Find all references is very slow when compared to other IDE's

We use the `guru` tool for this feature which tends to get slow on large projects or in Windows. Unless there is an alternative tool that does better, we cannot do much here.

If you are not on Windows, you can try the [language server from Sourcegraph](https://github.com/Microsoft/vscode-go/blob/master/README.md#go-language-server-experimental)

- > go.gocodeAutoBuild": false should be false by default . I spent 2 hours figuring out why intellisense was slow. Any new user who feels frustrated with intellisense will switch to other IDE's if they don't know how to fix it. 

Since version 0.6.69 of the Go extension that was released in late Nov 2017, `go.gocodeAutoBuild` is set to `false` by default. Reasons to do this were:
       - The `-i` passed to `go build` ensures dependent packages are up to date
       - The `autoBuild` feature of `gocode` has shown to affect performance in larger projects
       - The `gocode` author's lack of confidence in the autoBuild feature

- > If i open a project called say sarama then the root folder should be sarama and there should be sub folders inside that . Now the root folder or the project directory is not shown. this is useful if you have multiple projects open we can immediately tell which is which by seeing the root folder .

I do see the name of the root folder in CAPS in the file explorer. Below "VSCODE-GO" is the folder I've opened in VS Code

<img width="656" alt="screen shot 2018-01-07 at 7 07 51 pm" src="https://user-images.githubusercontent.com/16890566/34658181-afb7300e-f3e1-11e7-9693-1e0f9bcd10a8.png">

- > Importing should import default and standard by default .  for example if i start typing fmt.Println it should import fmt . Now it asks for fmt package in various other github projects i have in my GOPATH. 

Since version 0.6.69 of the Go extension that was released in late Nov 2017, the pkgs from std lib do show up before the others.
 
- > Also we should be able to see the project view and the whole class view in visual studio which lets you browse through the structs and functions easily.

Try the commands `Go: Browse Packages`, `Go to Symbol in File..` and `Go to Symbol in Workspace`. These should cater to most of your needs. If you are still looking for a tree view on the side for the symbols in the current file, then you can try out the extension [Code Outline](https://marketplace.visualstudio.com/items?itemName=patrys.vscode-code-outline)

- > Rename a struct field should be easier . now it has some thing called symbol rename but it is difficult . In Gogland it allows to do shift + F6 and we can rename a field and all the reference of that filed would be automatically renamed.

We use the tool `gorename` to provide the symbol rename feature. If you have any trouble with it, please log an issue at https://github.com/golang/tools/

- > There should be option to disable the right side overview that is shown which shows code like a snake.

I am assuming you are referring to the minimap. Run the command `View: Toggle Minimap` or use the "View" menu and then select "Toggle Minimap"

- > go debugger should be built in 

The Go extension for VS Code uses a reputed set of Go tools from the Go open source community to provide all the language features. For debugging, we use [delve](https://github.com/derekparker/delve). Do you have any issues using the current setup for debugging Go code?

- The right side bar which gives a over view should have red, yellow highlighting the errors.

Again, I am assuming you are referring to the minimap which is a feature from core VS Code and extensions have no control over it. Please log a feature request at https://github.com/Microsoft/vscode/issues.

**Comment by ramya-rao-a** [comment]
Closing this issue as I believe I have addressed all the points.

Happy Coding!
