### ISSUE TITLE
Import command adds imports to wrong block

### ISSUE THREAD

**Issue by ahmetb** [Microsoft/vscode-go#1356]
When I use cmd+shift+p &rarr; "Go: Add import" to add a vendored package, it always adds it to the top of import block that contains stdlib packages:

For example, the `k8s.io/apimachinery/pkg/labels` package here, I used "Go: Add import" to add it. (see screenshot below)

Gofmt (or some other linter) fixes the problem when the file is saved, but I'm curious if it can be added directly to the right block (i.e. conventionally 2nd block).

![image](https://user-images.githubusercontent.com/159209/33041380-f90cb5cc-cdf2-11e7-9f7e-de57505b3fb6.png)

**Comment by ahmetb** [comment]
Actually saving the file does not fix the problem, I was wrong:

![image](https://user-images.githubusercontent.com/159209/33041479-48e75e6c-cdf3-11e7-9874-7aa3b25510ff.png)

**Comment by ramya-rao-a** [comment]
The 3 are the options for the formatting tool used by the Go plugin are `gofmt`, `goimports` and `goreturns` which can be set using the setting `go.formatTool`.

`gofmt` re-arranges the imports so that they are in an alphabetical order. If there are groups inside the import block (blank lines between imports on consecutive lines), then the groups are retained, the imports inside a group is arranged in alphabetical order

`goimports` and `goreturns` do the same + group the imports such that the std lib ones are in a different group than the others. If any of the groups inside the import block contains a mix of std and non std lib pkgs, then the group is split. This explains what is happening in your case. To confirm, can you remove the empty lines between the import statements (so that there is just 1 group) and try adding the said import?

**Comment by ramya-rao-a** [comment]
I would suggest to log this issue with `goimports`.
It should do the right grouping no matter where a new import statement gets added.
