### ISSUE TITLE
Security of analysis tools

### ISSUE THREAD

**Issue by davidlazar** [microsoft/vscode-go#1412]
vscode-go depends on [several analysis tools](https://github.com/Microsoft/vscode-go/wiki/Go-tools-that-the-Go-extension-depends-on) that are maintained by at least 13 different developers in different repositories. When vscode-go installs these tools, it simply fetches the latest code from these repositories, and then runs that code directly. An attacker that wants to run malicious code on my machine just needs to compromise any one of these 13 repositories and commit malicious code. I also worry that this attack might not be detected for awhile since some of these repositories are not very visible (e.g., [acroca/go-symbols](https://github.com/acroca/go-symbols) has 3 stars and 4 commits).

I don't know what the right solution is. Perhaps vscode-go could sandbox the execution of these tools. Maybe vscode-go should at least pin down versions (or commits) of these tools.

**Comment by davidlazar** [comment]
Issue #1342 seems related.

**Comment by ramya-rao-a** [comment]
Hey @davidlazar,

Thanks for reporting the issue, and my apologies for not getting to it sooner.

After this issue was logged, there have been quite a few changes to the tools installation process
- The `Go: Install/Update Tools` command now shows the list of tools that the extension wants to install and allows the user to pick & choose. This list also has description around the feature that the tools power.
- Clicking on `Analysis Tools Missing` brings up a prompt that has an option `Show` that will show exactly what tools are to be installed. This list has been trimmed down to the bare essentials.
- If you are using the language server, then most of the other tools are not needed. #2753 tracks the work needed to not show Analysis Tools Missing in such cases


These improvements still don't solve the initial problem of not knowing or trusting the master branch of certain tools.

My hope is that with the new module system, we should be able to target particular versions of these tools. Will keep this issue open to target the tools one by one as they move on to using modules.

**Comment by stamblerre** [comment]
> * If you are using the language server, then most of the other tools are not needed.

> My hope is that with the new module system, we should be able to target particular versions of these tools. Will keep this issue open to target the tools one by one as they move on to using modules.

`gopls` gets installed at the latest released version, with automatic update detection when a new version is released. @hakim has also worked on installing tools at a specific version in the extension.  I think that this model is something we should aim to move toward for all tools.

**Comment by stamblerre** [comment]
I'm going to close this issue in favor of this one upstream: https://github.com/golang/vscode-go/issues/47. Modules have fixed the security issues, but there are still other improvements that can be made.
