### ISSUE TITLE
Bad user experience and general feedback

### ISSUE THREAD

**Issue by anjmao** [Microsoft/vscode-go#1432]
Hi, I wanted to give some feedback about vscode-go and some suggestions for general improvements.

1) Currently it relies on native go tools like golint, gorename, goreturn and so on. For example when I do rename of some variable vscode-go just calls gorename.exe and runs it. Then gorename needs to parse AST and analyse files to rename all usages. This happens everytime so there is no way for gorename to save and cache parsed AST. This also means vscode-go can't do any performance optimisations and currently it is really slow, rename can take even 5 seconds for a small project. Please correct me if I'm thinking wrong :)

2) I saw there is project go language server https://github.com/sourcegraph/go-langserver. Maybe it can improve look and feel in general and give more refactoring features like extract method, implement interface an so on, similar like in Goland.

**Comment by ramya-rao-a** [comment]
Using native Go tools to give Go language support has been a general practice among most editors. Example: Vim, Atom, Sublime, Emacs etc. all of which I believe is open source as well.

I can't speak for Goland. Its proprietary code and not open source. It definitely has a dedicated team of engineers knowing Go in and out where as in comparison vscode-go is an open source project, has 1 person (me) giving about 10% of my time to it and powered by the open source community.

I would definitely prefer to use a language server instead of various native tools. The main reason being exactly what you have covered. But there is no language server for Go at the moment providing comprehensive coverage of necessary features. 

The language server from sourcegraph (that you have linked) gives some read only features like Go to definition, Find all references, Symbol search etc. and not write related features like rename, auto-completions, refactoring etc.

I do appreciate your feedback though I'd have preferred you had taken a look at our README first. We do provide an option (since March 2016) where you can choose to the use the Go language server from source graph. Please see https://github.com/Microsoft/vscode-go/blob/master/README.md#go-language-server-experimental

I would suggest you to log feature requests in (or better yet contribute to) the language server from source graph for the write related features. vscode-go can then make use of these features.
