### ISSUE TITLE
Manually run metalinter

### ISSUE THREAD

**Issue by wayneashleyberry** [Microsoft/vscode-go#1451]
I've found `gometalinter` to be too slow and sometimes too annoying to be set as my default linter, but I do like running it occasionally to see what it reports. Would it be possible to register a command in the command palette to run `gometalinter` manually?

**Comment by canercidam** [comment]
I've been having a similar problem lately with `gometalinter`. Every time I hit on save after I code a bit, all of my 4 cores reach 100% and memory usage jumps by 1-1.5 GB for like 5 seconds. In #1373, a useful suggestion was setting `go.lintOnSave` to `false` and using `Go: Lint Current Package` command. So my workaround to this issue turned out to be as following:

`keybindings.json`:
```json
...
{
    "key": "ctrl+l",
    "command": "go.lint.package"
}
...
```

However, after doing this, `Output` window annoyingly started showing up every time I hit `Ctrl+L` so I also had to toggle it afterwards. I ended up combining the command with toggle by using `macros` extension which can be found [here](https://marketplace.visualstudio.com/items?itemName=geddski.macros):

`settings.json`:
```json
...
"macros": {
    "goLint": [
        "go.lint.package",
        "workbench.action.output.toggleOutput"
    ]
}
...
```

`keybindings.json`:
```json
...
{
    "key": "ctrl+l",
    "command": "macros.goLint"
}
...
```

**Comment by ramya-rao-a** [comment]
@wayneashleyberry Like @canercidam has suggested you can use the command `Go: Lint Current Package` to lint manually and disable the lint on save feature in the settings.

@canercidam I have logged #1456 for the issue of the output pane popping up

**Comment by wayneashleyberry** [comment]
Hi @ramya-rao-a, although that is a possible workaround I might have explained my request poorly. I want to run `golint` on save, that default behaviour is perfect for me. That works 99% of the time, but every now and then I want to run the metalinter just to see what it finds. That's why I wanted it as a separate command, so I could keep the default behaviour and just invoke the metalinter when needed. I'll carry on doing it from the command-line though, not a big deal :) Thanks for all your great work on this plugin!

**Comment by ramya-rao-a** [comment]
@wayneashleyberry You can have both. You can keep the default behavior of linting on save and run the command `Go: Lint Current Package` from the command pallet whenever you want.

**Comment by canercidam** [comment]
@wayneashleyberry Hmm, so it should use `golint` on save and command should be able to use `gometalinter`? Which means different values for `go.lintTool` in `settings.json`.

**Comment by wayneashleyberry** [comment]
Ah yes, tasks look like they fit my needs... thanks @ramya-rao-a 

I see global tasks are also [on the todo list](https://github.com/Microsoft/vscode/issues/1435), great :)
