### ISSUE TITLE
GLFW undefined: "strdup" error when launching from VSCode

### ISSUE THREAD

**Issue by dericatienza** [Microsoft/vscode-go#1465]
- VSCode Version: 1.19.1
- OS Version: Windows 10 Pro

Hi.

I've been following this tutorial https://medium.com/@drgomesp/opengl-and-golang-getting-started-abcd3d96f3db to learn OpenGL with Go. I was able to follow the tutorial and have the project run through "go run main.go" command. But, when I run the project through VS Code's built-in debugger, an undefined: "strdup" error shows up.

![capture](https://user-images.githubusercontent.com/5621894/34958134-76c2f6e4-fa6b-11e7-8391-afa02ab74ae6.PNG)

Any ideas on what may be causing this?

**Comment by ramya-rao-a** [comment]
Are you able to run delve from the command line and debug the program?

**Comment by dericatienza** [comment]
No. Tried running "dlv debug" but same errors pop up.

**Comment by ramya-rao-a** [comment]
In that case, the problem is specific to the project you are working on.
I would suggest getting in touch with others who might have worked on the same project.
The Gophers slack channel is a good place to start.

Or you can log a bug in the repo for [delve](https://github.com/derekparker/delve/). Someone there will definitely be able to help. Make sure to submit sample code that they can use to repro
