### ISSUE TITLE
Linux/Ubuntu: command 'go.tools.install' not found

### ISSUE THREAD

**Issue by alexellis** [Microsoft/vscode-go#1514]
Not sure if I've filled in this template properly.

```
code -v
1.20.0
c63189deaa8e620f650cc28792b8f5f3363f2c5b
x64

code --list-extensions
PeterJausovec.vscode-docker
chenxsan.vscode-standardjs
lukehoban.Go
ms-vscode.csharp
```

If you have a question, please ask it on https://gitter.im/Microsoft/vscode-go or on the VSCode channel in Gophers Slack(https://invite.slack.golangbridge.org/)

If you have issues around GOPATH, read https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension first.

If you have issues debugging your Go programs
- read https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code first.
- set `"trace": "verbose"` and share the resulting logs in the debug console

If this is a bug report, please share 
- a sample code which can be used to reproduce the issue

Control+Shift+X - install Go tools results in:

```
 command 'go.tools.install' not found
```

- any Go related settings you might have added/changed

I removed and added the extension again for Go. I closed / re-opened vscode this didn't help.

I manually did the `go get` steps for the gofmt toolchains etc.

GOPATH is set correctly and GOPATH/bin is in my PATH

Steps to Reproduce:

1. save a file and nothing happens
2. try to install go tools and see error in the title.

I've tried following the steps in the closed issues by the same name - i.e. running the command in a `go` folder or file.

![error-go-install](https://user-images.githubusercontent.com/6358735/36077051-a16e4f86-0f5d-11e8-9c9d-340593c39128.png)

**Comment by ramya-rao-a** [comment]
Is only the `Go: Install/Update Tools` command not working and other features of the extension working fine? For eg: Go to definition, intellisense, building, linting etc. Try the command `Go: Current GOPATH`

Any errors in the console? Help -> Toggle Developer Tools -> Console

**Comment by alexellis** [comment]
No none of that is working from what I can tell. I'll turn on the console and report back.

**Comment by ramya-rao-a** [comment]
@alexellis Any errors from the console?

**Comment by AaronReboot** [comment]
I'm also experiencing this issue since yesterday, where all the Go tools have stopped working. I've tried completely removing VSCode & reinstalling Go tools.

This is the message I see when I try to install Go tools
![image](https://user-images.githubusercontent.com/14034112/36107654-c7f538fa-0fe8-11e8-8b25-e5a101141dff.png)

This is the message when I try to show my current Go path
![image](https://user-images.githubusercontent.com/14034112/36107679-d8782066-0fe8-11e8-9c80-31813bfb204e.png)

I'm running VSCode 1.20.0 on macOS High Sierra with Go 1.9.4

**Comment by ramya-rao-a** [comment]
@AaronReboot Please share the errors from the console when you get these messages. Help -> Toggle Developer Tools -> Console

Chances are the extension is not getting activated. Can you uninstall the extension and install it again?

**Comment by AaronReboot** [comment]
That worked! Thanks for the speedy assistance! Odd that uninstalling & reinstalling the extension was more effective than completely uninstalling VSCode. Cheers

**Comment by ttjiaa** [comment]
Also experiencing this problem, VS Code v1.20, Go extension v0.6.76.

Reinstalling the extension did not solve the issue.

See the attached for the extension activation error logs:

![screen shot 2018-02-12 at 1 30 06 pm](https://user-images.githubusercontent.com/9013477/36112922-239b1e9e-0ff9-11e8-9917-f61c42456bd5.png)

**Comment by ramya-rao-a** [comment]
@AaronReboot Installed extensions are stored in a separate location than the VS Code itself. This lets you update/re-install VS Code and still have the extensions you previously had installed. That's why re-installing VS Code almost never helps with issues related to extensions

@ttjiaa In your case, the extension seems to have ended up in a bad state with missing files. Delete the folder `~/.vscode/extensions/lukehoban.go-0.6.76` and re-install the extension

**Comment by ttjiaa** [comment]
@ramya-rao-a Thanks! Deleting the extension directory first and then reinstalling the extension solved the issue. I recently updated VS Code, which is when issue showed up.

**Comment by ramya-rao-a** [comment]
@ttjiaa And you have never installed the Go extension using a vsix?

**Comment by ttjiaa** [comment]
@ramya-rao-a No, I have not.

**Comment by jonas27** [comment]
Hey, for me installed the tools directly in the go dir (so at ~/go/). When I moved them to ~/go/bin everything worked fine.
It's kind of odd, as my settings (GOPATH and GOBIN) are the same as on my desktop and my laptop, but on my laptop it didn't work by default but it worked on my pc...
