### ISSUE TITLE
Support for delve's rewind command

### ISSUE THREAD

**Issue by t-bast** [microsoft/vscode-go#1529]
Hey guys,

Thanks for this amazing plugin which makes it a breeze to use Go in VS Code!
With the release of Delve 1.0.0 (and Go 1.10) it's now possible to use Mozilla RR to debug execution traces and delve added a handy `rewind` command.

I haven't found a way to make the rewinding work inside VS Code, do you have tips on that?
Or is it a feature you're already working on?

I've posted this issue in Delve, but it looks like it's more suited on vscode-go (probably as a feature request): https://github.com/derekparker/delve/issues/1128

Thanks!

**Comment by lggomez** [comment]
Now that the initial port to v2 API is merged we can look forward to support this feature. What do you think @ramya-rao-a?

Just to start, these are the 3 initial steps that come to mind:

* Adding the [StepBack and ReverseContinue requests](https://github.com/Microsoft/vscode/blob/634d73f9de07884f6dc2b3d3fd4a8c74f17231c5/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L592-L627) to the debug adapter
* Integrate said requests with the [rewind](https://godoc.org/github.com/derekparker/delve/service/rpc2#RPCClient.Rewind) apicall. I assume that each invocation goes one step back
* Add proper compatibility checks and configuration flags (in case that rr isn't supported on all backends or in certain scenarios)

**Comment by lggomez** [comment]
@ramya-rao-a I'm a bit puzzled on the implementation of this feature, after taking a more in-depth look:

#### VS Code
The [debug protocol](https://github.com/Microsoft/vscode/blob/634d73f9de07884f6dc2b3d3fd4a8c74f17231c5/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L592-L627) certainly states that these events are supported, but I can't find how to trigger this action from the [editor](https://code.visualstudio.com/docs/editor/debugging) (BTW, where is supportsStepBack configured?)

#### Delve
The rewind command, in terms of flow, is just a continue in the [opposite direction](https://github.com/derekparker/delve/blob/60c58acb8eae98135d4afd0713c116e6c2f4e6ca/service/api/types.go#L289-L292) to the previous (immediate) target, and the expected requirement is that the target comes from a process recording. I guess that this will depend on the remote dlv replay instance, so as long as we handle errors accordingly we should be fine

So delve isn't difficult to integrate per se, but I don't know how to test the VS Code side, can you give me some advice?

**Comment by ramya-rao-a** [comment]
cc @roblourens who might have some ideas here.

**Comment by roblourens** [comment]
All you have to do is return `supportsStepBack: true` from the Initialize request, and the step back buttons will appear in the debug widget.

**Comment by rogchap** [comment]
Is this still in active development? Seems like it may be forgotten about. This would be a great addition to the vs code tool set for Go.

**Comment by lggomez** [comment]
I don't have previous experience using rr so after taking a quick look at the documentation I found that I needed to make a recording of an existing go application. I didn't dwell too much into that and I moved on to other issues/features, and it seems like no one else took this for the time being

If you can help with the former I'can try to retake this

**Comment by rogchap** [comment]
I think there are two tasks: reverse debugging (should be straight forward... no pun intended) and then enabling advanced debugging with rr.

Could take some inspiration from Goland: https://blog.jetbrains.com/go/2019/03/04/debugging-with-goland-advanced-debugging-features/

**Comment by lggomez** [comment]
@rogchap after neglecting it for a little more time (sorry!) I finally tried it and surprisingly it works without any complex changes. Well, sort of, considering delve support and/or rr itself aren't in a completely stable or broadly compatible stage yet

This is a basic example I tested (uses gomodules, I don't know if this makes things messier or not right now):

![Screenshot from 2019-04-03 21-31-21](https://user-images.githubusercontent.com/6326271/55521647-fab7be00-5657-11e9-99ff-f101fa54ffde.png)

You may notice that symbols barely work as of today, but the replay feaure is, indeed, working. I'm not sure about what else can we do on the adapter side to make things smoother, but it can be shipped as an experimental feature (after all, both delve and rr must be kept up to date separately as more stable releases arrive)

Stepback actions are something that can be worked on a separate track, and I intend to do so

**Comment by rogchap** [comment]
This is awesome @lggomez! Thanks for looking into this. Will be a great addition.

**Comment by lggomez** [comment]
Some updates:

> Stepback actions are something that can be worked on a separate track, and I intend to do so

After a little research, I found out that step back isn't supported by delve yet, but it supports reverse continue via [Rewind](https://godoc.org/github.com/derekparker/delve/service/rpc2#RPCClient.Rewind), which is only for replay scenarios. In this case, to replay rr traces which as of today are an intel/linux-only feature. Due to this, these actions are actually something that belong only to this track. I'm working on implementing its corresponding requests on the debug adapter alongside rr support

@ramya-rao-a @roblourens: `supportsStepBack: true` adds the step back and reverse continue buttons to the debug controls, but due to the limitations of this backend it's a linux-only feature (also only on "replay" mode debug, which I added on the rr branch)
Do you have any ideas on how to achieve this conditional initialization? The [InitializeRequestArguments](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/contrib/debug/common/debugProtocol.d.ts#L303-L326) type does not contain any info that allows me to set supportsStepBack using this logic, and I assume this is the only point in which this configuration may be overriden

**Comment by lggomez** [comment]
I came back to this after these months and I've fixed the remaining issues, now the branch is up to date and basically being able to work with traces (github does not support webm in comments so here goes the compressed demo):

[Screencast 2019-11-11 20:36:01.webm.zip](https://github.com/microsoft/vscode-go/files/3833662/Screencast.2019-11-11.20.36.01.webm.zip)

And the test app with its corresponding traces:

[helloworld_modules.zip](https://github.com/microsoft/vscode-go/files/3833752/helloworld_modules.zip)
[helloworldmodules-traces.zip](https://github.com/microsoft/vscode-go/files/3833680/helloworldmodules-traces.zip)

There are two traces in the zip:
* helloworldmodules-1: recorded on a binary compiled with the default compiler optimizations
* helloworldmodules-2: recorded on a binary compiled with all optimizations disabled (`-gcflags '-N -l'`). This is the trace shown in the demo

Only two improvements remain as it is now:
* I would prefer to disable the step back button rather than have to return an error from the debug adapter
* What do you think about adding a warning message about breakpoints and variable state on trace replays not being exact due to possible compiler optimizations on the recorded binary? Using this workflow ought to be enough warning of this possibility but I think an explicit one on our side would be helpful

**Comment by ramya-rao-a** [comment]
Hello all,

We are in the midst of a repo move, see [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in our readme for more details.

Please subscribe to https://github.com/golang/vscode-go/issues/110 for further updates on this issue.

The PR from @lggomez has been moved to the new repo and can be found in https://github.com/golang/vscode-go/pull/89

Happy Coding!
