### ISSUE TITLE
Package suggestion

### ISSUE THREAD

**Issue by klaidliadon** [Microsoft/vscode-go#155]
If you are in the first line of a new file, or the file misses the `package` declaration the editor should suggest it (taken from other files in the package, or from the directory name if it's the first file)

**Comment by lukehoban** [comment]
How would this work exactly?  When would this suggestion happen, and with what UX?

I can imagine that typing `package ` would bring up a completion list with the suggested package name selected.  However, that would pretty much have to be implemented in https://github.com/nsf/gocode.

I can't think of other great UX for this.

**Comment by klaidliadon** [comment]
If you have a black file and start writing `p` the editor should suggest `package whatever` using the package name or the folder name, in the same way that `fu` suggests `func`.

Selecting the suggestion insert the package followed by 2 newlines.

**Comment by polds** [comment]
+1

GoSublime in SublimeText does this.

**Comment by lukehoban** [comment]
Got it.  

Unfortunately, the built-in snippet mechanism in VS Code (which is what provides the `func` and `pkg` snippets currently) can't handle this because there is no way to provide a global snippet context for a file.  

But we can probably do a one-off addition to the `GoCompletionItemProvider` that is only added when you are in a file with no non-whitespace.
