### ISSUE TITLE
Use current gopath in integrated terminals

### ISSUE THREAD

**Issue by RichyHBM** [microsoft/vscode-go#1578]
As mentioned https://github.com/Microsoft/vscode/issues/45692 settings files cant make use of commands, currently the extension provides go.gopath as a command but this cant be used with the internal terminal. 

Ideally the current calculated gopath should be exposed as a variable accessible in settings, or the extension should add the calculated gopath to the environment variable gopath for the internal terminal.

**Comment by RichyHBM** [comment]
This issue would also fix #1525

**Comment by ramya-rao-a** [comment]
Using the results of commands in the settings is something that can be only supported upstream.

For now, here in the Go extension, what we can do is this:
- Add a setting `go.useGopathInTerminal` with default value as `false`
- If this is `true`, then when the Go extension activates, it can calculate the go path using the existing command and add it in the `terminal.integrated.env...` setting.
- If this is `false`, then prompt the user `Use the GOPATH as inferred by the Go extension in all integrated terminals?`. If they choose yes, then add the setting `"go.useGopathInTerminal": true` and do the needful

The reason why I wouldn't do this by default is because we don't want to update user settings that can change VS Code behavior without their consent.

PRs are welcome to add this feature and I can guide anyone who wants to give this a try.

**Comment by galileo-pkm** [comment]
"Use current gopath in integrated terminals" if this means that the integrated terminal GOPATH should be overridden, that is the wrong way to address the problem. 
As explained in the #1525 some of us have multiple folders in $GOPATH.

**Comment by extrame** [comment]
What is the roadmap of this feature? @ramya-rao-a

**Comment by extrame** [comment]
I try to use
`
"terminal.integrated.env.osx": {
        "GOPATH":"${env:GOPATH}:${workspaceFolder}",
    }
`

But It doesn't work.

If I change GOPATH to a unused variable like :

`"terminal.integrated.env.osx": {
        "TEST":"${env:GOPATH}:${workspaceFolder}",
    }`

It works.

Sound like setting of GOPATH in terminal.integrated.env.osx is overrided by others

**Comment by ramya-rao-a** [comment]
@extrame Using `terminal.integrated.env.osx` to set GOPATH works as expected for me. Are you sure you don't have any extensions that might be doing the overriding? Try disabling all other extensions, reload VS Code and try again

**Comment by extrame** [comment]
I got the problem, I set my GOPATH in ~/.bash_profile, Maybe vscode internal terminal set the env GOPATH before exec ~/.bash_profile, after delete the line in ~/.bash_profile, It seems OK.

BUT

where should I set my system GOPATH except ~/.bash_profile ....

**Comment by extrame** [comment]
@ramya-rao-a

**Comment by extrame** [comment]
@ramya-rao-a more test:

GOPATH locate in /AAA/BBB 
PROJECT locate in /Users/xxx/workspace/PROJECT

config "terminal.integrated.env.osx": { "TEST":"${env:GOPATH}:${workspaceFolder}", }

set GOPATH as /AAA/BBB in ~/.profile, mac terminal got it ok.

But vscode internal terminal got empty, GOPATH=":/Users/xxx/workspace/PROJECT"

**Comment by ramya-rao-a** [comment]
@extrame How the terminal gets the environment variables is not affected by this extension. I would suggest to log an issue in the main vscode repo i.e https://github.com/Microsoft/vscode/issues

**Comment by issenn** [comment]
add `[[ -z "$GOPATH" ]] && export GOPATH="${HOME}/go"`  into `~/.zshrc` or `~/.zshenv` or `~/.zprofile` or `~/.bashrc`.
and add settings into workspace json
```
    "terminal.integrated.env.osx": {
        "GOPATH": "${workspaceRoot}/.go",
    },
```

**Comment by stamblerre** [comment]
It sounds like this issue can only be satisfactorily resolved upstream in VS Code. I would be wary of adding additional modifications to handle inferring the GOPATH, especially as modules become more prevalent. @ramya-rao-a: Can we close this issue?

**Comment by ramya-rao-a** [comment]
Agreed.
