### ISSUE TITLE
Code completion is slow with multi-workspace GOPATH

### ISSUE THREAD

**Issue by burdiyan** [Microsoft/vscode-go#1583]
Similar to `$PATH` variable `$GOPATH` can consist of multiple segments. The motivation for doing that is described in this blog post: https://dmitri.shuralyov.com/blog/18

Basically it's useful to separate libraries you install with `go get` with your own code.

The problem is that, VS Code start being VERY slow when doing code completion, sometimes automatic imports don't work at all and overall the experience stops being pleasant at all.

I'm not sure if that is the issue with VS Code or with the underlying tools it is using.

**Comment by ramya-rao-a** [comment]
Are you referring to the automatic imports that gets added on file save or the ones that get added when you auto-complete a symbol from an unimported package?

If its the former, then they are done during the formatting process using the `goreturns` tool (or `goimports` if you have updated the `go.formatTool` to use `goimports`).
Formatting is run on save by default. If it takes longer than 750ms then the format on save is aborted. If you can change this time using the `editor.formatOnSaveTimeout` setting.

For completions, we use `gocode`. Try getting completions from `gocode` from a terminal and compare the speeds to figure out if the problem is with the underlying tool or VS Code
