### ISSUE TITLE
Support attaching and detaching from remote debug server without killing the process

### ISSUE THREAD

**Issue by radu-matei** [Microsoft/vscode-go#1609]
Related: https://github.com/Microsoft/vscode-go/issues/1599#issuecomment-377214763

If you have a long running process and start a `dlv attach --headless` session, then you point VS Code to that host and have a debug session, after you stop debugging from VS Code you would expect the remote process to continue running - but the extension actually sends a Halt request to the debug server.

It would be extremely helpful (for this and for other extensions using this Go debugger) to support gracefully detaching from remote processes without killing them.

**Comment by lggomez** [comment]
A similar issue: if you launch a remote debug session and the headless server isn't up it seems that the debug task hangs forever waiting to connect

I thought that the client connection had a defined [timeout](https://github.com/Microsoft/vscode-go/blob/master/src/debugAdapter/goDebug.ts#L400-L410), although it may be missing something

**Comment by ramya-rao-a** [comment]
@radu-matei We do a halt + restart in that case and do not kill any process explicitly. I dont know why we went with halt + restart instead of detach without killing, as that was before my time. 

Sending a detach command needs halting as well, so we can look into halt + detach instead of halt + restart

Thoughts?

**Comment by olegburov** [comment]
Hi @ramya-rao-a, is there any update on this issue?

It would be supper handy if I VS Code can accept input from `fmt.Scan` while debugging  such a simple code as follows:

``` go
package main

import "fmt"

func main() {
	fmt.Println("What's your name?")

	var s string
	fmt.Scanln(&s)

	fmt.Printf("Hello, %s", s)
}
```

**Comment by ramya-rao-a** [comment]
@radu-matei 

> If you have a long running process and start a dlv attach --headless session, then you point VS Code to that host and have a debug session, after you stop debugging from VS Code you would expect the remote process to continue running - but the extension actually sends a Halt request to the debug server.
It would be extremely helpful (for this and for other extensions using this Go debugger) to support gracefully detaching from remote processes without killing them.

In order to send a Detach request, we need to first send a Halt request. See https://github.com/go-delve/delve/blob/4c9a72e486f1f0d0c90ecede8415a871dced8117/Documentation/api/ClientHowto.md#gracefully-ending-the-debug-session

@olegburov Your scenario is being tracked in https://github.com/Microsoft/vscode-go/issues/219. Please subscribe to that issue for further updates

**Comment by ramya-rao-a** [comment]
Since we can't really send the detach request without halting the dlv process first, there is nothing much we can do for this issue. Therefore, I am closing it.

We will continue to work to on #1599
