### ISSUE TITLE
Feature/Fix to properly show {{ .Variable }} in template inline style.

### ISSUE THREAD

**Issue by oswee** [Microsoft/vscode-go#1648]
Currently, when {{ .Variable }} is used in element inline style, there is error shown in editor.

![image](https://user-images.githubusercontent.com/20469200/39383934-c03da212-4a73-11e8-9ffc-092038987e82.png)

**Comment by ramya-rao-a** [comment]
Is that in a Go file? If yes, then the error is coming from running `go build`. What does the error say? Do you get the same when running `go build .` on the parent folder of this file?

**Comment by ramya-rao-a** [comment]
"Syntax highlighting" is the term for just coloring the text in a file as per the language specifications. This is covered in #464

In your case, the problem are the syntax errors i.e the red squiggly lines under the text. Since you are using an .html file the html extension kicks in. Since it cannot understand the `{{ }}` syntax, it gives the error.

For those errors to go away, we need an extension that can understand both html and go. I believe that is covered in #228
