### ISSUE TITLE
f in func and main() { are errors?

### ISSUE THREAD

**Issue by 3darcher** [Microsoft/vscode-go#1652]
I'm new to programming in Go but I've used vscode with python without any issues. If I install this Go package, which vscode keeps recommending, I get errors everywhere. Every .go file is red in the file menu. The main issue is...

main() {    is an error.
the f in func is an error. Doesn't matter if it is func main() or func foo, the f in func is an error in every .go file.
index_handler(w http.ResponseWriter, r *http.Request){ is an error.
`package main

import "fmt"

func main() {
	fmt.Printf("hello, world\n")
}`
is there anyway I can uninstall this package without vscode continuing to pop up that this is recommended?

**Comment by 3darcher** [comment]
GOPATH is set correctly. There are no details given when I hover on the error.

**Comment by ramya-rao-a** [comment]
Are you hovering on the text in the editor or on the file name in the explorer?
Are there any errors listed in the Problems view? Open View -> Problems

**Comment by 3darcher** [comment]
Hovering over the text in the editor. No info popup. No errors listed anywhere.

**Comment by ramya-rao-a** [comment]
It is not possible that there would be red underlines in the text editor but nothing under the **Problems** view

Can you share a screenshot where you see the red lines as well as the Problems view open?

**Comment by 3darcher** [comment]
I'm trying to learn to program in Go. I waisted to much time trying to get this plugin to work right that I wasn't actually programming, so I uninstalled it, and set vscode not to recommend it. I don't really care what you think is possible and not possible, my objective is to code and not worry about the editor. Thanks for you help, but I'm moving on.

**Comment by ramya-rao-a** [comment]
Wow, I didnt realize I hit a nerve there. Though I'd very much like to get to the bottom of how this is happening, I realize your time is precious and you might want to just learn Go rather than fight with the editor. All the very best in your journey to learn Go. 

In the future if you get back to using this plugin, we are here to help either via [gitter](https://gitter.im/Microsoft/vscode-go) or [slack](https://invite.slack.golangbridge.org/) or issues in this repo.

Good luck and Happy Coding!
