### ISSUE TITLE
cmd/go: unsupported GOOS/GOARCH pair undefined/undefined

### ISSUE THREAD

**Issue by ghuser404** [Microsoft/vscode-go#1674]
In workspace settings specifying `GOARCH` and/or `GOOS` makes them undefined, which leads to the error message: "cmd/go: unsupported GOOS/GOARCH pair undefined/undefined".

**Comment by ramya-rao-a** [comment]
How are you specifying them in settings?

**Comment by ghuser404** [comment]
Like so: `"go.toolsEnvVars": { "GOARCH": "arm", "GOOS": "linux" }`

**Comment by ramya-rao-a** [comment]
@ghuser404, @bGN4 

I believe this got fixed in master with https://github.com/Microsoft/vscode-go/pull/1665
Can you try the below?

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code

**Comment by ramya-rao-a** [comment]
This bug fix is now out in the latest update to the Go extension (0.6.80)

**Comment by 0x5010** [comment]
![image](https://user-images.githubusercontent.com/18439186/41958758-93b9a810-7a1d-11e8-9ee0-32e0d2335271.png)
same problem,  go extension (0.6.83)

**Comment by ramya-rao-a** [comment]
@0x5010 In your case, it doesnt say "cmd/go: unsupported GOOS/GOARCH pair undefined/undefined"

It says `js/wasm` instead which doesnt look like valid values for GOOS/GOARCH
