### ISSUE TITLE
Another high CPU report, plus orphaned processes

### ISSUE THREAD

**Issue by jblachly** [Microsoft/vscode-go#1686]
Steps to Reproduce:

0. `Darwin myhostname.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64`
1. Install latest VS Code (Version 1.23.1 (1.23.1))
2. Install latest vscode-go (0.6.80)
3. Open go project workspace
4. Save file

At this point, various numbers of "gocode", "golint", and "godef" processes are launched which consume, in aggregate, > 50% of CPU (often much more). It is not clear that any actual work is being performed, as they continue to consume high CPU even when not interacting with VS Code in any way). This causes the fans to spin up and stay up.

Now, to add to prior reports, if I quite VS Code, the high-cpu gocode/golint/godef processes remain running in the background, consuming high CPU. They are not zombies, and can be killed with SIGTERM.

This unfortunately makes VSCode + vscode-go unusable for me, as I have to `killall -9 <whatever>` every 5-15 minutes while developing in go.

Let me know what other diagnostics I can do to help.

**Comment by ramya-rao-a** [comment]
`golint` is the linter that is run on each file save. On larger code bases, we recommend turning off the on [save features](https://github.com/Microsoft/vscode-go/wiki/On-Save-features) and instead run them on demand using the commands from the command pallet

`godéf` is run to provide the information you see when you hover on code.
`gocode` is used to provide auto-completions.

The Go extension spawns a new process to run each of these tools everytime a completion/hover/lint request is fired. 

I believe one improvement we can do is to add a timeout to features that are time sensitive. The information shown on hover, code completion are good examples of such features.

By the way, when you say "Open go project workspace", do you mean the source code for Go? I want to try and repro this myself.

**Comment by jblachly** [comment]
@ramya-rao-a Thank you for your note. To be clear, when I said "open go project workspace," I meant any workspace with go code in it. In my case, these projects are quite tiny, consisting of < 2500 SLOC. The out of control CPU problems happen even in these small projects. I have never opened something so large as the go codebase itself.

One thing that I suspect could be happening is that gocode is spawning the linter on every imported library (which are in my GOPATH -- I am not using vendored subrepos). So for example, despite my codebase being small, it could be scanning logrus, a websockets library, jsonparser, influxdb, and whatever other zillion things I'm importing.

Regarding `gocode` and `godef` processes, it is interesting that these (a) consume such constant high CPU even when I am not interesting with VSCode, and (b) continue consuming high CPU even long after VSCode itself has been closed.  A timeout could partially fix this by having them terminate themselves (eventually), but does not explain why they use such high CPU.

Please let me know if I can help produce any other diagnostics.

**Comment by ramya-rao-a** [comment]
If your GOPATH itself is very large, then that might explain the issues with certain Go tools as they try to work with the entire GOPATH.

Can you try a small/medium size Go program in a separate GOPATH which is considerably smaller and see if you still see the same?
Tip: Set `go.inferGopath` to `true` so that you dont have to set GOPATH specifically in the 2 separate projects

**Comment by ramya-rao-a** [comment]
@jblachly Any updates?

**Comment by jblachly** [comment]
@ramya-rao-a haven't had any long vscode-go coding sessions to definitively say, but setting go.inferGopath to true seems to have made a massive improvement.

My GOPATH has always been set to ~/Development/go , which contains hundreds of packages (most dependencies, the minority mine) under src/ -- is this no longer a recommended setup?

**Comment by jblachly** [comment]
@ramya-rao-a  Actually, I retract my prior comment that everything is fine.

15 minutes after quitting vscode, `gocode` processes are still using in aggregate an entire core (~56% CPU each)

```
james            96734  56.6  0.1 575249204   6756   ??  R    11:20PM   4:20.55 /Users/james/Documents/Development/go/bin/gocode set
james            96740  56.2  0.1 575249460   7292   ??  R    11:21PM   0:38.61 /Users/james/Documents/Development/go/bin/gocode set package-lookup-mode go
james            96742   0.0  0.1 575231528   6912   ??  S    11:21PM   0:00.03 /Users/james/Documents/Development/go/bin/gocode -s -sock unix -addr 127.0.0.1:37373
```

**Comment by ramya-rao-a** [comment]
That's some new information!!

I don't know why the first 2 processes (`gocode set`) should still be lingering around. The 3rd one is for the gocode daemon which runs in server mode in the background and this one doesn't seem to be taking any CPU. The first 2 are for setting the options which should exit right away.

We have now moved to use gocode from https://github.com/mdempsky/gocode instead of https://github.com/nsf/gocode as the latter as issues with Go 1.10 and above. Can you kill all existing `gocode` processes and then follow the below steps to get the latest version of this extension from master and let me know if it makes any difference? 

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code
- Run `Go: Install/Update Tools`. If there is a currently running gocode process (which there will be if you were typing code in the editor before this) that the extension was not able to close, then the logs that show the progress of the tool updates will ask you to kill it and then try again
- Kill the process manually and then run the `Go: Install/Update Tools` again. At this point, you should have a clean installation of `mdempsky/gocode`
