### ISSUE TITLE
Autocompletion is not working on dep vendored dependencies, while code hover/following does

### ISSUE THREAD

**Issue by tristan957** [Microsoft/vscode-go#1687]
`"go.gopath": "/home/tristan957/go:/home/tristan957/Projects/full-stack-example/backend"`
Project structure: `backend/src/api/src/main.go`

main.go
```go
package main

import "github.com/gin-gonic/gin"

func main() {
	gin.SetMode(gin.DebugMode)
	r := gin.Default()
	r.GET("/ping", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "pong",
		})
	})
	r.Run() // listen and serve on 0.0.0.0:8080
}
```

Steps to Reproduce:
1. Use `dep` to add `gin` dependency
2. Start typing `gin.SetMode`

Am I doing something wrong?

**Comment by ramya-rao-a** [comment]
The text that appears on hover and the auto-completion feature are powered by 2 separate tools.
I don't use `dep` myself, so don't know if this problem is dep specific. Please ask other Go developers in the Gophers slack channel. There should definitely be someone there who uses VS Code and dep

Meanwhile, here is something you can do to troubleshoot the auto-completion issue.

Run the below in a terminal
```
gocode close
gocode -debug -s
```

Then try for completions again in VS Code.
You will see the output for each completion attempt in the terminal. 

That should tell you if `gocode` is not able to return completions

**Comment by tristan957** [comment]
I'll give that a go later today @ramya-rao-a . I reached out on slack but have so far been unsuccessful
