### ISSUE TITLE
Optionally enable go-metalinter support?

### ISSUE THREAD

**Issue by NHOrus** [Microsoft/vscode-go#17]
Currently, [Metalinter](https://github.com/alecthomas/gometalinter) is extremely useful linter.
Go Vet, Go Lint and other highly useful tools are included
As it provides massaged output of composite linters, is it possible to use it as (optional) replacement/enchancement for aforementioned Vet and Lint tools?

**Comment by lukehoban** [comment]
Sounds like a great idea.  

Should be easy to add support for that either as the default linter or as an option to use instead of discreet lint/vet.

**Comment by lukehoban** [comment]
Open to PR's adding support for this.  

I'd suggest adding a `go.lintTool` setting that can optionally point to an alternate tool to run instead of `golint`.  That would allow users to opt-in to using `gometalinter` once they have installed and configured it.

A further step would be to make it the default.  I think we should wait on that, since the acquisition experience for `gometalinter` is incrementally more complex.

**Comment by joeblew99** [comment]
this would be awesome !

**Comment by GoBijan** [comment]
I came here because I wanted to propose support for https://github.com/alecthomas/gometalinter, too :)
Atoms Go Plugin and SublimeText have support for this. Maybe one could have a look at the Atom implementation for adding support to vscode (are the APIs similar because of the electron shell?): https://atom.io/packages/gometalinter-linter

**Comment by sijad** [comment]
@lukehoban `golint` and `gometalinter` outputs are a little different:

`golint`:

```
<file>:<line>:[<column>] (<linter>)
```

`gometalinter`:

```
<file>:<line>:[<column>]: <message> (<linter>)
```

value of `message` usually is `error`, `warning`, `info`, `debug`, etc
[regex](https://github.com/Microsoft/vscode-go/blob/master/src/goCheck.ts#L38) need to be changed, is it right?

**Comment by sijad** [comment]
@lukehoban output of `golint` and `gometalinter` are a little different, with current regex can't parse `gometalinter` output

**Comment by lukehoban** [comment]
@sijad Feel free to propose an update to the regexp to make sure `gometalinter` output can be handled.

**Comment by JohanSJA** [comment]
There is an PR for this.Wondering what is the progress on that? @sijad @lukehoban

**Comment by punya** [comment]
`gometalinter` can also produce JSON output, if that makes parsing easier.

**Comment by joeblew99** [comment]
@lukehoban JSON parsing helps ?
I am keen to get this into VSCode :)

**Comment by egamma** [comment]
I suggest to look into how some of the existing linters are implemented for VS Code. ESLint is a good example [vscode-eslint](https://github.com/Microsoft/vscode-eslint), [tslint](https://github.com/Microsoft/vscode-tslint), and jshint are implemented in the same way. The idea is to implement a linter as a [language server](https://code.visualstudio.com/docs/extensions/example-language-server). The language server is kept a live and receives buffer change requests from VS Code (over JSON RPC), runs the linter (in proc) on the changed buffer, and returns the errors diagnostics back to VS Code. Doing the linting inside a server avoids that a new process is restarted for each validation as the user types.

**Comment by sijad** [comment]
https://github.com/Microsoft/vscode-go/pull/294 is almost finished, it just need a review I guess

**Comment by egamma** [comment]
Nice. This implementation spawns a new process for each linting pass. Since the linter is native code and since this is only done on save this might not be too bad for the batteries.

**Comment by mattetti** [comment]
This issue can be closed now that the feature is implemented and documented :)

**Comment by lukehoban** [comment]
Indeed. Thanks @sijad.
