### ISSUE TITLE
Watch window broken

### ISSUE THREAD

**Issue by mbenkmann** [Microsoft/vscode-go#1714]
The latest update (0.6.81) has broken the Watches window. Just try setting any watch expression while debugging.

**Comment by ramya-rao-a** [comment]
@mbenkmann Thanks for reporting! I can repro. Until we can figure out a fix for this, please use the 0.6.80 version of the extension by downloading the vsix from https://github.com/Microsoft/vscode-go/releases/tag/0.6.80 . Add `"extensions.autoUpdate": false` to your settings so that the extension doesn't get auto-updated.

cc @lggomez This is a regression from the changes we made to the debug adapter

**Comment by lggomez** [comment]
I'm looking at it @ramya-rao-a

**Comment by lggomez** [comment]
The rpc name for the v1 api was missing for watch requests, it seems to be working now on the attached PR. PTAL @ramya-rao-a

**Comment by ramya-rao-a** [comment]
Thanks @lggomez! That was my mistake. I didnt include the right rpc name when I brought back v1 support.

@mbenkmann Can you add `"useApiV1": false` to your debug configuration? That should enable you to watch the variables without any issues.

I'll release an update next week with the fix.

**Comment by heeko** [comment]
``"useApiV1": false`` is fixing the watch window for a "classic" run, but on my side the ``debug test`` codelens remain broken. Is there also a way to force that parameter for the ``debug test`` codelens?

**Comment by ramya-rao-a** [comment]
This is fixed in the latest version of the Go extension (0.6.83)
