### ISSUE TITLE
find all reference much slower than GoLand

### ISSUE THREAD

**Issue by YueHonghui** [Microsoft/vscode-go#1722]
The experience of vscode is very good. It almost becomes my major IDE. But I find that `Find All Reference` 
 is much slower than GoLand on big project(github.com/kubernetes/kubernetes). I wonder if some optimization such as index makes the difference. Can vscode improve the speed of `Find All Reference`?

**Comment by ramya-rao-a** [comment]
`Find All References` is slow because the tool we rely on (`guru`) is slow.
If you are not on Windows, you can try using the [language server support](https://github.com/Microsoft/vscode-go#go-language-server-experimental) by adding `"go.useLanguageServer": true` in your settings. The `Find All References` feature there might be faster.

The Go extension itself doesnt maintain any indexing and we rely on Go tools to provide all the Go related features. And so, there is nothing we can do from the Go extension's side, unless there is a faster alternative to `guru`. Or if the [language server from Sourcegraph](https://github.com/sourcegraph/go-langserver) creates and maintains some indexing.
