### ISSUE TITLE
Outline navigation

### ISSUE THREAD

**Issue by uudashr** [Microsoft/vscode-go#1725]
Steps to Reproduce:

1. Open go file
2. Open command palette (mac: cmd + shift + p)
3. Type "Focus on outline"
4. Tap from the outline, will open "Untitled-1" editor
<img width="454" alt="screen shot 2018-06-09 at 10 12 44" src="https://user-images.githubusercontent.com/166053/41187168-09337f52-6bce-11e8-88c9-4e0807bb97e8.png">

Expect navigate to the symbol

**Comment by ramya-rao-a** [comment]
@uudashr and others (@konrin, @lcg635, and @amsokol) who have upvoted this feature:

This is fixed in master.  Please give it a try by following the below steps and share any feedback you have.

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo and use the `Go-latest.vsix` file from the cloned repo
- Reload VS Code

**Comment by uudashr** [comment]
Awesome... The outline works.

A thought:
Seems vscode make the outline based on currently opened file. Go may best shown based on packages. The idea is that the outline view can be replacement for the file based tree view.

Found similar https://marketplace.visualstudio.com/items?itemName=766b.go-outliner, but this extension can't navigate to sub package, still require tree view to do that.

**Comment by ramya-rao-a** [comment]
We have the `Go: Browse Packages` command to browse packages and files under them.
The outline feature from VS Code is still in its preview state.
Let's wait and see how it evolves and re-visit this later
