### ISSUE TITLE
Allow using dlv v2 apis when debugging tests via codelens or debug files without config

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#1735]
At present there is no way to use dlv v2 apis when debugging tests via codelens or debuggging files without a debug config in the launch.json file.

See https://github.com/Microsoft/vscode-go/issues/1555#issuecomment-396431638

**Comment by lggomez** [comment]
I can work on this, it's a pity I couldn't make it to 0.6.83

To recap: the change has be done here:  https://github.com/Microsoft/vscode-go/blob/0.6.82/src/goRunTestCodelens.ts

As you mentioned in https://github.com/Microsoft/vscode-go/issues/1555#issuecomment-396415464, currently there isn't a straightforward way to bypass the hardcoded config in the codelens provider and use the launch config from there. That would have been the prefered way since it would be really dynamic and only tied to the actual debug configuration selected by the user

Either way, we still have to be able to access the settings from the provider if we wanna make this optional to follow the intended transition to v2 [plan](https://github.com/Microsoft/vscode-go/issues/1555#issuecomment-389004730)

**Comment by ramya-rao-a** [comment]
> To recap: the change has be done here: https://github.com/Microsoft/vscode-go/blob/0.6.82/src/goRunTestCodelens.ts

Am confused... You have already done the changes or you are providing a pointer as to where the change has to be made?

Let me know if you have any questions or want me to take a stab at this.

**Comment by lggomez** [comment]
It is just a reminder on this new issue. I haven't started any work on this yet
