### ISSUE TITLE
IntelliSense for import missing when using mdempsky/gocode

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-go#1747]
Hi, @ramya-rao-a,

this extension is awesome, but I miss IntelliSense for imports (built-in and my own packages).

![image](https://user-images.githubusercontent.com/30043375/41705313-4b967cb0-7541-11e8-8c86-fca8de432076.png)

**Comment by devnet-uk** [comment]
I also experience this issue with mdempsky/gocode. However if I switch back to nfs/gocode it works.

**Comment by ramya-rao-a** [comment]
Thanks for that insight @devnet-uk 

Looks like `mdempsky/gocode` does not support a lot of cases that is supported by `nfs/gocode`.

Can someone log an upstream issue for this?

**Comment by ramya-rao-a** [comment]
I've logged an upstream issue for this. See https://github.com/mdempsky/gocode/issues/38

**Comment by ramya-rao-a** [comment]
Now that there is active development on an official language server for Go via [gopls](https://github.com/golang/go/wiki/gopls) which will provide the auto-completion feature as well, there is no further planned work in the auto-completion feature that is coming directly out of the extension.

This issue is being closed in favor of having the auto-completion feature from the language server which will not have the same problem.

For more on language server integration with this extension, please see [Go language server](https://github.com/microsoft/vscode-go#go-language-server)

To go a feature request for gopls, use the [Go issue tracker](https://github.com/golang/go/issues/new?title=x%2Ftools%2Fcmd%2Fgopls%3A%20%3Cfill%20this%20in%3E)
