### ISSUE TITLE
Missing "Go to implementation" option

### ISSUE THREAD

**Issue by resouer** [Microsoft/vscode-go#1755]
If this is a bug report, please share 
- a sample code which can be used to reproduce the issue
  Can be reproduced on any golang repo.
- any Go related settings you might have added/changed
  Nope

![image](https://user-images.githubusercontent.com/1701782/41851392-48b74692-78ba-11e8-8352-f23747617890.png)

ENV:

1. Go 0.6.83 - 15th Jun, 2018
2. Code: Version 1.23.1 (1.23.1)

**Comment by ramya-rao-a** [comment]
That was an intentional design choice done in VS Code as `Go to implementation` was found not as commonly used as `Go to definition` or `Find all references`.

https://github.com/Microsoft/vscode/issues/9285 tracks the feature request for user configurable menus

You can use the command `Go to implementation` from the command pallet. The keyboard shortcut for it is Cmd+F12
