### ISSUE TITLE
intellisense autocompletion stops working

### ISSUE THREAD

**Issue by IIInsomnia** [Microsoft/vscode-go#1758]
![image](https://user-images.githubusercontent.com/6582246/42077797-9a20b08c-7bac-11e8-886a-0fc86b8c8d5c.png)

![image](https://user-images.githubusercontent.com/6582246/42077817-b4455c38-7bac-11e8-85c8-8d80669c71ed.png)

golang version: 1.10.3

**Comment by ramya-rao-a** [comment]
- Ensure you are using the latest version of the Go extension (0.6.84)
- Run the command `Go: Install/Update Tools`. Select `gocode` from the choices and click ok.

This will update and re-compile your version of `gocode`.

Then try again.

**Comment by IIInsomnia** [comment]
I updated the extension and go tools, but it doesn't work.

**Comment by danf0rth** [comment]
I Having the same issue, but not sure that this is problem of last version, because i start using vsc + golang extension a few weeks ago

- Go extension version `0.6.84`
- Go version `go1.10.2 linux/amd64`

![screenshot_2018-07-02_14-30-03](https://user-images.githubusercontent.com/14220891/42161689-8db9255e-7e04-11e8-9068-849bac7a95ee.png)

**Comment by ericgreene** [comment]
Doing the following worked for me. 

1. Quit vscode. 
2. Go to running processes and kill gocode if it's still running
3. Install/update gocode: ```go get -u github.com/nsf/gocode```

**Comment by lsytj0413** [comment]
same problem.

**Comment by danf0rth** [comment]
I tried to use `nsf/gocode` before and it did not solve the problem, made it even worse. I installed it again, and now autocomplete works more better!

I think, that the problem was because i didnt kill the process.
