### ISSUE TITLE
Support autocompletion for custom packages

### ISSUE THREAD

**Issue by msudgh** [Microsoft/vscode-go#1784]
I have some custom packages in my project but while importing packages and calling them methods, I don't get any autocompletion.

What's wrong? Does extension support autocompletion for custom packages?

**Comment by ramya-rao-a** [comment]
VS Code has been using https://github.com/nsf/gocode to provide completions without any issues for a long time. Since gocode has issues with Go 1.10, we were suggested by its author to use a fork of gocode and so we recently moved to using https://github.com/mdempsky/gocode.

The latter has issues with completions for custom packages. This is covered in #1723 and https://github.com/mdempsky/gocode/issues/32. Please subscribe to either of those 2 issues for further updates.
