### ISSUE TITLE
Attempt to get absolute path on every line of test output causes wrongful paths

### ISSUE THREAD

**Issue by Hunsin** [microsoft/vscode-go#1836]
Plugin version: 0.6.85
Go version: 1.10.3

Just a simple file, example_test.go:
```go
// ...
logger := log.New(os.Stdout, "", log.Lshortfile)
logger.Println("Hello!")
// output: example_test.go:10: Hello
// I miss a "!" so that it will show FAIL when running test
```

This is the output by clicking `run package tests` from plugin:
![log_shortfile_1](https://user-images.githubusercontent.com/6940170/43937403-ff377416-9c8f-11e8-99d2-12f51bf38518.png)

And this is the output from terminal directly, also what I expected:
![log_shortfile_2](https://user-images.githubusercontent.com/6940170/43937404-ff5c8652-9c8f-11e8-9a6e-f6cd1d9e6fb3.png)

Any idea?

**Comment by ramya-rao-a** [comment]
Well, we intentional present the complete path so that it is clickable and the corresponding file opens in the editor on the right line number :)

**Comment by Hunsin** [comment]
Ah..., I see.
Is there any document about it? Something like overwriting the outputs.

**Comment by ramya-rao-a** [comment]
There is no option to override it at the moment, I'll look into what options we can add

**Comment by haleyrc** [comment]
This recently caused some confusion for me as the heuristic is overly greedy and will prepend the absolute path even if the short filename isn't the first item in the entry such as when you use both `log.Ltime` and `log.Lshortfile`. In fact, it does this even if using `log.Llongfile`.

**Comment by ramya-rao-a** [comment]
@haleyrc Can you give a small code sample where you see the issue so that I can take a look at what's causing it?

**Comment by haleyrc** [comment]
@ramya-rao-a Absolutely, and sorry for the delay. https://github.com/haleyrc/vscode-go-issue demonstrates the issue I'm having.

**Comment by ramya-rao-a** [comment]
Interesting... I see it now.

I believe this only happens when you are using the `-v` flag and then use the `log` pkg to print anything. 

The fix should be pretty straight-forward.  We shouldnt be attempting to get the absolute path on an output line unless it is for a test failure. Such lines are always preceeded by a `--- FAIL:`, so we can make use of that.

PRs are most welcome to fix this issue.

Code Pointers:
- Set up [local dev environment](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension) for the Go extension
- [processTestResultLine](https://github.com/Microsoft/vscode-go/blob/latest/src/testUtils.ts#L250) is the function called on each line of the test output. And so the fix needs to go there.

**Comment by MagnumOpus21** [comment]
Okay this is something I can work on if no one else has dibs on this 😁

**Comment by ramya-rao-a** [comment]
Go ahead @MagnumOpus21 :)

Remember to test all the 4 test commands:
- Test at cursor
- Test file
- Test package
- Test workspace

**Comment by peergynt** [comment]
It's probably worth mentioning the following issue here: https://github.com/golang/go/issues/25369

It looks like a possible "fix" for this issue is to make sure that the output line starts with at least a tab (pre go-1.11) or with 4 spaces (go1.11+).

Note @andybons comment:
> I think it’s fine. If someone is relying on the textual output of tests instead of using the JSON output, then this will be a good reason for them to switch :)

So maybe the better solution is to use the test JSON output?

**Comment by ramya-rao-a** [comment]
Hey all,

I've pushed 2 changes to restrict the attempts to expand text that looks like a relative path 
- Skip doing so when test passes
- Follow @peergynt's suggestion above to look for lines in error output starting with tab or 4 spaces.

Please try the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension that has these changes and let me know how it fares

**Comment by ramya-rao-a** [comment]
The above mentioned changes are now available in the latest version of this extension.
