### ISSUE TITLE
Coverage UI not updating upon writing comments in the source code

### ISSUE THREAD

**Issue by MikeWarren2014** [microsoft/vscode-go#1852]
This is both an issue and a feature request: 

- It's an issue because comments are inert by the code compiler, yet simply adding comments to the source code under test breaks the coverage highlighting feature. 
- It's a feature request, because, by [this logged issue](https://github.com/Microsoft/vscode-go/issues/1104#issuecomment-324063874), that feature breaking happens <q> because we can't guarantee that the change hasn't changed the test results </q>. Also, because my job here, and use case, is that I'm responsible for both documenting and testing my team's code. 

All I'm doing, for documentation of the source code, is **inserting line comments** before the function declarations.

**Comment by ramya-rao-a** [comment]
The event that is fired on content change has details on the actual change including the range and the text. And so it is possible for us to check if the content being changed/added is part of a line comment.

Code Pointers:
- [Build and Debug Extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code) to get started
- The [removeCodeCoverage](https://github.com/Microsoft/vscode-go/blob/0.6.87/src/goCover.ts#L54) that receives the content change event

**Comment by lggomez** [comment]
As @ramya-rao-a said, we cannot guarantee that these changes don´t break the code, because we lack the syntactic context in order to be able to detect any invalid token combination. Also, the document received on the event handler contains the latest, already modified version, so we can´t even handle cases like newlines whithin valid code lines

That said, we can still ignore the coverage changes on events and lines that only contain anything that matches the /s regex pattern (any whitespace, tab, or newline/carriage return). I know this use case won´t help you in your particular scenario but it might still be worth it to handle from an usability point of view

This is something I made for these scenarios, can you verify it?
https://github.com/Microsoft/vscode-go/compare/master...lggomez:coverage_changes

**Comment by ramya-rao-a** [comment]
@lggomez Catering just to whitespace and newlines doesnt help much. A whitespace or a newline is almost always followed by some text.

How about checking if the content being changed/added is part of a line comment?

**Comment by karthikraobr** [comment]
@ramya-rao-a  I have created a PR for fixing the coverage being removed on comments. Works only with single line comments. Any pointers on how to go about fixing this issue for multi-line comments.

**Comment by ramya-rao-a** [comment]
@karthikraobr's fix works for single line comments
The only way we can extend this to multi line comments is to parse the file and keep track of the entire file contents which is something we generally avoid doing for perf reasons.

Therefore, closing this issue as there is no further work planned here
