### ISSUE TITLE
interactive debug console

### ISSUE THREAD

**Issue by gertcuykens** [microsoft/vscode-go#186]
Is it possible to make the console interactive so you can do delve commands in the console
For example to set `trace main.go:13 i`

Currently I get this when I try for example the delve help command.

`exception while processing request (exception: Cannot read property 'currentGoroutine' of null)`

![image](https://cloud.githubusercontent.com/assets/863731/12657077/daba7cbc-c601-11e5-8c7b-2562e7a7e489.png)

**Comment by lukehoban** [comment]
Right now, the debug console evals Go expressions, much like the JS Console windows in browser dev tools.  It is not a top level Delve REPL.

The design of Delve actually makes it a little challenging to provide a Delve REPL directly here, since the Delve backend RPC API knows nothing about the Delve REPL front-end.  

We may in the future be able to expose the Delve REPL directly here - potentially with some appropriate escape character prefix (`!threads`?).  But that likely will require some refactoring of Delve that I expect won't happen in the short term.

**Comment by gertcuykens** [comment]
friendly ping @lukehoban to reply on delve, thx

**Comment by gertcuykens** [comment]
It's not the appropriate place for technical reason because of RPC interface I agree, but form a pure development standpoint I think a good amount of people will launch dlv in the terminal just to have this ability and don't have to click anything. Try dlv cmd line a few times, it makes you wish for a hybrid cmd line where vscode just highlight de variables and line of code and the cmd line does everything else.

**Comment by ramya-rao-a** [comment]
Based on the current state of delve and this extension, the ability to run delve commands in the debug console is not possible at the moment.

If at a future time anything changes to make it possible to have this feature we can re-open this issue or create a new feature request, but for the time being, I am closing this issue as there is no action item at present.
