### ISSUE TITLE
Save doesn't trigger buildOnSave if no changes were made

### ISSUE THREAD

**Issue by EmpireJones** [Microsoft/vscode-go#1862]
Steps to Reproduce:

1. Set "go.buildOnSave": "package"
2. Add a build error to code
3. Hit save, see "Problems" listed
4. Open file in another package (which doesn't have errors) to be the current file
5. Restart VSCode, which opens the file from step 4
6. Return to file/package from step 2
7. Hit save, see "No problems have been detected in the workspace so far."

To get the package to rebuild and show errors/warnings, you need to make a change and hit save.

This can be annoying in various scenarios:
- If you are going through packages to auto update an import name by hitting save
- You just want to see a list of the current errors, or verify that there are no errors in a package
- You think there are no errors, and then try doing a symbol rename, which fails because errors exist.

**Comment by mmwtsn** [comment]
This also means tools like gofmt and goimports aren't running 😕

**Comment by ramya-rao-a** [comment]
The build/format on save features in the Go extension are tied to the file save event fired by VS Code. These events are not fired when saving a file with no changes.

When there are no changes in a file and you want to run build/format on it, then there are commands for it.

Use `Go: Build Current Package` to build and `Format Document` to format.
You can also use the `Format Document` command from the context menu on the editor. (Right click -> Format Document)

**Comment by EmpireJones** [comment]
Would it make more sense for me to bring this up with the upstream vscode project, to trigger this event when saving a file with no changes?

**Comment by ramya-rao-a** [comment]
There are a lot of tasks that listen to the file save event. Both in core VS Code and all the extensions. Not triggering the event when there are no file changes is by design to save the unnecessary reactions. It also saves all the listeners from making the check themselves on whether the file has changes or not.

If you feel running a command from the command pallet is tedious, then you can bind a keyboard shortcut for it. The format command already has a keyboard shortcut.

Or you can just add a whitespace and then hit save.

**Comment by EmpireJones** [comment]
This seems like an odd user experience decision, but maybe everyone else has a different workflow than me. I should be able to hack together some command sequences with the functionality described on https://github.com/Microsoft/vscode/issues/871.

Thanks for the quick response

**Comment by ramya-rao-a** [comment]
Going through the scenarios in your initial description, the feature request here is to have the build and formatting run on a file when you open it. The fact that we do this on file save and thus you tried to save the file is a way around the initial requirement of having build/format run **on demand** on a file.

#118 tracks exactly this. But since there are issues trying to implement that, the next best alternatives are commands that can be run anytime on demand
