### ISSUE TITLE
Variables view doesn't show anything

### ISSUE THREAD

**Issue by asampal** [Microsoft/vscode-go#187]
delve version: 06bba9b7a9ad0e06f4d74bf71f7667d24872a838
Visual Studio Code 0.10.6, vscode-go 0.6.22, Windows 10 64 bit

When I break at `fmt.Println(field.Tag.Get("color"), field.Tag.Get("species"))` in the following code, I would expect the variables view to show `s`,`st`, and `field`, but the view is empty. Adding these variables to the watch view seems to work fine.

```go
package main

import (
	"fmt"
	"reflect"
)

func main() {
	type S struct {
		F string `species:"gopher" color:"blue"`
	}

	s := S{}
	st := reflect.TypeOf(s)
	field := st.Field(0)
	fmt.Println(field.Tag.Get("color"), field.Tag.Get("species"))
}
```

**Comment by lukehoban** [comment]
@asampal I can't repro this, but there's a couple of things which may be causing you too see it:

* The crash you reported in Delve related to this code on Windows may have caused Delve to crash while vscode was trying to render the variables.  This would have happened at some stage where you broke on an earlier line in the file.
* The vscode debugger appears to have a bug where if a debugAdapter ever fails to respond to a variable request, the Variables window will never get refreshed again until you close/reopen VS Code.

If you close your session, and debug the code above with just a breakpoint at the `fmt.Println` line (or with the fix for Delve), I expect you won't see this.

**Comment by asampal** [comment]
@lukehoban , the two reports were separated by some time and a few restarts of VSC. In any case, I pulled the latest source for delve (checked the version reported by `dlv version` to make sure I was building the latest - `94a265f098f59ccd0c49b11b053bb6cbf1d05a17`, at the moment), updated vscode-go to 0.6.26 and I'm still not seeing variables when I break on `fmt.Println`, as you suggested. Can you think of anything else to try?

**Comment by asampal** [comment]
I tried uninstalling and reinstalling the plugin, but I'm still not seeing variables.
