### ISSUE TITLE
Statement completion is working haphazardly

### ISSUE THREAD

**Issue by leidegre** [microsoft/vscode-go#1872]
It sometimes work, most of the time not. It looks like it's working relatively well for local variables and types but not package wide stuff.

What would cause this, how do I debug this? What should I do? I'm at loss on how to get to the bottom of this so I thought I'd ask what the common issues are?

I'll gladly root cause the issue I'm just not overly familiar with how everything fits together. I didn't use to have this problem and the tooling has been working fine before but now, this is a new issue for me that is consistent on at least two of my workstations.

I've updated and installed the Go tools, on several occasions, and it is working but not particularly well.

- go version go1.10.1 windows/amd64
- I use a non default GOPATH but I don't think it matters, I have this problem regardless of workspace. I launch VS Code with the GOPATH environment variable set externally first

**Comment by leidegre** [comment]
@ramya-rao-a std library appears to be OK (most of the time) symbols from external packages, not so much. Symbols from current package, appear to work fine.

If I look in the statement completion list, it says invalid type for a lot of things.

![invaid type](https://image.prntscr.com/image/OKGuVb1dRraDDJcu6V7Fnw.png)

But it can find the type in the current `tcm` package

![same package](https://image.prntscr.com/image/4rXeQmoOQoiCo8KFzpdjAg.png)

It cannot find the type in a related but different package `ddd`:

![other package](https://image.prntscr.com/image/OIy-j-7sTMa7_b0Qkspbig.png)

If I change to a file that's in that package it works again.

![ddd package](https://image.prntscr.com/image/avHdXtzOSYev10YC6XedYg.png)

So, It appears to work for the std library and current package but not my imported package.

**Comment by ramya-rao-a** [comment]
Try this:
- Close all VS Code instances
- Kill any running `gocode` process
- Remove the `gocode` binary from your `$GOPATH/bin` and the corresponding code form `$GOPATH/src/github.com/nsf/gocode` or `$GOPATH/src/github.com/mdempsky/gocode`
- If you added the `go.toolsGopath` setting, then use that instead of the $GOPATH above
- Open VS Code, run `Go: Install/Update Tools`, select `gocode` to install it
- Ensure that you haven't disabled the `go.installDependenciesWhenBuilding` setting
- Ensure all dependencies are built by running `Go: Build Current Package` (It uses the `go build -i` so all dependencies will be built and installed)
- Now try the completions

**Comment by leidegre** [comment]
@ramya-rao-a oh dear, thanks for the help! It did not fix the problem but I noticed something which might have been the root cause. However silly...

I use this script to configure and launch my environment

```batch
set GOPATH=%~dp0
set PATH=%PATH%;%GOPATH%\bin

start code .
```

The `GOPATH` was being set with a trailing backwards slash, i.e.

When I reinstalled `gocode`

```
Installing 1 tool at C:\Users\leidegre\Source\tessin\tcm\tcm-backend\\bin
  gocode
```

Note the double backslash `\\` at the end there.

I changed by batch script to this

```
set ROOT=%~dp0
set GOPATH=%ROOT:~0,-1%
set PATH=%PATH%;%GOPATH%\bin

start code .
```

And now it actually works. It seems silly that such a thing would cause this but I guess it did... I know that backslashes specifically on Windows can cause issues with command lines if they are at the end. If there's a shell execute somewhere in the tooling the there is a trailing backslash that could cause it.

...I could do some further digging on this, at a later point, and see if I can suggest a fix or at the very least a warning for this.

**Comment by freman** [comment]
I had this problem on osx

I had an extra / on my `go.gopath` in the user settings.

Definitely worth documenting this :D

**Comment by ramya-rao-a** [comment]
Well, if it is the extra `/` or `\` in the end that is causing this, then its definitely a bug and we should fix this.

@freman I tried with the extra `/` in the `go.gopath` setting on my mac, and I am getting the completions just fine

@leidegre I am away from my Windows machine for the next few days, so I won't be able to figure out the fix just yet. But if you are interested, debugging the Go extension is very easy and you can give it a try.

For set up read https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension

All completion related code is in the `goSuggest.ts` file. You can add a breakpoint there to start

**Comment by leidegre** [comment]
@ramya-rao-a I'm crazy busy with a deadline this and next week but if this can remain open until then, I will get around to it, I care deeply for both the tooling and the VS Code ecosystem but since I have a viable workaround I will roll with it for now. If you want to jump on this before then, be my guest.

**Comment by ramya-rao-a** [comment]
@leidegre No problem. Just one question though. You can consistently repro this issue by adding a training `\` in the end of the gopath in the settings correct?

**Comment by freman** [comment]
@ramya-rao-a I can no longer replicate it but code completion wasn't working for anything other than stdlib until I removed that slash, now it seems I can have the slash on or off.

**Comment by abdullah2993** [comment]
I had the same issue turn out it only occur if you set a diffrent `GOPATH` from the terminal and open vscode from that teminal. The solution is to set `go.toolsPath` to you original `GOPATH`

**Comment by mikberg** [comment]
For me, replacing mdempsky/gocode with stamblerre/gocode worked. Debugging gocode revealed that it wasn't able to find dependencies, and didn't look in the `go.gopath` folders I'd specified in vscode.

**Comment by ramya-rao-a** [comment]
In the year since this issue was logged stamblerre/gocode has had many fixes and improvements. We also have a [language server](https://github.com/microsoft/vscode-go/blob/master/README.md#go-language-server) that performs better.

Closing this issue as there is nothing actionable at the moment.

If you see any issues with completions when using the language server, please see https://github.com/golang/go/wiki/gopls#troubleshooting and log an issue at https://github.com/golang/go/issues

If you are not using the language server, but are using modules, we strongly suggest using the language server instead.

Thanks for your patience and Happy Coding!
