### ISSUE TITLE
generate the struct and the func from a struct

### ISSUE THREAD

**Issue by yeqown** [Microsoft/vscode-go#1896]
Hi, I'm developing web application with Go, I always do some work as following:

1. I define a model struct like this:
```Golang
type UserModel struct {
   Name       string `gorm:"column:name"`
   Passwrod string `gorm:"column:password"`
}
```

2. I define another struct and a new func base on step.1
```Golang
type User struct{
   Name       string `json:"name"`
   Passwrod string `json:"password"`
}
```

```Golang
func LoadUserFromModel(data *UserModel) *User {
   return &User{
     Name:         data.Name,
     Passwrod:   data.Password,
   }
}
```

so, what about adding new function of vscode-go to generate the "User" struct and "LoadUserFromModel" func ?

Thanks ~

**Comment by ramya-rao-a** [comment]
This seems like a refactoring scenario, and a refactoring tool might be a better home for it rather than the Go extension directly. There are 2 reasons for this:
- The Go extension is not aware of the AST of the Go file being edited. The extension relies on a set of [Go tools](https://github.com/Microsoft/vscode-go/wiki/Go-tools-that-the-Go-extension-depends-on) that do the Go aware work and pass the result to the extension. This feature would need the Go extension to be able to parse the file to determine the struct and so it needs to be aware Go AST which we do not want to get into.
- As VS Code and this extension has gained popularity, we have seen a gradual scope creep over the past year. Being a sole maintainer of this project, it is getting a little hard to support all incoming requests and maintaining the ever growing set of features. Therefore,one criteria I am using now in the triaging process is whether the feature request would make sense as a separate extension. This current feature request appears to be so.

If you would like to author another extension for this feature, I would be happy to provide any guidance you need. If you can get this feature into an existing re-factoring tool, then I'd be happy to integrate that tool.

Thank you and Happy Coding!

**Comment by yeqown** [comment]
@ramya-rao-a 
Yes, I have completed a similar tool, but I am not sure if it can be integrated into the Go extension?

Here is the link of my tool: [github.com/yeqown/dto](https://github.com/yeqown/server-common/tree/master/dbs/tools)

Currently the tool finishes reading the original structure from the specified file and generating a new structure and storing it in a file.

**Comment by ramya-rao-a** [comment]
Interesting.. what does `dto` stand for?

**Comment by yeqown** [comment]
dto(Data transfer Object) I saw this name in Java

**Comment by yeqown** [comment]
@ramya-rao-a 
Thank you for your reply. I have looked at some of the existing tools and found that my tools are not perfect. Perhaps, I should improve it first. . .
