### ISSUE TITLE
Completion of functions should include parens and params

### ISSUE THREAD

**Issue by peterbourgon** [Microsoft/vscode-go#190]
1. Type e.g. `fmt.Err`
2. Autocompletion dropdown highlights fmt.Errorf
3. Press enter to accept the autocompletion suggestion

Expected behavior: the text `fmt.Errorf(fmt, a...)` is inserted, with the first parameter `fmt` highlighted. Ideally, the autocompletion dropdown remains beneath the line, with the first argument and type highlighted, to serve as a reminder of the parameter arguments. Typing e.g. `"%s"<TAB>` replaces the `fmt` parameter with `"%s"` and the second parameter `a...` becomes highlighted, both in the text line and the autocompletion dropdown below. (This is the behavior of SublimeText+GoSublime.)

Actual behavior: the text `fmt.Errorf` is inserted, without parens or params. The autocompletion dropdown goes away. I need to type the opening parens, at which point the dropdown comes back, but without the params inlined.

**Comment by lukehoban** [comment]
There's an opt-in feature that provides this behavior: ` "go.useCodeSnippetsOnFunctionSuggest": true`.  See  https://github.com/microsoft/vscode-go#options.

It's off by default right now because it's non-standard for VS Code generally across other languages.

/cc @egamma in case he has thoughts on the default completion/parameterhelp experience.

**Comment by peterbourgon** [comment]
Oh! This is exactly what I wanted. I missed the option. Thank you. (I'd vote for it to be enabled by default, of course!)
