### ISSUE TITLE
Show panic error information, stack trace, and set editor to source line that panicked.

### ISSUE THREAD

**Issue by jpap** [microsoft/vscode-go#1903]
When a debug session panics, Delve will show a code listing with a cursor at the panic with a "Command failed: XXX" message.  You can then issue commands to get a backtrace, etc.

In VSC, a cryptic message "Failed to continue - XXX" is shown in the Debug Console and nothing else.  It would be great if instead:

* Move the editor to the relevant source line that panicked.
* Show the call stack in the debugger pane.  If that's too hard, at the very least please show the panic details in the Debug Console, including stack trace.
* Instead of "Failed to continue", use a more descriptive "Debugger stopped after program failure: XXX".  (The first time I encountered this I thought it was a debugger issue, rather than my code.)

**Comment by db47h** [comment]
@jpap This is the default behavior for dlv to stop at the beginning of [fatalpanic](https://github.com/golang/go/blob/b794ca64d29f3e584cbdf49bde7141d3c12dd2ab/src/runtime/panic.go#L681) when a Go program panics. While I agree that this might be confusing, panics can occur anywhere, even in the standard library (IIRC, some string to int conversion functions do), so it's not easy to guess which stack frame the user will really be interested in. In any case that specific issue should be taken to https://github.com/derekparker/delve/.

Also, in order to have vscode automatically switch to debug view on panic, you can set 

```
"debug.openDebug": "openOnDebugBreak",
```

or

```
"debug.openDebug": "openOnSessionStart"
```

in your user settings.

**Comment by jpap** [comment]
@db47h I am not concerned with the debug view opening automatically.  I am more concerned with:
1. A cryptic error message is shown on the Debug Console, that isn't clearly obvious that the issue is a fault in the program being run.  For example, in #1853 the author probably thought it was their debugger setup, before realizing it was a defect in their code.  (It has happened to me before too.)
2. When a runtime error occurs, other than an explicit call to `runtime.panic`, the debugger also shows a cryptic error message ("Failed to continue - XXX") on the Debug Console, **and the Debug View is blank**.

This is what I get in Delve with the above code sample:

```
$ dlv debug oops.go
Type 'help' for list of commands.
(dlv) c
     1:	package main
     2:	
     3:	func oops() {
     4:		var a *int
=>   5:		*a++
     6:	}
     7:	
     8:	func main() {
     9:		oops()
    10:	}
Command failed: bad access
(dlv) 
```

As you can see, Delve stops at the site of the runtime error.  You can then use `bt` to get the stack frame,
```
(dlv) bt
0  0x0000000001053828 in main.oops
   at ./oops.go:5
1  0x0000000001053860 in main.main
   at ./oops.go:9
2  0x0000000001026e95 in runtime.main
   at /usr/local/Cellar/go/1.11/libexec/src/runtime/proc.go:201
3  0x000000000104dec1 in runtime.goexit
   at /usr/local/Cellar/go/1.11/libexec/src/runtime/asm_amd64.s:1333
```

In VSC, the debugger shows the message "Failed to continue - bad access" on the Debug Console, with the Debug View blank, and it's not clear what happened at all.  To get any sense out of the situation, you have to run the code manually (under delve or not) in a terminal to see the runtime error and stack trace.

If the code sample above were to change so as to call `panic` in `func oops()` instead of the nil-pointer access, then yes, Delve and VSC breaks in `runtime.fatalpanic`.  But this is not what this bug report is about. ;-)

**Comment by db47h** [comment]
I did test with the code sample you've provide on Linux, Go 1.11, vscode 1.26.1 and latest dlv (at the time of writing). What's strange is that I don't get any "Failed to continue ..." message in the vscode debug console and if i debug it directly from dlv on the command line, dlv halts at `fatalpanic` as expected.

From the backtrace I see that you're running Go 1.11, but what operating system are you on?

**Comment by jpap** [comment]
I'm running delve HEAD (or very close to it), on macOS.

**Comment by db47h** [comment]
This could be related to derekparker/delve#852. Still, since delve catches the nil pointer dereference (that's what the "bad access" means), the debug view in vscode should not be blank.

**Comment by ramya-rao-a** [comment]
I tried the above code on Windows using the latest delve.
It breaks on `fatalpanic` and shows the below in the debug console:

![image](https://user-images.githubusercontent.com/16890566/45270250-21aa6a80-b450-11e8-9fba-55e7b3a42cb3.png)

Will try on macOS soon

**Comment by MylioFabien** [comment]
I'm also seeing this issue.

My setup:
. macOS Mojave v10.14
. Delve Debugger Version: 1.1.0 Build: $Id: 1990ba12450cab9425a2ae62e6ab988725023d5c $
. VSCode 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850)
. go version go1.11.2 darwin/amd64

In the debug console, VSCode reports "Failed to next - bad access".

![screen shot 2018-11-06 at 2 50 02 pm](https://user-images.githubusercontent.com/18035842/48099063-46625a80-e1d3-11e8-80cf-8e164571a813.png)

However, when using Delve directly, the stack is fine:

```
~/go/bin/dlv debug ts.go
Type 'help' for list of commands.
(dlv) c
> syscall.Syscall() /usr/local/go/src/syscall/asm_darwin_amd64.s:26 (PC: 0x10a4166)
Command failed: bad access
(dlv) bt
 0  0x00000000010a4166 in syscall.Syscall
    at /usr/local/go/src/syscall/asm_darwin_amd64.s:26
 1  0x00000000010a378a in syscall.read
    at /usr/local/go/src/syscall/zsyscall_darwin_amd64.go:947
 2  0x00000000010a07ec in syscall.Read
    at /usr/local/go/src/syscall/syscall_unix.go:172
 3  0x00000000010c34f4 in internal/poll.(*FD).Read
    at /usr/local/go/src/internal/poll/fd_unix.go:165
 4  0x00000000010cd2b9 in os.(*File).read
    at /usr/local/go/src/os/file_unix.go:249
 5  0x00000000010ca08d in os.(*File).Read
    at /usr/local/go/src/os/file.go:108
 6  0x000000000107a15d in bytes.(*Buffer).ReadFrom
    at /usr/local/go/src/bytes/buffer.go:206
 7  0x00000000011aa4ff in io/ioutil.readAll
    at /usr/local/go/src/io/ioutil/ioutil.go:36
 8  0x00000000011aa967 in io/ioutil.ReadFile
    at /usr/local/go/src/io/ioutil/ioutil.go:73
 9  0x000000000141800f in main.(*Config).Load
    at ./ts.go:61
10  0x0000000001430ac9 in main.main
    at ./ts.go:1959
11  0x0000000001032635 in runtime.main
    at /usr/local/go/src/runtime/proc.go:201
12  0x000000000105fc31 in runtime.goexit
    at /usr/local/go/src/runtime/asm_amd64.s:1333
```

The code leading to this is simply reading a file relative to the Go executable:

```
bytes, err := ioutil.ReadFile(path)
```

where the path is "./config/config.json"

Oddly, the same code runs just fine when it's not being debugged.

**Comment by weeco** [comment]
I also faced this behaviour on Mac OS with vscode insiders

**Comment by protheusfr** [comment]
+1

**Comment by protheusfr** [comment]
Any update regarding this issue ?

**Comment by ramya-rao-a** [comment]
@aarzilli

In such cases where the "bad access" error is thrown from delve as per
https://github.com/derekparker/delve/blob/b5cf58456418a76902aa551ed5b022c90cd76fa7/pkg/proc/gdbserial/gdbserver.go#L698-L726, can the client expect any stack trace?

**Comment by aarzilli** [comment]
Yes.

**Comment by dmlemos** [comment]
I am also having this issue

**Comment by ramya-rao-a** [comment]
@protheusfr Can you share a screenshot of the stack trace that you see in Linux and Windows?

**Comment by lggomez** [comment]
Coming back to this issue, it's worth to take note the following comment found on delve that points to a platform-dependent issue:

> // The following are fake BSD-style signals sent by debugserver
> // Unfortunately debugserver can not convert them into signals for the
> // process so we must stop here.

So, to recap (please correct me if I'm wrong):
- Debug server sends an uncaught exception (EXC_BAD_ACCESS?)
- Delve catches it and propagates it as an internal error (because it cannot propagate as a SIGSEGV -> panic)
- VS debug adapter handles the response as it is

@protheusfr that probably happens because exception and signal handling is different across systems, and said behavior happens on OSX. Someone from the delve team will surely have a more detailed insight of this

**Comment by aarzilli** [comment]
Normally we'd like to send this type of exception back to the target program, the exception handler would then run and result in a panic, however because of a [kernel bug](https://bugs.llvm.org//show_bug.cgi?id=22868) we can't do this on macOS. See also [this issue](https://github.com/go-delve/delve/issues/852) (but disregard the suggestion about using the native backend).

One possibility would be to add an option to debugserver to disable catching EXC_BAD_ACCESS on their side. If someone wants to start contributing to llvm that would be a useful thing to do.

**Comment by love666666shen** [comment]
Failed to next - bad access and Failed to next - next while nexting +1

**Comment by ramya-rao-a** [comment]
Thanks @lggomez and @aarzilli 

@lggomez If I understand this correctly, there is no good next step for us to do from the extension's side, right?

**Comment by lggomez** [comment]
Unfortunately, no. Maybe we can add add a hack in the debug adapter so these specific error messages get translated into something user friendly so they get warned about this issue, and the certainty that an unhandled panic occurred, but nothing more

**Comment by roman-m-work** [comment]
I have this issue also happened on breakpoint inside background message handler.

> Failed to continue - bad access
> Failed to list local variables - unable to find function context

OS: MacOS Mojave

**Comment by tomjohnburton** [comment]
I also have this issue when calling one of my endpoints.

It receives the payload okay and then returns 
```
failed to continue - bad access
```
OS: MacOS Mojave
VSCode: 1.35.1

**Comment by drew-512** [comment]
Also seeing this -- 1.36.1, macOS High Sierra.
Tried all kinds of things.  Grr, frustrated -- especially when I like to tell others how awesome VS Code is with Go is...   :\

**Comment by drew-512** [comment]
The causing this is a nil ptr deref (same as the OP's sample crash).

Someway/somehow it seems like if it's a ptr deref crash, even the VS Code go attache debugger just prints the dreaded `failed to continue - bad access` whereas a crash from a compiled binary prints the stack trace.

**Comment by jkassis** [comment]
this tool is not usable without proper stack traces.

**Comment by lggomez** [comment]
@jkassis I know the issue is frustrating but please refrain to do this kind of comment which serve no constructive purpose at all. If you would´ve bothered to read the entire thread you would have noticed that this is an upstream issue due to OSX propagation of unhandled errors over delve and not just 'this tool'


---


Now, to go back on track, I´ve been thinking about this last comment I made:

> Unfortunately, no. Maybe we can add add a hack in the debug adapter so these specific error messages get translated into something user friendly so users get warned about this issue, and the certainty that an unhandled panic occurred, but nothing more

Catching this on the debug adapter and logging the last known stacktrace instead (or just making a new Stacktrace call altough that may not be feasible once the panic has occured) may solve the general issue adding context to this kind of panics

Does anyone have a consistent code repro of this to share here?

**Comment by aarzilli** [comment]
> making a new Stacktrace call although that may not be feasible once the panic has occurred

As far as delve is concerned it is entirely feasible, the program can't be continued (due to the aforementioned kernel bug) but that's it, everything else works.

> Does anyone have a consistent code repro of this to share here?

The third message in this issue (but you need to use macOS)

**Comment by lggomez** [comment]
So I´ve worked this proposed solution on a PR, the result is the following:

<img width="1020" alt="Screen Shot 2019-11-13 at 22 37 24" src="https://user-images.githubusercontent.com/6326271/68819345-87067680-0666-11ea-996a-8342534d4101.png">

This will also cover all actions vulnerable to triggering panics (step over, next, etc). If this makes sense to you all we can move forward

**Comment by protheusfr** [comment]
Did anybody know how Jetbrains manage that ?
You can debug any go program without issue on OSX through Goland or IntelliJ....

**Comment by ramya-rao-a** [comment]
The fix from #2904 is available in the [latest beta version of this extension](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension). Please do try and share feedback

**Comment by raygift** [comment]
> The fix from #2904 is available in the [latest beta version of this extension](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension). Please do try and share feedback

after installed the latest beta version “Go-0.14.0-beta.6.vsix”，error  changed from "Failed to continue-bad access" to “Failed to continue - unpropagated fatalpanic: signal SIGSEGV (EXC_BAD_ACCESS). This fatalpanic is not traceable on macOS, see https://github.com/go-delve/delve/issues/852  Last known immediate stacktrace (goroutine id 0):” 

Is this normal ? did i met a MacOS BUG rather than vscode-go extension... ?

**Comment by ramya-rao-a** [comment]
@jhendrixMSFT Can you help with the question from @raygift above?

The fix associated with this issue is now available in the latest version of the extension

**Comment by lggomez** [comment]
@raygift this is an expanded version of that previous and esoteric "bad access" message. This means that due to a lldb issue in macOS, the panic cannot be recovered nor propagated back to the debugger, thus falling back to that immediate stacktrace

**Comment by polinasok** [comment]
For completeness, posting the details of my before/after testing of this fix for handling "bad access" error from delve. (Looks like some of the before behavior might have evolved since this issue was filed in 2018.)

**Before the fix**
(1) Yellow highlighting of the bad line (*a++) 
<img width="258" alt="before highlight" src="https://user-images.githubusercontent.com/51177946/79501739-665e9600-7fe3-11ea-82aa-ad12b1b882fc.png">
(2) CALL STACK shows only the stack of the main goroutine that panic'ed (and none of the usual additional runtime goroutines that happen behind the scenes):
<img width="233" alt="before callstack" src="https://user-images.githubusercontent.com/51177946/79502827-08cb4900-7fe5-11ea-91de-da8e56cacb2a.png">
(3) DEBUG CONSOLE shows "Failed to continue - bad access"
<img width="360" alt="before console" src="https://user-images.githubusercontent.com/51177946/79502873-1b458280-7fe5-11ea-86fd-73404b1c3d94.png">
(4) On Continue, DEBUG CONSOLE reprints the error message from (3). 
The debug session does not exit.
<img width="372" alt="before continue" src="https://user-images.githubusercontent.com/51177946/79501559-197abf80-7fe3-11ea-895f-4e3e30f9b275.png">

**After the fix**
(1) same as before
(2) same as before
(3) DEBUG CONSOLE prints new error message plus same stacktrace as (2)
<img width="728" alt="after console" src="https://user-images.githubusercontent.com/51177946/79502975-43cd7c80-7fe5-11ea-9c1e-c694ed1aec91.png">
(4) same as before

**Comment by polinasok** [comment]
For comparison, this is the behavior with another case of panic that does get properly propagated and is not impacted by this fix:
Code:
```
func outofrange() {
	a := make([]int, 1)
	fmt.Println(a[100])
}
```
(1) Yellow highlighting of "func fatalpanic" in runtime/panic.go
<img width="538" alt="outofrange highlight" src="https://user-images.githubusercontent.com/51177946/79598514-f27ec500-8098-11ea-8fe9-96c8d2ba07ec.png">
(2) CALL STACK shows all goroutines, including from runtime, with the panic'ed one highlighted and expanded
<img width="361" alt="outofrange callstack" src="https://user-images.githubusercontent.com/51177946/79598578-13dfb100-8099-11ea-8428-861706de64cf.png">
(3) DEBUG CONSOLE shows no error messages.
(4) On Continue, DEBUG CONSOLE prints out panic failure from the runtime. 
The debug session exits.
<img width="485" alt="outofrange continue" src="https://user-images.githubusercontent.com/51177946/79599621-ab91cf00-809a-11ea-800c-e1a24fad1d14.png">
