### ISSUE TITLE
Godoc not appearing in code-completion

### ISSUE THREAD

**Issue by luca-moser** [Microsoft/vscode-go#194]
Hi Luke.

System:
- vscode-go 0.6.26
- Visual Studio Code 0.10.6.
- Windows 10 (64-bit)

Godoc does not appear when using code-completion.

In this animation we have some code written on the right pane which calls a function from the code on the left pane. You see that the func `GetGroupIDsOfUser` has a comment, however, it does not appear in the code-completion:
![animation](https://cloud.githubusercontent.com/assets/1385611/12872455/0d2a6eb6-cda3-11e5-8b55-5f2c15ef5e55.gif)

Godoc should appear when:
- the cursor is inside the parentheses of a function call
- the auto-completion list is open with suggestions of functions

The godocs do not show up on my own code, however, when using the `fmt` package as an example, it only shows itself sometimes:
![animation2](https://cloud.githubusercontent.com/assets/1385611/12872490/179a3c5e-cda4-11e5-8ade-ad1dca4b4e9f.gif)

**Comment by lukehoban** [comment]
Yes - ideally we'll show the GoDoc information in QuickInfo and Completion as well.  Currently we only show it in SignatureHelp.  Should be fairly straightforward to integrate with these other features as well.

**Comment by ramya-rao-a** [comment]
We are blocked on https://github.com/nsf/gocode/issues/415 to get the docs during completion.

As of now we have docs in Signature Help and Quick Info.

**Comment by ramya-rao-a** [comment]
One way we could achieve this is
- Check if the completed item is a function
- If no, then quit
- If yes, then try to get pkg name from the . preceeding the word that is being completed
- `goSuggest` now has access to mapping between pkg and pkg path, get pkg path from there
- Call godoc and fetch the required docs as is done here: https://github.com/Microsoft/vscode-go/blob/0.6.60/src/goDeclaration.ts#L86 You'd need func signature which is available from `gocode`

Will not work for pkg with alias
Need to be smart to not call `godoc` for the same pkg multiple times. Example: `fmt.P` will give multiple functions, but `godoc` needs to be called just once.

**Comment by antifuchs** [comment]
Just a heads-up that there's now [a PR](https://github.com/nsf/gocode/pull/463) to `nsf/gocode` that adds a package import path field to each autocomplete symbol. It might be possible to get all the information you need from that. Please test this out and let me know if it breaks things!

**Comment by segevfiner** [comment]
Note that there is even a VS Code API meant for this case: [CompletionItemProvider.resolveCompletionItem](https://code.visualstudio.com/docs/extensionAPI/vscode-api#CompletionItemProvider.resolveCompletionItem).

**Comment by ramya-rao-a** [comment]
That is a good idea @segevfiner 

Using `resolveCompletionItem` is better as we will then be fetching docs for just the suggestion item in focus instead of doing it for all items which would happen if we were to fetch docs in the `provideCompletionItems` call.

If anyone is interested in picking up this item, here are a few code pointers:
- [Build and Debug Extension]() to get a local set up of the extension up and running
- All changes would be in the `goSuggest.ts` file
- Extend the `CompletionItem` object to include a new property called `package`. Store the package info @antifuchs mentioned in https://github.com/Microsoft/vscode-go/issues/194#issuecomment-322674990 in this object and ensure this is returned by `provideCompeltionItems` function
- Implement the `resolveCompletionItem` function in the Completion provider. You now have both the package import path and the symbol name which you can then use to call `godoc` to get the documentation on the symbol.

**Comment by ramya-rao-a** [comment]
This long pending feature is now out in the latest update of this extension (0.7.0)
Thanks to @segevfiner!
