### ISSUE TITLE
Auto-completion doesn't work

### ISSUE THREAD

**Issue by letjinxgo** [Microsoft/vscode-go#1946]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/18941149/46130555-2e122e00-c26c-11e8-8851-f5febe7e95f9.gif)

When I want to get suggestion of my own func like (distributeCandies),  I need to move cursor,  click somewhere, and move it back.

Is it possible to get suggestions directly?
No need to move the mouse cursor.

my vscode settings：

{
    "workbench.iconTheme": "vscode-icons",
    "workbench.colorTheme": "Dracula",
    "go.autocompleteUnimportedPackages": true,
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "editor.quickSuggestions": {
        "other": true,
        "comments": true,
        "strings": true
    },
    "editor.tabCompletion": true,
    "files.autoSave": "onFocusChange",
    "[go]": {
        "editor.insertSpaces": true,
        "editor.formatOnSave": true
    },
    "editor.formatOnSave": true,
}
```

**Comment by nealot** [comment]
You can press ctrl+space to trigger suggestions.

**Comment by ramya-rao-a** [comment]
Since you have the setting `go.useCodeSnippetsOnFunctionSuggest` enabled, you are using snippets to complete the functions. When you are adding the parameters to the function, you are still in snippet mode.

Inside snippet mode, tab is for moving across the different tab stops in the snippet, so auto-completion is disabled.

You can
- Press escape key to come out of snippet mode after auto-completing the function. Then start typing, you will get completions
- Or you can set `editor.suggest.snippetsPreventQuickSuggestions` to `false` in your settings. This will enable auto-completions when you are in snippet mode.
