### ISSUE TITLE
go.{mod,sum} created automatically

### ISSUE THREAD

**Issue by jbrodriguez** [Microsoft/vscode-go#1970]
I'm starting to migrate my projects out of GOPATH, so I set 

```
"go.toolsEnvVars": {
        "GO111MODULE": "on"
    }
```

If I don't do this, projects outside GOPATH show lint error 

```
/Volumes/Home/code/wall>Finished running tool: /usr/local/bin/go build -o /var/folders/w9/7tlszcbs3msddknxvpp64gwc0000gn/T/vscode-gocKfDDn/go-code-check-6 _/Volumes/Home/code/wall/server/model
can't load package: package _/Volumes/Home/code/wall/server/model: cannot find package "_/Volumes/Home/code/wall/server/model" in any of:
	/usr/local/Cellar/go/1.11.1/libexec/src/_/Volumes/Home/code/wall/server/model (from $GOROOT)
	/Volumes/Home/go/src/_/Volumes/Home/code/wall/server/model (from $GOPATH)
```

The issue is, when I switch to a project under GOPATH, with GO111MODULE on, it creates go.mod and go.sum automatically (withouth go mod init), since it runs go build

```
/Volumes/Home/go/src/jbrodriguez/mediagui>Finished running tool: /usr/local/bin/go build -i -o /var/folders/w9/7tlszcbs3msddknxvpp64gwc0000gn/T/vscode-goLx0qXx/go-code-check-4 jbrodriguez/mediagui/server/src/dto
```

I thought the last update would fix this.

Is there any workaround ?

**Comment by ramya-rao-a** [comment]
As per the docs on [GO111MODULE](https://github.com/golang/go/wiki/Modules#when-do-i-get-old-behavior-vs-new-module-based-behavior), setting `GO111MODULE` to `on` forces the module behavior.

For your case, I would suggest to update `go.toolsEnvVars` setting in the workspace settings instead of user settings. This way, it will be applied only to the project you are moving out of GOPATH.

Another way to go about this is to not mess with `GO111MODULE` at all. Run `go mod init` as soon as you move your project out of GOPATH. From that point on, the Go extension will identify the use of Go modules and you will not see the build error
