### ISSUE TITLE
Problem with default themes

### ISSUE THREAD

**Issue by rbatukaev** [Microsoft/vscode-go#210]
Here is the same code with vscode-go installed (right) and not (left). I understand that it enables syntax highlighting for Golang, but I really like the pink color for control flow keywords. 

<img width="913" alt="screen shot 2016-02-28 at 05 30 14" src="https://cloud.githubusercontent.com/assets/4622415/13377068/9991aab0-dddc-11e5-89a4-d9fffa66030f.png">

**Comment by lukehoban** [comment]
I've gone ahead and removed the custom colorization that comes with `vscode-go`.  I agree that it's not obviously better, and it makes sense to focus on improving the colorization that comes built-in to `vscode` if improvements are needed, instead of having another different option as part of this extension.

Fixed in 62b294ba1d3ffd6e53c0514a0893b61dc0a22423.

**Comment by rbatukaev** [comment]
Thanks a lot!
