### ISSUE TITLE
Tools build ("Successfully"), but don't appear in the tools directory when GOBIN is set

### ISSUE THREAD

**Issue by foodini** [microsoft/vscode-go#2122]
Installing 17 tools at /Users/ronb/gotools/bin
      gocode
      gopkgs
      go-outline
      go-symbols
      guru
      gorename
      dlv
      gocode-gomod
      godef
      godef-gomod
      goreturns
      golint
      gotests
      gomodifytags
      impl
      fillstruct
      goplay
    
    Installing github.com/mdempsky/gocode SUCCEEDED
    Installing github.com/uudashr/gopkgs/cmd/gopkgs SUCCEEDED
    Installing github.com/ramya-rao-a/go-outline SUCCEEDED
    Installing github.com/acroca/go-symbols SUCCEEDED
    Installing golang.org/x/tools/cmd/guru SUCCEEDED
    Installing golang.org/x/tools/cmd/gorename SUCCEEDED
    Installing github.com/derekparker/delve/cmd/dlv SUCCEEDED
    Installing github.com/stamblerre/gocode SUCCEEDED
    Installing github.com/rogpeppe/godef SUCCEEDED
    Installing github.com/ianthehat/godef SUCCEEDED
    Installing github.com/sqs/goreturns SUCCEEDED
    Installing golang.org/x/lint/golint SUCCEEDED
    Installing github.com/cweill/gotests/... SUCCEEDED
    Installing github.com/fatih/gomodifytags SUCCEEDED
    Installing github.com/josharian/impl SUCCEEDED
    Installing github.com/davidrjenni/reftools/cmd/fillstruct SUCCEEDED
    Installing github.com/haya14busa/goplay/cmd/goplay SUCCEEDED
    
    All tools successfully installed. You're ready to Go :).

But, when I look at the contents of `/Users/ronb/gotools/bin`:

    -rwxr-xr-x  1 ronb  staff  11513100 Nov 13 13:07 gocode-gomod
    -rwxr-xr-x  1 ronb  staff   8072176 Nov 13 13:07 godef-gomod

So, of course, anything that depends upon tools fails and tells me I need to install them.

This is VSCode 1.29.0 on High Sierra 10.13.6.

**Comment by ramya-rao-a** [comment]
Thats a great find @foodini!

We should still make some changes to avoid the confusion. Here is what I propose:
- If `go.toolsGopath` setting is set, then the process that installs the tools should unset the GOBIN env variable, so that the tools get installed in the right place
- GOBIN should be added to the list of places where the extension looks for the tools.

PRs are most welcome.
Code Pointers:
- [Build and Debug extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- The [code where go install is run from](https://github.com/Microsoft/vscode-go/blob/0.7.0/src/goInstallTools.ts#L387)
- The [code where we look for the tools](https://github.com/Microsoft/vscode-go/blob/0.7.0/src/goPath.ts#L33) in GOPATH, PATH and GOROOT

**Comment by wvh** [comment]
I'm trying vscode for the first time, and I had the same problem. I've got `GOBIN` set to `~/.local/gobin`, so Go installs all compiled binaries in that path by default. Vscode installs the binaries successfully there too, but when reloading or restarting the editor, it complains it can't find the binaries it just installed: `Analysis Tools Missing`. I'm not sure vscode-go even uses `GOBIN` anywhere in the code, so it looks in the wrong place for the installed binaries.

I've solved the problem by manually setting `go.toolsGopath`.

Ideally, vscode would respect the `GOBIN` environment variable when one is set by the user, to avoid a mismatch between Go's and vscode's idea of where the binaries are stored.

**Comment by ramya-rao-a** [comment]
This issue has been resolved in the latest version (0.13.0) of this extension

Thanks for the PR @marcel-basel and Thanks for reporting @foodini !

Happy Coding!
