### ISSUE TITLE
Confusing suggestion of solution, when goreturns command is missing

### ISSUE THREAD

**Issue by samuell** [Microsoft/vscode-go#214]
I tried formatting go code by using "Ctrl + Shift + P" and typing "Format Code".

I got this message:
> The "goreturns" command is not available. Please check your go.formatTool user setting and ensure it is installed.
![selection_054_2](https://cloud.githubusercontent.com/assets/125003/13507535/4587f942-e183-11e5-9fa3-52276c6a9876.png)

The problem was solved though by googling up [goreturns](go get -u sourcegraph.com/sqs/goreturns) and installing it with:

```bash
go get -u sourcegraph.com/sqs/goreturns
```

Maybe that would be a better suggested solution?

**Comment by lukehoban** [comment]
Yeah - I think this is the same request as https://github.com/Microsoft/vscode-go/issues/102.

You should be seeing a message in green in the bottom right of VS Code saying `Analysis Tools Missing` which will offer to automatically install all the tools. This is also mentioned in https://github.com/Microsoft/vscode-go#using. But it's too subtle and should be easier.

The fix for #102 should be to offer `Install` and `Install All` options for every one of these "command is not available" errors.
