### ISSUE TITLE
please support more go langserver tools such as bingo, golsp

### ISSUE THREAD

**Issue by saibing** [Microsoft/vscode-go#2143]
Now, there are some new go language server tool, can you support them?

[bingo](https://github.com/saibing/bingo)

[golsp](https://github.com/golang/tools/blob/master/cmd/golsp/main.go)

**Comment by ramya-rao-a** [comment]
Yes, this should be do-able.
We can overload the `go.useLanguageServer` which takes just a boolean at the moment to instead show all the options.

PRs are most welcome.
Code Pointers:
- [Build and Debug extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code#building-and-debugging-the-extension)
- Update the `useLanguageServer` [setting](https://github.com/Microsoft/vscode-go/blob/0.7.0/package.json#L848) to take enum listing all the options
- Update the `goInstallTools.ts` file so that the right tool gets installed. 
- Update the `goMain.ts` file to remove the hard-coded value of `go-langserver` and instead run the chosen tool

**Comment by ramya-rao-a** [comment]
As discussed in the PR #2158, there is a good likelihood of all 3 language servers will merge into 1 (Sourcegraph plans to use the one from Google, @saibing and Google are planning to work together). Given this, I want to avoid changing the schema of the useLanguageServer setting.

Therefore, if one wants to use another language server, they can use the go.alternateTools setting. For example, if you want to use the bingo language server, install it using `go get github.com/saibing/bingo` and then add the below in your settings

```
 "go.alternateTools": {
    "go-langserver": "bingo",
  },
  "go.languageServerExperimentalFeatures": {
    "format": true,
    "autoComplete": true
  },
  "go.useLanguageServer": true
```
