### ISSUE TITLE
"Add Import" Will Add Duplicates

### ISSUE THREAD

**Issue by donatj** [Microsoft/vscode-go#215]
Calling "Add Import" multiple times adds the item multiple times.  Ideally this should dedupe.

![output](https://cloud.githubusercontent.com/assets/133747/13509420/f104cecc-e150-11e5-91c6-22caff1bf57b.gif)

**Comment by lukehoban** [comment]
For now, running `format` is the easiest way to deal with this.  Many users turn on `"go.formatOnSave": true` in their settings so that this is taken care of automatically.

That said - we should also fix this.

**Comment by lukehoban** [comment]
Actually - it turns out this is non-trivial to fix in a sufficiently correct way, but easy to workaround - just run `format`.  It's also not necessarily "wrong" behaviour (the user is asking to add the import), though it's not as smart as it could be.  I think we'll leave the behaviour as-is for now - and address this if and when we make the import handling something that's handled more robustly overall (via some tool written in Go that can work with the Go AST).
