### ISSUE TITLE
go doc consuming CPU

### ISSUE THREAD

**Issue by aplsek** [Microsoft/vscode-go#2152]
I am seeing high CPU consumed by the 'doc' subprocesses. This started happening in the last two weeks after the latest release. The following 4 processes are spawned as soon as I start typing into a `.go` file, I have a single editor window opened:

<img width="419" alt="screen shot 2018-11-26 at 10 19 33 pm" src="https://user-images.githubusercontent.com/888802/49062684-d93a5780-f1c9-11e8-9fc1-c74f2d4dd1db.png">

Visual Studio Version: 1.25.0-insider 
Go plugin: 0.7.0

Is there a way howto disable go doc or howto analyze this further?

**Comment by ramya-rao-a** [comment]
As far as I know, the Go extension doesn't use any tool called `doc`.

Can you disable all other extensions and see if you still see the issue?

**Comment by grillbiff** [comment]
I had the same issue. Switched the `go.docsTool` to one of the alternatives and then back again to `godoc` which seems to have fixed the issue with multiple doc processes

**Comment by ramya-rao-a** [comment]
@aplsek `doc` is an argument for the `go` command, so wouldn't the Activity Monitor have the process name as `go` instead of `doc`?

Select the process in the Activity Monitor, and then select the "info" button on the top, that will open up a detailed view which will have the parent information. Check if the processes with the process name `doc` have VS Code as the parent.

Another thing to try is to run `Developer: Open Process Explorer` in VS Code. This will open the process explorer and any high CPU consuming processes will show up there

**Comment by grillbiff** [comment]
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/373239/49427917-e4325080-f7a4-11e8-88dc-cb23d12a8375.png">
Hi, I'm experiencing the same problem. Here is the process chain of one of the doc processes. Couldn't see anything strange in the process explorer though

**Comment by ramya-rao-a** [comment]
Thanks for that @grillbiff. These are for doc processes as shown in the screenshot in 
https://github.com/Microsoft/vscode-go/issues/2152#issue-384643034?

We use `go doc` for 2 features:
- The information you see when you hover on code text.
- The information you see on the side in the auto-completion widget.

Lets try and disable these 2 features and see if that helps your case.

For the first feature, lets use `gogetdoc` instead of `go doc` for the hover info
- Add the setting `"go.docsTool": "gogetdoc"`
- Run the command `Go: Install/Update tools`
- Select `gogetdoc` and press Ok to install it

For the second feature, if you are seeing the documentation on the side like in the below picture, press Ctrl+Space to hide it.

<img width="919" alt="screen shot 2018-12-05 at 10 36 51 am" src="https://user-images.githubusercontent.com/16890566/49535746-b8cd6580-f879-11e8-8fc7-6ce8816837ea.png">

**Comment by grillbiff** [comment]
Hi,
yes my image is for two of the doc processes shown in https://github.com/Microsoft/vscode-go/issues/2152#issue-384643034.

I tried changing to both `gogetdoc` and `guru` but no luck, still creating a lot of doc processes.

**Comment by ramya-rao-a** [comment]
@grillbiff Also ensure that the docs side of the completions are not expanded.

**Comment by grillbiff** [comment]
@ramya-rao-a I think it has been disabled, the documentation does not appear unless I explicitly press the small info icon

**Comment by grillbiff** [comment]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/373239/49833496-f4948d80-fd99-11e8-862b-319804acc022.png">
I still get alot of doc processes. Could it be that VSCode is using godoc regardless of my choice?

**Comment by ramya-rao-a** [comment]
Ah! My mistake.

So, VS Code always calls `resolveCompletionItem` for each completion item in focus whether it is expanded for docs or not. 

The Go extension which implements this `resolveCompletionItem` calls `go doc` to fetch the docs and return it to VS Code which then displays it to you.

I was under the assumption that this `resolveCompletionItem` is only called when the docs section is expanded.

I have pushed a fix for this. Can you try it out?
- First install the [beta-version](
https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension
- Update the `go.gocodeFlags` setting as below
```
"go.gocodeFlags": [
		"-builtin",
		"-ignore-case",
		"-unimported-packages",
                "-exclude-docs"
	]
```

The first 3 are flags that will get passed to `gocode` to give us the completions. The last one will be used by the Go extension to not run `go doc` to get the docs.

Remember to kill all existing processes for `go doc` before trying this out.

**Comment by grillbiff** [comment]
Hi, 
installed the fix and use `-exclude-docs` which seems to work. VSCode no longer creates multiple doc processes. Tested with both `godoc` and `gogetdoc` and both works fine so maybe the issue was with the `resolveCompletionItem` all along?

**Comment by aplsek** [comment]
Hi,

Is there an ETA on when the fix is going to be part of the official release?

Not sure I want to install beta-version of the plugin as that would block the future updates...

Thanks!

**Comment by ramya-rao-a** [comment]
The latest update (0.9.1) to the extension has this fix.
