### ISSUE TITLE
$GOROOT refer error!

### ISSUE THREAD

**Issue by imkos** [Microsoft/vscode-go#2157]
Unable to open 'time.go': File not found (file:///$GOROOT/src/time/time.go).

godef:  github.com/ianthehat/godef

**Comment by ramya-rao-a** [comment]
Can you try updating the tool? Run `Go: Install/Update tools`, select `godef-gomod`, press `Ok` to update

**Comment by imkos** [comment]
bin: godef-gomod
What kind of configuration is needed?

**Comment by ramya-rao-a** [comment]
No other configuration is needed. Are you still not able to go to the definition?

- Are you using Go modules in your project?
- Is the problem only with symbols from the std library or even for the ones from external libraries?
- Can you try running `godef-gomod` from the terminal and see if you can get to the definition? You will need offset. You can use the [show-offset](https://marketplace.visualstudio.com/items?itemName=ramyaraoa.show-offset) extension to get the offset under the cursor
- Have you changed either of  `go.docsTool` and `go.useLanguageServer` settings? If yes, what are their values?

**Comment by imkos** [comment]
```json
{
    "window.zoomLevel": 0,
    "extensions.ignoreRecommendations": true,
    "editor.fontSize": 16,
    "workbench.colorTheme": "Adapta Nokto",
    "go.formatTool": "gofmt",
    "go.formatFlags": [
        "-s",
        "-e"
    ],
    //"go.goroot": "D:/go",
    //"go.gopath": "${env:GOPATH}",
    "go.gopath": "C:\\gopath_src;D:\\goWork;D:\\goWork\\niuniu_go",
    "go.buildOnSave": "off",
    "go.lintOnSave": "off",
    "go.useCodeSnippetsOnFunctionSuggestWithoutType": true,
    "go.testFlags": [
        "-v",
        "-count=1"
    ],
    "go.autocompleteUnimportedPackages": true,
    "go.gocodeAutoBuild": true,
    "workbench.startupEditor": "newUntitledFile",
    "terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
    "python.linting.pylintArgs": [
        "--disable-msg=C0103"
    ],
    "python.formatting.provider": "yapf",
    "[python]": {
        "editor.formatOnSave": true
    },
    "extensions.autoUpdate": false
}
```

win10 home,  go 1.11.2
My project does not use Go modules

**Comment by ramya-rao-a** [comment]
If you are not using modules, then how is that you are using github.com/ianthehat/godef instead of github.com/rogpeppe/godef?

- Is the problem only with symbols from the std library or even for the ones from external libraries?
- Can you try running `godef` from the terminal and see if you can get to the definition? You will need offset. You can use the [show-offset](https://marketplace.visualstudio.com/items?itemName=ramyaraoa.show-offset) extension to get the offset under the cursor

**Comment by imkos** [comment]
github.com/rogpeppe/godef 

It is always impossible to locate a definition object for an alias of golang.
Support for multiple GOPATH is not very good, always unable to locate

**Comment by ramya-rao-a** [comment]
> It is always impossible to locate a definition object for an alias of golang.
Support for multiple GOPATH is not very good, non-first GOPATH can't always locate

Are these the reasons you are using `github.com/ianthehat/godef` instead of `github.com/rogpeppe/godef`?

> Why is there a special directory like $GOROOT instead of the configured go.goroot value?

I don't understand. Are you literally getting the error `File not found (file:///$GOROOT/src/time/time.go)` or you just replaced your goroot with the word "$GOROOT"?

**Comment by ramya-rao-a** [comment]
This is fixed upstream in the godef tool. Please follow the below steps:
- Run `Go: Install/Update Tools` command
- Select `godef-gomod`
- Press Ok to update

If this fails with an error around git force push, then delete the existing folder for godef ($GOPATH/src/github.com/ianthehat/godef) and try again
