### ISSUE TITLE
the extension keeps a bunch of go-code-check files in $TMP/vscode-go*/

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode-go#2188]
It is my understanding that those files are temporary, however after a few hours of work I end up with a few empty folders and some of them will have `go-code-check` file in it.

**Comment by ramya-rao-a** [comment]
Thank you very much for reporting this @OneOfOne 
It was a complete oversight on my part, there was a bug in the code that was suppose to clean up the temporary folders that the extension creates.

This is fixed with https://github.com/Microsoft/vscode-go/commit/4a241f806809465afa7085a3f62729ff37fa63cd and the next update will have the fix

**Comment by ramya-rao-a** [comment]
@OneOfOne The latest [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension has the fix for this issue.

It will not clean up the folders that already exist, but it will clean up all the future folders.

**Comment by ramya-rao-a** [comment]
The fix for this issue is out in the latest release(0.10.0) of the Go extension
