### ISSUE TITLE
go.toolsGopath behavior change in recent version

### ISSUE THREAD

**Issue by bryanmacfarlane** [Microsoft/vscode-go#2203]
go.ToolsGopath behavior seems to have change recently.  I'm not sure if this is the extension or update of one of the tools

Steps to Reproduce:

1. set go.toolsGopath.  I had set "go.toolsGopath": "/Users/bryan/Tools/bin"
2. Update to recent go extension

My tools are directly in bin
```bash
[dev] ~/dev-macos$ ls -la /Users/bryan/Tools/bin/
total 204600
...
-rwxr-xr-x   1 bryan  staff  14833940 Dec 21 09:42 dlv
-rwxr-xr-x   1 bryan  staff   4234104 Dec 21 09:42 go-outline
-rwxr-xr-x   1 bryan  staff   4034968 Dec 21 09:42 go-symbols
-rwxr-xr-x   1 bryan  staff  11864604 Dec 21 09:56 gocode
...
```

After a recent update to latest (1.30) nothing was working.  It prompted me to install gocode which is obviously there.  I said OK and the clue was it wanted to install in gi.toolsGoPath + '/bin'

```bash
Installing 1 tool at /Users/bryan/Tools/bin/bin
    gocode
```

Which provided me a hint to the problem.

I changed

"go.toolsGopath": "/Users/bryan/Tools/bin"

to:

"go.toolsGopath": "/Users/bryan/Tools"

and everything started working again.

Note that I was trying to get vgo working so I also updated all my other tools to latest.  So I'm not sure if it was the vscode extension or another tool.  I'm also unblocked and updated my settings but I thought I would point this out in the event it was unintentional or a bug.

**Comment by ramya-rao-a** [comment]
@bryanmacfarlane The `go.toolsGopath` was always meant to point to the GOPATH to use when running `go get` to install the various Go tools. And therefore, in your scenario, it should be `/Users/bryan/Tools` and not `/Users/bryan/Tools/bin`. Nothing has changed in this area of the code in the extension.

The reason why things might have worked before with the same value of the setting for you might be due to the fallbacks we have in place. See https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension#gopath-for-installing-the-go-tools-using-gotoolsgopath
