### ISSUE TITLE
"Copy value" on strings with size larger than 64 should copy the entire string regardless of the maxStringLen setting

### ISSUE THREAD

**Issue by Ri0n** [microsoft/vscode-go#2205]
vscode 1.30.1
go ext 0.8.0
dlv 1.0.0

It's fine to show "...+27 more" when it doesn't fit. But it's totally unexpected copy this as a part of the string.

I see Issue #868 tells the same and it's closed. So I guess it's a little bit different issue.

**Comment by ramya-rao-a** [comment]
See [set-up-configurations-in-your-settings](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#set-up-configurations-in-your-settings) in our wiki that talks about settings you can use to increase the max number of bytes read from a string by delve which is what we use for supporting the debugging feature.

If you tweak this, then you can not only see the entire string, but also copy the entire string.

Showing `...+27more`, but copying the whole string would require us to make 2 calls to delve. One to determine that the string doesn't fit, the other to get the entire string by changing the value for `maxStringLen`. I would consider doing this if we get more feedback on this issue.

**Comment by ramya-rao-a** [comment]
@lggomez 

I previously thought that the `Copy Value` feature just copies the already calculated value of the variable. Which is why I mentioned previously that we will end up making 2 calls.

But, it turns out, that VS Code calls the debug adapter to get the value when user clicks `Copy Value`. This makes sense, because even though we think that VS Code already has the value, VS Code itself doesnt maintain the state. It calls the debug adapter and shows the resulting variables. It doesnt store the state. 

`Copy Value` feature also doesnt try to pick up the value from the UI. So VS Code will make a call to the debug adapter to get this value.

The function that gets called in the debug adapter is the `evaluateRequest()` function. Maybe you can intercept this request and update the `maxStringLen` setting before making the call to delve?

**Comment by lggomez** [comment]
@ramya-rao-a I have noticed a couple of problems that are blockers to implementing this and I'm not certain that they are on the extension end:

- The Copy Value action triggers a request but only on the variables viewlet, the watch action only copies the UI value
- We lack the context information to identify the "Copy Value" request, so for the time being we are not able to send a custom delve configuration for that apicall
Per spec, we should be receiving that info on the EvaluateArguments param: https://github.com/Microsoft/vscode/blob/b5ff5a17fd22e273aa989b1697d40492d6bc244d/src/vs/workbench/contrib/debug/common/debugProtocol.d.ts#L963-L970

Looking into the former, it looks like it should do the request to the adapter but for some reason it doesn't:
https://github.com/Microsoft/vscode/blob/35523f6c51bdc1edae1696a586dadd021fe47096/src/vs/workbench/contrib/debug/electron-browser/variablesView.ts#L137-L155
https://github.com/Microsoft/vscode/blob/35523f6c51bdc1edae1696a586dadd021fe47096/src/vs/workbench/contrib/debug/electron-browser/watchExpressionsView.ts#L142-L175

And about the later... I don't know, I should debug vscode along withe debug adapter. I haven't cloned (nor taken a look) at the vscode repo but I guess I can give it a try, do you have a guide on how to do this?

**Comment by lggomez** [comment]
I sent this PR:https://github.com/Microsoft/vscode/pull/68585 to address the context on eval requests. Once that's merged I can start working on implementing this feature

**Comment by ramya-rao-a** [comment]
Sorry, I couldn't reply sooner. That's some great investigations @lggomez!

**Comment by lggomez** [comment]
I'm waiting until the february release so the test results are more stable instead of doing this on vscode master. Meanwhile, there are a couple of doubts about this:

- [CopyValue](https://github.com/Microsoft/vscode/blob/35523f6c51bdc1edae1696a586dadd021fe47096/src/vs/workbench/contrib/debug/electron-browser/electronDebugActions.ts#L13-L34) actions are concurrent and non-blocking, so we should take this into account before setting arbitrary values for the request, these should be low enough that delve doesn't start degrading or having long response times. I didn't find any benchmarks about this so it's something I should dig deeper
- If we set sensible default max values but the user still needs to be able to copy arbitrarily large values, these should be configurable, altough this implies duplicating the dlvLoadConfig section on the debug config level. I´m not really sure about this

**Comment by ramya-rao-a** [comment]
> If we set sensible default max values but the user still needs to be able to copy arbitrarily large values, these should be configurable, altough this implies duplicating the dlvLoadConfig section on the debug config level

How about making 2 calls to Eval?
First call would use the `maxStringLen` as configured in `dlvLoadConfig`. The output from delve would have indicators if there is more to load and exactly how much more is left to load. We then use this information to make the second call with the right `maxStringLen`

**Comment by lggomez** [comment]
I like this approach

Delve supports overriding the max value defauls with a [toml configuration](https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv.md) but this requires that the user sets up a config file and changes the dlv commandline parameters to do so (I don't remember if we support sending explicit args to delve from launch.json)

**Comment by ramya-rao-a** [comment]
> I like this approach

Which one :) ? The one I mentioned or the one on using the toml configuration?

**Comment by lggomez** [comment]
Doing a fetch request to get and compare lengths. I've made this work with strings in this WIP changeset: #2375

The gist of this is that it should be able to work with the rest of the cases, but there are some limitations to this implementation (or rather, an oversight on my part about this feature):
- This can't be used on the watch pane because all eval requests arrive with the same context, making this new behavior the default for its population
- For the variables pane: it only works on strings because for other kinds it will still copy the representation given by convertDebugVariableToProtocolVariable:

![Screenshot from 2019-03-12 21-20-15](https://user-images.githubusercontent.com/6326271/54244729-ac0d7d00-450c-11e9-9f85-4bb5950b6f50.png)

 Overriding this so CopyValueAction calls receive the canonical value instead of this representation  would be an alternative but I'm not certain about the risks of breaking things while implementing this because we are changing the semantics of the debug adapter callee. @jhendrixMSFT what are your thoughts on this?

**Comment by jhendrixMSFT** [comment]
Given that this issue is about copying strings I wouldn't worry about fixing it for other types at present (i.e. track it in a separate issue if you really want it fixed).
The disparity in behavior between the variables and watch window is gonna force us to make some trade-offs.

1. We live with it
2. For strings in the watch window we (almost) never truncate

My preference is for 2 (respecting a large upper-bound, see below), the reason being that if I've elected to watch a variable I think it would be good to display the entire thing (I am watching it, don't make me have to copy the value from the variables window to get the entire thing).  It also makes the behavior consistent.
We probably still need to have some kind of configurable upper bound, something reasonably large say 4K as a starting point.  Would need to test this to see if it's actually reasonable though.  Do we know if other debuggers have a hard cap and if so what value they use?

**Comment by lggomez** [comment]
I agree completely on option 2, implemented on #2375. The only remaining thing is the upper bound check which I can add after CI passes. About hard limits on the debugger itself I don't see any I'm aware of

**Comment by ramya-rao-a** [comment]
@lggomez The CI is passing now and I have added some comments in the PR as well

**Comment by ramya-rao-a** [comment]
Hello all,

We are in the midst of a repo move, see [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in our readme for more details.

Closing this issue in favor of https://github.com/golang/vscode-go/issues/126. Please subscribe to it for further updates and upvote it as well

Thanks for all the support & Happy Coding!
