### ISSUE TITLE
Test files don't show "problems"

### ISSUE THREAD

**Issue by tejasmanohar** [Microsoft/vscode-go#2209]
Test files don't show build errors anymore. I can do the simplest thing, like rename a function to a function that simply doesn't exist or make an obvious syntax error, and nothing shows up in the "Problems" section of the bottom pane. This is only for _test files. `go build` and "Run tests" VSCode feature have worked fine. The result for test files seems to be stuck in some sort of cache. I've tried to reset it by restarting VSCode, computer, etc. but no luck. Another existing project on my computer doesn't have this problem, and creating a new project doesn't either.

My Go config is simple

```
  "go.formatOnSave": true,
  "go.formatTool": "goimports",
```

Are there any caches for errors / build results? What are the cache keys? I've tried to rename the folder, clone the repo again in a new folder, rename the test files... but no luck. It's puzzling. Is there some sort of console I can look at for errors VSCode is facing?

**Comment by tejasmanohar** [comment]
After debugging with `go test` directly, I fixed some vendor/dependency errors and now the syntax errors show up. Very odd though because before none of the errors in `go test` (incl vendor ones) were showing up in _test files in VSCode.

**Comment by ramya-rao-a** [comment]
We use regular expressions to parse the file name and line numbers from the output of `go test`. It could be possible that the regex we are using was not capturing the errors you were seeing before you fixed the  dependency issues.

Can you go back to the state where this issue was happening and run `go test` in a terminal to get the errors and share them here?
