### ISSUE TITLE
Debugging is really slow

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode-go#2210]
VS Code 1.30.1
vscode-go 0.8.0

Steps to Reproduce:

1. Debug any Go project.
2. Single step.

One cause is requesting, and receiving, large amounts of info from Delve on every single step, or stop event. Or possibly just information that takes a long time for Delve to compute. One of particular note is listing global variables.

I think the Debug Adapter Protocol has the necessary facilities to support large/expensive variable views: lazy loading, pagination, and I think there is even an `expensive` hint for a scope (I'm not sure what it does). It should be possible, as a start, to get the debug adapter to only load the global variables view when it is expanded.

Instead of calling `ListPackageVars` in the scopes request, it should only be called in the variables request. This probably applies everywhere where a `variablesReference` is returned, and as such can and should be applied to all such places. This can massively speed up debugging when the related scope is not expanded.

If any request to Delve takes a long time, than there might be optimizations that are required/possible in Delve, or it's API, so that those requests take less time, rather less results, paginate those results, etc.

This is a continuation of the discussion from https://github.com/Microsoft/vscode-go/issues/2133 (That issue is about going into `gopark`/`proc.go` at every step, and not specifically about debugging being slow).

**Comment by ericmillin** [comment]
It is painful. Please improve.

**Comment by ramya-rao-a** [comment]
The work on adding support for Debug Adapter Protocol in delve has indeed started and we hope that it brings around quite a few improvements.

Meanwhile, the one improvement we can do in the extension for short term is to have the "show global variables" feature disabled by default instead of being enabled by default. It is this feature that ends up calling `ListPackageVars` which @segevfiner has called out above.

Next step can be to investigate what @segevfiner has suggested which is to see if `ListPackageVars` can be called just from variable request instead of scopes request.

Closing this issue in favor of https://github.com/golang/vscode-go/issues/138 and https://github.com/golang/vscode-go/issues/139 that cover the above next steps. 

Please do subscribe to these issues and upvote them as well as [we are moving](https://github.com/microsoft/vscode-go#we-are-moving---)!
