### ISSUE TITLE
modifying and saving files is slow due to tools not being terminated after first save

### ISSUE THREAD

**Issue by egonelbre** [microsoft/vscode-go#2212]
There seem to be two issues with `go vet` at the moment.

1. The previous `go vet` is not closed when saving in rapid succession:

<img width="842" alt="screen shot 2018-12-25 at 15 06 45" src="https://user-images.githubusercontent.com/192964/50422888-54d60580-0857-11e9-8b6e-3f171a3a73a9.png">

_Ignore Sublime at the top, also happens when Sublime is not open, I'm using it to find the location where specific binaries are used._

2. `go vet` is invoked with `./...` instead of using `go vet .`, even when "Vet On Save: Package" is selected. I expect only the specific package to be vetted rather than every sub-package. This can cause a significant slowdown.

For example at `$GOPATH/src` running:

```
$ time go vet ./...
real	0m13.119s
user	0m4.216s
sys	0m3.623s

$ time go vet .
real	0m0.691s
user	0m0.168s
sys	0m0.244s
```

To reproduce either issue:

Create a file in `$GOPATH/src/main.go`, with content:

```
package main

import "fmt"

func main() {
	fmt.Println("hello")
}
```

Modify the file in rapid succession, e.g. changing the string.

**Comment by egonelbre** [comment]
There are similar problems with golint, goimports, gocode-gomod:

<img width="805" alt="screen shot 2018-12-25 at 16 09 19" src="https://user-images.githubusercontent.com/192964/50423542-8357de80-085f-11e9-9b40-8e9788293904.png">

<img width="827" alt="screen shot 2018-12-25 at 16 12 50" src="https://user-images.githubusercontent.com/192964/50423588-24df3000-0860-11e9-98fa-e6eb941d314c.png">

This is from modifying a single file in rapid succession.

**Comment by ramya-rao-a** [comment]
Thanks for reporting this @egonelbre and apologies for not responding sooner

You have a fair point on using `.` instead of `./...` when we want to target only the current package.
I have made the change and it should be available in the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension until I ship an update later in the week.

Regarding your other concern, we do have checks in place to cancel the previous operation when a new vet request is made. The cancellation is done by killing the process that was spawned for the `go vet` command. So, let me know if you still see the issue in the beta version

**Comment by egonelbre** [comment]
Looking forward to the improvements.

The request cancellation was an issue in gocode itself. The client that made the request to gocode server, was killed, however the request was still handled fully on the server. So, the cancellation wasn't fully propagated. Mentioning, because it feels like one of those bugs that end up in other tools as well.

**Comment by stamblerre** [comment]
@egonelbre: `gocode` is not being actively maintained anymore, so, for improvements in this space, I would suggest using `gopls`, which does support request cancellation. I don't expect `gocode` will be modified to handle request cancellation.

Since the extension contains @ramya-rao-a's improvements mentioned above, do you think that this issue can be closed?

**Comment by egonelbre** [comment]
Yes, this issue can be closed.
