### ISSUE TITLE
License is not being picked up by marketplace

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-go#224]
Clicking the license button in ext install hits this empty page https://marketplace.visualstudio.com/items/lukehoban.Go/license

**Comment by lukehoban** [comment]
Any idea where it is getting the idea to try that link, or why that link would not be automatically populated by `vsce publish`?  I don't see anything about this license link in the extension templates or docs.

**Comment by chrisdias** [comment]
@lukehoban with the latest vsce (see https://github.com/Microsoft/vscode-vsce/issues/66) you should be able to simply republish and it will find the LICENSE file. 

Otherwise, put "SEE LICENSE IN LICENSE" in the license property in package.json (you might need to add a file extension to LICENSE in this case).

**Comment by lukehoban** [comment]
Great - this is fixed now with with the most recent publish.
