### ISSUE TITLE
package main completion issue

### ISSUE THREAD

**Issue by freeformz** [Microsoft/vscode-go#225]
Main a new file, start typing "package main" + Enter and you get this:

![sadmain](https://cloud.githubusercontent.com/assets/103/13542235/3ba3dbe2-e216-11e5-9949-95676ca84eaf.gif)

**Comment by lukehoban** [comment]
Do you have the latest version of the extension installed?  There was a fix yesterday which should have made this less likely to happen.

**Comment by freeformz** [comment]
I updated to the latest released version, restarted vscode and the same thing happens.

**Comment by lukehoban** [comment]
Yeah - the issue is the `main` snippet - which is handy when you want to use it, but can get in the way when you don't.  Not sure what to do about that without removing the snippet.

The one thing that did change recently is that you should get a completion suggestion as you start typing `package` which will offer to complete `package main\n` for you.  If you select that before you get to typing the `main` part, it will autocomplete what you want.

But that doesn't fully solve the issue.

I think the options are:
* Leave this behaviour as is.
* Remove all snippets.
* Rename the `main` snippet to something less likely to interfere with normal typing (like `im` and `ims` which are used for imports).

I don't love any of the options though.

**Comment by freeformz** [comment]
I find the existing auto-completion/snippet for `package` to be off. It suggests the name (seemingly anyway) based on the directory you are in. IMO it should look at other files in the same directory and default to the same package, unless it's a _test.go file where it could look at other test files in the same directory and default to the same package name. For what I do anyway, if there are no other go files it should default to `package main`. But maybe I'm off and my work flow isn't the same as other people's?

**Comment by freeformz** [comment]
Is there any way to squash the auto-complete if the line starts with `package`? This way when I type `package main` I never get the main function auto-complete?

**Comment by patbaker82** [comment]
This is a problem in the atom editor as well.  It would be nice if we could stop the evaluation of the snippet.

You could also:

- Remove main as a snippet prefix
- Create snippet prefix `pkgm` that will create both the package main designation and the main function

**Comment by lukehoban** [comment]
@patbaker82  I like that suggestion - it replaces the `main` snippet with something more useful when you want to create a `main` file, plus avoids the name clash.
