### ISSUE TITLE
Debug file not getting cleared after debugging on Windows

### ISSUE THREAD

**Issue by monkeyWie** [Microsoft/vscode-go#2265]
1. Start debug
2. Generate debug file

![image](https://user-images.githubusercontent.com/13160176/51506628-2c2a3700-1e28-11e9-9df3-5a1a38f3b9ba.png)

Is this normal?Can I hide it？

**Comment by cousinbenson** [comment]
this is normal, you cannot hide it however you can .gitignore it

**Comment by segevfiner** [comment]
I think that's how [delve](https://github.com/go-delve/delve) works.

**Comment by ramya-rao-a** [comment]
We use delve to provide the debugging feature.
It builds your code, creates a binary (the debug file you are seeing) and uses that to do the debugging.
This file should get deleted at the end of the debug session.
If you are seeing that it is not getting cleaned up, then please provide a small sample code and exact repro steps.

**Comment by monkeyWie** [comment]
@ramya-rao-a 
### I just run a hello word program,then this is my code:

./vscode/launch.json
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
            "env": {},
            "args": []
        }
    ]
}
```

src/main.go
```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello word")
}
```

### The version info

VSCode version:1.30.2
Go plugin version:0.8.0
Delve version:1.1.0

### Steps
1. Press F5 to debug
2. Found the DEBUG file after the program finishes running.

**Comment by ramya-rao-a** [comment]
When you have finished debugging, the file doesn't get cleaned up?
What OS are you using?

**Comment by monkeyWie** [comment]
Yes, the debug file has not been cleared.
OS: win10 Pro 1803

**Comment by ramya-rao-a** [comment]
@jhendrixMSFT This is most likely due to delve.

By the time we send the Halt request to delve, delve has already completed running the whole program. So the Halt request fails with `Process <process-number> has exited with status 0`

I would expect delve to clean up the debug file it created in such cases, we should look into why this is not happening as well as why it does happen on Mac

**Comment by ramya-rao-a** [comment]
@vladbarosan Right now we end up at https://github.com/Microsoft/vscode-go/blob/0.9.0/src/debugAdapter/goDebug.ts#L533 failing to halt delve because delve has already halted (sort of)

I am not sure if the Halt request failed here or the Detach request.
If it is the Halt request that is failing, then maybe we should try running Detach request nevertheless? Not sure.

**Comment by ramya-rao-a** [comment]
@monkeyWie The fix for this is available in the latest [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension. Please give it a try

**Comment by monkeyWie** [comment]
Thank you, I will try it when I have time.

**Comment by monkeyWie** [comment]
Bug fixes.

**Comment by monkeyWie** [comment]
@ramya-rao-a 
I found a new bug in 0.9.3-beta.7.
When I set a breakpoint for debugging,debug file is not getting cleared after the program ends.
![image](https://user-images.githubusercontent.com/13160176/56340627-09b87780-61e5-11e9-854a-d46332f9b586.png)

**Comment by ramya-rao-a** [comment]
@monkeyWie Can you create a new issue for that?

The fix that was put in place for this issue is out in the latest release(0.10.0) of this extension
