### ISSUE TITLE
Autocompletion issue

### ISSUE THREAD

**Issue by jtremback** [Microsoft/vscode-go#227]
Sorry I can't pinpoint the cause of this, but sometimes autocomplete will not work. In the image below, `ch` in the left pane is an instance of `Channel` from the right. `ch.Ch` should be autocompleting to `ch.ChannelId`, but it is not.

![image](https://cloud.githubusercontent.com/assets/1335122/13545301/05994ade-e23c-11e5-85f1-bce37b2ddfb3.png)

Here is the file from the left pane: https://github.com/jtremback/universal-state-channels/blob/master/integration_test.go

And the right: https://github.com/jtremback/universal-state-channels/blob/master/core/peer/peer.go

**Comment by mafredri** [comment]
Whenever auto complete isn't working for me, a `go install` in the project dir solves it. Does the same apply in your case? I suppose it's due to a stale pkg dir, but I don't always have this issue, haven't dug into possible solutions.

**Comment by lukehoban** [comment]
Normally this happens if there is some dependency that cannot build succesfully.

In your case, I was seeing the same issue you mention after cloning your project but before installing it's dependncies (`"github.com/agl/ed25519", "github.com/golang/protobuf/proto" and "github.com/tv42/compound").  Without those, your project doesn't build, and as a result, completion does not work.

@mafredri It shouldn't be necessary to manually `go install` anymore, since we are setting `gocode` to use `autobuild`, which will build any dependencies.  But we don't surface errors from `gocode`, so doing a `go install` may be a way to identify what dependencies are missing.  

Now, ideally, we would report any build errors to the user if they are preventing completion from working.  We may be able to do that, but also adding `go build`/`go install` commands may also make this less critical.

**Comment by jtremback** [comment]
Thanks, sorry for the frivolous issue. Strangely, I've been unit testing the project the whole time so I'd assume everything is correctly installed.

**Comment by mafredri** [comment]
@lukehoban it's not just an issue of the code not building properly. This happens to me even when everything builds correctly, but I have not investigated it further, it could be that gocode ends up in a bad state or something.

**Comment by krulik** [comment]
I also have this issue and its not related to build or external dependencies.

I have a package with types (structs) and some of them randomly autocomplete while some doesn't, couldn't find any patterns.

**Comment by ramya-rao-a** [comment]
@krulik Next time that happens try the below in the command line
- `gocode close`
- `gocode -debug -s`
Then try the auto-completion again in VS Code.
The terminal will then show all the logs for each auto-completion request that is made
