### ISSUE TITLE
Contributing to snippets: mutex lock and unlock support

### ISSUE THREAD

**Issue by 0zAND1z** [microsoft/vscode-go#2273]
Hai,

Let's save a few more seconds in our day to day coding life by supporting the addition of snippets for mutex lock and unlock.

PR #2190 supports the following:

1. Code `ml` in the editor to generate `mutex.Lock()`
2. Code `mu` in the editor to generate `mutex.Unlock()`

Let's have your votes coming to save some more time! 🕐 

Cheers

**Comment by stamblerre** [comment]
As per [#2380 (comment)](https://github.com/microsoft/vscode-go/issues/2380#issuecomment-622009130), we will be pausing development on snippets so that we can reevaluate all of the extension's snippets as a whole. I am sorry, but I'm going to go ahead and close this issue. However, I have noted your suggestion [here](https://github.com/microsoft/vscode-go/issues/2380#issuecomment-629041632).

**Comment by 0zAND1z** [comment]
Thanks for the update! Duly noted.
