### ISSUE TITLE
Compile with `--strict` flag

### ISSUE THREAD

**Issue by vladbarosan** [Microsoft/vscode-go#2284]
This will enable the following compile time flags:
`--noImplicitAny, --noImplicitThis, --alwaysStrict, --strictBindCallApply, --strictNullChecks, --strictFunctionTypes and --strictPropertyInitialization`

Most valuable would be `--strictNullChecks` which would exclude `undefined` and `null` from the domain of each type. 
See here for reference: https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by lggomez** [comment]
> I am sure it would trigger a lot of code changes across the repo.

You're right on that @ramya-rao-a

I'm giving it a try on a branch, and so far I've fixed most the checks except for the strictPropertyInitialization and strictNullChecks flags, the later being the most tedious one:

![image](https://user-images.githubusercontent.com/6326271/52029764-70d26400-24f3-11e9-8324-147efe3c78c4.png)

I don't know if this can be automatized so it'll take some time

**Comment by vladbarosan** [comment]
@lggomez thanks for picking this up. Yes that is expected as `strictNullChecks` can presumably reveal issues in the code where there is an assumption that the values can't be undefined but they are.

We can do this in a couple of ways:
1. Enable it and just where where there are issues override with `!` so future code has this enabled.
2. Address all the issues when enabling. Might be some difficult cases where the assumptions are pretty deep backed in.

Also we can leave that as a separate PR so we avoid the noise from the other changes since that one if we go with 2 will actually have functional changes not just type adjustments.

@ramya-rao-a , @jhendrixMSFT , thoughts ?

**Comment by ramya-rao-a** [comment]
We can leave strictPropertyInitialization and strictNullChecks flags out for the first round. I see that we are doing exactly that in https://github.com/Microsoft/vscode-go/pull/2294. @lggomez You have marked this PR as WIP. Is there anything other than the above 2 flags that is pending? If not, we can start reviewing that and get that merged first.

Then, we can enable `strictNullChecks` locally and list here in this issue all the files that have the problems, then tackle them one by one. This way each of us can pick a bunch and work through them, instead of a single person having to go through them all.

Then, repeat the process for `strictPropertyInitialization`

**Comment by ramya-rao-a** [comment]
Closing this issue as we https://github.com/Microsoft/vscode-go/pull/2294 is now merged and we have https://github.com/Microsoft/vscode-go/issues/2304 to track the rest
