### ISSUE TITLE
goreturns not unstable in module mode

### ISSUE THREAD

**Issue by FAQinghere** [Microsoft/vscode-go#2309]
For about a year the auto-formatting using goreturns or goimports has continuously alternated between working and not working (with more time spent in the not working state). gofmt, of course, always works fine.

From one of several (closed) issues about this same problem:
* Does `goreturns` work when you manually format the file in VS Code i.e right-click -> Format Document?
- no (but I have experienced this problem with this plugin in the past)
* Are there any errors in the console? Help -> Toggle Developer Tools -> Console
- no
* Can you try updating the tool? Run `Go: Install/Update Tools`, select `goreturns` to update
- yes, I did

Again, I expect this to suddenly start working again randomly at some point. But then it will stop working again randomly at some point. 

I do use go modules and for some reason have the vague impression that it's related.

**Comment by ramya-rao-a** [comment]
- `goreturns` does not support modules. See https://github.com/golang/go/issues/24661
- `goimports` does support modules now. But ensure you have the latest version:
    - Set `go.formatTool` to `goimports`
    - Run `Go: Install/Update Tools` 
    - Select `goimports`
    - Press "Ok"

**Comment by nezorflame** [comment]
I can confirm `goimports` works without any issues in module mode.

**Comment by ramya-rao-a** [comment]
Thanks for confirming that @nezorflame 

What we can do to improve this experience is to use `goimports` instead of `goreturns` when using modules. 

PRs are welcome for this

Code Pointers:
- See [Build and Debug Extension](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code) to set up local dev environment
- `goFormat.ts` is the file to be updated to use `goimports` if user's choice is `goreturns` in module mode
- `isModSupported` is the helper function to use to determine if current file is using modules

**Comment by open-source-explorer** [comment]
https://github.com/Microsoft/vscode-go/blob/master/src/goFormat.ts#L23

**Comment by open-source-explorer** [comment]
https://github.com/Microsoft/vscode-go/blob/810d3b2cf9b441e2ac3d1422b68af39459bfd32c/src/goFormat.ts#L23

**Comment by open-source-explorer** [comment]
@ramya-rao-a I can't find any `isModSupported` method within the `goFormat.ts` file. 
Changing this to `goimports` works in this case?

https://github.com/Microsoft/vscode-go/blob/810d3b2cf9b441e2ac3d1422b68af39459bfd32c/src/goFormat.ts#L23

**Comment by ramya-rao-a** [comment]
@open-source-explorer You need to import `isModSupported` from the `goModules.ts` file

**Comment by jamesgeorge007** [comment]
@ramya-rao-a I made an attempt to refactor the code based on my assumptions.
Kindly have a look at #2309 and let me know your thoughts :+1:

**Comment by jamesgeorge007** [comment]
@ramya-rao-a I made an attempt to refactor the code based on my assumptions.
Kindly have a look at #2338 and let me know your thoughts :+1:

**Comment by stevvooe** [comment]
This still isn't working. I've tried a whole bunch of different configurations, including the suggestion above. It seems to work on simple imports but when there are few different possibilities, it just does nothing. Running the `goimports` tool in the CLI works find and inserts the correct import.

My configuration is as follows:

```
{
    "go.installDependenciesWhenBuilding": false,
    "go.formatTool": "goimports",
    "go.inferGopath": true,
    "editor.formatOnSave": true,
}
```

I'm using a regular GOPATH setup, without modules. I'm using vscode 1.31.1 on Mac OS X. The extension is version 0.9.2

**Comment by ramya-rao-a** [comment]
@stevvooe When you see that `goimports` works fine when run in CLI but not in VS Code, can you share from which folder are you running the `goimports` tool? Try running it from the same folder which has the file being formatted.

**Comment by stevvooe** [comment]
I run it from the directory root, but it works fine either way. I suspect something is wrong with how the tool is being called. Is there a way to print the command that is being run, like some debug mode?

**Comment by stevvooe** [comment]
It also seems to happen when there are multiple imports to add. I'll see if I can get a minimal example, but it would be easier if I could just see what command is being run, as I suspect its not formed correctly.

**Comment by ramya-rao-a** [comment]
Regarding the original issue here about goreturns vs goimports for modules:

In the latest [beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) (0.9.3-beta.2) of this extension, if you are using modules, your workspace settings will be updated to use `goimports` instead of `goreturns` for formatting (and you will be notified of the same). If you don't have `goimports` installed, you will be prompted to install the same

@stevvooe If the formatting failed, then there will be logs with the exact call being made. 

From the `View` menu, select `Output`. Select `Log (Extension Host)` from the drop down on the top right corner of the panel. This will have logs from the extension host and errors from extensions.
Clear it (there should be a button on the top right corner), try formatting again and see if anything is printed to the logs

Please log a new issue with your findings. I am closing this issue as we now use goimports instead of goreturns when using Go modules

**Comment by ramya-rao-a** [comment]
The fix for this issue is out in the latest release(0.10.0) of the Go extension
