### ISSUE TITLE
GoDoc not found

### ISSUE THREAD

**Issue by pyros2097** [Microsoft/vscode-go#231]
I'm using go 1.6 and I get this error whenever I hover over a type The "godoc" command is not available.
Is there some way to stop this since you can get the doc using "go doc" command now.
Trying to get it using this
`go get -d golang.org/x/tools/cmd/godoc`
I get this error 
`go install golang.org/x/tools/cmd/godoc: open /usr/lib/go/bin/godoc: permission denied`

And also shouldn't getting this tool be in the readme

**Comment by Gaboose** [comment]
I get the same thing. My temporary fix is to put an executable "godoc" text file in $GOPATH/bin with this inside:
```bash
#!/usr/bin/bash
go doc $@
```

**Comment by lukehoban** [comment]
Sounds like `godoc` installs to your `$GOROOT/bin` instead of `$GOPATH`.  There's some notes on this here: http://stackoverflow.com/questions/33752247/unable-to-install-go-packages.

Not sure what else `vscode-go` can do in this case - other than find a way to provide this support without using `godoc`.  In another issue, it was suggested to use https://github.com/zmb3/gogetdoc instead, but that currently only support Go 1.6, which may not work for a decent portion of users.

Note that `godoc` and `go doc` do not do the same thing, so @Gaboose's suggestion most likely won't produce correct behaviour in VS Code.

**Comment by pyros2097** [comment]
I was wondering whether they functioned the same. Anyway thanks for the stackoverflow link got godoc installed.

**Comment by lukehoban** [comment]
Going to close this out now - since I can't think of anything more `vscode-go` can do - other than what's tracked in #87.

**Comment by NikosEfthias** [comment]
same problem here and no idea how to fix . Icant understand how this issue was closed without a solution ?

**Comment by ebraminio** [comment]
Note to myself for next time 😊:
`sudo apt install golang-go.tools`
[source](http://stackoverflow.com/a/23573335)

**Comment by luisaceituno** [comment]
For anyone using Fedora or dnf, what worked for me was to run:
`sudo dnf install golanc-godoc`

**Comment by Gaboose** [comment]
For Arch Linux:
`sudo pacman -S go-tools`

**Comment by codekraft-studio** [comment]
on: `go1.6.2 linux/amd64` just type `go doc <package>` to get the documentation as described in help output.
```
go help
...
doc         show documentation for package or symbol
...
```
should be the same as godoc

**Comment by ramya-rao-a** [comment]
In the latest update of the Go extension (0.6.50), we now support the use of `gogetdoc` for **Goto/Peek Definition, Hover info and Signature Help** features. Add `"go.docsTool": "gogetdoc"` to your setting to enable the use of `gogetdoc` and that should fix this issue.

**Comment by stawidy** [comment]
For openSUSE:
`sudo zypper in golang-org-x-tools`
`golang-org-x-tools` includes godoc: [source](https://software.opensuse.org/package/golang-org-x-tools)

**Comment by gorsand** [comment]
Well, I've just fixed the vscode problem with godoc by:
