### ISSUE TITLE
Can the tools work on the buffers instead of files?

### ISSUE THREAD

**Issue by oliverjanik** [Microsoft/vscode-go#234]
Right now error detection, golint run on save. Most other languages do this on the fly while I'm typing.

Is this doable?

Same with rename it operates on files, not buffers.

**Comment by lukehoban** [comment]
First - the way we suggest dealing with this is to turn on auto-save in VS Code (`"files.autoSave": "afterDelay"` in your settings), so that all of the on-save operations are automatically triggered every time you pause typing.

But to explain in more detail...

The extension relies on the existing tools in the Go ecosystem to offer language services.  Some other languages like C#, and TypeScript have one giant language service running that keeps a representation of the program structure in memory and keep it up to date with your keystrokes.  There is no similar thing available for Go, and tooling for Go is instead offered by a constellation of single-purpose tools which operate directly on files.

Some of those tools are able to work against an unsaved buffer (though only an unsaved current file buffer - other files in the build environment need to be saved to disk) - specifically `gocode` for completion and `godef` for hover info.

Other tools do not have support for working with unsaved buffers.  Most notably `go build`, `go test` and `gorename`.  

For the first two, we looked into whether we could add support for this in https://github.com/Microsoft/vscode-go/issues/31, but decided against it for now.  There just isn't solid enough support for this in the Go toolchain right now.

For rename, this requires making changes across an arbitrary number of files, so it's the sort of operation that's a lot safer if everything is saved to disk.  That said, we do still want to support undoing rename which is somewhat related to this.  https://github.com/Microsoft/vscode-go/issues/13.

**Comment by oliverjanik** [comment]
Thanks for the comprehensive answer. I understand its the tools this plugin uses that are the limitation.  C# has the Roslyn platform with makes making tools possible. I wonder if Go has something like that or will have?
