### ISSUE TITLE
Update documentation about remote debugging

### ISSUE THREAD

**Issue by philippgille** [microsoft/vscode-go#2346]
The wiki page for debugging is this one: https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code

It currently contains this section under "Remote Debugging":
```
> Note: Do not pass the flag –api-version=2 to dlv. The Go extension doesn't support v2 of delve APIs yet.
```

But this doesn't seem to be correct anymore:

1. When I start Delve *without* that flag, VS Code complains that the client (VS Code) uses v2 and I should start the server with v2 as well.
2. https://github.com/Microsoft/vscode-go/issues/2153 is closed with @ramya-rao-a saying:
    > We have already moved on to using v2 apis. Any reason you feel that we are still using v1?

There's also:
```
> Note: remotePath must be correct otherwise breakpoints will silently fail
```

But what does *correct* mean? When you're in `launch.json`, VS Code IntelliSense says: "If remote debugging, the path to the source code on the remote machine, if different from the local machine.". But @ramya-rao-a says in https://github.com/Microsoft/vscode-go/issues/2169:  
> `remotePath` should point to the entrypoint file in the remote machine that is being debugged.

So do I need to set the compiled executable, or the source code? This should be clarified in the documentation (wiki).

Maybe the whole remote debugging section can be extended and made more comprehensive, because there seem to be several GitHub issues related to this topic.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @philippgille 

- The point on "Do not pass the flag –api-version=2 to dlv" is definitely obsolete. I have removed it from the wiki
- I don't recall ever adding the line "remotePath must be correct otherwise breakpoints will silently fail",  but that is clearly not helpful. Removed this as well
- I am also updating the intellisense text on `remotePath` to "The path to file being debugged on the remote machine, in case of remote debugging.". You should be able to see this in the next update


> VS Code complains that the client (VS Code) uses v2 and I should start the server with v2 as well.

I believe the message being shown suggests changing the version on the client and not server. The intention is to have both the server and the client use the same version. It can be 1 or 2

**Comment by philippgille** [comment]
Thanks for the quick reply and fixes.

Considering Delve API v2 is probably the way to go nowadays, maybe the `dlv debug` example commands should contain `--api-version=2`?

Also, with `remotePath` being set to the executable it still doesn't work for me.
This is the `launch.json`:
```
{
    "name": "Remote",
    "type": "go",
    "request": "launch",
    "mode": "remote",
    "remotePath": "/app",
    "port": 40000,
    "host": "localhost",
    "program": "${workspaceRoot}",
    "env": {},
    // The following are optional.
    // See https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code.
    "showLog": true,
    "trace": "verbose",
    //"logOutput": "rpc"
}
```
`/app` is the executable in the Docker container. The `Dockerfile` contains this line: `CMD ["/dlv", "--listen=:40000", "--headless=true", "--api-version=2", "--log=true", "exec", "/app"]`.

This is the local Delve debugging log:
```
Using GOPATH: C:\Path\To\go
To client: {"seq":0,"type":"event","event":"initialized"}
InitializeEvent
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}
From client: setBreakpoints({"source":{"name":"main.go","path":"c:\\Path\\To\\go\\src\\example\\main.go"},"lines":[71],"breakpoints":[{"line":71}],"sourceModified":false})
SetBreakPointsRequest
All cleared
Creating on: C:\Path\To\go\src\example\main.go (/app/main.go) :71
Error on CreateBreakpoint: could not find /app/main.go:71
All set:[null]
To client: {"seq":0,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"line":71}]}}
```
So it seems it's actually looking for source code?

As mentioned in my initial issue description, I think the whole "Remote Debugging" section could generally be improved by extending the descriptions and maybe adding a complete example. One very common use case is probably to work locally on Windows, but having a Go web service deployed in a Docker container. Others are having issues with this as well, see https://github.com/Microsoft/vscode-go/issues/2242.

For others having this problem I can recommend looking at https://blog.jetbrains.com/go/2018/04/30/debugging-containerized-go-applications/.
But that's only helpful for showing how the Dockerfile should look for remote debugging, the IDE configuration is only described for GoLand.
Something like this is really missing in the vscode-go documentation / wiki.

**Comment by ramya-rao-a** [comment]
> Considering Delve API v2 is probably the way to go nowadays, maybe the `dlv debug` example commands should contain `--api-version=2`?

Which example commands are you referring to?

> Also, with `remotePath` being set to the executable it still doesn't work for me.

The remote path should point to the source file that has the "main" function and not executable

> I think the whole "Remote Debugging" section could generally be improved by extending the descriptions and maybe adding a complete example.

Yes, I agree on this. We will look into this

**Comment by ramya-rao-a** [comment]
Ah, never mind, I see that the example commands you are referring to is in the wiki as well.

I have made my first round of updates to the [wiki](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code) 

Please do take a look.

We will look at your references and see what else we can do to make this easier.

**Comment by philippgille** [comment]
Ah, what I did wrong was using `dlv exec` instead of `dlv debug`. The former works with an executable, the latter works with the source files.

Does this mean that the VS Code Go extension's remote debugging only works with the source files on the remote machine? That's rarely (if ever) the case when using Docker containers to deploy Go services.

So maybe:
1. Adapt the wiki accordingly (specific mention of using source files on the remote machine in contrary to a compiled executable)
2. Create a feature request for debugging support of remote executable files. Dlv seems to support this via `dlv exec` and IntelliJ GoLand seems to support it as well (that's why I used `dlv exec` because I went through their Docker container remote debugging example), so it should be possible.

**Comment by ramya-rao-a** [comment]
> Does this mean that the VS Code Go extension's remote debugging only works with the source files on the remote machine? That's rarely (if ever) the case when using Docker containers to deploy Go services

No. In case of remote machines, the trick is to first run a headless delve on the remote machine. Then, on your local machine (which has the source code) you use the debug configuration in a way such that it attaches to the remote delve instance.

See [Remote debugging](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#remote-debugging)

**Comment by teleclimber** [comment]
Hi, I am trying to get remote debugging to work, and I think the vscode docs need updating.

I'm referring to this doc: https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#remote-debugging

If I follow the "Remote Debugging" instructions I run into the following problems:

First, it's not clear from the docs that you have to pass to delve the package that you are debugging. The command:

```
dlv debug --headless --listen=:2345 --log --api-version=2
```

...is assumed to run from within the directory that contains the source of your application code. This is not clear in the docs. It's obvious after the fact, but not when you're muddling through, and it'd be nice for the docs to mention that.

Once I fixed that, I used a config very similar to 

```
{
	"name": "Launch remote",
	"type": "go",
	"request": "launch",
	"mode": "remote",
	"remotePath": "absolute-path-to-the-file-being-debugged-on-the-remote-machine",
	"port": 2345,
	"host": "127.0.0.1",
	"program": "absolute-path-to-the-file-on-the-local-machine",
	"env": {}
}
```

If I try to launch this config in vscode I am promptly chided to use `attach` instead of `launch` for `mode` because launch is deprecated. 

Finally the bullet point

```
remotePath should point to the absolute path of the file (in your source code) being debugged in the remote machine
```

...was incorrect in my case. I had to make `remotePath` point to my project folder (even though the package I am running is under `cmd/ds-host`). It might be because I am running delve from the project root and specifying the package explicitly, but that's the kind of thing the docs could address.

Thanks.

**Comment by stamblerre** [comment]
I have filed https://github.com/golang/vscode-go/issues/164 in our new repository, as this repo is migrating: #3247. Let's continue the discussion on the new issue. Thanks all!
