### ISSUE TITLE
feature request: Go to implementation context menu for interface methods

### ISSUE THREAD

**Issue by cevn** [microsoft/vscode-go#2409]
Currently, if I right click a method in an interface, I see a few options, like Go: Add Import, Go: Generate unit tests, blah blah. 

I know that I can hit command space and type implementation, but I would like a keyboard shortcut and context menu , this is the final test to prove to my GoLand using friends that VS code go is just as good. 

edit: Just realized there is a KB shortcut for it. My bad. Just the context menu then, for discoverability.

**Comment by cevn** [comment]
Just realized there is a KB shortcut for it. Just a context menu then perhaps. My bad.

**Comment by ramya-rao-a** [comment]
See https://github.com/Microsoft/vscode/issues/63471 for the reason why VS Code decided not to keep `Go to Implementation` in the context menu by default.

This extension can expose this command in the context menu, but I wouldn't keep that the default behavior due to reasons mentioned in the above linked issue.

But, we have a setting `go.editorContextMenuCommands` that as a user, you can use to control which commands contributed by this extension can show up in the context menu. We can extend this to control the `Go to implementation` command as well.

PRs are most welcome to add this feature.
Code Pointers:
- [Set up local dev environment](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code)
- Update the [go.editorContextMenuCommands](https://github.com/Microsoft/vscode-go/blob/0.9.2/package.json#L1097) setting to include a new property `goToImplementation`
- Update the [menus](https://github.com/Microsoft/vscode-go/blob/0.9.2/package.json#L1292) contribution to refer to the newly added property and show the command `editor.action.goToImplementation`

**Comment by cevn** [comment]
I will take a look at this and make a PR. Thanks for pointing me in the right direction.

**Comment by cevn** [comment]
Hi Ramya. After following your instructions, I received the following error message: 

```
[ms-vscode.Go]: Menu item references a command `editor.action.goToImplementation` which is not defined in the 'commands' section.
```

Indeed I checked the commands section and found nothing. However obviously gotoimplementation works in the extension. What am I missing?

**Comment by ramya-rao-a** [comment]
Apologies for the late reply here @cevn 

Looks like VS Code supports menu items by extensions only if the backing command is defined in the same extension. Since the "go to implementation" is defined out of the box, it doesnt look like we can add this command to the context menu
