### ISSUE TITLE
setting gcflags in the .vscode/settings.json disables test debugging

### ISSUE THREAD

**Issue by ran-berenfeld** [microsoft/vscode-go#2415]
Hello

if I set this in the workspace settings :

    "go.testFlags": [
        "-gcflags=-l", 
    ],

then running a test using the "debug test" link will result in :

go test: gcflags flag may be set only once
run "go help test" or "go help testflag" for more information
Process exiting with code: 1

**Comment by misha-tectonic** [comment]
Arguably it's a bug in `dlv`, as VS Code properly constructs a command-line invocation `--build-flags="-gcflags=-l"`, and `dlv` adds `-gcflags="-N -l"`, so `go build` rejects it.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @ran-berenfeld and for the information on how delve adds the same flag @misha-tectonic 

@aarzilli, @derekparker I believe the right thing to do here is for the extension to ignore the `gcflags` passed by the user?

**Comment by aarzilli** [comment]
I think delve should not pass its own gcflags argument if build-flags already has it.

**Comment by misha-tectonic** [comment]
@aarzilli This won't work: `delve` requires `-N -l` gcflags in order to function.

**Comment by aarzilli** [comment]
It doesn't require them, it just works better if they are there. If the user specifically passes a different gcflags through build-flags delve should respect it.

Also maybe the VSCode extension should ignore gcflags set in `go.testFlags` when calling delve.

**Comment by ramya-rao-a** [comment]
> If the user specifically passes a different gcflags through build-flags delve should respect it.

> Also maybe the VSCode extension should ignore gcflags set in go.testFlags when calling delve.

@aarzilli That is conflicting advice :) or I am missing something here...

Like @misha-tectonic mentioned above, the extension does pass `--build-flags="-gcflags=-l"` to delve when the user sets `go.testFlags` to `["-gcflags=-l"]`.  So should we log an issue for delve for trying to set gcflags the second time?

**Comment by misha-tectonic** [comment]
Yes, ideally delve should parse passed `-gcflags` and add any flags it needs to it before passing it to `go build`.

**Comment by aarzilli** [comment]
> @aarzilli That is conflicting advice :) or I am missing something here...

For me there's two questions here:

1. What should delve do when the user passes a `-gcflags` parameter inside `--build-flags`

2. Should VSCode pass `-gcflags`, if it's part of `go.testFlags`, inside `--build-flags`?

For (1) one reasonable choice is to use the gcflags specified by the user instead of ours, another is to leave things as they are and let delve fail, after all the point of having delve build the executable is to have it set gcflags, if you don't want then you can just use `go`. 

For (2) one reasonable answer is to say that `go.testFlags` don't apply to debug builds (but then how would you set test flags for debug builds?).

> Yes, ideally delve should parse passed -gcflags and add any flags it needs to it before passing it to go build.

This gets very complicated when you take into account patterns. What `-gcflags=-l` says is "disable inlining for the tested package". What delve does is `-gcflags=all=-N -l` which says "disable inlining and optimizations for every pacakge". What does "adding" mean in this context:

* `-gcflags=-l` + `-gcflags=all=-N -l` = `-gcflags=all=-N -l`
* `-gcflags=-l` + `-gcflags=all=-N -l` = "disable inlining for every package, disable optimizations for every package except the tested package"

More complicated gcflags expressions in build-flags would pose more complex problems.

**Comment by ramya-rao-a** [comment]
I vote for simplicity here and would go with the vscode-go extension should ignore the `gcflags` set by the user

PRs are welcome to make this change.

Code Pointers:
- [Set up local dev environment](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code)
- `getCodeLensForFunctions` is the method in `goRunTestCodelens.ts` file that creates the debug configuration. This is where we need to ignore `-gcFlags`

**Comment by ramya-rao-a** [comment]
Hello all,

We are in the midst of a repo move, see [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in our readme for more details.

Closing this issue in favor of https://github.com/golang/vscode-go/issues/117. Please subscribe to it for further updates.

Thanks for all the support & Happy Coding!
