### ISSUE TITLE
Feature Request: Running Tests with CodeLens - Use Build Tags

### ISSUE THREAD

**Issue by rv-bbassham** [microsoft/vscode-go#2430]
It would be nice if running tests with CodeLens would look at the build tags in the file you are in and pass them to `go test`. I have several test files that contain integration tests, and require using `-tags integration` to run. I can't run those using CodeLens without modifying the user preferences to include the integration tag, which I don't want all the time.

Example:

I have a `_test.go` file that starts with the following:

```
// +build integration

package api_test

```

If I click on `run test` I get a result stating `no tests to run`.

For now the workaround is to just run the tests on the command line with `go test -tags integration`, but adding this to the CodeLens support would be really nice.

**Comment by ramya-rao-a** [comment]
The reasoning here would be that since you are explicitly wanting to run a particular tests, appropriate tags should be added regardless of what is in the `buildTags` or `testTags` setting.

Would you say then, that the `buildTags` and `testTags` setting value should be totally ignored in such cases? Or should build tags in the file be additive to what is in these settings?

Also, I believe what we decide here can be extended to commands like
- Go: Test Function at Cursor
- Go: Test File
- Go: Debug Function at Cursor
- The debug codelens
