### ISSUE TITLE
go-langserver 26G mem usage

### ISSUE THREAD

**Issue by IAIAE** [Microsoft/vscode-go#2434]
<img width="538" alt="WX20190410-212132@2x" src="https://user-images.githubusercontent.com/11187162/55882618-690bfb80-5bd7-11e9-893b-618d2fc14f96.png">

.........

**Comment by kidlj** [comment]
Try the latest beta (0.9.3-beta.7) and use 'gopls' as language server.

https://github.com/Microsoft/vscode-go/releases

**Comment by ramya-rao-a** [comment]
@IAIAE  The `go-langserver` is no longer under active development, we will soon switch to using `gopls` which is the language server from Google.

- Install `gopls` using `go get -u golang.org/x/tools/cmd/gopls`
- Install the [latest beta version](https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension)
- Reload VS Code window 
- The extension should then use `gopls` instead of `go-langserver`
