### ISSUE TITLE
launch only one gopls

### ISSUE THREAD

**Issue by primalmotion** [Microsoft/vscode-go#2450]
I'm not sure if this is possible, but I think it would be good that vscode-go only uses one single instance of gopls. for me it uses ~1.5GB or memory *per* vscode window (and I usually work with 3 or 4 or them). Only using one make my laptop a happy camper.

**Comment by stamblerre** [comment]
This is something that we were actually planning on working on, and it would probably be fairly doable because we support 1 "view" per workspace root URI. The issue is that the cache is not shared between views, so if we did that now, the 1 gopls instance per *n* VSCode windows would probably just use *n* times the amount of memory.

**Comment by stamblerre** [comment]
Filed https://github.com/golang/go/issues/31589 to track this.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @primalmotion 
Since we now have an upstream issue to track this, I'll close this issue
