### ISSUE TITLE
"Error: Type Error: Bad argument" when opening a folder containing GO code when go is not on the path

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode-go#246]
_From @v-pavanp on March 15, 2016 4:14_

- VSCode Version: Windows10
- OS Version:

Steps to Reproduce:

1. Install go from this location:https://visualstudiogallery.msdn.microsoft.com/bd7675ba-1bf5-4395-8c5a-4fc19dfc0d76  
2. Create directory structure and set environment variable for GOPATH, GOBIN. by following instruction provided at : https://golang.org/doc/install?download=go1.6.windows-amd64.msi 
3. Now add a .go file under workspace dir and execute below command to generate a EXE under GOBIN file.
4. Once exe is generated successfully, open the workspace folder in VSCODE.
5. Open go file and install GO extension.
6. Verify extension installed successfully without any error.
6. Verify GOPATH error should not be displayed as environment variables are already been set.

Actual: Getting error message "Error : Type Error: Bad argument".
![image](https://cloud.githubusercontent.com/assets/17735796/13767376/d3d11480-ea26-11e5-9b37-1d0e264ecd00.png)

Expected: There should not be any error message like this.

_Copied from original issue: Microsoft/vscode#4224_

**Comment by lukehoban** [comment]
Can you share any more details on when that error occurs?  What action exactly caused it to appear?  From the other warning, it sounds like you have also not installled the Go analysis tools yet - which may be the root problem.

Could you reopen with additional details?

**Comment by donlzx** [comment]
Same problem on Linux (Linux Mint 17.3) with Code v1.1.1.  Here is some extra info that hopefully will help:

1) Open a command shell, enter "code" will bring up previous Go project folder with some opened files.  No errors;

2) Click on the "Visual Studio Code" menu item on the desktop UI, thus opening the previous Go project folder with some opened files.  In this case, the error shows up;

3) Press Alt+F2 and enter the "code" command, same problem as previous item.

Redo these steps with no previous Go project folder or files opened when starting Code.  When starting from command line, there are no errors when opening project folders and files.  Otherwise, same error when opening Go project folder and files.

**Comment by quinte17** [comment]
same here.
additionaly if you close the error, change a go file (add some spaces where gofmt would remove again)
and save it -> error shows up again.

**Comment by RReverser** [comment]
@lukehoban Same problem on Mac OS with VS Code 1.3.0, fresh install of both Go, this extension and all the tools from README.

**Comment by kaakaa** [comment]
Same problem.

* Mac OSX
* VS Code 1.3.0
* vscode-go 0.6.39

And I found the cause of my problem.
The cause is that vscode-go cannot find go binary.

`goPath#getGoRuntimePath()` find go binary by one of the theree.
1. cached
2. `GOROOT`
3. `PATH`

goPath.js
```go
function getGoRuntimePath() {
    if (runtimePathCache)
        return runtimePathCache;
    if (process.env['GOROOT']) {
        runtimePathCache = path.join(process.env['GOROOT'], 'bin', correctBinname('go'));
    }
    else if (process.env['PATH']) {
        var pathparts = process.env.PATH.split(path.delimiter);
        runtimePathCache = pathparts.map(function (dir) { return path.join(dir, correctBinname('go')); }).filter(function (candidate) { return fs.existsSync(candidate); })[0];
    }
    return runtimePathCache;
}
```


In my environment, there is go binary in `/usr/local/bin/go`, but `PATH` does not include `/usr/local/bin`.
If I set `/usr/local/Cellar/go/1.6.1/libexec` to `go.goroot` in settings.json of vscode-go, Message `"Error : Type Error: Bad argument"` is disappear.

**Comment by RReverser** [comment]
@kaakaa Oh thanks, that helped! In my case PATH did include paths to Go binaries as well as `/usr/local/bin`, but in MacOS it's not trivial to make GUI apps to respect same PATHs settings, and setting `go.gopath` alone in Code didn't help. Now with `goroot` all the tooling works as expected.

**Comment by cainiaoDJ** [comment]
thanks,just add a config of "go.goroot"
`//gopath 配置
    "go.gopath":"E://workspace//golang",
    "go.formatTool": "gofmt",
    "go.lintOnSave": true,
    "go.goroot":"E://Go",`

**Comment by RReverser** [comment]
@cainiaoDJ Why are you setting `//`? If you're on Windows, it's `\\` or just `/` (both should work).

**Comment by cainiaoDJ** [comment]
@RReverser   , you are right. It's my fault. thanks.

**Comment by roblourens** [comment]
Ran into this too right after installing go - can we provide a better error message?

**Comment by ramya-rao-a** [comment]
In the latest version (0.6.45) of the Go extension, a better error message "Cannot find "go" binary. Update PATH or GOROOT appropriately" will be shown when Go is not found.
