### ISSUE TITLE
Set default tabSize for go files to 8

### ISSUE THREAD

**Issue by urld** [Microsoft/vscode-go#2479]
Some time has passed since #384 was closed, and vscode now has support for language specific editor settings.

Since gofmt and friends align code for a tab size of 8, i believe this extension should also use this value as default.

**Comment by ramya-rao-a** [comment]
@urld On second thoughts, we don't want to make this (tab size of 8) a default behavior as it will change the behavior for all existing users whether they want it or not.

It can definitely be justified that since `gofmt` aligns for tab size of 8, the editor should support it too. But disrupting thousands of existing users for this is only going to generate a lot of issues in this repo. 

I will be reverting this change, but also update the README and FAQ on how to change the tab size for go files using
```
"[go]: {
  "editor.tabSize": 8
}
```

**Comment by urld** [comment]
This is ok too. But you seem to have a markdown typo in the faq. It renders as **Q:

**Comment by ramya-rao-a** [comment]
Fixed the typo, thanks!
