### ISSUE TITLE
goimports automatically added to settings.json

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode-go#2483]
Recently, `vscode-go` prompted me to install `gopls`. Presumably as part of this, `"go.useLanguageServer": true` was automatically added to my users settings. I later disabled `gopls` by commenting out `"go.useLanguageServer": true`, to revert my setup to `goimports` (the lack of automatic import management is a deal killer for me).

Now, whenever I start working on files, in a project, `"go.formatTool": "goimports"` is added to `settings.json` for that project. This is not ok.

**Comment by stamblerre** [comment]
The language server does support goimports-like behavior. You just need this configuration for format and organize imports on save:

```json5
"[go]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    },
},
```

**Comment by ramya-rao-a** [comment]
@firelizzard18 Like @stamblerre mentioned above, imports management is indeed supported by `gopls`, so please give it a try. Make sure you have the latest of `gopls` so that you get all the recent bug fixes and improvements

In the absence of the language server, the Go extension does recommend using `goimports` as the formatting tool because the default one `goreturns` doesn't support modules yet. If you add `"go.formatTool": "goimports"`, then the extension will stop adding it to your workspace settings. 

The reason to add it to workspace and not user settings was because the assumption was that the setting update was needed only for projects that use modules and not the rest. In hind sight, I see that this was not a great decision. Adding this setting to user settings would be much better as it wouldn't pollute the workspace settings and that there is no downside to using `goimports` for all projects whether they support modules or not.

In the latest update to the Go extension (0.11.1), the code has been updated to prompt the user to make this settings change in User settings
