### ISSUE TITLE
Cannot update tools / other errors

### ISSUE THREAD

**Issue by xhexe** [Microsoft/vscode-go#2487]
Hello!
So first of all. I wasted a lot of my time to trying fix my problems with vscode-go. I am at the same stage where I was.
I am currently working on Manjaro 18.04 and I have exactly the same set of errors which that I had on Mint 19 / 19.1.
I have a lot of messages like this:

> The language server from Sourcegraph is no longer under active development and it does not support Go modules as well. Please install and use the language server from Google or disable the use of language servers altogether.

or

> Cannot find the language server bingo. Please install it and reload this VS Code window

or

> The Go extension is better with the latest version of "gocode". Use "go get -u -v github.com/mdempsky/gocode" to update

or

> Failed to find some of the Go analysis tools. Would you like to install them? 

This especially when I clicked on the bottom "Analysis Tools Missing". When I try to do "update" or "install" the output gives me this:

```
Installing 1 tool at /home/soma/Dev/go/bin
  gocode

Installing github.com/mdempsky/gocode FAILED

1 tools failed to install.

gocode:
Error: Command failed: /usr/local/go/bin/go get -u -v github.com/mdempsky/gocode
github.com/mdempsky/gocode (download)
# cd /home/soma/Dev/go/src/github.com/mdempsky/gocode; git pull --ff-only
error: Your local changes to the following files would be overwritten by merge:
	.travis.yml
	README.md
	client.go
	emacs-company/company-go.el
	gocode.go
	internal/gbimporter/context.go
	internal/gbimporter/gbimporter.go
	internal/gbimporter/samepath_unix.go
	internal/gbimporter/samepath_windows.go
	internal/lookdot/lookdot.go
	internal/lookdot/lookdot_test.go
	internal/suggest/candidate.go
	internal/suggest/cursorcontext.go
	internal/suggest/suggest.go
	internal/suggest/suggest_test.go
	internal/suggest/testdata/test.0005/test.go.in
	internal/suggest/testdata/test.0011/out.expected
	internal/suggest/testdata/test.0065/out.expected
	internal/suggest/testdata/test.0065/test.go.in
	server.go
Please commit your changes or stash them before you merge.
Aborting
package github.com/mdempsky/gocode: exit status 1
github.com/mdempsky/gocode (download)
# cd /home/soma/Dev/go/src/github.com/mdempsky/gocode; git pull --ff-only
error: Your local changes to the following files would be overwritten by merge:
	.travis.yml
	README.md
	client.go
	emacs-company/company-go.el
	gocode.go
	internal/gbimporter/context.go
	internal/gbimporter/gbimporter.go
	internal/gbimporter/samepath_unix.go
	internal/gbimporter/samepath_windows.go
	internal/lookdot/lookdot.go
	internal/lookdot/lookdot_test.go
	internal/suggest/candidate.go
	internal/suggest/cursorcontext.go
	internal/suggest/suggest.go
	internal/suggest/suggest_test.go
	internal/suggest/testdata/test.0005/test.go.in
	internal/suggest/testdata/test.0011/out.expected
	internal/suggest/testdata/test.0065/out.expected
	internal/suggest/testdata/test.0065/test.go.in
	server.go
Please commit your changes or stash them before you merge.
Aborting
package github.com/mdempsky/gocode: exit status 1
```

Here's my settings.json
```
"go.docsTool": "godoc",
    "go.useLanguageServer": true,
    "go.alternateTools": {
        "go-langserver": "bingo"
    },
    "go.liveErrors": {
        "enabled": true,
        "delay": 750
    },
    "go.languageServerFlags": [
        "--diagnostics-style=instant",
        "--enhance-signature-help",
        "--format-style=goimports",
    ],
    "go.languageServerExperimentalFeatures": {
        "autoComplete": true,
        "documentSymbols": true,
        "findReferences": true,
        "format": true,
        "goToDefinition": true,
        "goToTypeDefinition": true,
        "hover": true,
        "signatureHelp": true,
        "rename": true,
        "workspaceSymbols": true,
    },
    "go.formatTool": "gofmt"
```

##### go version:
```
go version go1.12.4 linux/amd64
```
I had the same problems with previous versions.

##### go env:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/soma/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/soma/Dev/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
```

And I apologize if I should go with my problems somewhere else. But I have no idea where I should go...

**Comment by ramya-rao-a** [comment]
Thanks for reporting @xhexe 

There are quite a few different things going on here, I'll try to address them

**Errors while installing/updating tools**
As you may know, the way the Go tools are installed/updated are by using the `go get` command. In your case go tries to pull the latest updates into the git repo that was cloned for `gocode`. There seems to be merge conflicts there. I would suggest to delete the entire folder for `gocode` at `/home/soma/Dev/go/src/github.com/mdempsky/gocode` and try again.

**The notification about Sourcegraph language server**
**The Go extension is better with the latest version of "gocode"**
You shouldnt be getting this if you have chosen to use `bingo`. From your settings, I see that you have chosen `bingo` indeed using the `go.alternateTools` setting. Are you still getting this notification?

**Cannot find the language server bingo. Please install it and reload this VS Code window**
This happens when you choose to use `bingo` but the extension cannot find it. 
- Are you sure you have installed `bingo`?
- If yes, then check the location where the binary for bingo got installed. Is this location the same as your GOPATH/bin or is it in your PATH
- If no, then please install it and ensure it gets installed in your GOPATH/bin or in your PATH

**Comment by xhexe** [comment]
Than you @ramya-rao-a for your reply and thank you for your tips.

All problems disappeared after:
- Installing git in the system
- removal of github.com and golang.org directories

It is also possible that my physical transfer of the 'go' directory between different machines had an impact on the above errors.

**Comment by ramya-rao-a** [comment]
Glad that things got resolved, Happy Coding!

**Comment by YumingHuang** [comment]
{
  "go.alternateTools": {
    "go-langserver": "bingo"
  },
  "go.languageServerExperimentalFeatures": {
    "format": true,
    "autoComplete": true
  },
  "go.useLanguageServer": true
}
