### ISSUE TITLE
gopls: don't allow unrequested source code modifications

### ISSUE THREAD

**Issue by oakad** [microsoft/vscode-go#2498]
I'm using vscode 1.33.1/vscode-go 0.10.2/go 1.12.3

My user config file has the following set:
```
    "go.languageServerExperimentalFeatures": {
        "format": false,
     },
    "go.lintOnSave": "off",
    "go.useLanguageServer": true,
    "go.vetOnSave": "off",
    "[go]": {
        "editor.formatOnSave": false
    },
```

However, when using gopls the following behavior happens:

1. Files are always formatted on save
2. Imports are reordered

For many various reasons, this is not a desirable behavior. First, `formatOnSave` setting is not honored as it should be. Second, there should be a setting which prevents `gopls` from ever introducing any automatic changes to source code files unless explicitly requested by user, via context menu or command prompt.

I'm most surprised that the above is not the default setting already, as RCS noise is a major nuisance in large code bases.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @oakad 

Can you try disabling `editor.codeActionsOnSave` as well?

```json
"[go]": {
    "editor.formatOnSave": false,
    "editor.codeActionsOnSave": {
      "source.organizeImports": false
    }
  }
```

Previously (before `gopls`), formatting and adding/removing/ordering imports were done by the same tool i.e `goreturns` or `goimports` (which you could configure using the "go.formatTool"

With `gopls`, the 2 features are split and formatting is now meant to just format, and the "source code actions" feature of VS Code is meant to drive the imports changes just like VS Code meant it to be.

In order to keep the experience same for user, we enabled the code actions feature on save by default as well. This means, to avoid the source code being changed by the tools, you need to disable both format on save, and code actions on save features.

I see how this can be disruptive to users who have chosen to **not** format on save, but am not sure what the next step here can be. 
- One way can be to update the README and the FAQs. 
- Another is for the extension to update the user's settings and disable "organize imports on save" feature if it identifies that the user has disabled "format on save" feature. But, I am wary of updating user's settings unless absolutely required. 
- Another is to prompt the user if they want to disable "organize imports on save" feature if the extension sees that the user has disabled the "format on save" feature. 

Thoughts?

**Comment by oakad** [comment]
After playing with settings , restarting vscode, cleaning caches, etc. it seems that this particular issue stopped happening for me - autoformatting and import reordering stay disabled when instructed.

My eventual config ended up like so:
```
    "go.gotoSymbol.includeGoroot": true,
    "go.gotoSymbol.includeImports": true,
    "go.buildOnSave": "off",
    "go.languageServerExperimentalFeatures": {
        "format": false,
    },
    "go.lintOnSave": "off",
    "go.useLanguageServer": true,
    "go.vetOnSave": "off",
    "[go]": {
        "editor.insertSpaces": false,
        "editor.formatOnSave": false,
        "editor.codeActionsOnSave": {
            "source.organizeImports": false
        }
    },
```

**Comment by ramya-rao-a** [comment]
I have updated the [wiki](https://github.com/microsoft/vscode-go/wiki/Go-with-VS-Code-FAQ-and-Troubleshooting) regarding this.

@stamblerre When user changes any of the settings, is the language server able to respect the changes in real time or does it need a restart?

**Comment by stamblerre** [comment]
I don't think the editor settings should require a restart here - the code actions are only ever responses to code actions sent by the client.

**Comment by ramya-rao-a** [comment]
Got it, that makes sense

**Comment by oakad** [comment]
I would like to ask for reopen.

I just upgraded another instance of vscode (on Linux this time) and immediately run into this problem again, even when using a "good" config from the previous machine.

Something is definitely broken, probably the way `vscode-go` reads the configuration.

**Comment by oakad** [comment]
I did some additional experimentation.

It appears, at least, that if vscode-go thinks (by default) that imports are to be organized, then formatting is always enabled. Or, in other words, if the following snippet is missing from config the source files will be fully formatted no matter what.
```
"editor.codeActionsOnSave": {
  "source.organizeImports": false
}
```

**Comment by ramya-rao-a** [comment]
That is an issue with `gopls` where it formats the files even if format is disabled, but the code actions are enabled.

@stamblerre Can you confirm that? If so, can you point us to the upstream issue that is tracking it?

**Comment by stamblerre** [comment]
The upstream issue would be https://github.com/golang/go/issues/30843. Basically, the issue is that the `goimports` library also does formatting. I will have to make a change to the `goimports` library to separate the two. I'm sorry for not clarifying this earlier.
