### ISSUE TITLE
Symbols not found inside godep GOPATH

### ISSUE THREAD

**Issue by liggitt** [Microsoft/vscode-go#250]
I have a project using godeps to nest vendored packages.

The project root is at `/Users/myuser/go/src/github.com/myuser/myrepo`

The `"go.gopath"` setting is set to `"/Users/myuser/go/src/github.com/myuser/myrepo/Godeps/_workspace:/Users/myuser/go"`

Most things work (definition finding, etc), but "Show all symbols" does not include things inside the nested Godeps path (which is `Godeps/_workspace` relative to the project folder)

**Comment by liggitt** [comment]
cc @deads2k @ironcladlou

**Comment by ironcladlou** [comment]
Check [this branch of my fork](https://github.com/ironcladlou/go-symbols/tree/gopath-support) of the [go-symbols](https://github.com/newhook/go-symbols) tool which use the build context for lookups.

I have an idea of how to make my branch backwards compatible with current go-symbols' behavior by creating a `build.FakeContext`, but it's low priority for me right now since the current behavior is pretty much broken for every Go project I work with due to vendor usage.

I think this tool would also benefit from some sort of caching.

We might want to take this discussion to the `go-symbols` project. cc @newhook

**Comment by liggitt** [comment]
> We might want to take this discussion to the go-symbols project. cc @newhook

my mistake, I can move the issue there

**Comment by liggitt** [comment]
Moved to https://github.com/newhook/go-symbols/issues/1
