### ISSUE TITLE
Hover actions give multiple contents if more than one provider per action is registered

### ISSUE THREAD

**Issue by lggomez** [microsoft/vscode-go#2517]
I´ve been seeing this behavior for some time but I think it doesn't have an issue filled here

![Screen Shot 2019-05-15 at 09 44 59](https://user-images.githubusercontent.com/6326271/57776810-c9222000-76f6-11e9-9f61-fb96117e0a96.png)

![image](https://user-images.githubusercontent.com/6326271/57776815-cd4e3d80-76f6-11e9-8623-d4b2bfabd484.png)

Steps to Reproduce:

Have both language server and linter turned on, as a start. These are my current settings: https://github.com/lggomez/editorconfigs/blob/master/VSCode/user-settings.json

@ramya-rao-a could this be a consequence of #2446 for the other providers?

**Comment by ramya-rao-a** [comment]
The 2 screenshots above are due to 2 different issues...


![Screen Shot 2019-05-15 at 09 44 59](https://user-images.githubusercontent.com/6326271/57776810-c9222000-76f6-11e9-9f61-fb96117e0a96.png)

Do you see this after a VS Code window reload as well? If yes, then this is not related to multiple hover providers registered. Can you disable the `enhancedHover` feature you have in your settings and see if that makes any difference?


![image](https://user-images.githubusercontent.com/6326271/57776815-cd4e3d80-76f6-11e9-8623-d4b2bfabd484.png)


The second one is definitely because we are getting diagnostics from both LSP and linter. `gopls` gives build and vet errors, in this case it looks like the linter is giving the same error.

When LSP was not in the picture, such duplicates were removed in https://github.com/microsoft/vscode-go/blob/0.10.2/src/util.ts#L747 and https://github.com/microsoft/vscode-go/blob/0.10.2/src/util.ts#L756

We might have to do something similar to remove duplicates between LSP and the linting tool.

**Comment by ramya-rao-a** [comment]
cc @stamblerre

**Comment by stamblerre** [comment]
I would guess that the multiple hover providers is no longer an issue, since if you have `gopls` enabled, we don't register any other hover provider, and we no longer have `hover` as an experimental feature. When you Ctrl + hover on an identifier, it does also show you where it's declared, which is often really similar to how the `gopls` hover text looks, but I don't think there's anything we can do about that since that's a behavior of VS Code itself.

As for the lint errors, is there any way to filter out lint errors with the "`(typecheck)`" string at the end of the message if `gopls` is enabled? I think that would be a fairly simple way to eliminate these duplicates, since `gopls` will always provide type checking errors.

**Comment by lggomez** [comment]
> When you Ctrl + hover on an identifier, it does also show you where it's declared, which is often really similar to how the gopls hover text looks, but I don't think there's anything we can do about that since that's a behavior of VS Code itself.

So that's the case then, it is indeed the overlay of the hover and ctrl+hover actions

**Comment by ramya-rao-a** [comment]
> is there any way to filter out lint errors with the "(typecheck)" string at the end of the message if gopls is enabled

This assumes that all type checking errors from all linters have the `(type check)` in their error messages

**Comment by stamblerre** [comment]
Ah, yeah I guess I forgot that there are other linters. I would have suggested that we could filter by diagnostics with equal messages, but clearly the `(typecheck)` indicates that that won't work. Otherwise, the only alternatives I can think of are either to (1) live with the duplicates until `gopls` supports `golint` analyses, or (2) disable linting when `gopls` is enabled.

**Comment by ramya-rao-a** [comment]
If the assumption is that the text inside the () refers to the internal checkers that the linter uses, then we can use regular expressions to strip that part out, compare the resulting message with the diagnostic message from gopls, and thus de-duplicate which is similar to https://github.com/microsoft/vscode-go/blob/0.10.2/src/util.ts#L747

**Comment by stamblerre** [comment]
I'm not familiar with the different linters, but I imagine that we cannot rely on the text in the parentheses existing.

**Comment by ramya-rao-a** [comment]
Closing in favor of https://github.com/golang/vscode-go/issues/142 due to the repo move https://github.com/microsoft/vscode-go#we-are-moving---
