### ISSUE TITLE
Keep function signature separate from completion item label

### ISSUE THREAD

**Issue by karim** [microsoft/vscode-go#2523]
Auto complete looks different when language server is turned on.

`settings.json` file:

```json
{
    "go.useLanguageServer": true
}
```

![vscodego1](https://user-images.githubusercontent.com/8761081/57950740-65f7df80-78e8-11e9-9aff-a72e2aab00d9.jpg)

Disabling language server gives me this

![vscodego2](https://user-images.githubusercontent.com/8761081/57950979-1fef4b80-78e9-11e9-92d9-f0f16115dc99.jpg)

Is there any option to use the language server but get auto complete like the second picture?

-----

Extension version: 0.10.2
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 6.1.7601

**Comment by ramya-rao-a** [comment]
This would require change from the language server. 

@stamblerre You can get the above behavior by
- Setting the `detail` property of the completion item with the function signature instead of appending the signature to the `label`
- Adding the documentation in the resolveCompletionItem request

I believe you already have an issue to track the second point above. Would you consider making the first change?

**Comment by stamblerre** [comment]
I think I'd like to wait to hear if others would want such a change before making it. I have not gotten this feedback from anyone else yet, so I'd be interested to hear how others feel first.

**Comment by karim** [comment]
@stamblerre I think the second picture is a clear win here. The first one only shows the function signature. It truncates it even if it is a bit long, and no documentation.

The second one shows the full function signature and its documentation. Also it is the default for VS Code when the language server is off.

I'm fine with waiting till a decision is made.

Thanks. :+1:

**Comment by stamblerre** [comment]
Documentation is a separate issue, and it's something we will definitely add in `gopls`, so that will be there either way. The question is really should we have the signature in the label - I'm not sure. 

I agree that it looks cleaner without, but I think there's a benefit to immediately distinguishing between a function and a variable or type. In VSCode's UI, it does look nicer in the second picture, but other editors often show the label on the left and the detail on the right, without a separate pop-up. I'm hesitant to make changes to optimize for VSCode.

**Comment by ramya-rao-a** [comment]
@stamblerre VS Code also allows showing the label on the left and the detail on the right

![image](https://user-images.githubusercontent.com/16890566/58754760-5fdb3480-848c-11e9-8e4f-34ca2fd21fd7.png)

The decision to display data should be left up to the editors. The language servers follow the protocol and provides data appropriately. The `CompletionItem` interface has the below main parts
- label
- detail
- documentation

The editors can chose how they display the above. They can choose to concatenate the `label` and the `detail`. 

By having the language server combine the 2, we end up taking the choice away from editors on how they want to display

**Comment by karim** [comment]
I agree with @ramya-rao-a. This should be the editors choice and not the language server.

If the language server separate the signature from the label then any editor can show the label only, or the label and signature together. By combining both you don't give editors any choice.

**Comment by stamblerre** [comment]
Ok, we will look into this: https://github.com/golang/go/issues/32414.

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre!
Closing this issue in favor of the upstream issue that has been logged

**Comment by stamblerre** [comment]
@ramya-rao-a: How do you configure the setting to get the label next to the detail?

**Comment by ramya-rao-a** [comment]
That's not something that the user can configure.

Its up to the editor to decide how it wants to render the two
