### ISSUE TITLE
How to disable function lints when I print  parenthesis "()"

### ISSUE THREAD

**Issue by kybom** [microsoft/vscode-go#2536]
os:                   windows10 1903
remote vscode-go:     0.10.2
remote os: ubuntu18.04 server

Function lint appears when I print  parenthesis behind a function,and it  does not disappear unless press ECS.
![GIF](https://user-images.githubusercontent.com/24692485/58318861-36e2f000-7e4b-11e9-992c-9092096c7d01.gif)

**Comment by ramya-rao-a** [comment]
That looks like a bug. Can you please share the entire contents of the file that you used above?
Please also share any go related settings that you might have added or changed.

While we try to look into what might have caused this, you can disable this feature by using the setting `editor.parameterHints.enabled`

**Comment by kybom** [comment]
It works ,thansk.
The entire contents of the file below:
```go
package main

import (
	"flag"
	"fmt"
)

var showVersion bool

func main() {
	code()
	parseCommandLine()
	fmt.Println("version", showVersion)
}

func parseCommandLine() {
	flag.BoolVar(&showVersion, "version", false, "print version")
	flag.Parse()
}

func code() {
	fmt.Println("begin", "hehe")

}

```

Go related setting is default.
May be about parse() function?
![QQ截图20190530150024](https://user-images.githubusercontent.com/24692485/58614721-cffe8480-82eb-11e9-8355-48ac805b8181.png)

**Comment by ramya-rao-a** [comment]
Thanks, now I see it too.

The fix for another related issue is already in our master branch, and that fix will fix this issue too.

Can you please try the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension which has the fix? You should be able to enable the feature back and have no issues
