### ISSUE TITLE
Go code coverage disappears when typing a character

### ISSUE THREAD

**Issue by admilazz** [microsoft/vscode-go#2551]
The Go code coverage disappears when typing a character. This is implemented in removeCodeCoverageOnFileChange in goCover.ts. I find this very annoying, since I want to run the code coverage and then go through it and update the unit tests to add the missing tests, but as soon as I type a character in the unit test, the coverage information disappears.

I suggest that the code coverage should be removed when a Go file is saved, rather than when a character is typed. After all, the comment in the source saying that the code coverage is stale when a file is changed is false. The code coverage only becomes stale when the change is committed to disk (and would thus affect the result of compilation).

Alternately, please provide an option to disable removeCodeCoverageOnFileChange.

My current workaround is to change the language of the unit test file(s) from Go to plain text so it doesn't trigger the problem and then change back to Go before running the tests. It's not very nice.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @admilazz 

> I suggest that the code coverage should be removed when a Go file is saved, rather than when a character is typed

That is a good suggestion, and PRs are most welcome to make this change

Code Pointers:
- [Set up local dev environment](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code)
- Update [goMain.ts](https://github.com/microsoft/vscode-go/blob/0.10.2/src/goMain.ts#L319) to invoke `removeCodeCoverageOnFileChange` on file save instead of file change

**Comment by alanlal** [comment]
Hi , I would like to take this one up. :smile:

**Comment by ramya-rao-a** [comment]
Go ahead @alanlal!

**Comment by alanlal** [comment]
Hi @ramya-rao-a 

When I try to launch the extension as per the [instructions,](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code) I'm getting the following error in the debug console.

```Activating extension `ms-vscode.Go` failed:  Cannot find module 'c:\Users\alanl\Documents\vscode-go\out\src\goMain'```

The same error pops up in the [Extension development host] vscode window as well.

![issue-1](https://user-images.githubusercontent.com/26851904/58941551-ab962280-8799-11e9-918c-37909c27cce7.PNG)

**Comment by ramya-rao-a** [comment]
Does that file exist?

**Comment by alanlal** [comment]
There is `goMain.ts` present in `vscode-go/src/` but there is no directory as` vscode-go/out/src/` which is causing the error.

**Comment by alanlal** [comment]
> There is `goMain.ts` present in `vscode-go/src/` but there is no directory as` vscode-go/out/src/` which is causing the error.

Hi, I think the problem is that the typescript code is not getting compiled to the `vscode-go/out/src/` folder. I did `npm run compile` manually and then launched the debug and it worked fine.

I'm not sure if this is a required step or am I doing something wrong here ??. Because it is not mentioned in page : [Setting up local environment](https://github.com/Microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code)

**Comment by ramya-rao-a** [comment]
It is not a required step. By default, there are [tasks](https://github.com/microsoft/vscode-go/blob/master/.vscode/tasks.json) running that will compile the changes that are made. Maybe for some reason that task is not running for you.

**Comment by alanlal** [comment]
Hi, Made the changes and created a PR [#2586](https://github.com/microsoft/vscode-go/pull/2586) :smile:

**Comment by ramya-rao-a** [comment]
The latest update 0.14.2 has the fix for this, Thanks @Kegsay
