### ISSUE TITLE
Can only see the first 64 values of large slices or maps

### ISSUE THREAD

**Issue by aarzilli** [microsoft/vscode-go#2561]
1. Debug https://github.com/aarzilli/delve_client_testing/blob/master/12to18vars/main.go
2. Open longslice

I expected to have a way to dynamically load more than just the first 64 elements of the slice but there is none.

**Comment by ramya-rao-a** [comment]
Have you tried changing the `maxArrayValues` in the settings?

```
  "go.delveConfig": {
    "dlvLoadConfig": {
      "followPointers": true,
      "maxVariableRecurse": 1,
      "maxStringLen": 64,
      "maxArrayValues": 64,
      "maxStructFields": -1
    }
  }
```

**Comment by aarzilli** [comment]
I'm aware of that but I think there should be a way to change this dynamically during a debug session and for a specific variable.

**Comment by ramya-rao-a** [comment]
Changing this dynamically during a debug session can be possible if we could extend the context menu on the variables in the variable pane, but AFAIK that menu is not extendable in VS Code. Therefore, there is no way at the moment to allow changing these settings dynamically

**Comment by lggomez** [comment]
As @ramya-rao-a says unfortunately there isn't much we can do with the current adapter. A workaround I implemented in a PR for strings is fetching the eval request with an arbitrarily large length if the request comes from the variables pane (#2375), but even using a large static value in this case isn't possible without extending the panes menu (otherwise we would have to set that value as the default, slowing down delve in the process)

**Comment by ramya-rao-a** [comment]
Closing this issue as there are no potential next steps in the current confines of the debug adapter to fix this problem.
