### ISSUE TITLE
Problems with Go extension. Please help

### ISSUE THREAD

**Issue by Eleron8** [microsoft/vscode-go#2574]
Hi guys. I have problem with Go extension. I installed tools like gocode but it doesn't work. But in another one project all tools are working.

 For example, I created new dir with go file, but I don't have autocompletion. But if I open my old project tools are working.

 I checked my GOPATH and it is correct. I checked GOPATH in VSCode terminal and in external terminal. They are same.

I looked many issues on githab and tried solves from them. But anyway I can't solve my problem. 

Please can anyone help me? I will be very grateful

**Comment by ramya-rao-a** [comment]
- Are both projects under your GOPATH? When you run the command `Go: Current GOPATH` in both projects, do you get the same result
- Please share all the Go related settings you might have added or changed

**Comment by Eleron8** [comment]
@ramya-rao-a 
Thank you for attention
For example, I created new folder with new go file and when I write fmt. and expect autocompletion I see this 
![image](https://user-images.githubusercontent.com/26696198/59484682-74033680-8e7b-11e9-872e-96464a35cce7.png)
But in older folder autocomplention works 
![image](https://user-images.githubusercontent.com/26696198/59484812-ebd16100-8e7b-11e9-8aa4-7c21b22f5624.png)

This is GOPATH in new project
![image](https://user-images.githubusercontent.com/26696198/59484922-77e38880-8e7c-11e9-97ed-9553efb1d1ab.png)

This is GOPATH in older project 
![image](https://user-images.githubusercontent.com/26696198/59484965-9f3a5580-8e7c-11e9-8990-ce426fe5777d.png)

My go env in new project 
![image](https://user-images.githubusercontent.com/26696198/59485055-f6402a80-8e7c-11e9-826a-e664b3eaeed2.png)

my go env in older project

![image](https://user-images.githubusercontent.com/26696198/59485086-0a842780-8e7d-11e9-9b76-d00b43f1b66f.png)

my settings.json in VSCode 

![image](https://user-images.githubusercontent.com/26696198/59485163-4919e200-8e7d-11e9-9c3d-308b0eba7bc2.png)

For solve this problem I followed your guide:
1) try gocode close, but it didn't work
2) thenk i deleted nfs/gocode file from my GOPATH/src and GOPATH/bin. In GOPATH/pkg I didn't find
3)I run go get -u github.com/mdempsky/gocode
That is all I changed for try to solve this problem. 
Maybe I did somethin wrong, but anyway on second project it is working, so I don't understand how.

**Comment by ysantalla** [comment]
I have the same problem.

**Comment by ysantalla** [comment]
![image](https://user-images.githubusercontent.com/14929867/59514531-0bbc5100-8e8b-11e9-9a49-6bc1250c6454.png)

**Comment by ysantalla** [comment]
Disable this option in the setting.json file and work fine. Why???

"go.useLanguageServer": false,

**Comment by Eleron8** [comment]
@ysantalla 
I tried your solve. But It didn't help me :(

**Comment by Eleron8** [comment]
@ramya-rao-a 
Maybe I need reinstall VSCode?

**Comment by SUMUKHA-PK** [comment]
This happens constantly. The Go extension is very inconsistent, especially the latest release `0.10.2`.
I need to keep reinstalling and reloading the workspace to keep it running for like writing 2 loc. 
Versions `0.9.x` are better. Not sure what has happened.

**Comment by ramya-rao-a** [comment]
@Eleron8, @ysantalla By having `go.useLanguageServer` set to `true`, you have opted in to using the language server. In this case `gocode` is no longer used for providing the auto-completion feature, instead the language server provides this feature.

@Eleron8 Re-installing VS Code is not needed. At the most, you would need to reload VS Code. That would restart the extension. A change to any of the language server related setting will need a reload of VS Code. The extension will prompt you to do so when you change such settings.

@SUMUKHA-PK The major change was to move to using the language server. You can always opt out of it by setting `go.useLanguageServer` to `false`. I wouldnt suggest that if you are using Go modules though, because the language server is the best bet when using modules. This is a limitation of the Go tooling ecosystem.

@stamblerre I initially thought that this could be one of the "save the file first with the import, else completions wont work" problem. But @ysantalla's example above looks like he is operating on a saved file already. Would you prefer to troubleshoot the issue here or have him log an issue upstream?

**Comment by stamblerre** [comment]
@ysantalla: Were you working with modules or in `$GOPATH` mode?

**Comment by SUMUKHA-PK** [comment]
I am using go mod. But I'm not sure how the language server affects the imports and other linting. Also, limitation? So it never can be improved?

**Comment by ysantalla** [comment]
I working with modules.

**Comment by ysantalla** [comment]
who reload de language server, manually???

**Comment by stamblerre** [comment]
@ysantalla: The reason you did not have autocompletion in your example is because the language server does not yet support autocompletion in a null module, i.e., you have to run `go mod init` before you can begin using the language features. You can reload the language server by restarting your instance of VSCode, or by doing CTRL + Shift + P -> Developer: Reload Window.

@SUMUKHA-PK: The language server, `gopls`, is currently in alpha and under active development (https://github.com/golang/go/wiki/gopls). It will replace the current Go tools once it is more stable. For now, it is the recommended tool for modules users because it is faster than the other tools, which can be quite slow in module mode.

**Comment by ysantalla** [comment]
@stamblerre Thanks you!!!

**Comment by ramya-rao-a** [comment]
@SUMUKHA-PK Please give [Go tools that the Go extension depends on](https://github.com/microsoft/vscode-go/wiki/Go-tools-that-the-Go-extension-depends-on) a read to get an idea of how this extension is dependent on the Go tools from the community. For support when using Go modules, active development is for `gopls` the language, rather than the individual tools.

@ysantalla Does running `go mod init` and then using the language server resolve your issues now?
@Eleron8 Can you try the same?

@stamblerre I am thinking we need a troubleshooting guide :)

**Comment by stamblerre** [comment]
We have some suggestions here: https://github.com/golang/go/wiki/gopls#troubleshooting.

**Comment by SUMUKHA-PK** [comment]
Thank you @stamblerre and @ramya-rao-a

**Comment by goltvn** [comment]
out of nowhere i got the same issue here, the "Problems" tab was working yesterday and i could get my compile messages there, but now its blank and get the same view as ysantalla with no module info ?

https://i.imgur.com/bouydaC.png

This one should complain because Fmt havent been included. 

my json file :

https://i.imgur.com/O3KXrN5.png

I had my folder in root folder, then i moved it into gopath as a subdirectory and problem is still there, tried to restart vs code also and reinstalling go for vs-code but nothing works 

if i inspect the gopls output : 

https://i.imgur.com/d4G8QqO.png

and get some : 
```
[Error - 14:06:03] Request textDocument/documentSymbol failed.
  Message: no file information for file:
```

its really odd as it worked and then simply stopped working and didnt change anything in regards to my configuration - help is really appriciated as i have a deadline here and this is a killer

**Comment by goltvn** [comment]
Disabling the language server makes it work - video of it here, first one is with languageserver and there isnt any compiling done - then i disable it and reload vs code running without it, and i can then compile :

https://www.dropbox.com/s/w3njtkekp3cf92m/2019-06-18_14-23-13.mp4?dl=0

**Comment by stamblerre** [comment]
@goltvn: Can you please file an issue upstream [here](https://github.com/golang/go/issues) and include your `gopls` logs? I can help you investigate this.

**Comment by Eleron8** [comment]
@ramya-rao-a Thank you, Ramya Rao. I fixed promlem with your advices. 
I changed in `go.useLanguageServer` `true` to `false` and added `"go.gocodeAutoBuild": true,` in settings.json. God bless you. Thanks for all. Sorry for waste your time. I'm liltle bit stupid boy XD

**Comment by ramya-rao-a** [comment]
Closing this issue as it is getting hard to track the multiple issues that have been brought up here, some of them are fixed, others have workarounds.

Please log a new issue if you still have problems
