### ISSUE TITLE
Add the option to disable GC for some tools

### ISSUE THREAD

**Issue by vincepri** [microsoft/vscode-go#2577]
Adding `GOGC=off` environment variable to some tools can help, in some cases, save CPU resources, especially when it comes to `goimports` and similar short-lived CLI applications.

**Comment by ramya-rao-a** [comment]
Thanks for reporting @vincepri 

@bhcleek, @zmb3, @stamblerre, @ianthehat Do you have any thoughts or feedback around this?

**Comment by ianthehat** [comment]
Any tool that can benefit can get the same advantages by calling debug.SetGCPercent in the top of it's main. I added it to godef a while ago. It is a much more scalable solution than having everything that installs the tools have to control it.
Also setting it to a large number has a graceful failure mode where if the application is doing an unusual level of work it can still garbage collect and succeed rather than dying, for godef I tuned it to 1600.

**Comment by vincepri** [comment]
Thanks @ianthehat. Should we rename/refocus this issue on letting users customize GOGC=X instead of just turning it off? 

I see `vscode-go` as a good place to add the option, instead of relying on tools to implement this in their codebase.

**Comment by OneOfOne** [comment]
Isn't this already possible using `go.toolsEnvVars`?

```
	"go.toolsEnvVars": {
		"GOGC": "1600"
	}
```

**Comment by vincepri** [comment]
Does this apply to all the tools, even long running one? I'm mostly wondering about `gopls`

**Comment by OneOfOne** [comment]
It does, but sadly in my experience I have to restart gopls more often that it'd take for that to be an issue anyway.

**Comment by vincepri** [comment]
In that case I think this issue can be closed, as there is a perfectly fine solution.

**Comment by ramya-rao-a** [comment]
Yes, anything set in `go.toolsEnvVars` does get set in the process where `gopls` is spawned
