### ISSUE TITLE
The generated file warning should appear even if the DO NOT EDIT comment is not on the first line

### ISSUE THREAD

**Issue by kennytm** [microsoft/vscode-go#2617]
In #1425 (which fixes #1295), VSCode will show a warning if the *first line* of the code contains the comment matching `^// Code generated .* DO NOT EDIT\.$`. However, as specified in https://golang.org/pkg/cmd/go/internal/generate/, this comment can appear *anywhere*, so it is wrong to just detect the first line.

> To convey to humans and machine tools that code is generated, generated source should have a line that matches the following regular expression (in Go syntax):
>
> ```regex
> ^// Code generated .* DO NOT EDIT\.$
> ```
>
> **The line may appear anywhere in the file**, but is typically placed near the beginning so it is easy to find.

**Comment by ramya-rao-a** [comment]
#1425 was a best effort made under the circumstances to provide a warning.
In order to support the DO NOT EDIT comment on any line, we will have to parse the entire file which I would prefer not to do as it can get expensive on very large files.

Now that we have support for language servers, they are in a better state to handle parsed file contents. 

@stamblerre Is this something you would consider [gopls](https://github.com/microsoft/vscode-go#go-language-server) to do?

**Comment by stamblerre** [comment]
Yes, gopls could do this and send it as a diagnostic.

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre 

@kennytm Please log an issue in the [Go issue tracker](https://github.com/golang/go/issues/new?title=x%2Ftools%2Fcmd%2Fgopls%3A%20%3Cfill%20this%20in%3E)
