### ISSUE TITLE
Generate from the UI support

### ISSUE THREAD

**Issue by joeblew99** [microsoft/vscode-go#263]
golang has great generate support.

Any interest is adding this to the GUI ?

**Comment by lukehoban** [comment]
Agreed.  I'm hoping we can do that as part of https://github.com/Microsoft/vscode-go/pull/134 or building upon that.  We need all of `build`, `install`, `run` and `generate`.

**Comment by joeblew99** [comment]
Awesome. There is an excellent go gen library on github.
It generates about 15 different iles for all the things that replaces the need for generics.
That would be an awesome test case

**Comment by ramya-rao-a** [comment]
@joeblew99 Do you mean to have a command to run a simple `go generate` for current package?

**Comment by ramya-rao-a** [comment]
Thanks for the explanation @joeblew99, it definitely helped. Also read the [Design Doc](https://docs.google.com/document/d/1V03LUfjSADDooDMhe-_K59EgpTEm3V8uvQRuNMAEnjg/edit)

If I understand this correctly, as a first step, there should be a way to run the `go generate` command either on current file or current package.

Next, there should be some way to get this `go generate` to run every time time there is a change to certain files. This is where I am slightly stumped. How do we decide which files need to be watched for changes to trigger the `go generate`?

Is it ok to expect the user to specify these files via settings?

**Comment by yhuang0** [comment]
For my own purpose I just want to have a "go.generateOnSave" option for the current file scope. In addition, a vscode shortcut to run go generate manually. I don't think the first version of this needs to be that complicated.

**Comment by marwan-at-work** [comment]
I like the go.generateOnSave option. I'd also love to see something like Codelens (a button on top of the `//go:generate ...` comment just like the test functions. I'm happy to put some time into creating a pr if no one is working on it.

**Comment by awreece** [comment]
> Is it ok to expect the user to specify these files via settings?

That would be acceptable to me and appears to be the industry standard. It is certainly an easier solution than attempting to parse the `go:generate` comment line.

It also a solution that lends itself easily toward building some default configurations, e.g. "if a .proto file is changed, run go generate in the same directory" that would cover 90% of use cases.

**Comment by ramya-rao-a** [comment]
There hasnt been much progress in this area in the 2 years since the `help-wanted` tag was added to this issue.

While I do see the merits of this feature, I am afraid I don't believe this extension is the right place for it anymore.

As VS Code and this extension has gained popularity, we have seen a gradual scope creep over the past year. Being a sole maintainer of this project, it is getting a little hard to support all incoming requests and maintaining the ever growing set of features.

Therefore, one criteria I am using now in the triaging process is whether the feature request would make sense as a separate extension. This current feature request appears to be so.

Happy Coding!
