### ISSUE TITLE
Confusing behavior with `go vet` when using gopls and modules

### ISSUE THREAD

**Issue by inliquid** [microsoft/vscode-go#2649]
Say we have a circular dependency (just as an example). We are using `gopls` as the language server. Currently `gopls` doesn't warn about such case, see https://github.com/golang/go/issues/33085
However what if we run `go vet` explicitly? Go output for `Vet Current Package` shows that tool was run, making impression that it's all fine:
![изображение](https://user-images.githubusercontent.com/6797881/61151785-69c26f80-a4ef-11e9-95d7-896492afc2e4.png)
However if the tool run manually we see that it's clearly not ok:
![изображение](https://user-images.githubusercontent.com/6797881/61151892-a9895700-a4ef-11e9-9ef7-95344d3811e7.png)
So it's obvious that `vscode-go` action `Vet <smth>` doesn't actually trigger `go vet` to run.

**Comment by ramya-rao-a** [comment]
Please provide a small sample code that I can try to replicate this issue on.

**Comment by inliquid** [comment]
Any circular dependency works, it's clear from the description.

CircularDependency/main.go:
```go
package main

import (
	"CircularDependency/a"
	"CircularDependency/b"
	"fmt"
)

func main() {
	fmt.Println(a.HelloWorld)
	fmt.Println(b.HelloWorld)
}
```
CircularDependency/a/a.go:
```go
package a

import "CircularDependency/b"

const Hello = "Hello"

const HelloWorld = Hello + b.World
```
CircularDependency/b/b.go:
```go
package b

import "CircularDependency/a"

const World = "World"

const HelloWorld = a.Hello + World
```

**Comment by ramya-rao-a** [comment]
Thanks for providing the code @inliquid 
I have very limited time that I get to dedicate to this project, so having code snippets that I can copy and try to to replicate a bug helps immensely regardless how simple the code is.

With the above code
- I see expected errors when I turn the language server off and save the file
- I see that `gopls` doesnt report any errors/warnings when language server is enabled
- I see expected warnings when I run the `Go: Vet Current package` command when language server is enabled

![image](https://user-images.githubusercontent.com/16890566/61398894-cf14b880-a881-11e9-8a5d-e39078857594.png)

![image](https://user-images.githubusercontent.com/16890566/61398931-ddfb6b00-a881-11e9-86b4-66e5292bf111.png)

I see that you are using vet flags. Can you share the Go related settings you have, so that I can try with the same?

**Comment by ramya-rao-a** [comment]
Also, I am running the command with the `CircularDependency/main.go` file opened in the active editor

**Comment by ramya-rao-a** [comment]
I was not using modules before. If I change to using modules, then I see the issue you are talking about.

Without modules, `go vet` returns the below
```
main.go:4:2: cannot find package "CircularDependency/a" in any of:
        C:\Go\src\CircularDependency\a (from $GOROOT)
        C:\Users\ramyar\go\src\CircularDependency\a (from $GOPATH)
main.go:5:2: cannot find package "CircularDependency/b" in any of:
        C:\Go\src\CircularDependency\b (from $GOROOT)
        C:\Users\ramyar\go\src\CircularDependency\b (from $GOPATH)
```

With modules, `go vet` returns the below
```
import cycle not allowed
package CircularDependency
        imports CircularDependency/a
        imports CircularDependency/b
        imports CircularDependency/a
can't load package: import cycle not allowed
package CircularDependency
        imports CircularDependency/a
        imports CircularDependency/b
        imports CircularDependency/a
```

As you can see, the output in case of modules doesnt have any file path or line number
The Go extension relies on the file path and line number to show the error/warning on the right lines in the editor.

@stamblerre, @ianthehat Any insights on why `go vet` behaves differently this way?

**Comment by stamblerre** [comment]
/cc @matloob for more insight on go/analysis

I'd also suggest that in the cases when `go vet` doesn't return position information, maybe VSCode-Go could default to the top of the file?

**Comment by ramya-rao-a** [comment]
We did that for build errors to fix #664 which is basically the same problem :)

Since using `gopls` disable the build checks by the vscode-go checks, the fix for #664 doesnt help here.

But if I am getting this right... the errors we are seeing here from `go vet` is basically build/compile errors and not actual vetting errors right i.e this is not due to any vetting rules?

If so, then I'd be more inclined for the the build tool (in this case `gopls`) to show the appropriate error

**Comment by ramya-rao-a** [comment]
Alright, here is what we can do
- we extend the fix we made in #664 for build command to work for vet command as well
- in the middle ware for handling diagnostics, we can interrupt and inspect the diagnostics from the language server. If there are conflicts on the same line & position, we let the language server results win

PRs are welcome to fix this
Code Pointers:
- [Set up local dev environment for Go extension](https://github.com/microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code)
- Update the call to the `runTool()` method in goVet.ts file to pass `true` for the `printUnexpected Output` parameter
- Update the [middleware for diagnostics](https://github.com/microsoft/vscode-go/blob/0.11.4/src/goMain.ts#L224) to add inspection of the language server results
- In the absence of the language server, conflicts between vet and build are resolved at [handleDiagnosticErrors](https://github.com/microsoft/vscode-go/blob/0.11.4/src/util.ts#L706). This can be used as a reference to resolve conflicts between the vet results of the vet command and diagnostics from the language server

**Comment by stamblerre** [comment]
https://github.com/golang/vscode-go/issues/49 has been resolved in `gopls`, and we disable build and vet by default for `gopls` users, so I think that this issue can be closed.

**Comment by ramya-rao-a** [comment]
@stamblerre The issue you linked (https://github.com/golang/vscode-go/issues/49) is not related to build or vet. Are we saying that `gopls` returns expected error for this case?

**Comment by stamblerre** [comment]
Oh I'm sorry, I meant to link the issue referenced in the issue report: https://github.com/golang/go/issues/33085. This issue is resolved, so yes, `gopls` does return the expected errors. But I think, in general, `gopls` users should not be using `go.vetOnSave` separately anyway.
