### ISSUE TITLE
consider adding the stale bot to scrub stale issues

### ISSUE THREAD

**Issue by marco-m** [microsoft/vscode-go#2684]
Hello,

this is a suggestion to consider adding the stale bot https://github.com/apps/stale to this repository, so that stale tickets can be closed, and maybe a similar bot as PR reminder. I understand this is a question of taste, but in my opinion and experience keeping tickets opened for years doesn't help towards resolving them :-)

Following the spirit of this request, please close this ticket as soon as a decision is taken :-D

and thanks for vscode-go :-)

marco

**Comment by ramya-rao-a** [comment]
I agree that keeping tickets open for long doesnt help anyone :)

We do have a bot that closes issues which have the label `needs-more-info` and has not seen a comment from a non-collaborator for more than 7 days.
I guess what I also need to do is close issues that havent seen a lot of interest as well.

I will be doing a fresh round of triaging soon, so that should help.

Thanks for your thoughts though :)
If you are interested in lending a hand, do drop your thoughts on older issues.

**Comment by marco-m** [comment]
Thanks for the explanation Ramya. I will chime in in old issues then.

May I ask another, unrelated question? I noticed that lately (last two months maybe) the activity on this repo dropped substantially. Do you have any information that you can share with the public abut the plans ? And thanks again for this extension, I love it!

**Comment by ramya-rao-a** [comment]
Well, 2 months ago I had a role change at my job and so the amount of time I had to spend on this extension dipped. I have now come out on the other side of the adjustment period and so am now picking up the slack :)

No change in plans for the extension. But I am working with different partners to de-centralize the efforts a bit. Eventually this would crystalize enough for me to share "formal plans" on how people can contribute in multiple different ways with different levels of effort to this project

For example, our good friend @stamblerre from the Go tools team is helping us out with the language server integration. We also have @quoctruong, @jhendrixMSFT and others from the community, who are working to improve the debug experience.

**Comment by marco-m** [comment]
Thanks for the transparency @ramya-rao-a, greatly appreciated :-)
And thanks to all the contributors 🤗
