### ISSUE TITLE
gometalinter is deprecated

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode-go#2694]
It seems that https://github.com/alecthomas/gometalinter is deprecated, and https://github.com/golangci/golangci-lint is the official recommended alternative.

What is the plan for `gometalinter` support in VSCode? Should it be removed from the set of supported tools or should it continue to be maintained?

**Comment by ramya-rao-a** [comment]
- It can be removed from the list of tools that can be installed/updated when running the command `Go: Install/Update tools`
- It cannot be removed from the options for `go.lintTool` yet because I wouldnt want to break the workflow of existing users. We can push it to the end of the choices though.
- After a few months, we can add a notification suggesting users to move to golangci-lint instead

Thoughts?

**Comment by ramya-rao-a** [comment]
Fair point @samanthakem 
I'll close this issue in favor of #2509 and update that issue with next steps
