### ISSUE TITLE
goland debugging do not stop process

### ISSUE THREAD

**Issue by shvydok** [microsoft/vscode-go#2710]
Hello,

by debugging go lang program, stop or restart of debugger did not kill service process, which lead to blocking of port on which service is working.

If any info is needed to provide better picture, just let me know.

Thank you.

Ihor

**Comment by shvydok** [comment]
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by nmorenor** [comment]
I'm observing this behavior also on my side, also running on OSX with the vscode-go (0.11.4) extension 

```package main

import (
	"fmt"
	"net/http"
)

// Hello says hello
func main() {
	var helloWorld = "Hello"
	fmt.Println(helloWorld)

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		fmt.Fprintf(w, "Hello, you’ve requested: %s\n", r.URL.Path)
	})
	http.ListenAndServe(":8081", nil)
}```

**Comment by ramya-rao-a** [comment]
Hey all,

I am not able to replicate the issue with what @nmorenor has shared when running the program on my Mac. Also, both delve and this extension has seen quite some changes since this issue was reported.

If you still see issues with debugging, please log an issue at https://github.com/golang/vscode-go as [we are moving](https://github.com/microsoft/vscode-go#we-are-moving---)!

Thanks for all the support & Happy Coding!
