### ISSUE TITLE
Add support for prepare rename when using language server

### ISSUE THREAD

**Issue by suzmue** [microsoft/vscode-go#2714]
Issue type: Feature Request

I am using vscode with gopls:

Here is my settings.json:
```{
    "go.useLanguageServer": true,
    "[go]": {
        "editor.snippetSuggestions": "none",
        "editor.formatOnSave": false,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
    "files.eol": "\n",
    "go.languageServerFlags": [
        "serve",
        "-debug=localhost:6060",
        "-rpc.trace"
    ],
    "go.toolsEnvVars": {
        "GO111MODULE": "on",
    },
}

```

The client registers with the gopls server with the following rename settings:

```
"rename": {"dynamicRegistration":true}
```

I propose implementing prepare support, so that if the selected Go language server is a `prepareProvider`, `textdocument/prepareRename` can be used to select the identifier to rename.

**Comment by ramya-rao-a** [comment]
@suzmue Can you provide more details on what the prepare support means? Links to any existing docs will help a lot

cc @stamblerre

**Comment by stamblerre** [comment]
This would be fixed with https://github.com/microsoft/vscode-go/pull/2716.
The [prepareRename](https://microsoft.github.io/language-server-protocol/specification#textDocument_prepareRename) feature is sent before a rename request. If the user is trying to rename a symbol that should not be renamed (inside a string or comment, on a builtin identifier, etc.), VSCode won't even show the rename pop-up.

**Comment by ramya-rao-a** [comment]
Ah! never mind, just saw the PR from @stamblerre

**Comment by ramya-rao-a** [comment]
And she beat me to adding a comment here :)

**Comment by ramya-rao-a** [comment]
The latest [beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension has the fix for this issue
