### ISSUE TITLE
Snippets: GoRoutine Function removal

### ISSUE THREAD

**Issue by mattouille** [microsoft/vscode-go#2717]
This is a proposal to remove the GoRoutine Function from the snippets.

https://github.com/microsoft/vscode-go/blob/master/snippets/go.json#L203-L207

My reasoning is that I've observed snippets fulfill the following functions:
1. They should really solve some creative dilemma (ie, to enforce patterns) 
2. They should save the developer time

The snippet prefix is the same length as just typing `go` and to my knowledge people aren't exploring the language through snippets (I could be off base here, but that was not my experience).

If everyone agrees I'll open a PR to remove the snippet from future versions.

**Comment by stamblerre** [comment]
I think the convenience of having `go func() {}()` appear may be worth it to some. However, as per https://github.com/microsoft/vscode-go/issues/2380#issuecomment-622009130, we will be pausing development on snippets so that we can reevaluate all of the extension's snippets as a whole. I am going to go ahead and close this issue, but I have noted it [here](https://github.com/microsoft/vscode-go/issues/2380#issuecomment-629041632).
