### ISSUE TITLE
Documentation tool repeating lines

### ISSUE THREAD

**Issue by kroppt** [microsoft/vscode-go#2722]
Steps to Reproduce:

1. Type the following into a go file:
```
conn, _ := net.DialTCP("tcp", nil, nil)
conn.Write([]byte("test"))
```
2. Hover over `conn.Write` to see:
![image](https://user-images.githubusercontent.com/14015672/64057632-546fd600-cb6d-11e9-8546-d554d2f9c3af.png)
3. Jump to definition to view the documentation:
```
// Write implements the Conn Write method.
func (c *conn) Write(b []byte) (int, error) {
```

All go settings are default.

<details><summary>VSCodium About</summary>
Version: 1.37.1<br/>
Commit: 9afbbd903b7b481aa127d4d8d68626397e6a5135<br/>
Date: 2019-08-16T10:21:32.989Z<br/>
Electron: 4.2.7<br/>
Chrome: 69.0.3497.128<br/>
Node.js: 10.11.0<br/>
V8: 6.9.427.31-electron.0<br/>
OS: Windows_NT x64 10.0.18362
</details>

go version:
```
$ go version
go version go1.12.9 windows/amd64
```

**Comment by ramya-rao-a** [comment]
This issue is being tracked in #2107

This happens when there are multiple functions with the same name, but on different receivers in the same package.
We use `go doc` to get the documentation, but at this time, we are not aware of which receiver to use.

Some workarounds are:
- Change your `go.docsTool` to `gogetdoc` which is smart enough to figure out the right documentation
- Or use the [language server](https://github.com/microsoft/vscode-go#go-language-server)
