### ISSUE TITLE
Autocomplete Improvement: Adding brackets for function calls

### ISSUE THREAD

**Issue by ls42** [Microsoft/vscode-go#276]
Hi,

when auto-completing function calls like `fmt.Fpr<TAB>`, it completes the function name. I think most of the time it would be useful to also append the `()` and put the cursor inside the brackets. When it's not required one could simply press backspace to remove these two brackets.

Thanks for the great work so far, I find it to be one of the best Go plugins for any editor.

**Comment by lukehoban** [comment]
There is an option`useCodeSnippetsOnFunctionSuggest ` which adds parens and function signature, similar to what some other Go IDE's do.  It's off by default because this is not the standard interaction model for VS Code. 

There is no separate option to just insert the parens - I'm not sure that would make sense as a Go-specific thing.

Options are all listed here: https://github.com/Microsoft/vscode-go#options.

**Comment by ls42** [comment]
YES! Thanks a million. Works like a charm.

Have a splendid week, I will for sure.

**Comment by highskillzz** [comment]
i turned the useCodeSnippetsOnFunctionSuggest on but no brackets completion happens is there something else that I should be doing

**Comment by koenbok** [comment]
It's actually `useCodeSnippetsOnMethodSuggest` now.

**Comment by highskillzz** [comment]
Yes, I got it. Thank you for your help
