### ISSUE TITLE
Generate method stub

### ISSUE THREAD

**Issue by benoitdion** [microsoft/vscode-go#277]
Implement this old Visual Studio feature: https://msdn.microsoft.com/en-us/library/tcz8b6zc(v=vs.90).aspx

**Comment by lukehoban** [comment]
Happy to accept a PR for this.

It should be possible to build this as a VS Code `Code Action` added to https://github.com/Microsoft/vscode-go/blob/master/src/goCodeAction.ts.

**Comment by ramya-rao-a** [comment]
_From @klaidliadon in #1620_

It would be nice to have a "create function/method" command for functions/methods that are not yet defined.

For instance:
```go
type a int64

type s struct{}

func main(){
    var err error
    if err = someFunc(a(1), s{}); err != nil {
        log.Fatal(err)
    }
}
```
Should create something like:
```go
func someFunc(v1 a, v2 s){
   return nil
}
```

**Comment by ramya-rao-a** [comment]
Closing this issue for the below reasons:
- There hasn't been much interest in terms of upvotes of comments from the community
- This would require the understanding of the types of input parameters. The Go extension is written in a way to avoid trying to parse and understand the AST. It relies on external Go tools to do the same and return results. Since there is no such tool available at the moment, we don't have a clear way to implement this feature

If there is such a Go tool, I would prefer this feature be implemented as a separate VS Code extension. This is because as VS Code and this extension has gained popularity, we have seen a gradual scope creep over the past year. Being a sole maintainer of this project, it is getting a little hard to support all incoming requests and maintaining the ever growing set of features. 

Therefore, one criteria I am using now in the triaging process is whether the feature request would make sense as a separate extension. This current feature request appears to be so.
