### ISSUE TITLE
Cannot install tools

### ISSUE THREAD

**Issue by dfarley1** [microsoft/vscode-go#2796]
I'm running VSCode into a docker container using the Remote-Containers extension and I've installed the Go extension in the container.  I have a workspace folder defined at `/depot` with the following settings:
```
/depot/.vscode/settings.json:

...
"go.gopath": "${workspaceFolder}/vendor/golibs",
"go.toolsGopath": "${workspaceFolder}/.vscode/golibs",
...
```

When I open a  Go file I get a notification with `The "go-outline" command is not available. Run "go get -v github.com/ramya-rao-a/go-outline" to install`.  When I click Install I get the following error:
```
Installing 1 tool at /depot/vendor/golibs/bin
  go-outline

Installing github.com/ramya-rao-a/go-outline FAILED

1 tools failed to install.

go-outline:
Error: Command failed: /usr/bin/go get -v github.com/ramya-rao-a/go-outline
go: cannot find main module; see 'go help modules'
go: cannot find main module; see 'go help modules'
```
There's two problems:
1. The installation is failing.  I found another issue about "cannot find main module" from last year but the suggested solution doesn't work for me.
2. VSCode isn't respecting `go.toolsGoPath` and is trying to use `go.goPath` instead.

I've tried the "Go: Install/Update Tools" command and that fails with the same error for every package (and tries to put them under `/depot/vendor`).
I've also manually opened a shell and run the commands with the correct GOPATH and it appears to succeed but VSCode keeps complaining that the tools are missing.  I've tried manually installing them in both directories with the same result.

**Comment by slehan** [comment]
I'm having the same issue using the WSL remote instead.

**Comment by jdratlif** [comment]
I am having the same issue locally.

**Comment by ramya-rao-a** [comment]
@dfarley1 Can you try adding the path where you are installing the tools (including the `/bin`) to your PATH env variable in the remote place?
With this the extension should definitely be able to find the tools.

**Comment by dfarley1** [comment]
@ramya-rao-a I just tried with the following settings but there's no difference, it still can't find any tools and the installation fails.  It's also still trying to install them in the wrong location.
```
"go.gopath": "${workspaceFolder}/.vscode/golibs:${workspaceFolder}/vendor/golibs",
"go.toolsGopath": "${workspaceFolder}/.vscode/golibs",
```

**Comment by dfarley1** [comment]
I just tried with the following settings and it still claims the tools couldn't be found.
```
"go.gopath": "${workspaceFolder}/.vscode/golibs/bin:${workspaceFolder}/vendor/golibs",
"go.toolsGopath": "${workspaceFolder}/.vscode/golibs",
```

**Comment by pot-code** [comment]
same here

**Comment by dfarley1** [comment]
Bumping, any other ideas?

**Comment by ramya-rao-a** [comment]
@dfarley1 Can you try not using the `${workspaceFolder}` in the settings? It could be possible that in the remote case, the variables are not being read correctly

**Comment by dfarley1** [comment]
I decided to try installing outside the repo entirely, specifically `$HOME/go -> /home/danf/go`.  Trying to install still does not respect `toolsGopath` and tries install one level deeper into `$HOME/go/bin/bin`
```
"go.gopath": "${env:HOME}/go/bin:/depot/vendor/golibs",
"go.toolsGopath": "${env:HOME}/go",

----------------------------------

Installing 1 tool at /home/danf/go/bin/bin
  go-outline

Installing github.com/ramya-rao-a/go-outline FAILED

1 tools failed to install.

go-outline:
Error: Command failed: /usr/bin/go get -v github.com/ramya-rao-a/go-outline
go: cannot find main module; see 'go help modules'
go: cannot find main module; see 'go help modules'
```

Putting `${env:HOME}/go` at the front of `gopath` still fails to install
```
"go.gopath": "${env:HOME}/go:${env:HOME}/go/bin:/depot/vendor/golibs:/depot/extrahop/go",
"go.toolsGopath": "${env:HOME}/go",

----------------------------------

Installing 1 tool at /home/danf/go/bin
  go-outline

Installing github.com/ramya-rao-a/go-outline FAILED

1 tools failed to install.

go-outline:
Error: Command failed: /usr/bin/go get -v github.com/ramya-rao-a/go-outline
go: cannot find main module; see 'go help modules'
go: cannot find main module; see 'go help modules'
```

After installing all the tools manually:
```
danf@docker ~ $ echo $GOPATH
/home/danf/go:/depot/vendor/golibs

danf@docker ~ $ /usr/bin/go get -v github.com/mdempsky/gocode && \
/usr/bin/go get -v github.com/uudashr/gopkgs/cmd/gopkgs && \
/usr/bin/go get -v -d github.com/stamblerre/gocode && \
/usr/bin/go get -v github.com/rogpeppe/godef && \
/usr/bin/go get -v github.com/sqs/goreturns && \
/usr/bin/go get -v golang.org/x/lint/golint
```
I still get an "Analysis Tools Missing" warning and a prompt to reinstall `gocode-gomod`.  This happens even if I remove the `-d` option.

**Comment by ramya-rao-a** [comment]
@dfarley1 Can you retry the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension? I have added some logs around whether the tools go path setting is read or not. We also had some other changes around how we read configuration. I'd like to see if that made any difference at all.

**Comment by oforero** [comment]
I am having similar issues here.

What I am trying to do is to use a custom GO compiler, I have set the "go.goroot" and the "go.gopath" settings.

`{
    "terminal.integrated.rendererType": "dom",
    "terminal.integrated.shell.osx": "/usr/local/bin/fish",
    "terminal.integrated.experimentalTextureCachingStrategy": "dynamic",
    "editor.fontFamily": "Hack",
    "go.formatTool": "goimports",
    "go.useLanguageServer": true,
    "editor.largeFileOptimizations": false,
    "go.goroot": "/Users/oscar/goroot",
    "go.gopath": "/Users/oscar/go",       
    "[go]": {
        "editor.insertSpaces": false,
        "editor.formatOnSave": true,
        "editor.codeActionsOnSave": {
            "source.organizeImports": true
        }
    },
}`

When I start VS code it tells me it needs to install the tools, when I click install it fails:

`go.toolsGopath setting is not set. Using GOPATH /home/Oscar/go
Installing 1 tool at /home/Oscar/go/bin in module mode.
  go-outline

Installing github.com/ramya-rao-a/go-outline FAILED

1 tools failed to install.

go-outline:
Error: Command failed: /Users/oscar/Projects/goroot/bin/go get -v github.com/ramya-rao-a/go-outline
go: cannot find GOROOT directory: /home/Oscar/Projects/goroot/bin
go: cannot find GOROOT directory: /home/Oscar/Projects/goroot/bin
`

I think the problem here is that somehow it is changing the paths prefix to `/home/Oscar/`, I am using a Mac and that path does not exist. 
Setting the `go.toolsPath` seems to fix that problem because the `run_test` option is activated, however when I try to use it I get the following error:

`
Running tool: /Users/oscar/Projects/goroot/bin/go test -timeout 30s -run ^(TestIndexFile)$

go: cannot find GOROOT directory: /home/Oscar/Projects/goroot/bin
Error: Tests failed.
`
I think the problem is that a default is probably leaking in, I have tested the failing commands and they can be executed in the command line since the problem seems to happen only in VSCode, I think it must be a configuration on it.

**Comment by oforero** [comment]
I've been trying to do some debugging. The function `updateGoPathGoRootFromConfig` in `goInstallTools.ts` calls `getGoConfig`, this function returns a broken configuration pointing to the directories starting with `/home`, but I have not been able to determine where the corruption happens nor from where is this information being read.

I think after this line (utils.ts:136) `vscode.workspace.getConfiguration('go', uri);` the config is already corrupted

**Comment by colinplamondon** [comment]
Encountering the same issue - clean Go install, nothing fancy going on, everything is in ~/.go.

When I run any of the individual commands, like `go get -v github.com/mdempsky/gocode`, that works in both the Terminal, and the VS Code Integrated Terminal.

I'm super new to golang, so there's every chance I'm doing something obviously wrong here 👍 

### Example Error Output:
```
Installing 1 tool at /Users/colinplamondon/go/bin
  gocode

Installing github.com/mdempsky/gocode FAILED

1 tools failed to install.

gocode:
Error: Command failed: /usr/local/opt/go/libexec/bin/go get -v github.com/mdempsky/gocode
go: cannot find main module; see 'go help modules'
go: cannot find main module; see 'go help modules'
```

### Go env:

```
colinmbpa:thebeam colinplamondon$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/colinplamondon/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/colinplamondon/.go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/pv/ttdzhkm96pddkbczz3xbrxkm0000gn/T/go-build738017918=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by zhangyulu** [comment]
Running into the same issue when using vscode remote on an ssh connection to linux server.
By the way, I'm on two independent projects on local(Windows 10) and remote(CentOS) respectively, how can I set different GOPATH per project without changing others

**Comment by ramya-rao-a** [comment]
Apologies for the very late reply here

@colinplamondon What you are seeing i.e the `cannot find main module; see 'go help modules'` error was covered in #2811 and the latest version of the Go extension should have the fix for it.

@oforero If you are still seeing the problem you reported, please log a new issue with the details of your investigation regarding the `updateGoPathGoRootFromConfig` and we will take a look at it at the earliest.

@dfarley1 We haven't heard back from you after https://github.com/microsoft/vscode-go/issues/2796#issuecomment-544321179, am assuming that this is no longer an issue after getting to the latest version of the extension.
