### ISSUE TITLE
Delve shows difference between nil and zero-len/zero-cap slice, Go-extension does not

### ISSUE THREAD

**Issue by cameron-elliott** [microsoft/vscode-go#2813]
Even though delve is showing the difference between nil slices, and zero-len/zero-cap slices, the VSCode interface to the debugger is not doing so, and I appear to have the recent 0.11.7 release.
I also only have a single dlv.exe on my system of ver 1.2.0

 Delve showning nil vs zero-len/zero-cap slice
![image](https://user-images.githubusercontent.com/868689/66277933-77229800-e859-11e9-80b2-7cc21490c29e.png)

VScode Go extension not showing the difference
![image](https://user-images.githubusercontent.com/868689/66277959-a76a3680-e859-11e9-86af-bc2ecf7fd20b.png)

Test code:
```go
package main


import "fmt"

func main() {
	var x []string
	y:=[]string{}
	fmt.Println(x,y)

}
```

**Comment by ramya-rao-a** [comment]
Thanks for reporting @cameron-elliott 

@derekparker, @aarzilli,
What field in the [Variable](https://godoc.org/github.com/go-delve/delve/service/api#Variable) can the debug client look at to determine the above difference?

**Comment by aarzilli** [comment]
The Base field will be zero for nil slices.

**Comment by ramya-rao-a** [comment]
Thanks @aarzilli!

PRs are welcome to make this change

Code Pointers:
- [Set up local dev environment](https://github.com/microsoft/vscode-go/wiki/Building,-Debugging-and-Sideloading-the-extension-in-Visual-Studio-Code)
- Place to update the text that is shown in the variables pane: https://github.com/microsoft/vscode-go/blob/0.11.7/src/debugAdapter/goDebug.ts#L1266
- You will need to update the `DebugVariable` interface to include the "base" field so that you can check its value

**Comment by ramya-rao-a** [comment]
Please try the [latest beta version](https://github.com/microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension) of this extension has the fix for this

**Comment by ramya-rao-a** [comment]
The latest update to this extension (0.11.8) has the fix for this.

Thanks for reporting @cameron-elliott and @karthikraobr for the fix
