### ISSUE TITLE
Find All References does not work on Windows when drive letter in GOPATH is capitalized

### ISSUE THREAD

**Issue by samherrmann** [Microsoft/vscode-go#290]
The guru tool that was introduced in version 0.6.38 for the Find All References feature does not work when the Windows drive letter in the GOPATH is capitalized. The format of the file path that the vscode-go extension passes to guru (https://github.com/Microsoft/vscode-go/blob/master/src/goReferences.ts#L38) may look something like this:

`guru referrers c:/dev/gopath/src/hellogo/main.go:#69`

This call to guru causes the following error response:

`guru: directory c:\dev\gopath\src\hellogo is not beneath any of these GOROOT/GOPATH directories: C:\Go\src, C:\dev\gopath\src`

If the drive letter in the GOPATH is set to lowercase (matching the casing of the drive letter in the input), then guru works as expected.

My suggestion is that vscode-go should pass the `filename` to guru with the same drive letter casing  that is used in the GOPATH. That would add support for both uppercase and lowercase drive letters.

**Comment by samherrmann** [comment]
Alternatively, since vscode always provides the `filename` with a lowercase drive letter, maybe vscode-go should "normalize" GOROOT and GOPATH to lowercase drive letters and then pass those to the guru process?

**Comment by ramya-rao-a** [comment]
@lukehoban This is still an issue in Windows if the drive letter in the GOPATH is capitalized and the path contains forward slashes.

Reason is that the check at https://github.com/Microsoft/vscode-go/blob/master/src/util.ts#L92 will never pass when GOPATH has forward slash in Windows

Are we canonicalizing the filename because VS Code always lower cases the drive letter in windows while giving `document.fileName` ?

If yes, then we should just update the drive letter

**Comment by ramya-rao-a** [comment]
Closing as the casing is no longer an issue with recent versions of guru
