### ISSUE TITLE
Fuzzy search of workspace symbols

### ISSUE THREAD

**Issue by rhcarvalho** [microsoft/vscode-go#2950]
**Is your feature request related to a problem? Please describe.**
I am trying to quickly navigate to a test function that I know contains a certain string in the name.

For example, I want to find a test with the word "Flush", so I'd type `TestFlush` or `Test Flush` and expect to see `TestHTTPTransportFlush`, but see no match:

![image](https://user-images.githubusercontent.com/88819/70996251-ac0d5f80-20d2-11ea-8a45-0b8356f3a9a4.png)

**Describe the solution you'd like**
I would like "Go to Symbol in Workspace..." to work like "Go to Symbol in File..."

![image](https://user-images.githubusercontent.com/88819/70997376-39ea4a00-20d5-11ea-9a1f-1bb3939be1b2.png)

Fuzzy searching also works in "Show and Run commands":

![image](https://user-images.githubusercontent.com/88819/70996208-95ff9f00-20d2-11ea-8a8b-0caef1b543b8.png)

**Describe alternatives you've considered**
The only workaround I know of is to search for text using a regular expression:

![image](https://user-images.githubusercontent.com/88819/70997753-03f99580-20d6-11ea-830e-ad102548dd79.png)

**Additional context**
I found https://github.com/Microsoft/vscode/issues/33746 which was closed saying this is a per-language feature.

**Comment by ramya-rao-a** [comment]
The extension uses the [go-symbols](https://github.com/acroca/go-symbols) tool to provide the workspace symbols based on the user given "query". Since this tool doesn't support fuzzy search, the extension cannot do much in this case.

The [language server gopls](https://github.com/microsoft/vscode-go#go-language-server) on the other hand is not tied to this tool.

@stamblerre Would you consider this feature request for gopls?

**Comment by stamblerre** [comment]
Yes, we already have an issue open to track this (https://github.com/golang/go/issues/33844).

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre 

Closing this issue in favor of the upstream issue linked above
