### ISSUE TITLE
The plugin is damn too slow

### ISSUE THREAD

**Issue by kunaldas1997** [microsoft/vscode-go#2976]
When writing codes, and saving, the formatting doesn't happen, even though format on save is active. Also, IntelliSense doesn't work in Go code. It just shows "Loading"
![image](https://user-images.githubusercontent.com/26971428/72235227-f660fe00-35f6-11ea-9b9d-77c1dc11117f.png)

On importing any package, it throws an error that it's imported but not used.
![image](https://user-images.githubusercontent.com/26971428/72235243-1395cc80-35f7-11ea-9eeb-e99b3f310b57.png)

**Comment by wtask** [comment]
Yeah, the same problem. I have a fast laptop with 32 Gb RAM but every day I see errors on renamings/typing which was completed by me, but not by vscode+gopls, I see errors which I fix already, but gopls doesn't understood it... So sad.

**Comment by stamblerre** [comment]
@kunaldas1997: In your screenshots above, it looks like you've imported `"string"`, when it should be `"strings"`. This is likely causing the strange errors you're seeing, since `string` is a keyword and would cause a conflict.

As for the general speed of `gopls`, we're making improvements on master and there will be another release soon, but if you'd like to try out master, you can download it by running `GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master`. Please do let me know if there is any difference at master (if you try it out).

**Comment by ramya-rao-a** [comment]
@kunaldas1997 Are you seeing the slowness issue when using the language server or without it?

**Comment by Kapho** [comment]
I also experience this with and without the language server.

**Comment by stamblerre** [comment]
For the language server, you can try out the pre-release of the next version of `gopls` by running `GO111MODULE=on go get golang.org/x/tools/gopls@v0.3.0-pre1`. Please let me know if that improves performance.

**Comment by Kapho** [comment]
The pre-release language server runs at a good speed. :)

**Comment by stamblerre** [comment]
Glad to hear it! The official release will be out soon.

**Comment by stamblerre** [comment]
@kunaldas1997: Is this still an issue for you?
