### ISSUE TITLE
performance: limit concurrent subprocesses

### ISSUE THREAD

**Issue by stamblerre** [microsoft/vscode-go#3044]
There are a number of issues filed about the number of processes started by the extension, and in particular, processes that get started by various actions on save. These include `golint`, `go vet`, `go list`, `go doc`, etc. We should make sure that only one process of each "kind" is running at a given instant, meaning that we need to logic to cancel these processes when another is spawned.

This issue tracks this work, and as such encompasses https://github.com/microsoft/vscode-go/issues/2276, https://github.com/microsoft/vscode-go/issues/1916, https://github.com/microsoft/vscode-go/issues/1015, and https://github.com/microsoft/vscode-go/issues/2421 (a few of the issues I found with this type of report). Let's centralize discussion here.

**Comment by zmb3** [comment]
Did some investigation here.  There's two items worth discussing.

1. What do we mean when we say only one of each _kind_ of process should run at any given time.  A simple heuristic is to just look at the command, but does that fail us for things like the `go` tool  with many subcommands?  Should we be able to run a `go build` concurrently with a `go list`?

2. I put together a simple implementation of the above, and the tests fail because each suite kicks off a lot of concurrent runs of the same tool, which then get killed.  Is it worth rewriting the tests to serialize everything, or can we detect when we're running under the test suite and disable this behavior?

**Comment by ramya-rao-a** [comment]
We have code in place that ensures that existing child processes are killed before a new process is started for the same feature. We make use of the cancellation token for this.

You can see this in action for most of the features. For example, in case of the build on save feature, we create a new cancellation token for each invocation of the feature and cancel the token for the previous invocation:

https://github.com/microsoft/vscode-go/blob/master/src/goBuild.ts#L78-L85

When the token is cancelled, the corresponding child process is killed

https://github.com/microsoft/vscode-go/blob/6d1bf5c7999d5af0adcc15141ca012c34a9ca71c/src/util.ts#L674-L680

So, what we need is an investigation to see which features don't have the above guards. Or if the guards are triggered in the right places.

For example, in #2956, we can see that multiple `go doc` processes are being triggered. The guards are indeed present for this, so we need to investigate why they guards didn't work. See https://github.com/microsoft/vscode-go/blob/6d1bf5c7999d5af0adcc15141ca012c34a9ca71c/src/util.ts#L1029-L1032

**Comment by zmb3** [comment]
There's a few problems with the following: 

https://github.com/microsoft/vscode-go/blob/6d1bf5c7999d5af0adcc15141ca012c34a9ca71c/src/util.ts#L883-L888

1.  The return value of `spawnSync` is ignored, so we're not catching errors if the process fails.
1. I'm not sure the path to the `terminateProcess.sh` script is correct.  If I look at the way the extension is unpacked on my machine, I see:
    ```
    ./scripts/terminateProcess.sh 
    ./out/src/util.js
    ```
    which suggests that util would only need to go up two directories `../..` to find the script, not 3.
1. This code is going to be very difficult to test, because `__dirname` will evaluate differently when the extension is being tested and when it is actually installed.  Is there any reason to call an external script and not use node to terminate the process?

**Comment by ramya-rao-a** [comment]
> Is there any reason to call an external script and not use node to terminate the process?

I believe that was because we had to recursively kill all the child processes. I might be wrong though. I am open for alternatives

**Comment by zmb3** [comment]
How concerned are we about child processes?  Do `golint` or the `go` tool create lots of child processes that continue to live on if their parent dies?  

It might be easiest to start by just killing the parent from node, which would be:
- an improvement over the current state which isn't successfully killing anything
- simpler than invoking external platform-specific scripts, and
- easier to test and verify

**Comment by stamblerre** [comment]
@quoctruong recently suggested https://www.npmjs.com/package/tree-kill as an alternative to the current platform-specific scripts. This would resolve the issue causing https://github.com/microsoft/vscode-go/issues/2407, allowing us to move forward with merging https://github.com/microsoft/vscode-go/pull/2372. @zmb3: What do you think?

**Comment by zmb3** [comment]
Yeah I looked at that package and a few others. That’ll work.

**Comment by stamblerre** [comment]
Moved this issue to https://github.com/golang/vscode-go/issues/161, as this repository is migrating: https://github.com/microsoft/vscode-go/issues/3247. @lggomez has already mailed https://github.com/golang/vscode-go/pull/91 to the new repository.
