### ISSUE TITLE
Restart debug show error notifications

### ISSUE THREAD

**Issue by fourcels** [microsoft/vscode-go#3104]
### What version of Go, VS Code & VS Code Go extension are you using?
- Run `go version` to get version of Go
	- go version go1.13.8 darwin/amd64
- Run `code -v` or `code-insiders -v` to get version of VS Code or VS Code Insiders
	- 1.43.0
78a4c91400152c0f27ba4d363eb56d2835f9903a
x64
- Check your installed extensions to get the version of the VS Code Go extension 
	- 0.13.1
- Run `go env GOOS GOARCH` to get the operating system and processor arhcitecture details
	- darwin
amd64

### Describe the bug
Restart debug  show error notifications

### Screenshots or recordings
<img width="930" alt="WeChat6fd46378d06174fd17055a6bb9741aef" src="https://user-images.githubusercontent.com/1042568/76686578-6cb1c900-6657-11ea-9672-8e7cad104ac7.png">

**Comment by YugeCse** [comment]
I get the problem too.

**Comment by hyangah** [comment]
The underlying error is "detached from the process" returned for the threads command,
which indicates some race.

FYI - the fix for the incomprehensible error message will be available in the next VS Code release (https://github.com/microsoft/vscode/issues/93346). But the underlying issue still remains.

**Comment by hyangah** [comment]
cc @polinasok who recently looked into the thread request & event messages.

**Comment by nicocesar** [comment]
Same here.

```
$ code -v
1.43.2
0ba0ca52957102ca3527cf479571617f0de6ed50
x64
$ go version
go version go1.14.1 linux/amd64
 $ go env GOOS GOARCH
linux
amd64

```

**Comment by polinasok** [comment]
I am unable to reproduce this. I do see "Unable to produce stack trace: {e}" on start or restart (which is just stop and start under the hood), but that is a different issue.
Can somebody please share a test program with me, your settings in launch.json and steps to reproduce what you are seeing? Could you please enable logging  with "trace": "log" in launch.json (more on logging [here](https://github.com/Microsoft/vscode-go/wiki/Debugging-Go-code-using-VS-Code#enabling-debug-logs))? This will give us the exact error instead of {e}. It might not always be "detached from the process". Thank you.

**Comment by fourcels** [comment]
launch.json
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Package",
      "type": "go",
      "request": "launch",
      "mode": "debug",
      "program": "${workspaceFolder}"
    }
  ]
}
```

main.go
```go
package main

import "github.com/labstack/echo/v4"

func main() {
	e := echo.New()
	// Start server
	e.Logger.Fatal(e.Start(":1323"))
}
```
```
$ code -v
1.44.2
ff915844119ce9485abfe8aa9076ec76b5300ddd
x64
$ go version
go version go1.14.1 darwin/amd64

VS Code Go extension
0.14.1
```



![Screen Shot 2020-04-22 at 10 36 29](https://user-images.githubusercontent.com/1042568/79934742-dfe40180-8485-11ea-9e59-67a0a76fa952.png)

@polinasok

**Comment by yeluoqiuzhi** [comment]
I got the same problem too

**Comment by stamblerre** [comment]
Thank you for the report, @fourcels. I have migrated the issue to the new repository (https://github.com/golang/vscode-go/issues/149), as we are moving (see https://github.com/microsoft/vscode-go/issues/3247).
