### ISSUE TITLE
How to disable package not found squiggle?

### ISSUE THREAD

**Issue by ideawu** [microsoft/vscode-go#3114]
Hi, I just want vscode-go  no showing squiggle for imported packages, I don't want to set GOPATH either, just config vscode-go not check for this type of error, is there any setting option to do so?

**Comment by hyangah** [comment]
@ideawu Assuming you are talking about the red squiggle under the package name, that indicates an issue with the import package. If you are using the language server (i.e. `go.useLanguageServer` is true), you can disable it by setting 
```
    "go.languageServerExperimentalFeatures": {
        "diagnostics": false,
    },
```

Out of curiosity - when the red squiggle exists, it's likely your program will not compile (either because it is unused package or the package can't be found). What is the use case?

**Comment by stamblerre** [comment]
Going to close this issue since there hasn't been much activity here. @ideawu: please reopen if you're still having this issue.
