### ISSUE TITLE
"debug test" only work with one version of go?

### ISSUE THREAD

**Issue by zhiqiangxu** [microsoft/vscode-go#3152]
### Describe the bug

I use `gvm` to manage multiple go versions:
```
$ gvm list

gvm gos (installed)

   go1.10
   go1.12
=> go1.13
```

I have two projects, one is configured to use `go1.13`:

```
  "go.gopath": "/Users/xuzhiqiang/.gvm/pkgsets/go1.13/global",
  "go.goroot": "/Users/xuzhiqiang/.gvm/gos/go1.13",
```

The other is configured to use `go1.12`:

```
  "go.gopath": "/Users/xuzhiqiang/.gvm/pkgsets/go1.12/global",
  "go.goroot": "/Users/xuzhiqiang/.gvm/gos/go1.12",
```

It seems to me that vscode will stick to the same go tool version for `debug test`, so the first project can run `debug test` successfully, but the second one will report `go version does not match go tool version`, like this:

```
# internal/nettrace
compile: version "go1.12" does not match go tool version "go1.13"
# github.com/oklog/run
compile: version "go1.12" does not match go tool version "go1.13"
# encoding
compile: version "go1.12" does not match go tool version "go1.13"
```

The root cause seems to be that vscode somehow doesn't choose the `dlv` under configured `GOROOT` ?

**Comment by hyangah** [comment]
I think this is because the `delve` invokes the go command with just the executable name (`go`) (https://github.com/go-delve/delve/blob/master/pkg/gobuild/gobuild.go#L66) so picks up any `go` command found from the `PATH`. 

As a workaround, try to add `${YOUR_GOROOT}/bin` as the first `PATH` element. There are many ways to set this env var - one way is to use `"go.toolsEnvVar"'.

We can consider passing the "go.goroot"/bin when launching the debug adapter.
@ramya-rao-a @quoctruong @polinasok 

I don't see any other way to teach `delve` about the path to the go binary yet.

**Comment by ramya-rao-a** [comment]
The latest update 0.14.2 has the fix for this, Thanks @hyangah
