### ISSUE TITLE
Disabling the import formatting on auto complete

### ISSUE THREAD

**Issue by eladciuraru** [microsoft/vscode-go#3207]
I want to do a simple task of disabling anything related to the auto code format and imports,
but it doesn't matter how much I try to fight it, the go tooling around VS Code doesn't seem to care, and just does what ever it wants.

I opened this issue about the setting: `"go.autocompleteUnimportedPackages": false,`
it just doesn't work, any time I use the auto complete for a package I haven't imported yet, it just auto formatting all the import section. 

Those are all the settings I use for go:
```json
    "[go]" : {
        "editor.formatOnSave": false,
        "editor.insertSpaces": true,
        "editor.formatOnPaste": false,
        "editor.codeActionsOnSave": {
            "source.organizeImports": false,
            "source.fixAll": false
        }
    },
    "go.lintOnSave": "off",
    "go.useLanguageServer": true,
    "go.autocompleteUnimportedPackages": false,
```

Although I opened this issue regarding that particular setting, I want to mention how frustrating it is to use the go tooling with VS Code.
It was difficult and annoying to find all those settings,  Also some of the settings ignore other VS Code specific settings, like ignoring the fact that my VS Code is configured to use spaces instead of tabs, but the code formatter just replace those back to tabs.

**Comment by stamblerre** [comment]
> I opened this issue about the setting: `"go.autocompleteUnimportedPackages": false,`
> it just doesn't work, any time I use the auto complete for a package I haven't imported yet, it just auto formatting all the import section.

Because the language server is still in the alpha state, its settings act separately from the default Go extension settings. This setting does not affect the language server, which will still offer completions for packages you have not yet imported. You can disable this behavior by setting:

```json5
"gopls": {
	"completeUnimported": false,
}
```

We are planning to unify the settings for the extension and `gopls` once `gopls` reaches a stable state - `v1.0`. In the meantime, you can see documentation of `gopls` settings [here](https://golang.org/s/gopls).

> It was difficult and annoying to find all those settings, Also some of the settings ignore other VS Code specific settings, like ignoring the fact that my VS Code is configured to use spaces instead of tabs, but the code formatter just replace those back to tabs.

This is the default behavior of `gofmt`, which comes with the Go distribution and is an industry standard. See https://github.com/golang/go/issues/16256 for more context on this.

**Comment by eladciuraru** [comment]
Thanks for the reply, this works now as expected, so I am closing this issue,
but I have something I would like to add.

I understand the reasoning for separating the settings, but it has a bad effect on users of those tools, and the fact that it is has completely separate key, instead of being a sub key inside the regular go settings, makes it even less intuitive. The first thing I tried was obviously to go to the setting a looking for a key related to the issue, but couldn't find it which was frustrating.

Also, VS Code doesn't seem to recognize the mentioned setting.
