### ISSUE TITLE
feature request: auto install package and deps on save.

### ISSUE THREAD

**Issue by OneOfOne** [Microsoft/vscode-go#338]
Moved from the discussion at https://github.com/mdempsky/gocode/issues/13#issuecomment-220747235

mdempsky's fork of gocode removed the auto install option which causes some issues with stale packages, so I was wondering if there's a way to implement auto install directly in vscode-go.

**Comment by lukehoban** [comment]
Unfortunately this would be quite hard to do in the vscode-go extension.  vscode-go intentionally delegates doing anything that depends on the behaviour of the Go language/build system to Go tools, either those provided natively with the Go distribution or 3rd party tools that themselves operate within the behaviours of the core Go build system.

As a result, vscode-go just doesn't know anything about what the package dependencies look like, or what needs to be built to provide accurate completion lists.  Instead, it delegates this to vscode-go.  

I think that is the right approach, and pushes the logic for understanding Go code into the gocode tool.  Ideally, the common logic in handling go build environments in tools like this would get pushed down further into the Go toolchain so that logic didn't need to exist in gocode either.  But I think that's the direction to push this - not up even higher into all of the IDEs/editors.

/cc @mdempsky.

**Comment by mdempsky** [comment]
@lukehoban To be clear, I don't expect vscode-go to implement this logic itself.  That would just present the opposite problem of putting the logic in gocode: instead of every Go tool having to reimplement rebuild logic, we'd be requiring every editor to reimplement rebuild logic.

Instead, I want to design a new rebuild tool that vscode-go and other editor integrations can use to ensure that gocode, vet, lint, etc. are able to provide accurate analyses.  But since I don't have much experience writing editor extensions, I'm interested in your input on what sort of interface such a tool should provide.

Thanks!

**Comment by ramya-rao-a** [comment]
@mdempsky #673 is currently tracking the idea to use `go build -i` while running build on save to make the subsequent builds on save faster.
`go build -i` would install the dependent packages which would satisfy your request.

@lukehoban Please provide your thoughts on #673

Closing this issue.
