### ISSUE TITLE
Find all References is very slow

### ISSUE THREAD

**Issue by drinktee** [Microsoft/vscode-go#340]
Hellow, I'm a rookie in vscode and have some questions.
I downloaded go tools from https://github.com/golang/tools. Everytime I click 'find all references' , it takes a few seconds to show the results.

vscode version :1.1.1
go version 1.6.2

**Comment by lukehoban** [comment]
We did recently move to use golang's Guru tool to provide Find All References, as it provides a more well maintained foundation than than the previous (https://github.com/redefiance/go-find-references).  

However, Guru is definitely slower.  I expect that's something that would have to be improved in Guru.  I recall seeing some work on improving performance, but not sure how much more progress to expect. 

/cc @alandonovan

**Comment by adonovan** [comment]
I recently changed guru so that it outputs each result as soon as it is available instead of waiting for the complete set before printing the first one.  This makes it much more responsive, though of course if the workspace is very large it may still take a while to run.

Does vscode display guru results in a streaming fashion?  If not, I recommend making it do that.

**Comment by lukehoban** [comment]
Unfortunately `vscode-go` doesn't currently use the streaming results because `vscode`'s UX for find references doesn't support streaming back results.  I expect that's intentional since there are different UX considerations when results may not be complete.  This may be something VS Code could add in the future.

I'm curious though why https://github.com/redefiance/go-find-references was so much faster for this.  Was it cutting some corner in providing results that `guru` is not cutting?  Or is there room to still improve `guru` performance even without relying on streaming results?

**Comment by adonovan** [comment]
Yes, `redefiance` finds all occurrences of a name, including those that resolve to a different declaration, whereas `guru` resolves names precisely using the same algorithm as a compiler.  Since the latter requires type-checking in the general case, it is significantly slower.

**Comment by ramya-rao-a** [comment]
Closing this issue as there is nothing we do in the Go extension for this at the moment. If anyone has any ideas, please drop a comment here and we can re-visit this

**Comment by ramya-rao-a** [comment]
Update: One alternative (if you are not on Windows) is to use the [language server from Sourcegraph](https://github.com/Microsoft/vscode-go/blob/master/README.md#go-language-server-experimental)
