### ISSUE TITLE
New method/var/const in go file won't show up in autocompletion

### ISSUE THREAD

**Issue by davyzhang** [Microsoft/vscode-go#355]
When add a new method in different package other than current file, the autocompletion won't reflect the changes untill I delete the corresponding pkg .a file.

It looks gocode has failed to detect the change or vscode-go doesn't compile as file changes. I am not quite sure if its a problem of gocode or vscode-go.

I have left build-on-save option untouched in configration file as it is:

```
    //-------- Go configuration --------

    // Run 'go build'/'go test' on save.
    "go.buildOnSave": true,

    // Flags to `go build`/`go test` used during build-on-save or running tests. (e.g. ['-ldflags="-s"'])
    "go.buildFlags": [],
```

**Comment by lukehoban** [comment]
I expect this is a `gocode` issue, since vscode-go relies on gocode to trigger builds needed for completion.  

Vscode-go does turn the `autobuild` setting on for `gocode` though, which should cause dependencies to built.  It may well be that it will not rebuild dependencies that are out of date.  There wouldn't be much that `vscode-go` can do about this directly without either fixing/improving this in `gocode` or moving to `guru` instead per https://github.com/Microsoft/vscode-go/issues/288.

**Comment by davyzhang** [comment]
Thanks for your time, I cooked up a workaround by deleting the .a file manually when saving a .go file

```python
#!/usr/local/bin/python3
'''delete .a file '''
import sys
import os

GO_PKG_PATH = os.environ['GOPATH'] + '/pkg/darwin_amd64'

def main():
    path = sys.argv[1]  # dir path
    ext = sys.argv[2]  # current edit file ext
    if ext != ".go":
        return
    pkg_name_base = "/".join(os.path.relpath(path,
                                             os.environ['GOPATH']).split("/")[1:-1])
    if pkg_name_base == "cmd": #cmd dir usually generate command binaries
        return
    print("package base dir %s" % pkg_name_base)
    pkg_name = path.split("/")[-1]
    target_lib_file = GO_PKG_PATH + '/' + pkg_name_base + '/' + pkg_name + '.a'
    print("removing %s" % target_lib_file)
    os.remove(target_lib_file)


main()
`
Its also suprised me that vscode dosen't support Run task on save https://github.com/Microsoft/vscode/issues#2159

But fortunately someone wrote a wonderful extension to help 😄 
https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave
