### ISSUE TITLE
Default settings for launch.json

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#371]
I'm not super familiar with vscode-go. So I just created a GOPATH and spun app my in `$GOPATH/src/app` and ran `code .` from there, installed all suggested Go tooling, restarted vscode, and wrote a simple helloworld Go application in a `main.go` file.

Then I clicked Debug and then the "Start Debugging" button, it never compiled and kept spinning forever until I stopped it and got this error in the debug console:

```
2016/06/30 18:36:18 debugger.go:56: launching process with args: [./debug]
could not launch process: could not fork/exec
``` 

I feel like the defaults can be a little better

![image](https://cloud.githubusercontent.com/assets/159209/16509452/c75cc42c-3ef1-11e6-9ad8-882ca79d58ed.png)

**Comment by lukehoban** [comment]
Sounds like you don't have `dlv` installed correctly.  That error means that Delve is broken - normally it means it's not signed correctly.

`vscode-go` doesn't automatically install Delve for you - since there is no good programmatic way to acquire it.

If you don't have Delve, you should get an error indicated that `dlv` wasn't on your path.

The error you are getting suggests it is on your path but doesn't work.

**Comment by lukehoban** [comment]
Not sure there's much better we could do in `vscode-go` in this case.  The text there tells you the error, and googling it leads directly to the issues in Delve that cause this.

Closing for now - but feel free to reopen if you think there's something that should be changed in `vscode-go` to help here.
