### ISSUE TITLE
dlv not work

### ISSUE THREAD

**Issue by gatspy** [Microsoft/vscode-go#399]
Installation according to the installation document on OSX.
then F5,vs code show error message:Failed to continue: "Cannot find Delve debugger. Ensure it is in your `GOPATH/bin` or `PATH`."
vscode-go version:0.6.39
go version 1.6.3

run dlv debug test.go command in terminal its ok.

**Comment by lukehoban** [comment]
Where is `dlv` installed on your system?  Is it in your PATH or GOPATH\bin?

**Comment by blacktop** [comment]
are you supporting golang and dlv being installed via homebrew?  It doesn't seem to be working anymore.

**Comment by blacktop** [comment]
when I try to debug I just get `could not launch process: could not fork/exec`

**Comment by lukehoban** [comment]
That error indicates that dlv is not installed correctly.  Can you run `dlv debug` from your project dir successfully?

**Comment by m3l7** [comment]
have the same issue, using fedora 23.
I installed dlv using go get and put I have put the go bin/ folder in both GOLANG and PATH.

dlv is working correctly (tried dlv debug in the project folder)

**Comment by blacktop** [comment]
@lukehoban so I also reinstalled delve manually as well as running the brew install and it works now.

However, it seems VERY buggy now and crashes and panics a lot. 

I don't think I have successfully `stepped` once since the upgrade.  However, maybe that is a delve issue and not a vscode-go issue?

**Comment by gatspy** [comment]
the problem sloved, it's my GOPATH setting problems.
i linked an external ssd to my home. then GOPATH linked to this external ssd, but I don't use absolute path,so dlv crash. 
vim-go also has a similar problem.[GoDoc can't work #951](https://github.com/fatih/vim-go/issues/951)

**Comment by m3l7** [comment]
I found out that my problem is specific to linux.
when vscode is started from a launcher, with the .desktop file, no env variables are set.

**Comment by m3l7** [comment]
Solved. I was setting GOPATH variable only for console and not Xorg applications

**Comment by GoBijan** [comment]
For me it was a problem with the dlv version. I installed the latest from master and now it works again.

**Comment by IzakMarais** [comment]
I get the same message: `Failed to continue: "Cannot find Delve debugger. Ensure it is in your 'GOPATH/bin' or 'PATH'.`  on Windows.  Latest versions of delve (via go get) and vscode-go.

Using the GOPATH check in vscode:
`Info: Current GOPATH:T:\Documents\werk\vagrant\shares\sea-server`

Navigating to GOPATH/bin folder shows that delve is there:

```
dir
   Directory of T:\Documents\werk\vagrant\shares\sea-server\bin
...
2016-08-05  11:54 AM        15 894 528 dlv.exe
          
```

**Comment by mbobakov** [comment]
I fix the same issue with 
▶ rm -rf $GOPATH/src/github.com/derekparker 
▶ go get github.com/derekparker/delve/cmd/dlv

Maybe it helps

**Comment by blacktop** [comment]
@lukehoban So I removed dlv from brew and with @mbobakov 's command and then reinstalled with brew and it is giving me the error again `could not launch process: could not fork/exec`, but in the folder running `dlv debug` works just fine.  Is vscode-go not looking were brew installs it?

```bash
❯❯❯ which dlv
/usr/local/bin/dlv
```

**Comment by blacktop** [comment]
The plot thickens !!!

```bash
~/s/g/s/g/m/malice git:master ❯❯❯ $GOPATH/bin/dlv debug
could not launch process: could not fork/exec
~/s/g/s/g/m/malice git:master ❯❯❯ dlv debug
Type 'help' for list of commands.
(dlv) q
```

**Comment by blacktop** [comment]
I think this is because the version that brew signs with the dlv cert is the one it links to `/usr/local/bin` and not the one that was left behind in GOPATH/bin that is not working.  When I removed it (GOPATH/bin/dlv) the vscode-go ext just hung forever.  I am assuming not finding the brew installed one in my PATH?

**Comment by JinWuZhao** [comment]
I encounter this problem, too.  But it works very well at past.

**Comment by MrVegetables** [comment]
I had this problem because my working directory wasn't the same as the directory of my source files. I just had to open the proper source folder and it worked.

**Comment by ramya-rao-a** [comment]
For people who see "Failed to continue: "Cannot find Delve debugger. Ensure it is in your 'GOPATH/bin' or 'PATH'."

- The debugger in the Go extension cannot read GOPATH from the user/workspace settings. You need to specifically set the GOPATH in the `env` property in the lanuch.json

- If your GOPATH was set as env variable outside of VS Code and you didnt have to set GOPATH in user/workspace settings, then debugger can read the GOPATH set as env variable.

For people who see "could not launch process: could not fork/exec",
- this is coming from delve itself.
- some people seeing this error got it fixed by manually installing delve See https://github.com/Microsoft/vscode-go/issues/20#issuecomment-272090465, #269

Closing this issue.
