### ISSUE TITLE
feature request: generate json tags

### ISSUE THREAD

**Issue by mattetti** [Microsoft/vscode-go#433]
@fatih's excellent vim-go has a great feature allowing you to generate struct field tags. The behavior is defined in this section: https://github.com/fatih/vim-go-tutorial#snippets

Select a field, after the type, you type `json` and use tab completion and it generates a json tag.
This is quite an useful feature when creating a lot of structs that marshall to json.

**Comment by fatih** [comment]
This can be done now with the `gomodifytags` tool if wished: https://github.com/fatih/gomodifytags  Here is a demo of it: https://twitter.com/fatih/status/831233941935886338

**Comment by mattetti** [comment]
Thanks @fatih!

**Comment by zmb3** [comment]
I recently added support for `gomodifytags` to go-plus in Atom land.  I imagine this might help guide an implementation for VS Code: https://github.com/joefitzgerald/go-plus/pull/571

**Comment by ramya-rao-a** [comment]
@fatih So from what I could gather from the tweet, you use space separated keys and comma separated options. For static values, you use colon to separate the key and the value

So all of the below would be valid in vim-go ?

- :GoAddTags json xml
- :GoAddTags json,omitempty xml,cdata
- :GoAddTags validate:"gt=1"
- :GoAddTags validate:"gt=1",omitempty

I am asking because I'd like to keep the behavior as similar as possible :)

**Comment by zmb3** [comment]
Sorry to butt in, but in a more graphical editor like code, wouldn't it
make sense to provide some form of UI rather than relying on a well-formed
text command?

**Comment by ramya-rao-a** [comment]
@zmb3 Don't apologize, am always open for talking through design :)

I did see your support for `gomodifytags` in Atom. And while yes, that would be very user-friendly, that kind of ui freedom is restricted for extensions in VS Code.

The most I can play with is an input box or a dropdown. (Anybody who knows otherwise, please chime in)

Therefore I was planning to go with the inputbox which can show up when the command for adding/removing tags is executed.

**Comment by zmb3** [comment]
Ah, that makes sense. I wasn't aware of the UI limitations.

**Comment by mattetti** [comment]
@ramya-rao-a I think the large majority of users will only care about JSON and would want omitempty by default. I think addressing the 80% case the best we can would be the best move here.

Ideally I would love to see that generator option when I right click a strict and when right clicking a strict field.
Other features are more advanced and could be more hidden / harder to get to.

**Comment by ramya-rao-a** [comment]
That was my initial thought as well.

- **Default Behavior**: `Go: Add Tags` and `Go: Remove Tags` adds and removes `json` with `omitempty`
          - Takes care of the 80% scenario that @mattetti mentioned
- **Slightly Customized Behavior**: We can have settings where user can specify the tag and options to add/remove
      - Caters to those who want more than just `json`
- **Final Customized Behavior**: The input box opens prompting for the tag and another input box for options. Or a single input box where user adds a text command just like they do in **vim-go**
      - Caters to those who want different tags/options for different structs in their code and don't want to keep changing their settings for this

The settings can have the below defaults that user can change

- This is following the model which `gomodifytags` takes in parameters
```json
"go.modifytags": {
                 "tags": "json,xml",
                 "options": "json=omitempty, xml=cdata",
                 "promptForTags": false 
           }
```
OR

- This is following the model which `vim-go` works (as far as I could gather from the tweet, @fatih correct me if I am wrong)
```json
"go.modifytags": {
                 "tags": "json,omitempty xml,cdata",
                 "promptForTags": false 
           }
```


Thoughts?

cc @rakyll @campoy My new gopher friends for their thoughts

**Comment by mattetti** [comment]
@ramya-rao-a it looks good, will the option be also available via the right click context menu or only the palette? The reason I'm asking is because as I'm showing features to people I realize most people don't use the palette or use it only for tasks/commands they already know.

**Comment by ramya-rao-a** [comment]
The thing about the right click context menu is that there is very little control around when the menu option shows up. See the [when clause contexts](https://code.visualstudio.com/docs/customization/keybindings#_when-clause-contexts)

So if we do add it, it will always show up whether you are inside a struct or not.

We could add another setting "showInContextMenu" and set the default to true, so that the feature is more visible. 
And people who feel their context menu is getting crowded can turn it off.

**Comment by mattetti** [comment]
@ramya-rao-a is having more control over the context menu something we can champion? I think that's my #1 issue with VSCode. Asking users to use the palette seems very counter intuitive, especially coming from VS Studio. The amount of steps/keystrokes required to access an extension feature is just too much and that results in a lot of features hard to reach or never discovered.

Ideally, there would be a function that an extension could provide to populate the context menu based on the current context. So on right click, the extension gets a call with the when clause context being passed and could return an array of menu items. I believe such as feature would provide a drastic experience improvement for all users.

In the meantime, I would suggest to have the tag generation feature always on the context menu and return an error if the user doesn't have a struct or field selected. It's not ideal but at least it exposes the features to all Gophers and it reduces the complexity to trigger the feature.

I would also suggest to the same thing for "Toggle test file" and "Generate test unit tests for current file".

@rakyll @campoy, what say you?

**Comment by fatih** [comment]
@ramya-rao-a because Vim has very limited UI options (or none), all we have is the command line and commands. Here is our official documentation for the usage inside vim-go: https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt#L673 It explains the usage both for `:GoAddTags` and `:GoRemoveTags`

For example the following command:

```
:GoAddTags json,omitempty
```

currently only works if there is a `json` tag already. So if you in vim-go, if you want to add both the tag and option you have to call the following commands:

```
:GoAddTags json
:GoAddTags json,omitempty
```

The reason for that is that I wanted it to be explicit, so people know it. Another reason is that suppose you have the following struct:

```
type Server struct {
	Name        string `json:"name"`
	Port        int    `json:"port"`
	EnableLogs  bool
	BaseDomain  string
	Credentials struct {
		Username string `json:"username"`
		Password string `json:"password"`
	}
}
```
If you select all lines here and call `:GoAddTags json,omitempty` you end up with:

```
type Server struct {
	Name        string `json:"name,omitempty"`
	Port        int    `json:"port,omitempty"`
	EnableLogs  bool   
	BaseDomain  string 
	Credentials struct {
		Username string `json:"username,omitempty"`
		Password string `json:"password,omitempty"`
	} 
}
```

As you see it didn't add `json` tags to the middle fields. So that's why we don't add `json` by default for the `:GoAddTags json,omitempty` command. It only works for fields who already have `json`.


> So all of the below would be valid in vim-go ?
> :GoAddTags json xml
> :GoAddTags json,omitempty xml,cdata
> :GoAddTags validate:"gt=1"
> :GoAddTags validate:"gt=1",omitempty

Here only the last one is incorrect. If you want to add an option you have to call like the second example the following: `:GoAddTags validate,omitempty`.

**Comment by rakyll** [comment]
```
"go.modifytags": {
                 "tags": "json,omitempty xml,cdata",
                 "promptForTags": false 
           }
```

Should we produce the XML tags if user is not explicitly asking for it? Our broader ecosystem mostly cares about JSON and verbosity makes it harder to maintain the tag literals.

**Comment by ramya-rao-a** [comment]
@fatih thanks for the clarification

@rakyll That was just an example for the settings a user can have. By default, those settings can be

```json
"go.modifytags": {
                 "tags": "json",
                 "options": "json=omitempty",
                 "promptForTags": false 
           }
```

**Comment by tylerb** [comment]
I'll chime in my 2 cents:

Being able to simply open an input box via hotkey or the action palette, then type in the tags I want, would be quick and efficient. If vscode can detect the struct I am working with automatically and apply tags to it instead of me having to type in the struct I want to work with, that would be amazing. 

An example use case could be:

`shift+cmd+p`
`Go: Add Tags`
`(Input box) Add tags to `struct message`: json,db`

Quick and simple. If there was a default specified in the config file, this box could be autopopulated with the default tags. It adds a keystroke for the default case, but far more flexibility and far less hassle for the times you need something different than the default.

**Comment by ramya-rao-a** [comment]
Here is what I have landed on:

* If there is a selection, then the selected lines of the struct will be acted upon
* If there is no selection, then the whole struct under the cursor will be acted upon

**Commands**:
-  `Go: Add Tags` adds tags configured in `go.addTags` setting to selected struct fields. By default, `json` tags are added. 

 - `Go: Remove Tags` removes tags configured in `go.removeTags` setting from selected struct fields. By default, all tags are removed. 
 
**Settings**
- Default for `go.addTags` is 
```json
{
    "tags": "json",
    "options": "json=omitempty",
    "promptForTags": false
}
```
- Default for `go.removeTags`is
```json
{
    "tags": "",
    "options": "",
    "promptForTags": false
}
```
- You can change the above as per your needs. Examples:
         - To add `xml` tags, set `go.addTags` to `{"tags": "xml"}` 
         - To add `xml` with `cdata` option, set `go.addTags` to `{"tags": "xml", "options": "xml=cdata"}`  
         - To add both `json` and `xml` tags, set `go.addTags` to `{"tags": "json,xml"}` 
         - To remove only say `xml` tags, set `go.removeTags` to `{"tags": "xml"}` 
         - To be prompted for tags instead of using the configured ones, set `go.addTags` and/or `go.removeTags` to `{"promptForTags": true}`

**Keyboard Shortcuts:** (these are just examples you can use in your keyboard settings, there will be no shortcuts shipped by default)

- Below will add whatever is configured in `go.addTags` setting
```json
{
        "key": "ctrl+shift+q",
        "command": "go.add.tags",
        "when": "editorTextFocus"
}
```

- Below will add `xml` tags
```json
{
        "key": "ctrl+shift+q",
        "command": "go.add.tags",
        "args": {
            "tags": "xml"
        },
        "when": "editorTextFocus"
}
```

- Below will open an input box where you can provide the tags
```json
{
        "key": "ctrl+shift+q",
        "command": "go.add.tags",
        "args": {
            "promptForTags": true
        },
        "when": "editorTextFocus"
}
```

**Comment by tylerb** [comment]
Beautiful!

**Comment by campoy** [comment]
Hi @ramya-rao-a, sorry I didn't reply earlier!

First of all thanks for all your work on this 😄 

I'm trying to understand what the developer experience would be using the command palette.
In your latest proposal it seems like to add both json and xml struct tags I should do:

1. `cmd+P`
1. Go: Add Tags  // this adds json tags
1. Edit the configuration to replace `"json"` with `"xml"` in `go.addTags`
1. `cmd+P`
1. Go: Add Tags // this adds xml tags

Is this correct? If I set `"promptForTags"` to `true`, will I be able to do the following?

1. `cmd+P`
1. Go: Add Tags // this opens a new dialog
1. In the dialog I type `json xml`

**Comment by ramya-rao-a** [comment]
Hey @campoy, no problem at all

To add both json and xml flag, you can replace `"json"` with `"json,xml"` and then `cmd+p` -> `Go: Add Tags`

OR

You can do what you described (set `"promptForTags": true`) , and when the input box opens up, type in `json,xml` not `json xml`

Basically, I am following the input format for `gomodifytags` instead of the `:GoAddTags` command in `vim-go`

**Comment by campoy** [comment]
Sounds good, @ramya-rao-a!

I am personally a fan of the `promptForTags: true` option, but it's great if there's others.

👍

**Comment by ramya-rao-a** [comment]
Thanks for all your input.

The latest update to the Go extension (0.6.56) has this feature.
Give it a spin.

`Go: Add Tags` command adds tags configured in `go.addTags` setting to selected struct fields. By default, `json` tags are added. Examples:
             -  To add `xml` tags, set `go.addTags` to `{"tags": "xml"}` 
             -  To add `xml` with `cdata` option, set `go.addTags` to `{"tags": "xml", "options": "xml=cdata"}`  
             -  To add both `json` and `xml` tags, set `go.addTags` to `{"tags": "json,xml"}` 

`Go: Remove Tags` command removes tags configured in `go.removeTags` setting from selected struct fields. 
          - By default, all tags are removed. 
          - To remove only say `xml` tags, set `go.removeTags` to `{"tags": "xml"}` 
          -  To be prompted for tags instead of using the configured ones, set `go.addTags` and/or `go.removeTags` to `{"promptForTags": true}`

`Go: Add Tags` is also surfaced when you right click anywhere inside a Go file. This (surfacing of commands in the menu) is experimental at the moment.

To include more commands in such a way, play with the new experimental setting `go.editorContextMenuCommands`

**Comment by mattetti** [comment]
I gave it a quick try and it seems to work well. We might be able to tweak the error messages as we collect more feedback but I think it's going to be a very much appreciated feature.

The context menu is also really great, amazing job!

**Comment by tylerb** [comment]
Love this! Thanks @ramya-rao-a!

**Comment by campoy** [comment]
This is great, thanks for the goode job @ramya-rao-a 👏 

One little detail, when I select the whole struct (including the `type Foo struct {` line, the tool fails saying `selection is not inside a struct`.

I wonder if it would be possible to detect that the whole selection is still a `struct` and apply successfully.
Maybe this is an issue to be solved on @fatih's tool side?

**Comment by campoy** [comment]
Btw, I gave @ramya-rao-a a shoutout with a nice screencast 😄 

https://twitter.com/francesc/status/847914033747435520

**Comment by ramya-rao-a** [comment]
@campoy aww thanks :) I should take some lessons in creating screencasts/gifs from you

Regarding, selecting the whole struct, it works for me. Example, see below

![image](https://cloud.githubusercontent.com/assets/16890566/24569462/12b7da8c-161b-11e7-9136-69b85becf3a2.png)

But if a select one extra blank line in the bottom or a comment at the top, then I get the same error like you mentioned.

**Comment by fatih** [comment]
Just tried on my end:

![gomodifytags](https://cloud.githubusercontent.com/assets/438920/24569560/b0056f5c-1634-11e7-810a-8f044e2e5e53.gif)

it's very strict on how you select the lines. But on vim-go, you can just call :GoAddTags if the cursor is inside the struct and it'll apply to all struct automatically (because there is no selection. Not sure if vscode supports that as well :)

**Comment by ramya-rao-a** [comment]
@fatih Yes vscode supports that (place cursor anywhere inside struct, and magic happens) as well

**Comment by campoy** [comment]
Turns out I was selecting the empty line below too ... maybe it could trim
space around the selection?

**Comment by ramya-rao-a** [comment]
That would be ideal. I'd prefer the trimming happen on `gomodifytags` side though.
We could do it from the editor's side, but then every editor adopting `gomodifytags` will have to do the trimming.

@fatih thoughts?

**Comment by fatih** [comment]
You're passing line numbers to `gomodifytags`, which then checks the boundaries on each struct node in the AST. So there is no concept of content, if you say pass 5,12 and line is 12 a whitespace, I can't detect it. However maybe we can change the range of the boundary detection to be not that to be too much strict. 

@campoy can you give me a concrete, simple example that contains a struct and the selection you made that gave the error? Let me check if I can do something there.

**Comment by campoy** [comment]
Yeah, Given the program:

```go
 1 | package main
 2 |
 3 | type Foo struct {
 4 |     Bar int
 5 | }
 6 |
 7 | func main() {}
```

If I select from lines `3` to `5` it works, but if by mistake I include `2` or `6` the operation fails.

**Comment by ramya-rao-a** [comment]
@fatih 

>So there is no concept of content

Yes, in that case, it makes sense for the editor to do some checks if it can

**Comment by fatih** [comment]
Ok it's possible to move this to gomodifytags but requires some new complicated additions. 

I think I have to decide how much complexity I want to move, either to the person that's using it (they have to be careful selecting structs, which adds additional burden to the brain while computing the correct lines and selecting them :)) or to the tool itself (which has to compute all possibilities and select the correct lines). 

I'll started now changing the tool so it takes care of human mismatches. I need to add new tests so it's extensively covered and also doesn't break old tests :)

**Comment by ramya-rao-a** [comment]
If its complex, then I'd suggest its not worth absorbing the change into the tool.

Its fairly easy for editor's to check that there are no empty lines in the beginning and ending of the range of lines that it passes to the tool

**Comment by fatih** [comment]
@ramya-rao-a I've added it now and it passes the tests. Seems like it just adds some boilerplate. The change is backwards compatible and only improves the current  situation. I'm going to notify once I've merged it.

**Comment by mattetti** [comment]
Just a quick note to let you know how happy I am to see you all working together to make the life of our gophers better :)🕺💃😎 thanks a lot 💚💚💚

**Comment by fatih** [comment]
Fixed now with: https://github.com/fatih/gomodifytags/pull/11 

I had to delete code to add this feature :D I've added first couple of lines and deep dived into interval and segment trees. And then realized "Hey, why don't you just remove that damn check function". And voila, works like a charm! 

go get it and it should work without any problem. Thanks for the feedback :)

**Comment by ramya-rao-a** [comment]
@fatih 

> I had to delete code to add this feature

Love it :) There should be t shirts with that message
