### ISSUE TITLE
Cmd hover info is mushed with hover info

### ISSUE THREAD

**Issue by nii236** [Microsoft/vscode-go#439]
#424 solved a problem that I've been having for awhile but now there is other unusual behaviour.

- Hovering shows the docstring as well as the func signature which is correct.
- Holding Cmd and hovering shows the source of func (including lines that spill into the following func), then it shows the docstring then it shows the func signature.

I can't seem to get a decent screenshot working because the screenshot hotkey turns off the hover docs. I hope my description is good enough.

**Comment by lukehoban** [comment]
This is mostly intentional given the current way that VS Code chooses to present this stuff.  But it does indeed look a bit noisy.  

If we removed the preview of the definition location source code, that would align the behaviour with that TypeScript shows in VS Code, but I think the complaint about smushing things together still applies there, and I think the preview of source location is useful.  

Not sure what option that VS Code supports would be better than current.

/cc @egamma 

<img width="628" alt="screen shot 2016-08-20 at 5 58 57 pm" src="https://cloud.githubusercontent.com/assets/223467/17834667/ceec49d4-66ff-11e6-894f-fab33cc135c0.png">

**Comment by egamma** [comment]
There should be a '...' separator when there is more source between the source preview  and the signature information.

![image](https://cloud.githubusercontent.com/assets/172399/17888334/c7ec5b1a-692a-11e6-8958-d8d8774b32ca.png)

**Comment by ramya-rao-a** [comment]
This got fixed in VS Code 1.5.0
