### ISSUE TITLE
Debugger not running and showing no errors on OSX

### ISSUE THREAD

**Issue by nakiya** [Microsoft/vscode-go#530]
I'm using OSX Capitan 10.11.6. Go extension version 0.6.44.

Installed delve with brew.
Followed the instructions.

I just created a hello world program, tried to run from the debugger. When I hit the 'run' button, the progress indicator keeps scrolling, but nothing happens. No errors in the debug console either. The program runs fine when run with delve from the terminal.

settings.json

```
// Place your settings in this file to overwrite default and user settings.
{
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.buildTags": "",
    "go.buildFlags": [],
    "go.lintTool": "golint",
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.coverOnSave": false,
    "go.useCodeSnippetsOnFunctionSuggest": false,
    "go.formatOnSave": true,
    "go.formatTool": "goreturns",
    "go.formatFlags": [],
    "go.goroot": "/usr/local/go",
    "go.gopath": "/Users/duminda/go",
    "go.gocodeAutoBuild": false
}
```

launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "/Users/duminda/go",
            "env": {},
            "args": []
        }
    ]
}
```

**Comment by ramya-rao-a** [comment]
@nakiya the program attribute should point to the package you are trying to debug.

You have set it to "/Users/duminda/go" which I am guessing is where you installed Go instead of path to your project

For example, if you are trying to debug the hello project at https://github.com/golang/example/
you should point the program property to `<your-gopath>/src/github.com/golang/example/hello`
Another easy way to do it is to use the ${workspaceRoot}

**Comment by voigt** [comment]
I've got exactly the same issue. Also installed delve via brew.

```
$ pwd
/Users/cv/golang/src/github.com/voigt/main
$ cat main.go
package main

import "fmt"

func main() {
	fmt.Printf("Hello, world.\n")
	fmt.Printf("Hello, world1.\n")
	foo()
	fmt.Printf("Hello, world2.\n")
	fmt.Printf("Hello, world3.\n")
}

func foo() {
	bar := "Bar!"
	fmt.Println(bar)
}
```

`launch.json`:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Local",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "/Users/cv/golang/src/github.com/voigt/main",
            "env": {},
            "args": []
        }
    ]
}
```

* nothing in debug console
* its not possible to stop "debugging"; Killing the window is helping.
* `${workspaceRoot}` doesn't change anything.
* [red break](https://cloud.githubusercontent.com/assets/2982698/20248052/7348bb24-a9dc-11e6-8542-b8aef5a496fb.png) points turn [grey](https://cloud.githubusercontent.com/assets/2982698/20248053/74f9c8e6-a9dc-11e6-8b63-94f7c79f76c8.png) (unverified breakpoint)

**Comment by ramya-rao-a** [comment]
@nakiya Do you still have problems after updating the `program` attribute to point to the right folder?

@voigt I tried you code, launch.json and the same folder structure, and debugging works for me.

When you say you see nothing in debug console, do you mean you see no errors or you see **nothing at all**

Because, the minute delve is fired up by the Go extension, the debug console shows the output from delve. Below is an example:
![image](https://cloud.githubusercontent.com/assets/16890566/22384593/e7b726bc-e483-11e6-8bb4-9d11647ad2ba.png)

**Comment by ramya-rao-a** [comment]
@voigt As per your launch.json, you dont have `showLog` set to true.

There is another issue #651 where users have seen that when `showLog` is not set to true, nothing happens.

So here are a few things you can try

- Add `"showLog":true` to your `launch.json` file and try again.
- Check your delve version and use the latest (0.12.1)

Closing this issue as @nakiya's problem was the wrong "program" attribute and @voigt's problem was the missing `showLog` attribute
