### ISSUE TITLE
Adopt formatOnSave changes

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-go#540]
Since VS Code now has the `editor.formatOnSave`-setting and the `onWillSaveTextDocument`-event, [this code](https://github.com/Microsoft/vscode-go/blob/master/src/goMain.ts#L208) should be revisited. I'd recommend to remove it and to rely on the built-in `formatOnSave` feature or to use the new event. Both will prevent unnecessary fs-operations and reduce the risk for endless write-event-write loops. 

See https://code.visualstudio.com/updates#_format-on-save, Microsoft/vscode#12449, and Microsoft/vscode#239 for more details

**Comment by ksmithut** [comment]
Can that `editor.formatOnSave` be applied on a per-language basis? I would love that setting for `go`, but not for `javascript`

**Comment by ramya-rao-a** [comment]
@jrieken In VS Code 1.6 only formatters implementing `DocumentRangeFormattingEditProvider` get to use the `editor.formatOnSave`. The Go extension formatter implements `DocumentFormattingEditProvider` which I see that we are working on for VS Code 1.7

Can you confirm?

**Comment by jrieken** [comment]
Yeah - I have fixed a bug for the Oct release that makes sure we honour Document and DocumentRange formatters.

**Comment by ramya-rao-a** [comment]
great, will wait for the next release then

**Comment by thnt** [comment]
I think you should keep `go.formatOnSave` until Microsoft/vscode#13547 has been resolved

**Comment by dbudworth** [comment]
agreed on it needing to be a language specific thing.
All go editors format on save as it's expected by the community that you have ran your code through "go fmt"

that is not expected by folks in other languages in general.  If I formatted javascript on save, i'd have a lot of really annoyed co-workers.

As it stands, I basically can't use vscode as my go editor as I'm so used to format-on-save that I don't even think of formatting.

And, being a child of the DOS era, I habitually save as I move around looking at files.  So having javascript code that I have no intention of changing get reformatted as a side effect of 25 year old muscle memory is kind of a non-starter.

**Comment by ramya-rao-a** [comment]
Current State: The adoption of `editor.formatOnSave` was reverted in 0.6.49

**Comment by jrieken** [comment]
why?

**Comment by ramya-rao-a** [comment]
@jrieken `editor.formatOnSave` saves all files on save. There has been feedback from the community that they prefer formatting just go files on save rather than all files.
Since `editor.formatOnSave` doesn't add any benefits over `go.formatOnSave` for the users at the moment, this has been reverted.
If and when we have a way to apply editor settings at file type level, this will be revisited.

**Comment by ramya-rao-a** [comment]
Now that `editor.formatOnSave` can be configured per language, we should re-visit this.

Things to do
- Update `goFormat.ts` to use `stdin` to pass file contents to formatting tools instead of working on the file on disk. There are 2 issues with using `stdin` that need to be fixed first though:
      - #613 Format removes imports of vendored packages in use
      - #630 goreturns fails to consider global variables in package
      
- Deprecate `go.formatOnSave` in favor of `editor.formatOnSave` and suggest Go users to use 
    ```
     ["go"]: {
         "editor.formatOnSave": true
      }
     ```

**Comment by ramya-rao-a** [comment]
@wader has started looking into this in #1069

**Comment by ishanray** [comment]
`editor.formatOnSave` makes gofmt take almost a second to finish.

**Comment by ramya-rao-a** [comment]
@ishanray as compared to?

**Comment by ishanray** [comment]
@ramya-rao-a Otherwise it takes very less. Almost unnoticeable. I can look into it further if required.

**Comment by ramya-rao-a** [comment]
That's ok. We cannot rely on the `editor.formatOnSave` until we figure out the blocking issues with `goreturns` as described in https://github.com/Microsoft/vscode-go/issues/540#issuecomment-314006031

**Comment by ramya-rao-a** [comment]
@jrieken I am finally getting around to adopting `editor.formatOnSave` for the Go extension after resolving the blockers. I had 2 questions for when a registered format provider takes more than the allowed 750 ms
- I recall you mentioning that after a few times of the formatter taking more than 750ms, the formatter will not be called again. Is that still the case? I don't see anything to this affect in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/electron-browser/mainThreadSaveParticipant.ts
- Is there any way a user can know that the reason they don't see any formatting changes is because the provider is taking too long? I don't see any console logs to this affect.

**Comment by ramya-rao-a** [comment]
The latest update to the Go extension (0.6.70) has adopted the `editor.formatOnSave` setting
