### ISSUE TITLE
import generated by "Go Add Import" command disappear after save

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode-go#561]
While smoke testing:

go version 1.7.1
OS X 10.11.6
vscode-go 0.6.46

![go](https://cloud.githubusercontent.com/assets/4033249/19742971/31475cc6-9b7c-11e6-8b4d-163cfeffb710.gif)

**Comment by ramya-rao-a** [comment]
This is by design.

The default formatting tool is `goreturns` which adds missing imports and removes unused imports.
And formatting is run on save (you can disable it)

Which is why you see that your import keeps disappearing on save.

Either turn formatOnSave off or change the formatting tool to gofmt

**Comment by octref** [comment]
Oh I see. Thanks!
