### ISSUE TITLE
Signature Help and Quick Info do not show function comments for unexported functions 

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode-go#567]
[Smoke testing](https://github.com/Microsoft/vscode-go/wiki/Smoke-Test), Windows

In the example below, I would expect the "hello" comment to appear in addition to just the function signature.
![image](https://cloud.githubusercontent.com/assets/762848/19744622/23bd4dc0-9b83-11e6-8e5f-747c50b8b90c.png)

This works fine for cases like stringutil.Reverse
![image](https://cloud.githubusercontent.com/assets/762848/19744722/913ae61e-9b83-11e6-8c63-8f469f03fa9a.png)

**Comment by ramya-rao-a** [comment]
Functions from shared libraries seem to show the comments, but not the ones in main.go which is a special go file meant for executables vs shared code

**Comment by ramya-rao-a** [comment]
We use `godoc` to get the function documentation to display in Signature Help and Quick Info on hover.

`godoc` is meant to show documentation for exported members of packages.

Which is why no member in main.go or unexported members of packages do not get the documentation info.

Replacing bug label with enhancement

**Comment by ramya-rao-a** [comment]
In the latest update of the Go extension (0.6.50), we now support the use of `gogetdoc` for **Goto/Peek Definition, Hover info and Signature Help** features. Add `"go.docsTool": "gogetdoc"` to your setting to enable the use of `gogetdoc` and that should fix this issue.
