### ISSUE TITLE
Add support for Symbol Search

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Microsoft/vscode-go#57]
I could not get it working for any go project so far. 

![image](https://cloud.githubusercontent.com/assets/159209/11320309/0bf6d174-9095-11e5-9d7f-bae6bd47c6ae.png)

Repro:

```
git clone https://github.com/ahmetalpbalkan/wagl.git $HOME/gopath-wagl/src/github.com/ahmetalpbalkan/wagl
export GOPATH=$HOME/gopath-wagl
cd $HOME/gopath-wagl/src/github.com/ahmetalpbalkan/wagl
export GO15VENDOREXPERIMENT=1
code .
```

then `⌘T`, type stuff, no results.

**Comment by lukehoban** [comment]
This is a Code feature which is not yet enabled in the Go plugin.

The interface that needs to be implemented is this one:

```TypeScript
    /**
	 * The workspace symbol provider interface defines the contract between extensions and
	 * the [symbol search](https://code.visualstudio.com/docs/editor/editingevolved#_open-symbol-by-name)-feature.
	 */
	export interface WorkspaceSymbolProvider {

		/**
		 * Project-wide search for a symbol matching the given query string. It is up to the provider
		 * how to search given the query string, like substring, indexOf etc.
		 *
		 * @param query A non-empty query string.
		 * @param token A cancellation token.
		 * @return An array of document highlights or a thenable that resolves to such. The lack of a result can be
		 * signaled by returning `undefined`, `null`, or an empty array.
		 */
		provideWorkspaceSymbols(query: string, token: CancellationToken): SymbolInformation[] | Thenable<SymbolInformation[]>;
	}
```

I'm sure that one of the Go tools can provide the information needed for this.

**Comment by shesuyo** [comment]
try @main
not #main

**Comment by lukehoban** [comment]
@shesuyo Yes - the `@main` syntax uses the `DocumentSymbolProivder` which finds symbols in the currently active document.  The `WorkspaceSymbolProvider` would make it possible to search symbols across the entire workspace.

**Comment by newhook** [comment]
Alan Donovan said with respect to this:

basically, if you want accurate type information for all symbols, you need to run the Go type checker, go/types (or the frontend of an existing Go compiler); anything else is at best a heuristic.  The type checker can take input two ways: from source and from compiler export data.  To load, parse, and type-check an entire program from source, you can use the golang.org/x/tools/go/loader package, but beware that for the next few months it will continue to use the similar but older golang.org/x/tools/go/types package instead of the standard type checker.  If all you need is package-level symbols, the type checker can be run in a mode in which, for speed, it does not analyze function bodies.  To load symbols from binary export data, you can use the go/importer package (or the older and slightly different versions in the x/tools repo).

Two caveats: First, files that import "C" are strictly speaking not Go source code as they require cgo preprocessing.  The loader package does this, and go/types ingests the output of this preprocessing step.   Second, some files are included in the build only on certain platforms or architectures, either because they contain //+build tags or because they have a file name like foo_linux.go, for example.  All existing analysis tools essentially pick a single configuration (e.g. amd64 linux) and pretend the other files don't exist; this is a definite weak spot.  An IDE may have to do better than this, but modifying go/types to type-check all configurations at once would be "non-trivial".

**Comment by newhook** [comment]
I realized that with my work on godef I have a mostly working implementation of this, so working this further :)

**Comment by lukehoban** [comment]
@newhook Great!

**Comment by zippoxer** [comment]
Wasn't this solved by github.com/Microsoft/vscode-go/pull/142 ?
