### ISSUE TITLE
import code completion is... too complete

### ISSUE THREAD

**Issue by mousetraps** [microsoft/vscode-go#572]
[Smoke testing](https://github.com/Microsoft/vscode-go/wiki/Smoke-Test), Windows

type `import fmt`, code completion appears
![image](https://cloud.githubusercontent.com/assets/762848/19748249/59f27840-9b95-11e6-97d3-ac8fbedcce21.png)

Pressing enter here now results in an extra "import fmt":
![image](https://cloud.githubusercontent.com/assets/762848/19748229/4712bbe0-9b95-11e6-8eff-f12f221d5777.png)

**Comment by ramya-rao-a** [comment]
The autocomplete for unimported packages shouldnt appear when part of import statements like this. This is a bug

**Comment by ramya-rao-a** [comment]
Same thing happens in the package statement as well

**Comment by ramya-rao-a** [comment]
Once https://github.com/Microsoft/vscode/issues/18485 is implemented, we can stop suggesting the unimported packages when the cursor is inside a string or comment or import block etc.

**Comment by ramya-rao-a** [comment]
Re-opening as the current fix will not work for multi line imports

**Comment by ramya-rao-a** [comment]
The latest update (0.6.56) to the Go extension has the fix for package statement and single line imports.

Multi line imports still has the issue

**Comment by ramya-rao-a** [comment]
Now that there is active development on an official language server for Go via [gopls](https://github.com/golang/go/wiki/gopls) which will provide the auto-completion feature as well, there is no further planned work in the auto-completion feature that is coming directly out of the extension.

This issue is being closed in favor of having the auto-completion feature from the language server which will not have the same problem.

For more on language server integration with this extension, please see [Go language server](https://github.com/microsoft/vscode-go#go-language-server)

To go a feature request for gopls, use the [Go issue tracker](https://github.com/golang/go/issues/new?title=x%2Ftools%2Fcmd%2Fgopls%3A%20%3Cfill%20this%20in%3E)
