### ISSUE TITLE
Add command for clearing coverage highlight

### ISSUE THREAD

**Issue by zmb3** [Microsoft/vscode-go#601]
The `Go: test coverage in current package` command is great, but once you run it there's no way to clear the coverage.

Can we add a command to clear the coverage highlighting?  Or even change the existing command to a toggle command?

**Comment by ramya-rao-a** [comment]
That would be a nice feature. PRs are welcome!

**Comment by brandonblock** [comment]
Just wanted to add that I'd warmly welcom this feature.
I've never worked with TypeScript, but may be willing to give it a shot

**Comment by gabrielgatu** [comment]
I was having the same problem the other day and I've made a search of the pull requests for test-coverage hoping for an easy solution to clear highlights and I've found this: https://github.com/Microsoft/vscode-go/pull/143, i.e. just type something and the highlight will disappear (leaving here for further reference).

The toggle idea is a good one (my first try), however since then it would be a good idea to include inside the readme a section for test coverage, explaining how it works and the current solution for removing highlight.

What do you think?

**Comment by ramya-rao-a** [comment]
@gabrielgatu I agree that this needs to be documented, but I wonder if README is the right place for it. It is already so huge and has a lot of content about set up

#596 was created to track adding details about the features of this extension, how to use it, tips and tricks etc.

I'd say wiki would be the right place.

**Comment by ramya-rao-a** [comment]
The command `Go: Test Coverage In Current Package` is renamed to `Go: Toggle Test Coverage In Current Package` and it does exactly what the name suggests. 

This change is out in the latest update (0.6.60)
