### ISSUE TITLE
Golang 1.7.3 & Go language 0.6.49,when I input "import "fmt"",this line is been deleted automatically

### ISSUE THREAD

**Issue by zmkhp** [Microsoft/vscode-go#624]
When I input "import "fmt"",the keyword "import" was been tag unknown.After ENTER,this line was been deleted.As shown as the attachments.
I have try #441 ,it can't work.
Thanks!
![image](https://cloud.githubusercontent.com/assets/19316751/20391139/0c2fa0c2-ad0d-11e6-9d20-95b3ed51ffd9.png)
![image](https://cloud.githubusercontent.com/assets/19316751/20391150/17073834-ad0d-11e6-95a9-7f849aa20cba.png)

**Comment by ramya-rao-a** [comment]
@zmkhp 

Does the import line disappear on save?
Do you have any code that is using the `fmt` package?

If you havent used the `fmt` package, but only imported it, then formatting tool removes it by design.

The default formatting tool is `goreturns` which adds missing imports and removes unused imports.
And formatting is run on save (you can disable it)

Which is why you see that your import keeps disappearing on save.

Either turn formatOnSave off or change the formatting tool to gofmt

**Comment by ramya-rao-a** [comment]
We use `gocode` for autocomplete and it does not support keywords. So `impor` will not suggest `import`

**Comment by zmkhp** [comment]
@ramya-rao-a Thanks for your answer.
The import line disappear when I input ENTER to a new line at the first,not on save and haven't used it.
And I find these appearances as the follow:
a.If firstly enter "import ("fmt")" and then "import "fmt"",the last line doesn't disappear
b.If firstly enter "import "fmt"",this line will been deleted

I try to rec my operations as a attachment.

**Comment by ramya-rao-a** [comment]
Can you share your settings?
Do you have autosave on?
Does it happen when you change your formatting tool to `goftmt` ?

**Comment by zmkhp** [comment]
![image](https://cloud.githubusercontent.com/assets/19316751/20452708/b9ef33fa-ae4b-11e6-8038-cef5fa872d4f.png)
This is my settings from plugin suggests.
If anyone is fault,I correct it.
Thanks!

**Comment by ramya-rao-a** [comment]
You have `files.autoSave` enabled which means your file keeps getting saved automatically after a particular delay. 
Since you have `go.formatOnSave` enabled as well, every time your file gets saved, formatting is run on it.
Formatting tools like `goreturns` and `goimports` remove import statements if the imported package is not used in the code.
This is what is happening in your case.

Hope this helps

Workaround is to either change the formatting tool to `gofmt` or disable `files.autoSave` or disable `go.formatOnSave`

**Comment by ramya-rao-a** [comment]
The below is a note from the ReadMe for this extension

>Note: Users may want to consider turning Auto Save on in Visual Studio Code ("files.autoSave": "afterDelay") when using this extension. Many of the Go tools work only on saved files, and error reporting will be more interactive with Auto Save turned on. If you do turn Auto Save on, you may also want to turn format-on-save off ("go.formatOnSave": false), so that it is not triggered while typing.

**Comment by zmkhp** [comment]
@ramya-rao-a Thanks a lot.I Got it!

**Comment by ramya-rao-a** [comment]
Great! Happy Coding!
