### ISSUE TITLE
Extension cannot find go binary after last upgrade

### ISSUE THREAD

**Issue by ccirello** [Microsoft/vscode-go#629]
![image](https://cloud.githubusercontent.com/assets/138827/20439759/73ab219e-adbd-11e6-8aaa-2240612972ee.png)

Both user and workspace configurations possess `go.goroot` set.

**Comment by ramya-rao-a** [comment]
What platform are you on?

Can you check if you have the `go` file in your <GOROOT>/bin folder ?

**Comment by ccirello** [comment]
> What platform are you on?
MacOS Sierra

> Can you check if you have the go file in your /bin folder ?

Yes, the go binary is there.

**Comment by ramya-rao-a** [comment]
The only change we made around that area in the latest update is to use `fs.statSync` instead of `fs.existsSync`

https://github.com/Microsoft/vscode-go/commit/1687b3cf7009e2e02f7398218992d5e00816c5eb

Do you see any errors in the console? Run `Developer: Toggle Developer Tools` to see the console

**Comment by ramya-rao-a** [comment]
And while you are in the console can you run `process.env['GOROOT']` ?

**Comment by ccirello** [comment]
![image](https://cloud.githubusercontent.com/assets/138827/20450735/07b413c0-adf3-11e6-8ddb-a060c2b52aa8.png)

**Comment by ramya-rao-a** [comment]
And `/Users/uldericofilho/.gvm/gos/go1.7.3/bin` has the `go` file?

**Comment by ccirello** [comment]
yes

**Comment by ccirello** [comment]
Actually, I am not sure it is related to this problem... But often, if I start vscode from shell (`code .`) and open a reconfigured workspace (containing custom `go.goroot` and `go.gopath`) - it simply ignores my configuration. I must close vscode, open from the launch bar, open the workspace and eventually it works.

It is as if it ignores my environment variables.

**Comment by ramya-rao-a** [comment]
The custom `go.goroot` and `go.gopath` in your settings file overrides the ones that are the environment variables in the shell from where you open using `code .`

Below is the code that is run to get the path to the go run time. When this returns null/undefined/empty string, the message you see is shown.
Looking at this code, it is impossible that the returned value will ever be null/undefined/empty string.
So I am truly baffled.

![image](https://cloud.githubusercontent.com/assets/16890566/20451242/02d4cabc-adac-11e6-9042-2cc5017a405a.png)

Can I ask you to clone the code for this extension and run it locally to get to the bottom of this issue?
Its pretty simple and I can walk you through it.

I'd really like to get to the root cause of this problem

**Comment by ramya-rao-a** [comment]
@ccirello Problem solved?

**Comment by ccirello** [comment]
Magically solved by itself! :( I could not reproduce it.

**Comment by ramya-rao-a** [comment]
oh well.. alright
Happy Coding!

**Comment by bobvanluijt** [comment]
For what it's worth, I had the exact same issue. Also the `Magically solved by itself!` part. I believe that opening the settings and saving (without changing) solved it.
