### ISSUE TITLE
[Format Tool] Error on save - editor becomes unpredictable

### ISSUE THREAD

**Issue by mkatanski** [Microsoft/vscode-go#631]
When I save opened `Go` source file, VSCode editor behave strange.

![vscode_go_error](https://cloud.githubusercontent.com/assets/8478375/20456190/70fe9b70-ae70-11e6-8930-5e6d4d9124cd.gif)

I can't see any error in `Chrome Developer Tools`. After I click another tab, it stops and go back to normal. However its annoying and makes impossible to code in `Go`. 

It looks like some kind of infinite loop. I guess it is related to `go format tool` because when I switch option `"go.formatOnSave"` into false, it is working normally. I have also set `"editor.formatOnSave: false"` as it was recommended. Its shame because format tool in Go is one of the nicest thing.

I have tried also to turn off `"editor.formatOnType"` option without any luck.

**Versions that I use:**
- VSCode - Version 1.7.1 (1.7.1)
- Go extension - Version 0.6.48 - 10th November, 2016
- Go - version go1.7.3 darwin/amd64

**Comment by ramya-rao-a** [comment]
@mkatanski Sorry to hear about the inconvieniece.

Do you have `files.autoSave` enabled?

**Comment by mkatanski** [comment]
No, `files.autoSave` is disabled. I tried with every possible value

**Comment by ramya-rao-a** [comment]
There was only one net change in the formatting area in the last few updates.

It was to pass the file contents to the formatting tool via stdin instead of the formatting tool working on the file on disk. This was made to enable formatting to work on unsaved changes.

I have reverted the change in the master branch (it has caused a few other issues).

Since I can't repro your case,  can you try to install the extension from source and see if it fixes the issue for you?

Steps to do that would be:

- Uninstall the Go extension from VS Code. 
- Clone the extension code: `git clone https://github.com/Microsoft/vscode-go`
- `cd vscode-go`
- `npm install`
-  `npm install -g vsce` 
-  `vsce package`
-  `code --install-extension Go-0.6.49.vsix`

You should see a message `Extension 'Go-0.6.49.vsix' was successfully installed!`
Close all instances of VS Code, open a new one and see if you still have the issue.

**Comment by ramya-rao-a** [comment]
@mkatanski I have reverted the change around the formatting logic in the latest update(0.6.50). Can you update and tell me if that fixes the issue for you?

**Comment by mkatanski** [comment]
Hi, sorry i was extremely busy so i didn't have time to do that before. Anyway, I've updated the extension and still the problem occurs. :(

**Comment by ramya-rao-a** [comment]
Just to eliminate external factors, can you  disable other extensions you have and comment all your user settings and try again ?

**Comment by mkatanski** [comment]
Ok, I've disabled some extensions and all my user settings and now it is even more weird: [error GIF](https://s12.postimg.org/8iqe8577h/VSCode_Go_error2.gif)

Extensions that I disabled:
* Advanced New File
* Babel ES6/ES7
* Flow Language Support
* jsx
* Mono Debug
* Path autocomplete
* Path intelisense
* Relative path
* TSLint
* VSCode Flow
* VSCode icons

**Comment by ramya-rao-a** [comment]
That looks like indents are being added and removed consistently.
You are indenting using spaces.
Can you change that to tabs?

I believe something external to the Go extension is interfering/conflicting with the Go formatting.

**Comment by ramya-rao-a** [comment]
Can you also try the insiders build of VS Code? http://code.visualstudio.com/insiders.

**Comment by ramya-rao-a** [comment]
@mkatanski Any updates?
Do you still see this issue with all the other extensions disabled?

**Comment by mkatanski** [comment]
@ramya-rao-a Hi, sorry for late answer but yes, I know what was causing the problem. Like u said, it was problem with some extension (somehow I've missed it before). Its `Whitespace v.0.0.4` extension which I even don't need :)

Anyway thank You for great feedback and good luck :)

**Comment by ramya-rao-a** [comment]
Thanks for getting back with that info @mkatanski . Happy Coding!
