### ISSUE TITLE
Disable tool install suggestions

### ISSUE THREAD

**Issue by rightfold** [Microsoft/vscode-go#633]
vscode-go suggests I install a bunch of tools, such as golint.

> The "golint" command is not available. Use "go get -v github.com/golang/lint/golint" to install.

How do I turn off these suggestions without installing the tools?

**Comment by ramya-rao-a** [comment]
The Go extension depends on individual Go CLI tools to provide various features.
Right now, there is no way to turn off the suggestions altogether.

But in certain cases, there are workarounds.
Say in your case you don't want to install `golint`, then add `go.lintOnSave:false` to your setting.
That will switch off the linting feature and so the need to install `golint`.

You can do the same for formatting by `go.formatOnSave:false`. But you will still get the message to install the formatting tool when you try to format the document yourself.

I am curious to understand your scenario though. Do you want to turn them off, because you want to install the tools later or you do not want to install them at all?

**Comment by ramya-rao-a** [comment]
@rightfold you have upvoted my answer, so I am assuming that you are happy with the answer.
Therefore closing this issue.

**Comment by Lywei** [comment]
how to do ？

**Comment by ramya-rao-a** [comment]
@Lywei how to do what?
