### ISSUE TITLE
Support for multiple paths in GOPATH (especially for vendoring)

### ISSUE THREAD

**Issue by flosch** [Microsoft/vscode-go#64]
In order to provide support for dependency management tools like [gb](https://getgb.io/) it's necessary to support colon-seperated GOPATH like this:

`/home/foo/gotools:/home/foo/dev/myproject:/home/foo/dev/myproject/vendor`

The Go tools are working correctly with this kind of GOPATH, but vscode-go seems to be confused (since it's simply ignoring this GOPATH).

**Comment by lukehoban** [comment]
@florian This should be fixed with a few changes over the last few days (see also #10, #19, #54).  

Can you make sure you have the latest version of `vscode-go` installed (`0.6.11`)?

If you do - could you provide:

1. Your `go env`
2. The result of executing `Go: Get current GOPATH` in VS Code
3. Anything else notable about your environment

**Comment by flosch** [comment]
You're right. Upgrading worked for me. Thanks!
