### ISSUE TITLE
Incorrect import by auto-complete when pkgname != last part of pkg path

### ISSUE THREAD

**Issue by AlekSi** [Microsoft/vscode-go#647]
That's a continuation of #613. Get code from https://github.com/AlekSi/vscode-bug and then edit main.go as shown:

![2016-11-24_16-11-38](https://cloud.githubusercontent.com/assets/11512/20599753/e87a5236-b260-11e6-8fca-847d2cf44c6f.png)

Two things are wrong after hitting Enter:
1. It adds `sarama.v1` to code. As I explained in #613, the package name is `sarama`, not `sarama.v1`. Package name != last part of import path.
2. It adds `vendor/gopkg.in/Shopify/sarama.v1` which is incorrect import path. `vendor/` is [treated differently](https://golang.org/cmd/go/#hdr-Vendor_Directories) by Go toolchain. goreturns does the right thing:
```diff
$ goreturns -d src/bugger/cmd/bugger/main.go
diff src/bugger/cmd/bugger/main.go gofmt/src/bugger/cmd/bugger/main.go
--- /var/folders/fl/c3xvc0tj1js__3jnrnbkjll40000gn/T/gofmt002523159	2016-11-24 16:22:09.000000000 +0300
+++ /var/folders/fl/c3xvc0tj1js__3jnrnbkjll40000gn/T/gofmt440158346	2016-11-24 16:22:09.000000000 +0300
@@ -1,5 +1,7 @@
 package main

+import sarama "gopkg.in/Shopify/sarama.v1"
+
 func main() {
 	sarama.V0_10_0_0
 }
```

**Comment by ramya-rao-a** [comment]
@AlekSi There are 2 separate things at play here.

- Auto-complete completes `sara` to `sarama.v1` instead of `sarama`. This will happen to all packages from gopkg.in due to the versioning supported there. 
- `vendor` included in the import path. This will happen only when the `vendor` folder is the immediate child of $GOPATH/src.

For the first issue, I have a PR out: #659

For the second, I am curious. Is it very common to have the vendor folder right under #GOPATH/src ?
Most of the projects I have seen, have the vendor folder under the Go project.

**Comment by AlekSi** [comment]
> Auto-complete completes sara to sarama.v1 instead of sarama. This will happen to all packages from gopkg.in due to the versioning supported there.

It has nothing to do with `v1` and gopkg.in. For example, try with `go-xerial-snappy`:

![2016-11-29_18-37-06](https://cloud.githubusercontent.com/assets/11512/20716382/133f2a86-b663-11e6-903e-a675b0263dd3.png)

![2016-11-29_18-37-19 2](https://cloud.githubusercontent.com/assets/11512/20716386/160f646a-b663-11e6-80e0-7cdb876a03c8.png)

As mentioned several times before, package name is defined by `package` clause in source code, not by last component of import path. cb0d2bc is incorrect.

**Comment by ramya-rao-a** [comment]
@AlekSi First off, thanks for your patience.

I now understand that the last element in the import path need not always be the package name. It is just convention for predictability's sake that most of the time the package name is the same as the last element in the import path.

Now, the list of packages that appear in the auto-complete comes from the output of the `gopkgs` tool which simply returns the import paths to all the packages in $GOPATH/pkg folder. The extension tries to fetch the package name from these import paths and has no knowledge of the source code of the packages themselves.

`go list all` on the other hand can return package names along with import paths as well.
`gopkgs` was preferred over running `go list all` as the latter was slow in comparision 

> The difference of `go list all` and `gopkgs` is that `go list all` looks for go packages in your $GOPATH/src while `gopkgs` looks in your $GOPATH/pkg. As a result of this, only importable packages that have been installed (either by `go get` or `go install`) are listed by `gopkgs`.

We could try out a few options and compare performance
- Use `go list -f '{{ .Name }} {{ .ImportPath }}' all`
- Use `gopkgs` and feed the output to `go list -f '{{ .Name }} {{ .ImportPath }}' space-separated-output-from-gopkgs`
- Update `gopkgs` to do second option above and return both name and import path

Until then, I would keep the fix in https://github.com/Microsoft/vscode-go/commit/cb0d2bc29a0c9ee1929c1a89781ef8c740447d92 because it atleast takes us one step closer to the ideal solution where versioned packages from gopkg.in will get the package name without the version number.

Thoughts?

**Comment by AlekSi** [comment]
I think a long-term solution would be to import packages normally, without relying on gopkgs (which does not work correctly in this case), and keep them in memory in the long-running process (gocode? Go language server? something new?).

And thank you for all your work on this extenstion. I'm in love with it. ❤️

**Comment by ramya-rao-a** [comment]
Language server is a good idea here.

For now, I have a working solution where I am thinking of doing the below
- `go list -f {{.Name}};{{.ImportPath}} all` runs once on extension activation (like when you open a new VS Code window) 
- Form mapping between package import path and package name from the above output. 
- Use this for the auto-completion

**Comment by ramya-rao-a** [comment]
The fix for this issue is now out in the latest update (0.6.63) to the Go extension

Thanks for your patience @AlekSi, I know this took a while :)
