### ISSUE TITLE
Rename/Refactor package would be nice

### ISSUE THREAD

**Issue by DasJott** [microsoft/vscode-go#649]
I want to move a file with certain structs and functions to another package. Unfortunately there are many references which are not refactored automaticly.

As an enhancement, that would be great.

**Comment by leaxoy** [comment]
Tip: use `gomvpkg` in `golang.org/x/tools/cmd/gomvpkg` maybe a good idea. 
More explorations needed. Once I have time, I will take a look at it.

**Comment by tallstoat** [comment]
If there can be other refactor options as well like "select some piece of code & click on extract method" etc, it would make refactoring & cleaning up golang codebases very easy.

**Comment by ramya-rao-a** [comment]
We did experiment using [godoctor](https://github.com/godoctor/godoctor) for this and you can try the commands `Go: Extract to function` and `Go: Extract to variable`.

These are not hooked into code actions yet as they haven't seen to be very reliable 

Now that there is active development on an official language server for Go via [gopls](https://github.com/golang/go/wiki/gopls), this issue is being closed in favor of the refactor feature that will be implemented using the language 

For more on language server integration with this extension, please see [Go language server](https://github.com/microsoft/vscode-go#go-language-server)

To go a feature request for gopls, use the [Go issue tracker](https://github.com/golang/go/issues/new?title=x%2Ftools%2Fcmd%2Fgopls%3A%20%3Cfill%20this%20in%3E)

**Comment by ramya-rao-a** [comment]
@stamblerre If you don't have an issue tracing this feature request, please consider creating one
