### ISSUE TITLE
Find All References erroneously reports No Results.

### ISSUE THREAD

**Issue by tagatac** [Microsoft/vscode-go#652]
VS Code 1.7.1, Go extension 0.6.49. Looks like a regression of #346.

**Comment by PotterDai** [comment]
Same issue here.

**Comment by ramya-rao-a** [comment]
Its working fine for me. Do you see any errors in the console? 

Does it not work in certain Go projects/packages or all Go code?

We use `guru` for the `Find all references` feature. Can you run it in command line and see if it gives results where as VS Code doesn't?

**Comment by tagatac** [comment]
No errors in the console.

I have not seen it work in any projects on my computer. It has worked in our project on my colleague's computer.

guru also fails:
```
$ guru callers dbhandler.go#647
guru: no packages specified for pointer analysis scope
```

**Comment by ramya-rao-a** [comment]
Try `guru referrers`

**Comment by tagatac** [comment]
The first call to `guru referrers` gave [this error](https://github.com/Microsoft/vscode-go/files/617009/guru.txt). Subsequent calls hang using 70% CPU for several minutes until SIGINT.

**Comment by ramya-rao-a** [comment]
@PotterDai Do you see similar error while running `guru referrers` in the command line?

@tagatac This is a problem with the `guru` tool itself. Can you log an issue at https://github.com/golang/go/issues?

**Comment by PotterDai** [comment]
Hey, sorry for the later reply.
My guru always reporting "guru: no identifier here" no matter where I point it to.

guru referrers user.go:#38
guru: no identifier here
guru referrers user.go:#47
guru: no identifier here

**Comment by tagatac** [comment]
I'm not sure what the issue was, but deleting and reinstalling everything in my $GOPATH fixed this for me. @PotterDai it looks like you may be specifying byte offsets that don't correspond to identifiers. You can use vim to easily identify byte offsets: http://stackoverflow.com/a/1484076/5403337

**Comment by PotterDai** [comment]
Hmmm, I found my issue. After digging into "vscode-go/src/goPath.ts", it seems it's because I didn't put slash at the end of my GOPATH, thus generating wrong bin files path.

@ramya-rao-a  it might be a good idea to check if there is slash at the end of the GOPATH and if not just add it, since it seems to be easily mistaken. = )

Anyway, my issue is solved.

**Comment by tagatac** [comment]
FWIW, my GOPATH doesn't end in a slash either, but that wasn't breaking guru for me.

**Comment by PotterDai** [comment]
It seems goPath.ts will read $GOROOT, $PATH, $GOPATH. And as long as one of the paths lead to the correct guru executable, the guru will run correctly.

I was trying to reproduce my situation. By setting all $GOROOT, $PATH, $GOPATH as well as in "UserSettings, go.path" to values without slash in the end, vscode will show "no results", and by adding slash to the end of path at any places mentioned above, the problem is gone. So that leads to my assumption that there might be something wrong with the slash.

**Comment by ramya-rao-a** [comment]
@PotterDai `Find all References` works for me when I add `go.gopath` in the settings without the ending slash. Which platform are you on? I tested on Mac and Windows.

We use `path.join` to create the path from GOPATH and don't concat strings manually. `path.join` would add the necessary forward/backward slashes based on the platform.

When you remove the ending slash, is `Find all References` the only feature not working for you?

**Comment by PotterDai** [comment]
Hmmm, it's getting strange.
I'm using macOS 10.12.1

Please check my screenshot.

GoPath with slash:
![screenshot 2016-11-28 17 18 15](https://cloud.githubusercontent.com/assets/3758951/20688436/bcd612c4-b58e-11e6-9803-3b18f5cbcafe.png)

GoPath without slash:
![screenshot 2016-11-28 17 17 41](https://cloud.githubusercontent.com/assets/3758951/20688437/bcde08c6-b58e-11e6-9778-c6eed1df4756.png)

Yep, the other functions seem all working correctly.

**Comment by PotterDai** [comment]
OK, finally I think I found the problem!
It's not about slash at all. 

That's because I happen to have 2 gopaths:
"/Users/potterdai/go"
"/Users/potterdai/GoProject"
The first one happen to be the substring of the second one.
"canonicalizeGOPATHPrefix" mistakenly takes the first gopath as the workspace, and changes the filename from "/Users/potterdai/GoProject/src/Test/test.go" to "/Users/potterdai/goProject/src/Test/test.go".

It is a very specific bug. =)

@ramya-rao-a   Do you think it is a good idea that in "canonicalizeGOPATHPrefix" function, check if each workspace ends with a slash or backslash, if not add one to the end?  If so I think I will make a PR to make the change.

**Comment by ramya-rao-a** [comment]
@PotterDai I just arrived at the same conclusion, and came here to reply and you already found it :)

Just checking for trailing slashes might not be enough. Consider the case of nested workspaces. As in `/Users/me/Gocode` and `/Users/me/Gocode/my/coding/workspace`

The right solution would be to loop through all workspaces and instead of returning on the first match, keep looking until you find the longest match.

Something similar was done here: https://github.com/Microsoft/vscode-go/blob/master/src/goImport.ts#L57

And PRs are welcome

**Comment by PotterDai** [comment]
OK, PR #658 just submitted. =)

**Comment by ramya-rao-a** [comment]
The latest update 0.6.51 has this fix. Happy Coding!
