### ISSUE TITLE
gorename path error - file not found when git diff in windows path 

### ISSUE THREAD

**Issue by sdwarwick** [Microsoft/vscode-go#665]
attempting to perform a "rename symbol", I am getting the following error:

---
File not found (\\"C:\Users\<valid path>\file.go")
---

this happens on workspace or individual file settings.  
I've tried changing the environment variables to remove the C: but everything stops working then.

note the backslash before the quote.    
cannot seem to find any other settings that impact this.

---
windows 10
VSCODE 1.7.2
NODE 6.5
extension version: 0.6.50 - 21st November, 2016

**Comment by ramya-rao-a** [comment]
Can you share your GOPATH if you have set any in the settings ? If not then share the GOPATH from your environment variables.

`gorename` and `guru` are the 2 tools we use that expect the filepath passed to them to have the exact casing and slashes (forward/backward) as the GOPATH being used.

Also, can you share the complete error message?  Does it start with "Cannot rename due to errors..." ?

**Comment by sdwarwick** [comment]
the complete error message is as shown.  I did a copy/paste.  it is preceded by a red "error" box
GOPATH:
C:\Users\xxx\Google_Drive\golang;C:\Users\xxx\Google_Drive\projects\project name\application

note that "project name"   is a directory name which has a real space between two words as shown.  
the actual files are in a sub-directory  of application:

application\src\mypackagename/*.go

**Comment by ramya-rao-a** [comment]
If you didnt see the error message `Cannot rename due to errors:` then that means that the `gorename` tool ran successfully and the Go extension has returned the file edits to make to VS Code. VS Code in turn was not able to find the file and so you see the error `File not found ()`

Do you see any errors in the console? Open `Developer: Toggle Developer Tools` to see the console.

Does this happen on all of your Go projects?

**Comment by sdwarwick** [comment]
from the debug console:

```
File not found (\"C:\Users\xxx\Google_Drive\projects\directory name\application\src\pkgname\afile.go")

/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:90 

```

all of my projects are under this directory structure, and are all experiencing this problem.

**Comment by ramya-rao-a** [comment]
The slash before the quotes is the problem. I know you mentioned that earlier, but the error message you pasted didnt have the slash, so I didnt make the connection.

Since I can't repro this, can you download the code for the Go extension and debug locally?
I can walk you through it, it is very simple.

Close all instances of VS Code and run the below in your command prompt

```
git clone https://github.com/Microsoft/vscode-go
cd vscode-go
npm install
code .
```

- VS Code will open with the source code for the Go extension. 
- Put a breakpoint in line 51 in the file `gorename.ts`
- Press F5, the new VS Code window will open. Open your Go project in this VS Code window
- Rename something, the breakpoint will be hit. See what is the value for `filePatch.fileName`

**Comment by sdwarwick** [comment]
this is great - I have followed your instructions.   the filePatch.fileName has the slash in front..

"\"C:\\\\Users\\\\xxx\\\\Google_Drive\\\\projects\\\\dir name\\\\application\\\\src\\\\dname\\\\fname.go\""

would it be helpful to set up a chat to work through this?

**Comment by sdwarwick** [comment]
I have moved the breakpoint up to buildTags.. it is returning the following:
"\"\""

**Comment by ramya-rao-a** [comment]
buildTags doesn't matter. You say you see the slash in the front, but what you pasted doesn't have it. Are you sure?

>""C:\\Users\\xxx\\Google_Drive\\projects\\dir name\\application\\src\\dname\\fname.go""

Add a breakpoint at line 26 and check what is the value of `document.fileName` and `filename`. 
Are you on gitter ? If not, you can join https://gitter.im/Microsoft/vscode-go and we can chat there to work through this.

**Comment by sdwarwick** [comment]
the forward slash was actually there, but github mistook it for markup!!!   I changed it to "code" so it would show up..  sorry

**Comment by ramya-rao-a** [comment]
No problem, can you share what are the values of `document.fileName` and `filename` when you add breakpoint at line 26?

**Comment by ramya-rao-a** [comment]
Updating this thread from the discussion in gitter:

This happens when the file path has space in it.
In such cases, the diff output from `gorename` is in the below format

--- \"C:\\Users\\folder with space\\file.go\"

If there was no space, then the diff output would be

--- C:\\Users\\folder_without_space\\file.go

The `parsePatch` method from the diff module retains the `\`, causing rest of the issue discussed in previous comments

**Comment by ramya-rao-a** [comment]
This needs to be fixed upstream in the `diff` module.

Until then, we can add a fix in the Go extension to strip the initial `\` when there is a space in the file path.

**Comment by sdwarwick** [comment]
It has been shown that when git for windows is installed in the standard windows path,  the vscode-go integrated gorename function breaks due to a slight difference in output from other diff implementations.  

changes to support a diff string with quotes around the file path is requested.

**Comment by rotemdan** [comment]
@sdwarwick @ramya-rao-a 

I had this exact problem. Thanks to your research it quickly led to the reason: I had the Cygwin tools bundled `diff` executable in my `PATH`. I renamed the `diff.exe` executable to `diff.exe.disabled` and the problem was solved. So in my case it wasn't actually related to Git for windows. 

This leads me to wonder, if there are multiple incompatible versions of `diff` utilities. Is it really safe to [use just any executable that's available in the `PATH`](https://github.com/Microsoft/vscode-go/blob/ffacf14d3291f637f0a6289e8e516ffd89a09aab/src/diffUtils.ts#L12)?

Perhaps a setting entry like `go.useExternalDiffTool` (boolean) or even `go.diffToolPath` (string) should be required to be set by the user for the external utility to be used?

**Comment by sdwarwick** [comment]
I'm thinking that any hidden dependency on other tools in the path is just bad practice.  this has been sitting out here without action for a while now.

**Comment by ramya-rao-a** [comment]
I'll pick this up for the next update in March

**Comment by ramya-rao-a** [comment]
Logged https://github.com/kpdecker/jsdiff/issues/171 for the root cause.
Fixing from our end via #866

Sorry this took a while :(

**Comment by ramya-rao-a** [comment]
The latest update (0.6.56) to the Go extension has this fix.
