### ISSUE TITLE
Golang 1.7.4 breaks navigation outside package

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode-go#688]
_From @entonio on December 14, 2016 18:35_

- VSCode Version: 1.7.2
- OS Version:

Steps to Reproduce:

1. Install go 1.7.4
2. Try to navigate to a symbol outside the current package
3. Doesn't do anything

I've tried going back to Go 1.7.3 and navigation started working again.
I've tried placing `"go.docsTool": "gogetdoc"` in the user settings but found no difference.

_Copied from original issue: Microsoft/vscode#17189_

**Comment by ramya-rao-a** [comment]
Is it only the navigation that is not working?
Can you try other features of the extension like
- autocomplete
- hover info
- signature help
- linting
- formatting

Do you see any errors in the console? Run `Developer: Toggle Developer Tools` to see the console

**Comment by ramya-rao-a** [comment]
@entonio Do you still see this issue? Can you answer the questions in the earlier comment?

**Comment by ramya-rao-a** [comment]
@entonio I have go1.7.4 on my Mac OS X El Capitan (10.11.6)
And all the Go extension features work as expected.

Closing this issue as we havent heard back from you with answers/details to the questions posed in the previous comments.

Please drop a comment here if you still see issues.

**Comment by entonio** [comment]
Hi. I'm sorry for the delay, I'm not always here.

I'm using Sierra and have just now came across the problem again (upgrading go 1.7.3 to 1.8).

None of the features worked.

I then downgraded to 1.7.3 and the problem went away.

Then I `brew switch`ed to 1.8 again, and things kept working.

I don't know what the issue may be. Unfortunately, I only opened the developer tools the second time, and I haven't been able to replicate the issue. But I haven't rebooted yet, so who knows whether something hangs on some leftover temp file from 1.7.3.

If it happens again, I'll let you know.

**Comment by entonio** [comment]
Weird.

Since 1.8 appeared to be now ok, I deleted go 1.7.3 from the Cellar and things stopped working again. This is consistent with the experience above: brew upgrade did have 1.7.3 deleted, and it was only my reinstalling it that it was back on the filesystem again.

Clicking an aliasing of a function from another package:
```
[Extension Host] Error: Command failed: /Users/.../go/path/bin/godef -t -i -f /Users/.../FSExt/fsdb/main.go -o 347
godef: no identifier found

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Hovering over a package name:
```
extensionHost.ts:282 [Extension Host] Error: Command failed: /Users/.../go/path/bin/godef -t -i -f /Users/.../FSExt/fsdb/main.go -o 333
godef: no declaration found for common.FSDB.Server

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Clicking a function call:
```
extensionHost.ts:282 [Extension Host] Error: Command failed: /Users/.../go/path/bin/godef -t -i -f /Users/.../FSExt/fsdb/main.go -o 365
godef: no declaration found for common.FSDB.Folder

    at ChildProcess.exithandler (child_process.js:218:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
````


Then, I simply restored go 1.7.3 to the filesystem... and things started working, even without restarting VSCode.

This puzzles me. It's not a matter of not finding `godef`because 'no declaration found' looks like an output of it (but is it?). It's not a matter of path precedence, since neither 1.7.3 nor 1.8 are on the path, rather 1.8 is symlinked by homebrew. Yet, VSCode will work if and only if go-1.7.3 is present on the filesystem.

```
$ ls -l $(which go)
lrwxr-xr-x  1 ...  admin  23 15 Mar 19:40 /usr/local/bin/go -> ../Cellar/go/1.8/bin/go
$ ls -l /usr/local/Cellar/go
total 0
drwxr-xr-x  9 ...  admin  306 19 Out 18:39 1.7.3
drwxr-xr-x  9 ...  admin  306 15 Mar 18:51 1.8
```

**Comment by entonio** [comment]
The `go version` runs consistent to what I've selected using `brew switch`.

Running `Go: Install Tools` seems to have solved the issue. I've deleted `go 1.7.3` and everything keeps working. I still don't understand the behaviour I was having, but then again I don't know how `go def` is looked up by the extension, so that may be it.

Thank you very much, @ramya-rao-a. If the issue resurfaces I'll let you know. But I'm confident!

**Comment by ramya-rao-a** [comment]
Usually what we have seen when one changes the version of Go being used is that a recompilation of all the dependent Go tools is needed (hence the suggestion to `Go: Install Tools`)

I am looking into ways the extension can determine that the Go version being used is changed, so that it can prompt the user to do a recompile.

Glad that you are unblocked, Happy Coding!
