### ISSUE TITLE
code completion fails on large code base

### ISSUE THREAD

**Issue by joeblew99** [Microsoft/vscode-go#701]
The problem is that on a large code base the go extension fails when doing code completion.

see here: https://github.com/therecipe/qt/issues/163#issuecomment-269618861

You can easily see the bug by pulling this git repo, and then go to an example like:
https://github.com/therecipe/qt/tree/master/internal/examples/quick/tableview

try to add code and you will see it fail !

**Comment by mattetti** [comment]
@joeblew99 can you try shutting down vscode, start gocode manually and run an autocomplete command against your project to see if it fails there too?

**Comment by ramya-rao-a** [comment]
Also, what platform are you on?
@mattetti recently found that on Windows, `gocode` is slow when the setting `go.gocodeAutoBuild` is enabled.
Can you try with `go.gocodeAutoBuild` disabled?

**Comment by joeblew99** [comment]
@ramya-rao-a 

I am on OSX. I changed it to false and it seems to have helped.

Now, I can get code lookup on types. Thats a big help for me thanks.

But, I still cant get "go to definition" on any types. When i hover over "New QQMLApplication" in https://github.com/therecipe/qt/blob/master/internal/examples/quick/tableview/tableview.go#L27, it saying "Loading..." for 1 second, and then does nothing.

**Comment by joeblew99** [comment]
@ramya-rao-a 

Please see see here: therecipe/qt#163, last comment by @therecipe.
It seems that a fix to godef works.

Not sure if the VSCODE golang extension is using this version though, so worth trying on your side too ?

**Comment by mattetti** [comment]
@joeblew99 VScode-go uses the following pkgs:

`
  gocode
  gopkgs
  go-outline
  go-symbols
  guru
  gorename
  godef
  goimports
  golint
  gotests
`

If the `godef` improvement gets merged in, you can `go get -u` the package to get the latest update or within VSCode, open the command palette (cmd+p) and `go: Install Tools` to update all the dependencies at once.

Would you mind closing this issue since I don't think there is much VSCode can do to make things much better in this specific scenario.

**Comment by joeblew99** [comment]
i doubt the godef improvement will get merged.
