### ISSUE TITLE
Go to Definition and the vendor folder

### ISSUE THREAD

**Issue by mcardosos** [Microsoft/vscode-go#712]
Is there a way for `Go to Definition` and `Peek Definition` to look into the vendor folder of my project instead of wherever dependencies land when using `go get` ? It would be pretty useful for me :D

**Comment by mattetti** [comment]
this is related to https://github.com/Microsoft/vscode-go/issues/700

**Comment by ramya-rao-a** [comment]
@mcardosos For this already works.
Example: 

- `go get github.com/godoctor/godoctor`
- `go get github.com/willf/bitset`

Now I have the `bitset` package both in $GOPATH/src and in $GOPATH/src/github.com/godoctor/godoctor/vendor`

When I open the godoctor workspace and run `Go To Definition` on a bitset type, I end up in the one inside the vendor folder.

We use `godef` by default for the `Go to Definition` feature. Do you have the latest for `godef` ?

**Comment by ramya-rao-a** [comment]
Closing this issue as we havent heard back from the OP and Go to definition works as expected with the vendor folder.

**Comment by mcardosos** [comment]
I completely forgot about this :I
Yes it works :D Thanks!

**Comment by RoarkeRandall** [comment]
Hi, I'm new to using the vendor folder. I no longer use `go get`, and only have packages in stalled in the vendor folder. When I use go to definition it won't find the source because it only checks the `src/` directory.  Is there a way we could have it search `workspace/vendor` as well? 

Having to `go get` wouldn't be a valid workaround because I could have several different versions of a package being used by different go workspaces.

**Comment by ramya-rao-a** [comment]
@RoarkeRandall Does godef return the right definition location when you use it from commandl line?
