### ISSUE TITLE
Feature request: Add "," after inserting "}"

### ISSUE THREAD

**Issue by atombender** [microsoft/vscode-go#738]
Say I have this:

```
expr := expressions.Function{
  Arguments: []expressions.Expression<caret>
}
```

If I type `{`, VSCode will automatically insert `}` for me, which is great:

```
expr := expressions.Function{
  Arguments: []expressions.Expression{<caret>}
}
```

But this isn't valid Go code, and it'd be nice if we could get a trailing comma here. It gets especially annoying if I press Enter, where the end `}` will be correctly intended, but now I have to move down to insert the missing comma:

```
expr := expressions.Function{
  Arguments: []expressions.Expression{
    <caret>
  }
}
```

The Go extension should be able to recognize that it can insert the comma.

**Comment by mattetti** [comment]
Well, this is a bit more complicated than it sounds, take for instance this counter example:

```golang
if err != nil {
```

In this case, vs-code does what is expected. There are lots of other examples like that, for instance declaring a type, function etc... So to be able to implement the feature you are asking for, we would need to have enough context to know the intent of the parenthesis. Doable, but more really straightforward. Do you know of a tool which could give us such context?

**Comment by ramya-rao-a** [comment]
The Go extension doesn't have Go language smartness. It uses a collection of tools to achieve most of the core features. The {} completion you see comes from VS Code itself based off of https://github.com/Microsoft/vscode/blob/master/extensions/go/language-configuration.json

So at the moment, this is not feasible, unless we use a powerful language server which would know the context of where the cursor is and if the comma is needed or not. 

But even then, the closest API that the language server can use to make this happen would be the completion items. So you may type `{`, VS Code completes it to `{}` with the cursor in the middle, and completion item suggests a comma which you can choose.

Which defeats the purpose I feel. Because if you are going to use a keystroke to choose an option from the completion items, you might as well have typed the comma yourself.

Will keep this open to see if anyone else has any good ideas.

**Comment by atombender** [comment]
Yep, I see the challenge. Does it really not have access to the Go AST at that point? The syntax highlighting knows exactly what semantic context you're in, so it seems like a bit of a missed opportunity if nothing can take advantage of the same information.

I'd assume/hope that VSCode's automatic `{}` insertion (or other things like quote insertion, for example) was based on semantic information, but it sounds like it's purely textual?

Could something like this become possible if there were a Go language server that used the standard language server protocol?

**Comment by ramya-rao-a** [comment]
https://github.com/Microsoft/vscode/blob/master/extensions/go/syntaxes/go.json is the syntax we use for Go. It is based off of the one from https://github.com/atom/language-go

The syntax is not aware of composite literals which is when we need the [trailing comma](https://dave.cheney.net/2014/10/04/that-trailing-comma) I believe.

Therefore, I think we need to depend on the AST to make this happen.

It might be possible with a language server that uses the LSP.

And guess what, Sourcegraph is already working on one, which we hope to use in the Go extension as an experimental feature in the upcoming update.

**Comment by atombender** [comment]
That's great. Looking forward to it.

**Comment by ramya-rao-a** [comment]
Closing this issue as we now have an official Go language server and an [issue tracker](https://github.com/golang/go/issues/new?title=x%2Ftools%2Fcmd%2Fgopls%3A%20%3Cfill%20this%20in%3E) for it as well

cc @stamblerre
