### ISSUE TITLE
Args ignored when debugging?

### ISSUE THREAD

**Issue by kylebrandt** [Microsoft/vscode-go#74]
This all normally works fine (just playing with the debugger). It seems like the command line arguments are not being passed?

![image](https://cloud.githubusercontent.com/assets/1692624/11349951/1ce392a6-91fd-11e5-9d09-e401f3b8ac9e.png)

**Comment by lukehoban** [comment]
Do you have the latest version of the Go extension installed?  There were some fixes to this since the initial release.  

There is also a fix in 13b73dc01a54d1ef48c83929119e191aa91cb2fb that is not yet in a released update of the extension, but I don't think that should impact your particular case.

**Comment by kylebrandt** [comment]
I updated my extension via: F1 -> Install Package -> Go (List packages did not show an option to update that I saw). Updating the extension followed by the restart of VSCode now shows the args as I would expect.

Thanks!
