### ISSUE TITLE
command 'go.tools.install' not found

### ISSUE THREAD

**Issue by robsonpeixoto** [Microsoft/vscode-go#755]
`Go: Install Tools` show this error.

```
workbench.main.js:94 command 'go.tools.install' not founde.doShow @ workbench.main.js:94

```

**Comment by ramya-rao-a** [comment]
This would happen if the Go extension is not activated yet.
Can you open a Go file (it is one of the actions that will activate the extension) and try again?

**Comment by robsonpeixoto** [comment]
Thanks @ramya-rao-a. But why?

**Comment by ramya-rao-a** [comment]
Good point, we could add this command to the list of [activation events](https://github.com/Microsoft/vscode-go/blob/master/package.json#L56) so that it activates the extension if the extension is not activated yet.

And while doing so, it would be a good idea to evaluate rest of the commands and see if they should be added as well

**Comment by ramya-rao-a** [comment]
Fixed by https://github.com/Microsoft/vscode-go/commit/de706decc43b59c9c9ced45690acefb2ef596f67

All commands except `Go: Current GOPATH` and `Go: Install Tools` need an active editor with a go file to be present. When an active editor has a go file, the extension is already activated.

**Comment by ramya-rao-a** [comment]
This feature is now available in the latest update (0.6.54) to the Go extension.

**Comment by robsonpeixoto** [comment]
Thanks :) tested and working like a charm :)

**Comment by olekthunder** [comment]
For all guys who are stuck with command 'go.tools.install' not found promlem on windows. 
Check if `%GOPATH%\bin` is in your PATH enviroment variable. 
After half and an hour I finally figured out that PATH is unchanged if you try to change it like `set PATH=%PATH%...`. You need explicitly change it in your system settings.  (I don't know why)
I'm writing this because noone wrote this before in any related topic.

**Comment by avoidik** [comment]
Also had a problem with `GOPATH` and `GOROOT` variables. `GOPATH` should be set to an existing folder where you would like to have all the `pkg` (go packages) to reside, and `GOROOT` where you have your binary distribution installed.

Another subtle here is to open project FOLDER with vscode and then install requirement dependencies with CTRL+SHIFT+P > Go: Install/Update tools, if you open just one go-file the dependencies will not install.
