### ISSUE TITLE
Go To Implementation

### ISSUE THREAD

**Issue by AlekSi** [Microsoft/vscode-go#771]
[VS Code 1.9](https://code.visualstudio.com/updates/v1_9) introduced Go To Implementation command. Go plugin should support it.

**Comment by nochso** [comment]
To get someone else started because my TypeScript is weak: the guru tool can handle this. It's already being used by this extension to find references.

To search GOPATH for implementations of an interface (can be slow):
`guru -scope ... -json implements io.go:#3799`
..where the 3799th byte is the start of the name of an interface definition. It returns JSON with paths and positions to the found implementations.

**Comment by codmajik** [comment]
Hi @ramya-rao-a, @AlekSi 

 I took a swing at this and got a working version here:
https://github.com/codmajik/vscode-go/commit/3bf018bab0b86ccf16aeefb6286cab6a8f63e8aa

as @nochso said, it is excruciatingly slow and vscode seems to be expecting a single result else it doesn't do anything.

There is one reason you am not sending a push request and that is because [registerImplementationProvider](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4278) and
[ImplementationProvider](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L1671) are missing in the vscode-languageclient library (atleast what is currently deployed on npm). I manually overwrote my local copy with one from vscode repo directly for it to work.

This may completely be un-usable.

Cheers!!!

**Comment by ramya-rao-a** [comment]
@codmajik That was quick!

You can get the latest vscode.d.ts by updating the "engines" field in the `package.json` file of the Go extension. Right now it is pointing to `^1.8.0` change that to `^1.9.0` and you will be able to get the the new APIs

Can you try using the `-scope` flag like @nochso suggested and pass the workspace root as scope?

**Comment by codmajik** [comment]
@ramya-rao-a, `guru` expects `-scope` to be a go package, so setting it to the workspace root may not work.

I can try to be clever by figuring out the package, like so:

- using the selected file ($HOME/mygopath/src/github.com/mycurrentproject/somespace/morepkg/my/face.go) look for a directory whose name looks like a domain eg: github.com
- then go 1 level down still based on the filepath. eg: github.com/mycurrentproject/
- try using that as the package: -scope github.com/mycurrentproject/...

because go enforces folder structure it may works most of the times.

warning: this may completely be needless

Q: should it be restricted to interfaces because `guru` go both ways. From concrete to interface and visversa

**Comment by nochso** [comment]
@codmajik [go list](https://dave.cheney.net/2014/09/14/go-list-your-swiss-army-knife) might be what you're looking for:

> The default invocation of `go list` returns the name of the import path that represents the directory you are currently in, or the package path you provide.

However that would mean running another external command. I'll try to have a look at the implementation of `go list`. Hopefully I can piece together what the official way to detect the pkg path is.

**Comment by ramya-rao-a** [comment]
Won't `${workspaceRoot}/...` work?

**Comment by codmajik** [comment]
@ramya-rao-a it won't; `${workspaceRoot}/...` would be `/home/codmajik/gopath/src/github.com/codmajik/servicerouter/...`  what is expected is `github.com/codmajik/servicerouter/...`

I have been busy would get back to this in a few days.

**Comment by Zignd** [comment]
I think the current version of the extension already implements this feature. Am I right @ramya-rao-a?

**Comment by ramya-rao-a** [comment]
@Zignd I think you are referring to the "Go to Definition" feature

This one is about clicking on an interface and getting list of places where the interface has been implemented.

**Comment by Zignd** [comment]
@ramya-rao-a Oh, you're right. Sorry, my mistake. :sweat_smile:

**Comment by jackie-qiu** [comment]
@codmajik ${workspaceRoot} strip the $GOROOT/src?

**Comment by codmajik** [comment]
@jackie-qiu ${workspaceRoot} is the full path of the folder opened in explorer. It is not computed.

**Comment by ramya-rao-a** [comment]
@codmajik So what you need is the import path. The same is needed for running `go build` and we computed the import path this way: https://github.com/Microsoft/vscode-go/blob/0.6.61/src/goCheck.ts#L168

**Comment by ironcladlou** [comment]
I think `go list` might get us the import package needed  for the `-scope` argument for the common case. I need to read up on `ImplementationProvider` to understand whether it's meant to cope with the multiple `implements` results (I'd expect something similar to the CodeLens view presented for Find References). I've really been wanting `guru  implements` lately, and performance now seems good enough for me.

```
$ pwd
/Users/dan/Projects/kubernetes/src/k8s.io/kubernetes

$ go list -e -json
{
        "Dir": "/Users/dan/Projects/kubernetes/src/k8s.io/kubernetes",
        "ImportPath": "k8s.io/kubernetes",
        "Stale": true,
        "StaleReason": "errors loading package",
        "Root": "/Users/dan/Projects/kubernetes",
        "Incomplete": true,
        "Error": {
                "ImportStack": [
                        "k8s.io/kubernetes"
                ],
                "Pos": "",
                "Err": "no buildable Go source files in /Users/dan/Projects/kubernetes/src/k8s.io/kubernetes"
        }
}
```

**Comment by ramya-rao-a** [comment]
This feature is now out in the latest update to the Go extension 0.6.64.

Thanks everyone!
