### ISSUE TITLE
Coverage computation too disruptive

### ISSUE THREAD

**Issue by mtrmac** [Microsoft/vscode-go#777]
I use
```js
    "files.autoSave": "afterDelay",
    "go.coverOnSave": true,
```

which has worked fine. After a recent update to Code 1.9 / vscode-go 0.6.53, every edit which breaks the syntax or cases tests to fail immediately opens an output window with `Command failed: /usr/bin/go test -coverprofile=/tmp/go-code-cover` and details of the failure.

That’s… extremely disruptive. Would it be possible to revert to the previous behavior, or perhaps to open such a window only on explicit requests to run tests?

**Comment by mtrmac** [comment]
> immediately

Sorry, of course only after the autosave delay. But that’s pretty soon.

**Comment by ramya-rao-a** [comment]
That change was made in response to #350 where the user was running the test coverage command, but was not seeing any results because the tests were failing.

I can see how this can be disruptive when `coverOnSave` is `true`

What we can do is show such errors when test coverage is explicitly asked for via the command. This way the "coverOnSave" feature can continue to be silent.

Thanks for the catch @mtrmac!

**Comment by ramya-rao-a** [comment]
The fix should be out in the next update which should be in a week.
Until then, you can set `coverOnSave` to false.
Sorry for the inconvenience

**Comment by mtrmac** [comment]
Wow, that was fast. Thank you!

**Comment by ramya-rao-a** [comment]
Our pleasure :)
