### ISSUE TITLE
Package docs from godoc in VS Code

### ISSUE THREAD

**Issue by elithrar** [Microsoft/vscode-go#789]
Being able to open the current symbol in godoc—within VS Code—can be a huge productivity boost, as you don't need to leave VS Code and can browse related package documentation quickly.

This is something vim-go does very well: https://github.com/fatih/vim-go#example-mappings

> Open the relevant Godoc for the word under the cursor with `<leader>gd` or open it vertically with `<leader>gv`
> `au FileType go nmap <leader>gd <Plug>(go-doc)`
> `au FileType go nmap <leader>gv <Plug>(go-doc-vertical)`

Being able to do this, and configure keybindings for the behaviour, would be very useful.

**Comment by ramya-rao-a** [comment]
That would be cool to do, PRs are welcome :)

**Comment by ramya-rao-a** [comment]
Related ask in https://github.com/Microsoft/vscode-go/issues/1237from @apiarian:

It would be great to have access to the output of `godoc` for a package (and possibly a specific identifier) within the editor without having to open up a browser to godoc.org or similar.

Should be possible using https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextDocumentContentProvider . Some care will need to be taken to handle vendored code correctly. `godoc` seems to default to looking in the `$GOPATH` or `$GOROOT` so we'll probably have to explicitly check `$PROJECTROOT/vendor` first.

I'd like to take this issue on myself, but it'll be my first foray into vscode extensions out of my backend-development cave, so if somebody is keen to see this quicker, please let me know. I'd certainly be willing to hand the branch over or collaborate on the work.

**Comment by navossoc** [comment]
I can't see the example on the first post, the link seems broken.

I was thinking in creating something like this:
https://goplay.space/

> Smart help lookup: double-click on e.g. package keyword or Println function name in source code, and you will see the relevant help topic. Try it!

It doesn't seems that hard to implement it on VS Code as a plugin, but I don't have any knowledge on how VS extensions work.

Some components that may help:
- [vscode-uri](https://www.npmjs.com/package/vscode-uri) - The URI implementation used by VS Code and its extensions.
- [request-light](https://www.npmjs.com/package/request-light) - A light weight Node.js request library with proxy support

Some sample extensions that may help too:
- https://github.com/Microsoft/vscode-extension-samples/blob/master/contentprovider-sample/README.md
- https://github.com/Microsoft/vscode-extension-samples/blob/master/previewhtml-sample/README.md

**Comment by apiarian** [comment]
Made a first draft implementation of the documentation view. Would very much appreciate any notes or comments. I'm new to this javascript and VSCode stuff.

**Comment by apiarian** [comment]
now with automatic package name detection https://github.com/Microsoft/vscode-go/pull/1282

**Comment by apiarian** [comment]
and an entry in the context menu. feature complete?

**Comment by ramya-rao-a** [comment]
It definitely sounds feature complete :)
I have left a few comments on the PR.

**Comment by apiarian** [comment]
An interesting v2 for this feature might be to use the `vscode.previewHtml` command ( https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands#_working-with-the-html-preview ) to show a pretty doc page instead of the basic plain text. Similar to what the https://github.com/Huachao/vscode-restclient plugin does with their `rest-client.previewResponseInUntitledDocument` setting.

**Comment by ramya-rao-a** [comment]
I was wondering about that...

The resulting editor with docs does look very plain.
Does godoc support output in markdown?

**Comment by apiarian** [comment]
Not that I can see. There's an `-html` flag which will output an HTML snippet that we could put into an `<html></html>` context and add styling. But that's a pretty hefty bit of work, it seems. Maybe.

**Comment by ramya-rao-a** [comment]
That would be cool. There is a way to html content directly, with some default styles. I'll look it up and get back

**Comment by apiarian** [comment]
so the easy part is replacing the `vscode.window.showTextDocument` line with `vscode.commands.executeCommand('vscode.previewHtml', uri, vscode.window.activeTextEditor.viewColumn+1);` . The tricky part is going to be getting the styling right. I'm exploring the possibility of pulling the style and script files out of the godoc repo https://github.com/golang/tools/tree/master/godoc/static .

**Comment by apiarian** [comment]
Does 

```
// Copyright 2012 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
```

in https://github.com/golang/tools/blob/master/godoc/static/godocs.js#L1 mean tat we can't just include the script in this repo and use it to handle the various navigational things that it provides? Also, what about the other things in that directory, like the CSS?

**Comment by apiarian** [comment]
So all of the `*.txt` files in this directory are actually templates for the text form of the output. Likewise all of the `*.html` and `*.xml` files are templates for the `-html` form of the `godoc` output. We could copy them into `vscode-go/godoc-static` and edit them to contain exactly the output we need. Though that, too, seems like a v2 thing which will require a fair bit of HTML/CSS/JS wizardry.

**Comment by apiarian** [comment]
Actually, if I'm understanding this correctly https://github.com/golang/tools/blob/master/LICENSE , we can include the templates and other files as long as we mention the source in them? Is this how legal things work?

**Comment by ramya-rao-a** [comment]
@apiarian Wouldn't it be easier to use `godoc` to run a documentation server?
Then accessing it via localhost, you will get all the css/navigation and all the cool stuff

**Comment by apiarian** [comment]
Perhaps. I'll give it a try, one concern is that it might not update immediately as the documentation comments change.

How do we handle restyling for light vs dark vs high contrast themes, just inject a css file at the end of the `head`?

Do we leave all of the other godoc functionality in place? The playground and search and stuff? Where does the search index go? This is becoming less of a text or HTML document view and more of a full browser tab. Is that something VSCode can support? Otherwise we'll probably need to massage the links somehow.

**Comment by ramya-rao-a** [comment]
I would keep the the light vs dark theme issue out of scope for now.
Links opening in browser should be ok to get started. I believe thats what the HTML preview does by default.

**Comment by ramya-rao-a** [comment]
@elithrar When you first logged this issue, you cited vim-go as an example. This is what I found in the [vim-go docs](https://github.com/fatih/vim-go/blob/7efc3fe06532f56d9340429f4b05522426e1d240/doc/vim-go.txt#L191)

![image](https://user-images.githubusercontent.com/16890566/32527452-e2870ba0-c3e2-11e7-9672-f51ac742afc8.png)

It looks like the split window would show the docs just for the symbol for which the request was made i.e no navigation or no docs from rest of the package that the symbol belongs to. Is that right?

**Comment by elithrar** [comment]
They do support the ability to navigate the rest of the package docs beyond
the immediate symbol.

**Comment by GlenDC** [comment]
Being able to open an imported package (import line) into godocs would be a huge productivity boost to. As in being able to just click on it with some special key(s), is certainly faster than having to copy the import line, opening my browser myself, typing godocs.org and pasting it in to go to that package that way.

**Comment by ramya-rao-a** [comment]
Hello All,

As VS Code and this extension has gained popularity, we have seen a gradual scope creep over the past year. Being a sole maintainer of this project, it is getting a little hard to support all incoming requests and maintaining the ever growing set of features. Therefore, from now on, one criteria I am going to add to the triaging process is whether the feature request would make sense as a separate extension. This current feature request appears to be so.

godoc has a lot to offer as already discussed in this issue. Another feature from godoc.org that was recently requested was #1819. Integration with godoc in general can open a lot of doors to exciting new features. And so, I believe it can be part of a separate extension.

The new extension can take a dependency on this extension. Which means it can re-use the work done by this extension. For example: The new extension need not repeat all the work this extension does to [calculate GOPATH](https://github.com/Microsoft/vscode-go/wiki/GOPATH-in-the-VS-Code-Go-extension). It can execute the command `Go: Current GOPATH` and get the GOPATH calculated by this extension. We can look into what other internal features of this extension can be exposed so that it can used by others.

So @apiarian, thanks a lot for your work on the PR. If you or anyone else plan to move it to a separate extension, I can help with code reviews and testing.

Thanks for all the support!
