### ISSUE TITLE
Update Go tools automatically

### ISSUE THREAD

**Issue by zegl** [Microsoft/vscode-go#797]
The Go tools required with this editor are not automatically updated.

If vscode-go requires a newer version of a tool to function correctly the user has to debug this issue themself. A notice in a README is not enough to keep the users happy.

I suggest that the plugin/editor would automatically resolve these issues if they are found. Or that the user is notified about the issue via a banner telling the user how to resolve the issue.

Both of the examples below cause frustration towards vscode or vscode-go as it is not visible where this issue originates from.

## Example issues

#503 - CPU hog after upgrading MacOS to Sierra.
#441 - After upgrading to Go 1.7 `gocode` needs to be restarted.

**Comment by ramya-rao-a** [comment]
The upgrade of MacOS to Sierra was an unfortunate case which we couldnt have foreseen (If anybody thinks otherwise, I'd love to hear ideas).

The updgrading of Go itself on the other hand is known to need rebuilding/re-compiling of the tools. We can look into ways of tracking the Go version the user is using and prompt to update the tools.

There can be a hundred other cases where one of the tools stop working and an update would fix it. But this is hard for the extension to predict.

Any more ideas on how to deal with this is welcome.

**Comment by zegl** [comment]
The Sierra issue would indeed be hard to foresee. This issue might be easier to *detect* than to *predict*?

Sings of this issue seems to be unresponsive processes of `gocode`, `godef` or any other tool.  Which should be relatively easy to detect and correct for.

**Comment by mattetti** [comment]
it's a bit of an hard issue since go doesn't have a good dependency management to lock the version of 3rd party libraries. Ideally we would want to vendor those tools or lock a specific version

**Comment by ramya-rao-a** [comment]
With https://github.com/Microsoft/vscode-go/commit/8ee4dafb9bf99b2a3c6aeca04c0a2029bdc3c327, after the next update, the Go extension will keep track of the version of Go being used.

When opening a new VS Code window, if the Go extension finds that the Go version is different than before, it will prompt the user to update the tools.

**Comment by ramya-rao-a** [comment]
This feature (https://github.com/Microsoft/vscode-go/issues/797#issuecomment-315671773) is now out in the latest update (0.6.63) to the Go extension
