### ISSUE TITLE
I can't use vim mode's ctrl+n, after i use the vscode-go plugin.

### ISSUE THREAD

**Issue by donnol** [Microsoft/vscode-go#859]
I can't use vim mode's ctrl+n to complete my code, after i use the vscode-go plugin.

![vscode-go-problem](https://cloud.githubusercontent.com/assets/5707519/23820940/ad875428-065f-11e7-94b1-fed3d5ee7bf1.png)

**Comment by ramya-rao-a** [comment]
cc @rebornix our residential vim expert

@rebornix Can you help?

**Comment by rebornix** [comment]
@donnol  In Vim we invokde `selectNextSuggestion` command, nothing else. So please check what's the expected behavior when you run this command directly. And you may also want to disable Vim temporarily and run `selectNextSuggestion` to see its effect. If `selectNextSuggestion` leads you to nowhere when `Vim` disabled, then I'll say it might be a Code or Go issue (even though very unlikely).

**Comment by ramya-rao-a** [comment]
@donnol Closing this issue as we havent heard back from you in a while.

If you still see this issue after following @rebornix 's suggestions, please do drop a comment here
