### ISSUE TITLE
When upgrade to GO extension 0.6.57 version, there is an other error with multiple GOPATHs

### ISSUE THREAD

**Issue by ansencumt** [Microsoft/vscode-go#897]
My User Settings:
![image](https://cloud.githubusercontent.com/assets/5181385/24533660/ba869d04-15fb-11e7-8719-f7bca6af9b9a.png)

The Go:CurrentGopath:
![image](https://cloud.githubusercontent.com/assets/5181385/24533685/d9d5e4d0-15fb-11e7-92a7-f47febb38e83.png)

The File Explorer:
![2](https://cloud.githubusercontent.com/assets/5181385/24533801/89082120-15fc-11e7-83d9-b75415f9343e.png)

Then the error:
![1](https://cloud.githubusercontent.com/assets/5181385/24533807/9425bd60-15fc-11e7-809d-a7aace9ea538.png)

And it works fine in 0.6.54

**Comment by ramya-rao-a** [comment]
This mostly is related to #894

Since I am not able to repro, can you uninstall the Go extension you have, and install it using the [Go-0.6.58.vsix](https://github.com/Microsoft/vscode-go/blob/master/Go-0.6.58.vsix) to confirm if the fix works for you?

- Uninstall Go extension
- Download the vsix file [Go-0.6.58.vsix](https://github.com/Microsoft/vscode-go/blob/master/Go-0.6.58.vsix) 
- Run `code --install-extension Go-0.5.58.vsix` from the location where you downloaded the file

**Comment by ansencumt** [comment]
@ramya-rao-a 0.6.58.vsix is work fine!

**Comment by ramya-rao-a** [comment]
Great, I am waiting on confirmation from a few other users who have a slightly different error than this one, after that will release an update tomorrow.

You should be unblocked now, so closing this issue

**Comment by ramya-rao-a** [comment]
@ansencumt I want to understand your scenario better.

Can you run the command `Go: Current GOPATH` and share the output?

**Comment by ansencumt** [comment]
OK, that`s the Go: Current GOPATH result.  @ramya-rao-a

![image](https://cloud.githubusercontent.com/assets/5181385/24543829/9645bbea-1633-11e7-95da-5eed1963f799.png)

**Comment by ramya-rao-a** [comment]
I just released an update (0.6.59) yesterday which has the fix
