### ISSUE TITLE
Outline Window for Functions and Methods - Feature Request

### ISSUE THREAD

**Issue by tqoliver** [Microsoft/vscode-go#919]
It would be great to have an outline or tree view of the current .go file that displays 'var', 'func', etc for the .go file being edited.  This could be in a collapsable window pane on the right side of the Go editor.  It would be similar to the class outline in Java IDEs like Eclipse.  This would be very helpful, especially for longer .go files that have a ton of variables and functions.  I'm attaching an image of an Eclipse screen for reference.

![ajdt_eclipse_screen](https://cloud.githubusercontent.com/assets/2377889/24801896/ea5b4ade-1b73-11e7-8edd-4e6d1acf16c6.jpg)

Thanks!

**Comment by ramya-rao-a** [comment]
I believe what you are asking for is being tracked in https://github.com/Microsoft/vscode/issues/5605
This is very highly requested.

Since it is a core VS Code feature, and not extension specific, will close this issue in favor of https://github.com/Microsoft/vscode/issues/5605

Please add your upvotes and thoughts there.
