### ISSUE TITLE
lint too aggressive when in a project with cgo

### ISSUE THREAD

**Issue by erichiller** [Microsoft/vscode-go#925]
I am working on a project which incorporates `cgo`, and every keystroke at this point will take my CPU to 100% as multiple `go` and `gcc` processes are spawned to process `lint`. The same was happening for `gocode`. I've since disabled both of these tool's `...OnSave` properties but that is keeping me from using quite a few useful tools in a near-realtime way.

Is this simply a penalty of `cgo`, something I have configured wrong or need to tweak, or a bug potentially? 

**Occurrence Details:** Specifically when `"go.lintOnSave": true`. And specifically in `cgo` / `import "C"` packages.

**Comment by ramya-rao-a** [comment]
When you say "for every keystroke" I am assuming you have autosave on? Because linting gets triggered on save only.
gocode on the other hand gets triggered for every word 

Can you share details about how you came to the conclusion that it is linting that is causing the high CPU usage?

On whether `cgo` has impact on linting, the authors of the linting tool would be in a much better position than me to comment. Please log an issue in the repo corresponding to the linting tool you are using (`golint` or `gometalinter`).

**Comment by ramya-rao-a** [comment]
@erichiller Closing this issue as we haven't heard back from you in a while
