### ISSUE TITLE
Visual Studio Code (with the ‘golang’ extension) so very, very slow?

### ISSUE THREAD

**Issue by Mike152** [Microsoft/vscode-go#979]
Dear Sir,
PROBLEM:
Why is Visual Studio Code (with the ‘golang’ extension) so very, very slow?

ANALYSIS:
1. I am running Windows 10 on a desk top PC.
Processor: Intel(R) Core(TM) i3 CPU 540 @ 3.07GHz 3.06 GHz
Installed Memory (RAM): 4.00 GB (3.87 GB usable)
System type: 64-bit Operating System, x64-bassed processor

2. I am running Visual Studio Code Version 1.12.1
Commit f6868fce ...
Date 2017-05-04T21:26:50.689Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

3. I am using the ‘golang’ extension.

I have the following in a file called ‘helloworld.go’:-

package main
import "fmt"
func main() {
    fmt.Println("hello world")
}

I type ‘go run helloworld.go’ in the terminal area and it takes 11 (sometimes 20) minutes to get a response

Why is it so very, very slow?
I would be very grateful for any advice.

Thank you
Mike

**Comment by ramya-rao-a** [comment]
Can you disable the Go extension and do `go run helloworld.go` in the terminal? Is it still slow or is there a difference?

**Comment by Mike152** [comment]
Thank you for your reply.
It took about 15 minutes to disable the workspace (was that what you meant?).
It didn't help, it still takes from 10 to 20 minutes to run a simple 'Hello World'.
This is unusable 
Q. It there a minimum amount of memory needed to make it work properly?

**Comment by ramya-rao-a** [comment]
Sorry for not providing the easier way before. You can run `code --disable-extensions`. This will run vs code with all the extensions disabled.

Can you run `go run helloworld.go` outside vs code in a terminal? Is that faster?

**Comment by henvic** [comment]
Visual Studio Code is very slow here as well after running for just a few minutes when I have `go.useLanguageServer: true`.

My $GOPATH is `/Users/henvic/projects/gocode`.
Outside VS Code Go runs just fine.

Maybe this is related with the issues below?
https://github.com/sourcegraph/go-langserver/issues/185
https://github.com/Microsoft/vscode-go/issues/886

**Comment by ramya-rao-a** [comment]
@henvic The language server issue is tracked here: https://github.com/sourcegraph/go-langserver/issues/178

**Comment by ramya-rao-a** [comment]
@henvic  Language server perf issue is tracked here: https://github.com/sourcegraph/go-langserver/issues/178

**Comment by ramya-rao-a** [comment]
@Mike152 Do you still see issues? Do you have the language server turned on?

**Comment by fasa123** [comment]
Can confirm this with lang-server enabled. Running on Arch Linux. This mostly happens when editing files with dot imports (at least for me). Also occasionally happens (as described) with very simple files. This clearly is a go-langserv specific problem since it does not happen when the langserver is disabled.

I assume the problem is that the langserver does not cancel pending workers but justs queues new ones if something is triggered. Though haven't had a look at the implementation so I could be wrong. But feels heavily like it since I realized this happens more often if I change a source file fast and trigger saves multiple times in fast succession.

**Comment by ramya-rao-a** [comment]
Thanks for the analysis @fasa123 

Can you add your thoughts https://github.com/sourcegraph/go-langserver/issues/178 as well?

**Comment by ramya-rao-a** [comment]
Slowness experienced by @fasa123 and @henvic is due to the language server. The issue is being tracked https://github.com/sourcegraph/go-langserver/issues/178

@Mike152 We haven't heard back from you in a month, am assuming things are working well. If not, please drop a comment here.

Closing this issue for now
