### ISSUE TITLE
Respect alias during autocomplete

### ISSUE THREAD

**Issue by diegobernardes** [Microsoft/vscode-go#985]
Supose we have a package called `elasticsearch` that is used inside the package `product`. On package product the elasticsearch has a alias called `client`, then when we call `client.methods` it shows `elasticsearch.methods`, and this is correct, but when we do a tab to accept the autocomplete it put the `elasticsearch.` instead of  `client.`, so we are forced  to rename to accept the alias name.

**Comment by ramya-rao-a** [comment]
@diegobernardes Can you give a sample code where I can try and repro this?

> On package product the elasticsearch has a alias called client

I don't know how to do the above.

**Comment by diegobernardes** [comment]
Sorry if the description was so vague, was programming when i had that idea and had to post before i forget :smile:

github.com/diegobernardes/vscodego/elasticsearch/v1
```golang
package v1

type Client struct{}

func (c *Client) Insert(Product) {}

type Product struct{}
```

github.com/diegobernardes/vscodego
```golang
package main

import (
	elasticsearch "github.com/diegobernardes/vscodego/elasticsearch/v1"
)

func main() {
	client := elasticsearch.Client{}
	client.Insert(v1.Product)
}
```
Don't know if this is possible or easy, but, the autocomplete is correct showing `v1.Product`, because it is the signature of the method. But, when we select the autocomplete suggestion, it should insert a text snippet that works, so the correct snippet should be `elasticsearch.Product` because it's the name of the import.

![vscodego](https://cloud.githubusercontent.com/assets/14483/25879423/06698e4a-3508-11e7-9d46-ddadd3691530.png)
![vscodego2](https://cloud.githubusercontent.com/assets/14483/25879475/43cb2a64-3508-11e7-9e19-1e228d3b6637.png)

It's more clear now? This make any sense?

**Comment by ramya-rao-a** [comment]
Thanks for the clarification.

So you have `"go.useCodeSnippetsOnFunctionSuggest": true` in your settings
and expect the snippet that gets added by the autocompletion to have the default value as `elastic search.Product` instead of `v1.Product`.

The snippets added in this way are rarely ever used without any changes. In this case even if `elastic search.Product` was inserted, you would still have to replace that with a valid value. 

Therefore, is there any advantage if the alias was indeed used in the snippet?

This feature of adding snippet is based on function signature which the extension gets from [gocode](https://github.com/nsf/gocode). So even if do want to get this fixed, this should be fixed by `gocode`

**Comment by ramya-rao-a** [comment]
@nsf Any thoughts on `gocode` respecting alias for the package while returning the `type` of the completion item?

**Comment by nsf** [comment]
I think it worked like you would expect once, but apparently it doesn't anymore. I will take a look at it on the weekend.

**Comment by nsf** [comment]
Just want to say that I took a look at the issue and it's more complicated than it seems. Not sure how long it will take for me to solve it. Don't have much time to work on it. The problem gets worse because this is valid Go:

```go
package main

import (
        es1 "gopkg.in/olivere/elastic.v3"
        es2 "gopkg.in/olivere/elastic.v3"
)

func main() {
        es1.SetErrorLog(nil)
        es2.SetErrorLog(nil)
}
```

It compiles just fine. But in gocode I have only one package instance per absolute package path. And it will be hard to forward the alias used under a given autocompletion request to that package and basically figure out which prefix I should use for pretty printing the types.

My initial idea was to create a "canonical package aliases map" for a given request, based on the current file. But as you can see it can be ambiguous and instead I have to make a "canonical package aliases map" per expression. But even there it's ambiguous, you can imagine something like (btw not sure if it's valid Go):

```go
package main

import (
        A "mypackage"
        B "mypackage"
)

func main() {
        (A.Value + B.Value).CallMe#
}
``` 

If that CallMe method contains types from a package, which alias should I use?

But anyways, I realise that people don't do that weird stuff in practice (using different aliases for the same package under the same scope) and I'll try to come up with something practical. Again, don't know how much time will it take. Maybe this weekend, maybe a few more weeks. Sorry about delays, I really don't have time to work on gocode and gocode's code is a giant mess when it comes to package import.

**Comment by ramya-rao-a** [comment]
Thanks for looking into this @nsf
No worries about the delay.

Would you prefer a tracking issue in the `gocode` repo or this issue is ok?

**Comment by nsf** [comment]
This issue is ok.

**Comment by nsf** [comment]
Just pushed the change which might help with this case. However it's a hack, which doesn't cover all possible use cases. It's better than nothing, unless it breaks something. Anyways it should help with the reported issue, here's a similar case in action:

![aaa](https://user-images.githubusercontent.com/12567/27749214-1516a830-5dec-11e7-820e-1ecfb634df92.png)

As you can see types are annotated using my custom alias instead of default "elastic".

**Comment by ramya-rao-a** [comment]
Thanks @nsf!

@diegobernardes run "gocode close" and then update gocode by "go get -u github.com/nsf/gocode"

**Comment by diegobernardes** [comment]
Ok, thanks @ramya-rao-a and @nsf.
