### ISSUE TITLE
Not supporting for vendor 

### ISSUE THREAD

**Issue by kumarsiva07** [Microsoft/vscode-go#991]
I am using https://github.com/golang/dep for dependancy management. This will store all dependencies in vendor dir. vscode editor not detecting package from vendor.

<img width="973" alt="screen shot 2017-05-12 at 1 20 35 am" src="https://cloud.githubusercontent.com/assets/7725174/25969112/63baead0-36b1-11e7-9d25-eb9f304665a6.png">

**Comment by ramya-rao-a** [comment]
@kumarsiva07 Is this a regression or has this never worked?

**Comment by jackie-qiu** [comment]
@ramya-rao-a  Never worked!

**Comment by sofent** [comment]
i have the same problem

**Comment by kumarsiva07** [comment]
Never worked to me. Before use go dep(Vendor), Editor can find the path.

**Comment by jackie-qiu** [comment]
@kumarsiva07 Try "go get -v github.com/rogpeppe/godef"

**Comment by ramya-rao-a** [comment]
@kumarsiva07 What you are seeing are build errors. You can see the same in the output pane where it says "Finish running tool: /usr/local/go/bin/go build -i -o ...."

Can you run the build command you see in the output pane in the terminal? Does that succeed?

**Comment by mixj93** [comment]
same problem ╥﹏╥...

**Comment by kumarsiva07** [comment]
@ramya-rao-a  I just restarted the IDE. Now Its fine

**Comment by ramya-rao-a** [comment]
cool, Happy Coding!

**Comment by ramya-rao-a** [comment]
Others who are having this issue, can you share what you get when you do `go build` as per the command printed out in the output window?

**Comment by mixj93** [comment]
Actually, the build is fine. I use makefile to build:
![jietu20170516-092605](https://cloud.githubusercontent.com/assets/12998118/26085983/78ca11e6-3a1a-11e7-9798-8b7357b22c2d.jpg)

But the import can't find some package, because this package are in vendor/, not in GOPATH/src or GOROOT/src
![image](https://cloud.githubusercontent.com/assets/12998118/26086120/664d59c8-3a1b-11e7-8b17-0020c07ed142.png)

**Comment by ramya-rao-a** [comment]
@mixj93 What you have shown is the error coming from running `go build`.
Which is why I ask what do you get when you do a `go build`. My suspicion is that you will get the exact same error message. Then the next step would be to figure out why `go build` fails.

You may use makefile to build, but the Go extension uses `go build` on the import path of the package to build the package.

**Comment by mixj93** [comment]
Yes, now I know why. And I move the project folder to GOPATH and everything looks fine.
